export interface GeneratedPersonForms {
  readonly plural: string;
  readonly singular?: string;
  readonly feminineSingular?: string;
  readonly obliqueSingular?: string;
  readonly genitiveSingular?: string;
}

// Automatisch erzeugte, normalisierte Produktdaten. Häufige Flexionsmuster
// werden kompakt als Mengen gespeichert; nur Sonderfälle tragen Vollformen.
const unchangedForms: ReadonlySet<string> = new Set([
  "abenteurer",
  "abgänger",
  "abnehmer",
  "absender",
  "abteilungsleiter",
  "abtreibungsgegner",
  "afrikaner",
  "afroamerikaner",
  "ägypter",
  "akademiker",
  "albaner",
  "alkoholiker",
  "allergiker",
  "allgemeinmediziner",
  "altenpfleger",
  "amerikaner",
  "amtsinhaber",
  "amtsleiter",
  "amtsträger",
  "anbieter",
  "anfänger",
  "anführer",
  "angler",
  "angreifer",
  "anhalter",
  "anhänger",
  "ankläger",
  "anleger",
  "anlieger",
  "anrainer",
  "anrufer",
  "ansprechpartner",
  "anteilseigner",
  "antragsteller",
  "anwärter",
  "anwender",
  "anwohner",
  "apotheker",
  "arbeiter",
  "arbeitgeber",
  "arbeitnehmer",
  "arbeitnehmervertreter",
  "arbeitsvermittler",
  "argentinier",
  "asylbewerber",
  "atomkraftgegner",
  "attentäter",
  "aufklärer",
  "aufsteiger",
  "auftraggeber",
  "augenoptiker",
  "ausbilder",
  "ausflügler",
  "ausländer",
  "außenminister",
  "außenseiter",
  "aussiedler",
  "aussteiger",
  "aussteller",
  "austauschschüler",
  "australier",
  "auswanderer",
  "autobesitzer",
  "autofahrer",
  "babysitter",
  "bäckermeister",
  "bademeister",
  "bahnfahrer",
  "banker",
  "barkeeper",
  "bauarbeiter",
  "befürworter",
  "begleiter",
  "behördenmitarbeiter",
  "beifahrer",
  "beisitzer",
  "beitragszahler",
  "benutzer",
  "beobachter",
  "berater",
  "bergsteiger",
  "berichterstatter",
  "berliner",
  "berufsanfänger",
  "berufsberater",
  "berufseinsteiger",
  "berufspolitiker",
  "berufsrichter",
  "berufsschüler",
  "beschwerdeführer",
  "besetzer",
  "besitzer",
  "bestatter",
  "besucher",
  "betrachter",
  "betreiber",
  "betreuer",
  "betrüger",
  "bewahrer",
  "bewährungshelfer",
  "bewerber",
  "bewohner",
  "bezirksbürgermeister",
  "bildhauer",
  "bildungsforscher",
  "bildungsminister",
  "bildungspolitiker",
  "blogger",
  "botaniker",
  "botschafter",
  "boxer",
  "brandenburger",
  "brandstifter",
  "brasilianer",
  "bremer",
  "briefträger",
  "brillenträger",
  "buchhalter",
  "buchhändler",
  "bundesbürger",
  "bundeskanzler",
  "bundesminister",
  "bundespolitiker",
  "bündnispartner",
  "bürger",
  "bürgermeister",
  "bürgerrechtler",
  "busfahrer",
  "camper",
  "chemiker",
  "chorleiter",
  "chorsänger",
  "cutter",
  "darsteller",
  "datenschützer",
  "dealer",
  "demonstrationsteilnehmer",
  "denker",
  "designer",
  "deutschlehrer",
  "diabetiker",
  "dichter",
  "dienstleister",
  "dolmetscher",
  "doppelgänger",
  "dorfbewohner",
  "dortmunder",
  "dramatiker",
  "drittklässler",
  "ehepartner",
  "ehrenamtler",
  "ehrenbürger",
  "eigentümer",
  "eigner",
  "einbrecher",
  "einsteiger",
  "einwanderer",
  "einwohner",
  "einzelgänger",
  "einzelhändler",
  "einzelkämpfer",
  "einzelspieler",
  "eisenbahner",
  "elektriker",
  "elektroniker",
  "elektrotechniker",
  "empfänger",
  "endverbraucher",
  "enkel",
  "entdecker",
  "entertainer",
  "entscheider",
  "entscheidungsträger",
  "entwickler",
  "entwicklungshelfer",
  "erbauer",
  "erfinder",
  "ermittler",
  "erntehelfer",
  "ersthelfer",
  "erstklässler",
  "erstwähler",
  "erzähler",
  "erzeuger",
  "erzieher",
  "europäer",
  "fabrikarbeiter",
  "facharbeiter",
  "fachlehrer",
  "fachpolitiker",
  "fachwissenschaftler",
  "fahnder",
  "fahrer",
  "fahrlehrer",
  "fahrradfahrer",
  "fahrschüler",
  "fanatiker",
  "fechter",
  "fernsehzuschauer",
  "filialleiter",
  "filmemacher",
  "filmkritiker",
  "finanzminister",
  "finder",
  "fischer",
  "fleischer",
  "fliesenleger",
  "flüchtlingshelfer",
  "flugbegleiter",
  "follower",
  "förderschüler",
  "forscher",
  "förster",
  "frankfurter",
  "freiberufler",
  "führer",
  "funktionsträger",
  "fürsprecher",
  "fußballer",
  "fußballspieler",
  "fußgänger",
  "fußpfleger",
  "gaffer",
  "gamer",
  "gärtner",
  "gastarbeiter",
  "gastgeber",
  "geburtshelfer",
  "gegenspieler",
  "gegner",
  "geisterfahrer",
  "geisteswissenschaftler",
  "geldgeber",
  "genießer",
  "gerichtsvollzieher",
  "geringverdiener",
  "geschäftsführer",
  "geschäftsinhaber",
  "geschäftspartner",
  "geschichtenerzähler",
  "geschichtslehrer",
  "gesellschafter",
  "gesetzgeber",
  "gesprächspartner",
  "gesundheitsminister",
  "gewalttäter",
  "gewerkschafter",
  "gewinner",
  "gläubiger",
  "gottesdienstbesucher",
  "grafiker",
  "grenzgänger",
  "gründer",
  "grundschüler",
  "grundschullehrer",
  "gruppenleiter",
  "gutachter",
  "gymnasiallehrer",
  "hacker",
  "hamburger",
  "handballer",
  "handlanger",
  "händler",
  "handwerker",
  "handwerksmeister",
  "handynutzer",
  "hauptdarsteller",
  "hauptmieter",
  "hauptschüler",
  "hausbesitzer",
  "hausmeister",
  "heimbewohner",
  "heimkehrer",
  "helfer",
  "herausgeber",
  "herrscher",
  "hersteller",
  "hinweisgeber",
  "historiker",
  "hobbygärtner",
  "hobbymusiker",
  "hochschullehrer",
  "hoffnungsträger",
  "hörer",
  "hundebesitzer",
  "hundehalter",
  "imker",
  "immobilienmakler",
  "impfgegner",
  "inder",
  "industriearbeiter",
  "influencer",
  "informatiker",
  "inhaber",
  "inländer",
  "innenminister",
  "insider",
  "internetnutzer",
  "interviewer",
  "interviewpartner",
  "iraner",
  "islamwissenschaftler",
  "isländer",
  "italiener",
  "jäger",
  "japaner",
  "jazzmusiker",
  "jogger",
  "jugendrichter",
  "jünger",
  "jungunternehmer",
  "jungwähler",
  "justizminister",
  "kämpfer",
  "kampfrichter",
  "kanadier",
  "kanzler",
  "kassierer",
  "käufer",
  "kellner",
  "kenner",
  "keramiker",
  "kieler",
  "kinobesucher",
  "kinobetreiber",
  "kläger",
  "klassenlehrer",
  "klassensprecher",
  "kleinunternehmer",
  "kletterer",
  "klimaforscher",
  "klimaschützer",
  "kölner",
  "komiker",
  "kommunalpolitiker",
  "kontoinhaber",
  "kosmetiker",
  "kraftfahrer",
  "krankenpfleger",
  "kreditnehmer",
  "krieger",
  "kritiker",
  "kubaner",
  "kulturwissenschaftler",
  "kultusminister",
  "kunsthistoriker",
  "künstler",
  "kunstsammler",
  "kursleiter",
  "kursteilnehmer",
  "landarbeiter",
  "landbewohner",
  "landespolitiker",
  "läufer",
  "lebenspartner",
  "lebensretter",
  "lehrer",
  "lehrmeister",
  "lehrstuhlinhaber",
  "leiharbeiter",
  "leipziger",
  "leistungssportler",
  "leistungsträger",
  "leiter",
  "lenker",
  "leser",
  "liebhaber",
  "liedermacher",
  "literaturkritiker",
  "literaturwissenschaftler",
  "lokalpolitiker",
  "lyriker",
  "macher",
  "mainzer",
  "makler",
  "maler",
  "manager",
  "mandatsträger",
  "märchenerzähler",
  "mathematiker",
  "maurer",
  "mechaniker",
  "mechatroniker",
  "medienwissenschaftler",
  "mediziner",
  "meinungsführer",
  "meister",
  "menschenrechtler",
  "menschenrechtsverteidiger",
  "mexikaner",
  "mieter",
  "minijobber",
  "minister",
  "mitarbeiter",
  "mitbegründer",
  "mitbewerber",
  "mitbewohner",
  "mitbürger",
  "mitgründer",
  "mitläufer",
  "mitschüler",
  "mitspieler",
  "mitstreiter",
  "mittäter",
  "mittelständler",
  "mitwisser",
  "modedesigner",
  "modeschöpfer",
  "mörder",
  "motorradfahrer",
  "münchner",
  "museumsbesucher",
  "musiker",
  "musiklehrer",
  "musikliebhaber",
  "muttersprachler",
  "nachahmer",
  "nachfolger",
  "nachhilfelehrer",
  "nachrichtensprecher",
  "nachtschwärmer",
  "nachwuchswissenschaftler",
  "näher",
  "naturschützer",
  "naturwissenschaftler",
  "neubürger",
  "neueinsteiger",
  "neurowissenschaftler",
  "newcomer",
  "nichtraucher",
  "niederländer",
  "nobelpreisträger",
  "norweger",
  "notfallsanitäter",
  "nutzer",
  "nutznießer",
  "oberbürgermeister",
  "oberstufenschüler",
  "opernsänger",
  "oppositionspolitiker",
  "orchestermusiker",
  "organspender",
  "österreicher",
  "osteuropäer",
  "pächter",
  "palästinenser",
  "parlamentarier",
  "partner",
  "pendler",
  "peruaner",
  "pfadfinder",
  "pfarrer",
  "pfleger",
  "pförtner",
  "physiker",
  "pilger",
  "politiker",
  "politikwissenschaftler",
  "prediger",
  "preisträger",
  "pressesprecher",
  "pressevertreter",
  "priester",
  "programmierer",
  "projektleiter",
  "projektpartner",
  "prüfer",
  "psychiater",
  "puppenspieler",
  "querdenker",
  "quereinsteiger",
  "radfahrer",
  "radler",
  "rapper",
  "raser",
  "raucher",
  "realschüler",
  "rechnungsprüfer",
  "rechtshänder",
  "redner",
  "regierungsvertreter",
  "reichsbürger",
  "reiseleiter",
  "reiserückkehrer",
  "reiter",
  "religionslehrer",
  "religionswissenschaftler",
  "rentner",
  "reporter",
  "ressortleiter",
  "retter",
  "rettungssanitäter",
  "rettungsschwimmer",
  "richter",
  "ringer",
  "ritter",
  "rollstuhlfahrer",
  "romantiker",
  "römer",
  "rückkehrer",
  "ruderer",
  "sachbearbeiter",
  "saisonarbeiter",
  "sammler",
  "sänger",
  "sanitäter",
  "satiriker",
  "schatzmeister",
  "schauspieler",
  "schiedsrichter",
  "schlagzeuger",
  "schneider",
  "schöpfer",
  "schreiber",
  "schriftführer",
  "schriftsteller",
  "schulabbrecher",
  "schulabgänger",
  "schulanfänger",
  "schulbegleiter",
  "schuldner",
  "schuldnerberater",
  "schüler",
  "schulleiter",
  "schuster",
  "schweizer",
  "schwimmer",
  "seefahrer",
  "seelsorger",
  "segler",
  "selbstdarsteller",
  "seminarleiter",
  "seminarteilnehmer",
  "sender",
  "sexualpartner",
  "siedler",
  "sieger",
  "skeptiker",
  "skifahrer",
  "softwareentwickler",
  "sozialarbeiter",
  "sozialhilfeempfänger",
  "spanier",
  "spätaussiedler",
  "spaziergänger",
  "spender",
  "spieler",
  "spielleiter",
  "spielverderber",
  "spinner",
  "spitzenpolitiker",
  "spitzensportler",
  "sportler",
  "sprachlehrer",
  "sprachschüler",
  "sprachwissenschaftler",
  "sprecher",
  "staatsbürger",
  "stadtbewohner",
  "städter",
  "stadtführer",
  "starter",
  "stellvertreter",
  "sternsinger",
  "steuerberater",
  "steuerhinterzieher",
  "steuerzahler",
  "stifter",
  "störer",
  "straftäter",
  "straßenkünstler",
  "straßenmusiker",
  "streamer",
  "studienanfänger",
  "südafrikaner",
  "südamerikaner",
  "surfer",
  "synchronsprecher",
  "syrer",
  "tänzer",
  "tanzpartner",
  "täter",
  "taucher",
  "taxifahrer",
  "teamleiter",
  "techniker",
  "teenager",
  "teilhaber",
  "teilnehmer",
  "tester",
  "texter",
  "theoretiker",
  "tierhalter",
  "tierpfleger",
  "tierschützer",
  "tontechniker",
  "touristiker",
  "trainer",
  "trauerbegleiter",
  "tüftler",
  "türsteher",
  "übersetzer",
  "übungsleiter",
  "ukrainer",
  "umschüler",
  "umweltschützer",
  "unionsbürger",
  "unionspolitiker",
  "unternehmer",
  "unterstützer",
  "unterzeichner",
  "urheber",
  "urlauber",
  "user",
  "veganer",
  "vegetarier",
  "veranstalter",
  "verbraucher",
  "verbrecher",
  "verehrer",
  "verfasser",
  "verfassungsrichter",
  "verfassungsschützer",
  "verfechter",
  "verführer",
  "verkäufer",
  "verkehrsteilnehmer",
  "verleger",
  "verleiher",
  "verlierer",
  "vermieter",
  "vermittler",
  "verschwörungstheoretiker",
  "verteidiger",
  "vertragsarbeiter",
  "vertragspartner",
  "vertreter",
  "verursacher",
  "verwalter",
  "viertklässler",
  "volksvertreter",
  "vollstrecker",
  "vorarbeiter",
  "vordenker",
  "vorgänger",
  "vorleser",
  "vorreiter",
  "wächter",
  "wähler",
  "wahlhelfer",
  "waldbesitzer",
  "wanderarbeiter",
  "wanderer",
  "wegbereiter",
  "weltbürger",
  "weltmeister",
  "werber",
  "wettkämpfer",
  "widersacher",
  "widerstandskämpfer",
  "wiener",
  "wikipedianer",
  "winzer",
  "wirtschaftsprüfer",
  "wirtschaftswissenschaftler",
  "wissenschaftler",
  "wohnungseigentümer",
  "wortführer",
  "yogalehrer",
  "youtuber",
  "zauberer",
  "zeichner",
  "zeitarbeiter",
  "zimmerer",
  "zöllner",
  "züchter",
  "zugbegleiter",
  "zuhörer",
  "zuschauer",
  "zusteller",
  "zuwanderer",
  "zwangsarbeiter",
  "zweitklässler"
]);
const weakEnForms: ReadonlySet<string> = new Set([
  "abiturient",
  "abonnent",
  "absolvent",
  "adressat",
  "agent",
  "aktivist",
  "alevit",
  "alpinist",
  "analphabet",
  "analyst",
  "anarchist",
  "antagonist",
  "antifaschist",
  "antisemit",
  "arbeitsmigrant",
  "architekt",
  "artist",
  "aspirant",
  "assistent",
  "astronaut",
  "astronom",
  "atheist",
  "athlet",
  "auslandskorrespondent",
  "bassist",
  "bundespräsident",
  "bundestagspräsident",
  "cellist",
  "chirurg",
  "choreograf",
  "christ",
  "christdemokrat",
  "cineast",
  "demokrat",
  "demonstrant",
  "dezernent",
  "diplomat",
  "direktkandidat",
  "dirigent",
  "diskutant",
  "disponent",
  "doktorand",
  "dozent",
  "dramaturg",
  "enthusiast",
  "ergotherapeut",
  "exot",
  "extremist",
  "faschist",
  "favorit",
  "feminist",
  "fernsehjournalist",
  "finalist",
  "florist",
  "fotograf",
  "fundamentalist",
  "fürst",
  "gastronom",
  "gegenkandidat",
  "generalist",
  "geograph",
  "germanist",
  "gratulant",
  "gymnasiast",
  "held",
  "hochschulabsolvent",
  "hospitant",
  "idealist",
  "idiot",
  "immigrant",
  "informant",
  "innenarchitekt",
  "instrumentalist",
  "intendant",
  "interessent",
  "interpret",
  "islamist",
  "journalist",
  "jurist",
  "kamerad",
  "kandidat",
  "kapitalist",
  "karikaturist",
  "karnevalist",
  "katholik",
  "klassenkamerad",
  "klient",
  "klimaaktivist",
  "kolumnist",
  "kommunist",
  "komponist",
  "konfirmand",
  "konkurrent",
  "konsument",
  "kontrahent",
  "korrespondent",
  "krebspatient",
  "kulturjournalist",
  "kunststudent",
  "laborant",
  "leichtathlet",
  "lieferant",
  "literat",
  "lobbyist",
  "mandant",
  "medizinstudent",
  "migrant",
  "ministerpräsident",
  "ministrant",
  "musikant",
  "nationalist",
  "nationalsozialist",
  "netzaktivist",
  "ökonom",
  "opportunist",
  "optimist",
  "organist",
  "passant",
  "patient",
  "pazifist",
  "petent",
  "philosoph",
  "physiotherapeut",
  "pianist",
  "pilot",
  "pirat",
  "poet",
  "polizist",
  "populist",
  "praktikant",
  "präsident",
  "präsidentschaftskandidat",
  "privatpatient",
  "proband",
  "produzent",
  "protagonist",
  "protestant",
  "psychotherapeut",
  "publizist",
  "querulant",
  "rassist",
  "rebell",
  "rechtsextremist",
  "rechtspopulist",
  "referent",
  "rekrut",
  "repräsentant",
  "rettungsassistent",
  "rezensent",
  "rezeptionist",
  "rezipient",
  "risikopatient",
  "salafist",
  "soldat",
  "solist",
  "sozialdemokrat",
  "sozialist",
  "spekulant",
  "spezialist",
  "spitzenkandidat",
  "sportjournalist",
  "statist",
  "stipendiat",
  "student",
  "superheld",
  "sympathisant",
  "terrorist",
  "therapeut",
  "tourist",
  "umweltaktivist",
  "veteran",
  "vizepräsident",
  "zivilist"
]);
const pluralEForms: ReadonlySet<string> = new Set([
  "admiral",
  "akteur",
  "aktionär",
  "amateur",
  "animateur",
  "archivar",
  "bauingenieur",
  "betriebswirt",
  "bibliothekar",
  "chefredakteur",
  "dekan",
  "detektiv",
  "diplomingenieur",
  "feind",
  "freund",
  "friseur",
  "funktionär",
  "gastwirt",
  "generalsekretär",
  "ingenieur",
  "installateur",
  "jubilar",
  "kapitän",
  "kommissar",
  "könig",
  "konstrukteur",
  "kontrolleur",
  "kurier",
  "masseur",
  "mäzen",
  "milliardär",
  "millionär",
  "missionar",
  "monteur",
  "notar",
  "passagier",
  "pionier",
  "redakteur",
  "referendar",
  "regisseur",
  "sekretär",
  "spediteur",
  "spion",
  "sportredakteur",
  "staatssekretär",
  "visionär",
  "volontär",
  "wirt"
]);
const pluralEnForms: ReadonlySet<string> = new Set([
  "administrator",
  "autor",
  "direktor",
  "doktor",
  "drehbuchautor",
  "generaldirektor",
  "hauptautor",
  "illustrator",
  "initiator",
  "investor",
  "juror",
  "koautor",
  "kommentator",
  "koordinator",
  "kurator",
  "laudator",
  "lektor",
  "mentor",
  "mitautor",
  "moderator",
  "multiplikator",
  "organisator",
  "pastor",
  "professor",
  "programmdirektor",
  "rektor",
  "restaurator",
  "senator",
  "senior",
  "sponsor",
  "studienautor",
  "systemadministrator",
  "tutor"
]);
const pluralSForms: ReadonlySet<string> = new Set([
  "chef",
  "clown",
  "fraktionschef",
  "parteichef",
  "regierungschef"
]);
const specialForms: Readonly<Record<string, GeneratedPersonForms>> =
  Object.freeze({
  "afghan": {
    plural: "afghanen",
    singular: "afghane",
    feminineSingular: "afghanin",
    obliqueSingular: "afghanen",
    genitiveSingular: "afghanen"
  },
  "amtskolleg": {
    plural: "amtskollegen",
    singular: "amtskollege",
    feminineSingular: "amtskollegin",
    obliqueSingular: "amtskollegen",
    genitiveSingular: "amtskollegen"
  },
  "anwält": {
    plural: "anwälte",
    singular: "anwalt",
    feminineSingular: "anwältin",
    obliqueSingular: "anwalt",
    genitiveSingular: "anwalts"
  },
  "arbeitskolleg": {
    plural: "arbeitskollegen",
    singular: "arbeitskollege",
    feminineSingular: "arbeitskollegin",
    obliqueSingular: "arbeitskollegen",
    genitiveSingular: "arbeitskollegen"
  },
  "archäolog": {
    plural: "archäologen",
    singular: "archäologe",
    feminineSingular: "archäologin",
    obliqueSingular: "archäologen",
    genitiveSingular: "archäologen"
  },
  "artgenoss": {
    plural: "artgenossen",
    singular: "artgenosse",
    feminineSingular: "artgenossin",
    obliqueSingular: "artgenossen",
    genitiveSingular: "artgenossen"
  },
  "ärzt": {
    plural: "ärzte",
    singular: "arzt",
    feminineSingular: "ärztin",
    obliqueSingular: "arzt",
    genitiveSingular: "arztes"
  },
  "assistenzärzt": {
    plural: "assistenzärzte",
    singular: "assistenzarzt",
    feminineSingular: "assistenzärztin",
    obliqueSingular: "assistenzarzt",
    genitiveSingular: "assistenzarztes"
  },
  "augenzeug": {
    plural: "augenzeugen",
    singular: "augenzeuge",
    feminineSingular: "augenzeugin",
    obliqueSingular: "augenzeugen",
    genitiveSingular: "augenzeugen"
  },
  "bauer": {
    plural: "bauern",
    singular: "bauer",
    feminineSingular: "bauerin",
    obliqueSingular: "bauern",
    genitiveSingular: "bauern"
  },
  "bäuer": {
    plural: "bauern",
    singular: "bauer",
    feminineSingular: "bäuerin",
    obliqueSingular: "bauern",
    genitiveSingular: "bauern"
  },
  "bauherr": {
    plural: "bauherren",
    singular: "bauherr",
    feminineSingular: "bauherrin",
    obliqueSingular: "bauherrn",
    genitiveSingular: "bauherrn"
  },
  "bayer": {
    plural: "bayern",
    singular: "bayer",
    feminineSingular: "bayerin",
    obliqueSingular: "bayern",
    genitiveSingular: "bayern"
  },
  "biolog": {
    plural: "biologen",
    singular: "biologe",
    feminineSingular: "biologin",
    obliqueSingular: "biologen",
    genitiveSingular: "biologen"
  },
  "bogenschütz": {
    plural: "bogenschützen",
    singular: "bogenschütze",
    feminineSingular: "bogenschützin",
    obliqueSingular: "bogenschützen",
    genitiveSingular: "bogenschützen"
  },
  "brit": {
    plural: "briten",
    singular: "brite",
    feminineSingular: "britin",
    obliqueSingular: "briten",
    genitiveSingular: "briten"
  },
  "bulgar": {
    plural: "bulgaren",
    singular: "bulgare",
    feminineSingular: "bulgarin",
    obliqueSingular: "bulgaren",
    genitiveSingular: "bulgaren"
  },
  "chines": {
    plural: "chinesen",
    singular: "chinese",
    feminineSingular: "chinesin",
    obliqueSingular: "chinesen",
    genitiveSingular: "chinesen"
  },
  "dieb": {
    plural: "diebe",
    singular: "dieb",
    feminineSingular: "diebin",
    obliqueSingular: "dieb",
    genitiveSingular: "diebes"
  },
  "ethnolog": {
    plural: "ethnologen",
    singular: "ethnologe",
    feminineSingular: "ethnologin",
    obliqueSingular: "ethnologen",
    genitiveSingular: "ethnologen"
  },
  "französ": {
    plural: "franzosen",
    singular: "franzose",
    feminineSingular: "französin",
    obliqueSingular: "franzosen",
    genitiveSingular: "franzosen"
  },
  "frauenärzt": {
    plural: "frauenärzte",
    singular: "frauenarzt",
    feminineSingular: "frauenärztin",
    obliqueSingular: "frauenarzt",
    genitiveSingular: "frauenarztes"
  },
  "gäst": {
    plural: "gäste",
    singular: "gast",
    feminineSingular: "gästin",
    obliqueSingular: "gast",
    genitiveSingular: "gasts"
  },
  "genoss": {
    plural: "genossen",
    singular: "genosse",
    feminineSingular: "genossin",
    obliqueSingular: "genossen",
    genitiveSingular: "genossen"
  },
  "geolog": {
    plural: "geologen",
    singular: "geologe",
    feminineSingular: "geologin",
    obliqueSingular: "geologen",
    genitiveSingular: "geologen"
  },
  "gesell": {
    plural: "gesellen",
    singular: "geselle",
    feminineSingular: "gesellin",
    obliqueSingular: "gesellen",
    genitiveSingular: "gesellen"
  },
  "gesundheitsexpert": {
    plural: "gesundheitsexperten",
    singular: "gesundheitsexperte",
    feminineSingular: "gesundheitsexpertin",
    obliqueSingular: "gesundheitsexperten",
    genitiveSingular: "gesundheitsexperten"
  },
  "gött": {
    plural: "götter",
    singular: "gott",
    feminineSingular: "göttin",
    obliqueSingular: "gott",
    genitiveSingular: "gottes"
  },
  "griech": {
    plural: "griechen",
    singular: "grieche",
    feminineSingular: "griechin",
    obliqueSingular: "griechen",
    genitiveSingular: "griechen"
  },
  "gynäkolog": {
    plural: "gynäkologen",
    singular: "gynäkologe",
    feminineSingular: "gynäkologin",
    obliqueSingular: "gynäkologen",
    genitiveSingular: "gynäkologen"
  },
  "hausärzt": {
    plural: "hausärzte",
    singular: "hausarzt",
    feminineSingular: "hausärztin",
    obliqueSingular: "hausarzt",
    genitiveSingular: "hausarztes"
  },
  "ideolog": {
    plural: "ideologen",
    singular: "ideologe",
    feminineSingular: "ideologin",
    obliqueSingular: "ideologen",
    genitiveSingular: "ideologen"
  },
  "insass": {
    plural: "insassen",
    singular: "insasse",
    feminineSingular: "insassin",
    obliqueSingular: "insassen",
    genitiveSingular: "insassen"
  },
  "junggesell": {
    plural: "junggesellen",
    singular: "junggeselle",
    feminineSingular: "junggesellin",
    obliqueSingular: "junggesellen",
    genitiveSingular: "junggesellen"
  },
  "kleinbäuer": {
    plural: "kleinbauern",
    singular: "kleinbauer",
    feminineSingular: "kleinbäuerin",
    obliqueSingular: "kleinbauern",
    genitiveSingular: "kleinbauern"
  },
  "köch": {
    plural: "köche",
    singular: "koch",
    feminineSingular: "köchin",
    obliqueSingular: "koch",
    genitiveSingular: "kochs"
  },
  "kolleg": {
    plural: "kollegen",
    singular: "kollege",
    feminineSingular: "kollegin",
    obliqueSingular: "kollegen",
    genitiveSingular: "kollegen"
  },
  "kommiliton": {
    plural: "kommilitonen",
    singular: "kommilitone",
    feminineSingular: "kommilitonin",
    obliqueSingular: "kommilitonen",
    genitiveSingular: "kommilitonen"
  },
  "kompars": {
    plural: "komparsen",
    singular: "komparse",
    feminineSingular: "komparsin",
    obliqueSingular: "komparsen",
    genitiveSingular: "komparsen"
  },
  "kund": {
    plural: "kunden",
    singular: "kunde",
    feminineSingular: "kundin",
    obliqueSingular: "kunden",
    genitiveSingular: "kunden"
  },
  "kurd": {
    plural: "kurden",
    singular: "kurde",
    feminineSingular: "kurdin",
    obliqueSingular: "kurden",
    genitiveSingular: "kurden"
  },
  "landwirt": {
    plural: "landwirte",
    singular: "landwirt",
    feminineSingular: "landwirtin",
    obliqueSingular: "landwirt",
    genitiveSingular: "landwirtes"
  },
  "libanes": {
    plural: "libanesen",
    singular: "libanese",
    feminineSingular: "libanesin",
    obliqueSingular: "libanesen",
    genitiveSingular: "libanesen"
  },
  "logopäd": {
    plural: "logopäden",
    singular: "logopäde",
    feminineSingular: "logopädin",
    obliqueSingular: "logopäden",
    genitiveSingular: "logopäden"
  },
  "meteorolog": {
    plural: "meteorologen",
    singular: "meteorologe",
    feminineSingular: "meteorologin",
    obliqueSingular: "meteorologen",
    genitiveSingular: "meteorologen"
  },
  "muslim": {
    plural: "muslime",
    singular: "muslim",
    feminineSingular: "muslimin",
    obliqueSingular: "muslim",
    genitiveSingular: "muslim"
  },
  "nachbar": {
    plural: "nachbarn",
    singular: "nachbar",
    feminineSingular: "nachbarin",
    obliqueSingular: "nachbarn",
    genitiveSingular: "nachbarn"
  },
  "naturfreund": {
    plural: "naturfreunde",
    singular: "naturfreund",
    feminineSingular: "naturfreundin",
    obliqueSingular: "naturfreund",
    genitiveSingular: "naturfreundes"
  },
  "neukund": {
    plural: "neukunden",
    singular: "neukunde",
    feminineSingular: "neukundin",
    obliqueSingular: "neukunden",
    genitiveSingular: "neukunden"
  },
  "oberärzt": {
    plural: "oberärzte",
    singular: "oberarzt",
    feminineSingular: "oberärztin",
    obliqueSingular: "oberarzt",
    genitiveSingular: "oberarztes"
  },
  "ökolog": {
    plural: "ökologen",
    singular: "ökologe",
    feminineSingular: "ökologin",
    obliqueSingular: "ökologen",
    genitiveSingular: "ökologen"
  },
  "pädagog": {
    plural: "pädagogen",
    singular: "pädagoge",
    feminineSingular: "pädagogin",
    obliqueSingular: "pädagogen",
    genitiveSingular: "pädagogen"
  },
  "paketbot": {
    plural: "paketboten",
    singular: "paketbote",
    feminineSingular: "paketbotin",
    obliqueSingular: "paketboten",
    genitiveSingular: "paketboten"
  },
  "parteifreund": {
    plural: "parteifreunde",
    singular: "parteifreund",
    feminineSingular: "parteifreundin",
    obliqueSingular: "parteifreund",
    genitiveSingular: "parteifreundes"
  },
  "parteikolleg": {
    plural: "parteikollegen",
    singular: "parteikollege",
    feminineSingular: "parteikollegin",
    obliqueSingular: "parteikollegen",
    genitiveSingular: "parteikollegen"
  },
  "patholog": {
    plural: "pathologen",
    singular: "pathologe",
    feminineSingular: "pathologin",
    obliqueSingular: "pathologen",
    genitiveSingular: "pathologen"
  },
  "psycholog": {
    plural: "psychologen",
    singular: "psychologe",
    feminineSingular: "psychologin",
    obliqueSingular: "psychologen",
    genitiveSingular: "psychologen"
  },
  "rechtsanwält": {
    plural: "rechtsanwälte",
    singular: "rechtsanwalt",
    feminineSingular: "rechtsanwältin",
    obliqueSingular: "rechtsanwalt",
    genitiveSingular: "rechtsanwaltes"
  },
  "rival": {
    plural: "rivalen",
    singular: "rivale",
    feminineSingular: "rivalin",
    obliqueSingular: "rivalen",
    genitiveSingular: "rivalen"
  },
  "rumän": {
    plural: "rumänen",
    singular: "rumäne",
    feminineSingular: "rumänin",
    obliqueSingular: "rumänen",
    genitiveSingular: "rumänen"
  },
  "russ": {
    plural: "russen",
    singular: "russe",
    feminineSingular: "russin",
    obliqueSingular: "russen",
    genitiveSingular: "russen"
  },
  "schirmherr": {
    plural: "schirmherren",
    singular: "schirmherr",
    feminineSingular: "schirmherrin",
    obliqueSingular: "schirmherrn",
    genitiveSingular: "schirmherrn"
  },
  "schöff": {
    plural: "schöffen",
    singular: "schöffe",
    feminineSingular: "schöffin",
    obliqueSingular: "schöffen",
    genitiveSingular: "schöffen"
  },
  "schulfreund": {
    plural: "schulfreunde",
    singular: "schulfreund",
    feminineSingular: "schulfreundin",
    obliqueSingular: "schulfreund",
    genitiveSingular: "schulfreundes"
  },
  "schütz": {
    plural: "schützen",
    singular: "schütze",
    feminineSingular: "schützin",
    obliqueSingular: "schützen",
    genitiveSingular: "schützen"
  },
  "sitznachbar": {
    plural: "sitznachbarn",
    singular: "sitznachbar",
    feminineSingular: "sitznachbarin",
    obliqueSingular: "sitznachbarn",
    genitiveSingular: "sitznachbarn"
  },
  "sklav": {
    plural: "sklaven",
    singular: "sklave",
    feminineSingular: "sklavin",
    obliqueSingular: "sklaven",
    genitiveSingular: "sklaven"
  },
  "sonderpädagog": {
    plural: "sonderpädagogen",
    singular: "sonderpädagoge",
    feminineSingular: "sonderpädagogin",
    obliqueSingular: "sonderpädagogen",
    genitiveSingular: "sonderpädagogen"
  },
  "sozialpädagog": {
    plural: "sozialpädagogen",
    singular: "sozialpädagoge",
    feminineSingular: "sozialpädagogin",
    obliqueSingular: "sozialpädagogen",
    genitiveSingular: "sozialpädagogen"
  },
  "soziolog": {
    plural: "soziologen",
    singular: "soziologe",
    feminineSingular: "soziologin",
    obliqueSingular: "soziologen",
    genitiveSingular: "soziologen"
  },
  "staatsanwält": {
    plural: "staatsanwälte",
    singular: "staatsanwalt",
    feminineSingular: "staatsanwältin",
    obliqueSingular: "staatsanwalt",
    genitiveSingular: "staatsanwaltes"
  },
  "stammkund": {
    plural: "stammkunden",
    singular: "stammkunde",
    feminineSingular: "stammkundin",
    obliqueSingular: "stammkunden",
    genitiveSingular: "stammkunden"
  },
  "steinmetz": {
    plural: "steinmetze",
    singular: "steinmetz",
    feminineSingular: "steinmetzin",
    obliqueSingular: "steinmetzen",
    genitiveSingular: "steinmetzen"
  },
  "teamkolleg": {
    plural: "teamkollegen",
    singular: "teamkollege",
    feminineSingular: "teamkollegin",
    obliqueSingular: "teamkollegen",
    genitiveSingular: "teamkollegen"
  },
  "theaterpädagog": {
    plural: "theaterpädagogen",
    singular: "theaterpädagoge",
    feminineSingular: "theaterpädagogin",
    obliqueSingular: "theaterpädagogen",
    genitiveSingular: "theaterpädagogen"
  },
  "theolog": {
    plural: "theologen",
    singular: "theologe",
    feminineSingular: "theologin",
    obliqueSingular: "theologen",
    genitiveSingular: "theologen"
  },
  "tierärzt": {
    plural: "tierärzte",
    singular: "tierarzt",
    feminineSingular: "tierärztin",
    obliqueSingular: "tierarzt",
    genitiveSingular: "tierarztes"
  },
  "tierfreund": {
    plural: "tierfreunde",
    singular: "tierfreund",
    feminineSingular: "tierfreundin",
    obliqueSingular: "tierfreund",
    genitiveSingular: "tierfreundes"
  },
  "tischnachbar": {
    plural: "tischnachbarn",
    singular: "tischnachbar",
    feminineSingular: "tischnachbarin",
    obliqueSingular: "tischnachbar",
    genitiveSingular: "tischnachbars"
  },
  "türk": {
    plural: "türken",
    singular: "türke",
    feminineSingular: "türkin",
    obliqueSingular: "türken",
    genitiveSingular: "türken"
  },
  "vietnames": {
    plural: "vietnamesen",
    singular: "vietnamese",
    feminineSingular: "vietnamesin",
    obliqueSingular: "vietnamesen",
    genitiveSingular: "vietnamesen"
  },
  "virolog": {
    plural: "virologen",
    singular: "virologe",
    feminineSingular: "virologin",
    obliqueSingular: "virologen",
    genitiveSingular: "virologen"
  },
  "weggefährt": {
    plural: "weggefährten",
    singular: "weggefährte",
    feminineSingular: "weggefährtin",
    obliqueSingular: "weggefährten",
    genitiveSingular: "weggefährten"
  },
  "zahnärzt": {
    plural: "zahnärzte",
    singular: "zahnarzt",
    feminineSingular: "zahnärztin",
    obliqueSingular: "zahnarzt",
    genitiveSingular: "zahnarztes"
  },
  "zeitgenoss": {
    plural: "zeitgenossen",
    singular: "zeitgenosse",
    feminineSingular: "zeitgenossin",
    obliqueSingular: "zeitgenossen",
    genitiveSingular: "zeitgenossen"
  },
  "zeitzeug": {
    plural: "zeitzeugen",
    singular: "zeitzeuge",
    feminineSingular: "zeitzeugin",
    obliqueSingular: "zeitzeugen",
    genitiveSingular: "zeitzeugen"
  },
  "zeug": {
    plural: "zeugen",
    singular: "zeuge",
    feminineSingular: "zeugin",
    obliqueSingular: "zeugen",
    genitiveSingular: "zeugen"
  }
});

export const generatedPersonFormCount =
  unchangedForms.size +
  weakEnForms.size +
  pluralEForms.size +
  pluralEnForms.size +
  pluralSForms.size +
  Object.keys(specialForms).length;

function regularForms(
  base: string,
  plural: string,
  obliqueSingular = base,
  genitiveSingular = `${base}s`
): GeneratedPersonForms {
  return {
    plural,
    singular: base,
    feminineSingular: `${base}in`,
    obliqueSingular,
    genitiveSingular
  };
}

export function getGeneratedPersonForms(
  normalizedBase: string
): GeneratedPersonForms | undefined {
  if (unchangedForms.has(normalizedBase)) {
    return regularForms(normalizedBase, normalizedBase);
  }
  if (weakEnForms.has(normalizedBase)) {
    const inflected = `${normalizedBase}en`;
    return regularForms(normalizedBase, inflected, inflected, inflected);
  }
  if (pluralEForms.has(normalizedBase)) {
    return regularForms(normalizedBase, `${normalizedBase}e`);
  }
  if (pluralEnForms.has(normalizedBase)) {
    return regularForms(normalizedBase, `${normalizedBase}en`);
  }
  if (pluralSForms.has(normalizedBase)) {
    return regularForms(normalizedBase, `${normalizedBase}s`);
  }
  return specialForms[normalizedBase];
}
