import type { GeneratedPersonForms } from "./generated-person-lexicon";

// Quellenneutraler und einzeln geprüfter Zusatzbestand aus Welle 83.
// Ableitungen gelten ausschließlich für die exakt aufgeführten Personenbasen.
const unchangedForms: ReadonlySet<string> = new Set([
  "aachener",
  "aargauer",
  "abholer",
  "achtklässler",
  "alleingänger",
  "allrounder",
  "altwiener",
  "amsterdamer",
  "anti-raucher",
  "ausbildungsabbrecher",
  "autopfandleiher",
  "badener",
  "berufskomiker",
  "bezahler",
  "bieler",
  "bittsteller",
  "bootslenker",
  "braunschweiger",
  "bummler",
  "bundesberner",
  "bundesliga-handballer",
  "champagnertrinker",
  "chefbanker",
  "chefdenker",
  "cloppenburger",
  "cola-trinker",
  "computer-einsteiger",
  "crowdsurfer",
  "curler",
  "datenbroker",
  "deutsch-afrikaner",
  "drogenlenker",
  "durchschnittszürcher",
  "eichsfelder",
  "elftklässler",
  "ennetbadener",
  "ermöglicher",
  "essener",
  "ex-boxer",
  "ex-komiker",
  "expresszusteller",
  "fahrzeuglenker",
  "faktenleugner",
  "festordner",
  "filmkomiker",
  "flachdenker",
  "fuldaer",
  "geisterjogger",
  "gelegenheitsraucher",
  "gifhorner",
  "grabräuber",
  "grazer",
  "grevener",
  "hannoveraner",
  "hauptbeeinflusser",
  "hauptzahler",
  "hersfelder",
  "hinterwäldler",
  "hobbybläser",
  "hobbyjogger",
  "hornbläser",
  "internet-broker",
  "internet-komiker",
  "interneteinsteiger",
  "jobeinsteiger",
  "jugendfußballer",
  "jungbanker",
  "junggewerkschafter",
  "junglenker",
  "kaffeetrinker",
  "katzenhalter",
  "kiewer",
  "kirchgänger",
  "kitesurfer",
  "klardenker",
  "kleinbasler",
  "klippenspringer",
  "klotener",
  "kopenhagener",
  "kulturgenießer",
  "landstreicher",
  "lehrabgänger",
  "lehrergewerkschafter",
  "lerner",
  "leugner",
  "lübecker",
  "medienwissenschafter",
  "mitdenker",
  "motorradlenker",
  "münsteraner",
  "nachwuchsboxer",
  "nachwuchskomiker",
  "nachwuchssurfer",
  "nacktschläfer",
  "negativdenker",
  "neuntklässler",
  "nichtskönner",
  "nordafrikaner",
  "nordbadener",
  "nordostschweizer",
  "normalschläfer",
  "nutztierhalter",
  "oberaargauer",
  "oberösterreicher",
  "ostschweizer",
  "pfeifenraucher",
  "pkw-lenker",
  "reformverweiger",
  "regelhüter",
  "rigaer",
  "rückenschläfer",
  "saalordner",
  "schnelldenker",
  "sechstklässler",
  "selbstdenker",
  "staatenlenker",
  "staatsanbeter",
  "staatsleugner",
  "starkomiker",
  "studienabbrecher",
  "supermarkträuber",
  "trierer",
  "vaduzer",
  "vorausdenker",
  "wahlschweizer",
  "warschauer",
  "weingenießer",
  "weintrinker",
  "weltrekordhalter",
  "westafrikaner",
  "whiskytrinker",
  "wiesbadener",
  "wismarer",
  "wissenschaftsleugner",
  "wolfenbütteler",
  "würzburger",
  "zagreber",
  "zehntklässler",
  "zigarettenraucher",
  "zukunftsdenker",
  "zweiradlenker",
  "zwölftklässler"
]);

export const reviewedPersonFormCountWave83 = unchangedForms.size;

export function getReviewedPersonFormsWave83(
  normalizedBase: string
): GeneratedPersonForms | undefined {
  if (!unchangedForms.has(normalizedBase)) {
    return undefined;
  }
  return {
    plural: normalizedBase,
    singular: normalizedBase,
    feminineSingular: `${normalizedBase}in`,
    obliqueSingular: normalizedBase,
    genitiveSingular: `${normalizedBase}s`
  };
}
