import type { GeneratedPersonForms } from "./generated-person-lexicon";

// Einzelne geprüfte Personenwortstämme; keine verallgemeinerte Suffixregel.
// Die Flexionsklassen gelten nur für exakt eingetragene Basen.
// Maskuliner Plural ohne Endungsänderung.
const unchanged: ReadonlySet<string> = new Set([
  "3d-computer-aided-design-entwickler",
  "3d-designer",
  "3d-produktentwickler",
  "abfüllanlagenbediener",
  "abfüllanlagenfahrer",
  "aktionskünstler",
  "altgriechischlehrer",
  "anlagenbediener",
  "anlagenführer",
  "anlagenmechaniker",
  "anlagentechniker",
  "apparatebauer",
  "aquakulturtechniker",
  "arbeitsplaner",
  "aufbereitungsmechaniker",
  "aufsteller",
  "aufzuchttechniker",
  "ausbildungsoffizier",
  "bankettmanager",
  "bankettplaner",
  "bauleiter",
  "baustoffhändler",
  "bauwerksmechaniker",
  "bediener",
  "begutachter",
  "bekleidungstechniker",
  "berufskraftfahrer",
  "bildbeschreiber",
  "binnenfischer",
  "cad-musterdesigner",
  "cad-techniker",
  "cad-zeichner",
  "cheftierpfleger",
  "chembalobauer",
  "chemietechniker",
  "chemikalienhändler",
  "deckshelfer",
  "dienstleistungsmanager",
  "drogenberater",
  "drucker",
  "drucktechniker",
  "einkaufsbegleiter",
  "einrichter",
  "einsatzleiter",
  "endbearbeiter",
  "entwicklungsleiter",
  "entwicklungsmanager",
  "erntearbeiter",
  "exportmanager",
  "exportsachbearbeiter",
  "fachberater",
  "facherzieher",
  "fachinformatiker",
  "fachkrankenpfleger",
  "fachleiter",
  "fahrzeugbaumechaniker",
  "fahrzeugführer",
  "familienpfleger",
  "feldvermesser",
  "fernsehsprecher",
  "fernsehtechniker",
  "fertigungskontrolltechniker",
  "fertigungsleiter",
  "filialkundenberater",
  "fischerntetechniker",
  "fitnessberater",
  "flaschenabfüllanlagenbediener",
  "fluggerätemechaniker",
  "frachtarbeiter",
  "frachtführer",
  "funkbediener",
  "gemüseabfüller",
  "gemüsehändler",
  "gemüseverarbeiter",
  "gemüseverkäufer",
  "generalunternehmer",
  "geschlechtsbestimmer",
  "glasveredler",
  "glaswarenhändler",
  "hair-designer",
  "haltungstechniker",
  "hardware-designer",
  "harmoniumbauer",
  "hartwarenverkäufer",
  "hauswirtschaftsleiter",
  "helpdesk-mitarbeiter",
  "hilfsarbeiter",
  "hilfstrainer",
  "holzmechaniker",
  "holztechniker",
  "hubschraubervermieter",
  "ikt-lehrer",
  "individualkundenberater",
  "industrieelektriker",
  "industriekeramiker",
  "industriemeister",
  "installationstechniker",
  "instandhaltungsmechaniker",
  "instandhaltungstechniker",
  "it-lehrer",
  "kapazitätsplaner",
  "kaschiermaschinenführer",
  "kfz-techniker",
  "kleintransporter-lieferfahrer",
  "klimamechaniker",
  "knowledge-manager",
  "kochwärter",
  "konstruktionsmechaniker",
  "konstruktionsmitarbeiter",
  "kostümschneider",
  "kraftfahrzeugmechatroniker",
  "kreislaufanlagentechniker",
  "kundendienstleiter",
  "kunsterzieher",
  "labortechniker",
  "lacktechniker",
  "lateinlehrer",
  "leitstandsfahrer",
  "lichtdesigner",
  "logistikleiter",
  "logistikmanager",
  "lüftungsanlagenbauer",
  "maschinenaufseher",
  "materialdesigner",
  "materialverwalter",
  "mathematiklehrer",
  "mediengestalter",
  "medienverkäufer",
  "metallarbeiter",
  "metalldesigner",
  "metalltechniker",
  "modellbaumechaniker",
  "modenäher",
  "montagearbeiter",
  "motorenmechaniker",
  "munitionshändler",
  "musterdesigner",
  "nachhaltigkeits-servicemanager",
  "netzkäfigtechniker",
  "ordner",
  "outdoor-trainer",
  "perforierer",
  "pflanzenhändler",
  "pharmawerker",
  "pinselmacher",
  "praxisanleiter",
  "presser",
  "produktentwickler",
  "produktionsarbeiter",
  "produktionsberater",
  "produktionsmanager",
  "produktionsmitarbeiter",
  "produktionsteamleiter",
  "produktprüfer",
  "programmgestalter",
  "protokollführer",
  "prozesssteuerungstechniker",
  "pyrotechnik-aufseher",
  "qualitätssicherungsmanager",
  "qualitätstechniker",
  "regionalplaner",
  "reparaturtechniker",
  "risikoanalytiker",
  "risikomanager",
  "risk-manager",
  "rollenmaschinenarbeiter",
  "rostschutztechniker",
  "saiteninstrumentenbauer",
  "sammlungsmanager",
  "sanitärtechniker",
  "sattler",
  "schaltungsdesigner",
  "schichtleiter",
  "schiffsführer",
  "schiffsoffizier",
  "schlächter",
  "schlüsselmacher",
  "schreibwarenverkäufer",
  "schuhtechniker",
  "serviceleiter",
  "servicetechniker",
  "sicherheitsmanager",
  "sicherheitstechniker",
  "spezialeffekt-künstler",
  "spezialeffekt-techniker",
  "steuerer",
  "stoffprüfer",
  "straßenarbeiter",
  "systemtechniker",
  "tabakwarenhändler",
  "telefonberater",
  "textilgestalter",
  "theorielehrer",
  "tierzuchttechniker",
  "tourbegleiter",
  "trader",
  "trickfilmzeichner",
  "uhrenverkäufer",
  "umweltmanagementbeauftragter",
  "umweltprojektleiter",
  "underwriter",
  "verankerungstechniker",
  "verfahrenstechniker",
  "vermögensberater",
  "video-techniker",
  "vollstreckungssachbearbeiter",
  "warenzusteller",
  "wartungsplaner",
  "wartungstechniker",
  "weiterbildner",
  "wirkstoffchemiker",
  "zahnarzthelfer",
  "zerspanungsfacharbeiter",
  "zoomitarbeiter",
  "zuchtmanager",
  "zuchttechniker",
  "zupfinstrumentenmacher",
  "zuschneider"
]);

// Maskuliner Plural mit -e.
const pluralE: ReadonlySet<string> = new Set([
  "berufschauffeur",
  "cad-modelleur",
  "damenfriseur",
  "drainageingenieur",
  "elektroingenieur",
  "erdgasingenieur",
  "fachingenieur",
  "hardware-ingenieur",
  "inbetriebnahmeingenieur",
  "leasingfachwirt",
  "lüftungsanlageninstallateur",
  "maßekontrolleur",
  "motoreningenieur",
  "planungsingenieur",
  "polier",
  "projektingenieur",
  "qualitätssicherungsingenieur",
  "raumfahrtingenieur",
  "sicherheitsingenieur",
  "sicherheitskontrolleur",
  "softwareingenieur",
  "systemingenieur",
  "werkstoffingenieur",
  "zivilingenieur"
]);

// Maskuliner Plural mit -en.
const pluralEn: ReadonlySet<string> = new Set([
  "animator",
  "compliance-koordinator",
  "containerkoordinator",
  "fachautor",
  "kälteinspektor",
  "klimaanlageninspektor",
  "logistikkoordinator",
  "planungsinspektor",
  "produktionskoordinator",
  "programm-koordinator",
  "sicherheitsinspektor",
  "transkriptor",
  "transportkoordinator",
  "verkehrskoordinator"
]);

// Schwache Deklination mit -en in obliquen Singularfällen.
const weakEn: ReadonlySet<string> = new Set([
  "applikationsspezialist",
  "bewegungstherapeut",
  "evaluationsspezialist",
  "fachassistent",
  "fachlagerist",
  "fernsehproduzent",
  "finanzreferent",
  "gesichtschirurg",
  "hochschuldozent",
  "jugendlichenpsychotherapeut",
  "laborassistent",
  "laboratoriumsassistent",
  "lehrassistent",
  "praxisassistent",
  "radiologieassistent",
  "reporting-analyst",
  "sprachtherapeut",
  "teamassistent",
  "telefonist",
  "tv-produzent",
  "videolaborant",
  "wachmaschinist",
  "zuchtassistent"
]);

export const reviewedPersonFormCountWave92 =
  unchanged.size + pluralE.size + pluralEn.size + weakEn.size;

export function getReviewedPersonFormsWave92(normalizedBase: string): GeneratedPersonForms | undefined {
  let plural: string;
  let weak = false;
  if (unchanged.has(normalizedBase)) plural = normalizedBase;
  else if (pluralE.has(normalizedBase)) plural = `${normalizedBase}e`;
  else if (pluralEn.has(normalizedBase)) plural = `${normalizedBase}en`;
  else if (weakEn.has(normalizedBase)) {
    plural = `${normalizedBase}en`;
    weak = true;
  } else return undefined;

  return {
    plural,
    singular: normalizedBase,
    feminineSingular: `${normalizedBase}in`,
    obliqueSingular: weak ? plural : normalizedBase,
    genitiveSingular: weak ? plural : `${normalizedBase}s`
  };
}
