import type { GeneratedPersonForms } from "./generated-person-lexicon";

// Exakte freigegebene Personenbasen, nach ihren geprüften Flexionsformen getrennt.
// Keine Ableitung für fremde Wortstämme oder unbelegte Zusammensetzungen.
// Unveränderter maskuliner Plural.
const pluralUnveraendert: ReadonlySet<string> = new Set([
  "abgrater",
  "ablader",
  "ablänger",
  "alkoholmischer",
  "anodisierer",
  "anspruchsschätzer",
  "autoverwerter",
  "bandsäger",
  "baugeräteschlosser",
  "behältermontierer",
  "berufsfussballer",
  "besamer",
  "betongiesser",
  "betonierer",
  "bevölkerungsstatistiker",
  "bildungsstatistiker",
  "blattbinder",
  "bodypainter",
  "bodypiercer",
  "bohrhäuer",
  "bootsausrüster",
  "brennereiaufseher",
  "bronzierer",
  "broschürenverteiler",
  "brückenaufseher",
  "chemiefaserspinner",
  "chemischbügler",
  "cnc-stanzer",
  "cocktailbarmixer",
  "dämpfer",
  "desktop-publisher",
  "devisenbroker",
  "dokumentencontroller",
  "düngermischer",
  "eb-schweisser",
  "eisenentroster",
  "elektronenstrahlschweisser",
  "elektroplattierer",
  "extrudierer",
  "fact-checker",
  "fadenspinner",
  "faserspritzer",
  "fassadendecker",
  "fassader",
  "feiler",
  "fellgerber",
  "fellsortierer",
  "feuerschlucker",
  "film-toncutter",
  "finanzbroker",
  "finanzstatistiker",
  "formengiesser",
  "fotografiedrucker",
  "garnspuler",
  "garnzwirner",
  "gebäudeschätzer",
  "gefahrgutlenker",
  "geflügelgeschlechtsfinder",
  "gehaltsverrechner",
  "gerüster",
  "gesellschaftsstatistiker",
  "gesundheitsstatistiker",
  "glasurbrenner",
  "glaszieher",
  "granitbohrer",
  "granithauer",
  "granulatmischer",
  "greissler",
  "groundrigger",
  "gummistanzer",
  "gussputzer",
  "halal-fleischer",
  "halal-fleischhauer",
  "halal-metzger",
  "halal-schlachter",
  "handgiesser",
  "heeresflieger",
  "heissfoliendrucker",
  "holzfeiler",
  "hörfunkproducer",
  "hühnerfänger",
  "industrieschlosser",
  "inkassogebühreneinheber",
  "investmentbroker",
  "jagdaufseher",
  "jagdhüter",
  "kaffeebrenner",
  "kakaobohnenbrater",
  "kakaobohnenbrenner",
  "kalfaterer",
  "kanalräumer",
  "katastergeometer",
  "katastervermesser",
  "keilriemenausrüster",
  "keilriemenbeschichter",
  "keramgiesser",
  "keramikgiesser",
  "keramikpresser",
  "kfz-wäscher",
  "kiesstrahlbläser",
  "kokillengiesser",
  "koscher-fleischer",
  "koscher-metzger",
  "koscher-schlachter",
  "kostenschätzer",
  "kostümentwerfer",
  "kunststoffextrudierer",
  "kunststofffeiler",
  "kunststoffspritzmaschineneinsteller",
  "kunststofftemperer",
  "kupferschlosser",
  "lackmischer",
  "ladner",
  "lagerwirtschafter",
  "landwirtschaftsstatistiker",
  "laserschweisser",
  "lederwarenfinisher",
  "leichtmetallgiesser",
  "liegenschaftsschätzer",
  "lohnverrechner",
  "mälzereiaufseher",
  "marmorhauer",
  "maschinenöler",
  "maschinenzwicker",
  "massenberechner",
  "massengutfüller",
  "meeresbotaniker",
  "messerwerfer",
  "metallfeiler",
  "metallgiesser",
  "metalllöter",
  "metallschweisser",
  "metallsortierer",
  "militärfürsorger",
  "minenräumer",
  "möbelmontierer",
  "mülllader",
  "mülltrenner",
  "multimedia-storyboarder",
  "oberlederschärfer",
  "öler",
  "otoplastiker",
  "parkaufseher",
  "pflastersteinspalter",
  "physikstatistiker",
  "plastikspritzer",
  "plattenbrecher",
  "porzellangiesser",
  "profifussballer",
  "prospektzusteller",
  "prothetiker",
  "punktschweisser",
  "rechnungseintreiber",
  "reduzierwalzer",
  "regaleinräumer",
  "reifenreparierer",
  "rostentferner",
  "sandstrahlmattierer",
  "schächter",
  "schadensabschätzer",
  "schadstoffsanierer",
  "schafhüter",
  "schieferbohrer",
  "schieferhauer",
  "schiffsstauer",
  "schiffstakler",
  "schmuckentwerfer",
  "schneeräumer",
  "schnittgradierer",
  "schuhverpacker",
  "schulstatistiker",
  "schwenker",
  "seifentrockner",
  "sprachheilkundler",
  "stand-up-komiker",
  "steinbossierer",
  "steingutbrenner",
  "steinschärfer",
  "steuervollzieher",
  "stoffverpacker",
  "storyboarder",
  "strahler",
  "strassenfeger",
  "strassenkehrer",
  "synchroncutter",
  "synthetikspinner",
  "tabakblattbinder",
  "tabakblattknüpfer",
  "tabakblattsortierer",
  "taschner",
  "tauchmetallisierer",
  "textilentwerfer",
  "textilflechter",
  "tieraufpasser",
  "toncutter",
  "tonmischer",
  "tonwarenbrenner",
  "touristenunterhalter",
  "tütenkleber",
  "verkupferer",
  "vermesser",
  "vermessungsstatistiker",
  "verschieber",
  "verschleisser",
  "versicherungsstatistiker",
  "versilberer",
  "wahlstatistiker",
  "waldhüter",
  "wassermesser",
  "web-master",
  "werbemittelverteiler",
  "werkstattschlosser",
  "wetteransager",
  "winder",
  "wollgarnspinner",
  "wollgarnspuler",
  "wollgarnzwirner",
  "zahnprothetiker",
  "zellgenetiker",
  "zementierer",
  "ziegelgiesser",
  "zugfertigsteller"
]);

// Regulärer Plural mit -e.
const pluralMitE: ReadonlySet<string> = new Set([
  "appreteur",
  "auslagendekorateur",
  "bataillonskommandeur",
  "dekontaminateur",
  "elektrolysezellenfabrikateur",
  "emailleur",
  "extrudeur",
  "flugzeugtankwart",
  "forstwart",
  "fussjongleur",
  "geschwaderkommandeur",
  "hundedresseur",
  "instrumentenwart",
  "klärwart",
  "lederappreteur",
  "magazineur",
  "reifenvulkaniseur",
  "schaufensterdekorateur",
  "schiefermischanlagenwart",
  "stoffappreteur",
  "tiertransporteur",
  "verifikateur",
  "viehtransporteur",
  "voltigeur",
  "zentralbankgouverneur"
]);

// Regulärer Plural mit -en.
const pluralMitEn: ReadonlySet<string> = new Set([
  "antiquitätenrestaurator",
  "anwendungskonfigurator",
  "autofahrinstruktor",
  "autoinstruktor",
  "computer-animator",
  "epilator",
  "exekutor",
  "fahrschulinstruktor",
  "fahrtechnikinstruktor",
  "fahrzeugrestaurator",
  "hausautomationsintegrator",
  "immobilientaxator",
  "it-anwendungskonfigurator",
  "kfz-fahrinstruktor",
  "lichtpult-operator",
  "metall-am-operator",
  "motorradinstruktor",
  "musikinstrumentenrestaurator",
  "oldtimer-restaurator",
  "oldtimerrestaurator",
  "prägepresse-operator",
  "scan-operator",
  "steadicam-operator",
  "stop-motion-animator",
  "systemkonfigurator",
  "translator"
]);

// Schwache Deklination mit -en auch in obliquen Singularfällen.
const schwacheFlexion: ReadonlySet<string> = new Set([
  "advokat",
  "anthropogeograf",
  "antipodist",
  "buchhaltungsanalyst",
  "bühneninspizient",
  "bühnenkampfchoreograph",
  "call-center-analyst",
  "dividendenanalyst",
  "energieanalyst",
  "equilibrist",
  "fakturist",
  "figurant",
  "fingernagel-stylist",
  "gambist",
  "grossist",
  "haarstylist",
  "handstandartist",
  "haushaltsanalyst",
  "hochseilartist",
  "humangeograf",
  "hydrograf",
  "infanterist",
  "inkassant",
  "kartolithograf",
  "klarinettist",
  "kraftakrobat",
  "kuponanalyst",
  "lexikograf",
  "librettist",
  "logistik-analyst",
  "luftverschmutzungsanalyst",
  "make-up-artist",
  "markforschungsanalyst",
  "marktforschungsanalyst",
  "mergers-and-acquisitions-analyst",
  "nachhaltigkeitsanalyst",
  "nachkalkulant",
  "orthodontist",
  "percussionist",
  "pharmakovigilant",
  "physiogeograf",
  "prosthodontist",
  "querflötist",
  "rechtskonsulent",
  "schönheits-stylist",
  "software-analyst",
  "softwareanalyst",
  "spiritist",
  "strassenartist",
  "telekommunikationsanalyst",
  "telepath",
  "textilkolorist",
  "tier-osteopath",
  "tierosteopath",
  "trafikant",
  "unternehmensanalyst",
  "ventriloquist",
  "vergütungsanalyst",
  "verteidigungsanalyst",
  "vokalist",
  "wirtschaftskonsulent",
  "zeitungskolumnist",
  "zolldeklarant"
]);

export const reviewedPersonFormCountWave90 =
  pluralUnveraendert.size + pluralMitE.size + pluralMitEn.size + schwacheFlexion.size;

function formen(
  basis: string,
  plural: string,
  schwach = false
): GeneratedPersonForms {
  return {
    plural,
    singular: basis,
    feminineSingular: `${basis}in`,
    obliqueSingular: schwach ? plural : basis,
    genitiveSingular: schwach ? plural : `${basis}s`
  };
}

export function getReviewedPersonFormsWave90(
  normalizedBase: string
): GeneratedPersonForms | undefined {
  if (pluralUnveraendert.has(normalizedBase)) {
    return formen(normalizedBase, normalizedBase);
  }
  if (pluralMitE.has(normalizedBase)) {
    return formen(normalizedBase, `${normalizedBase}e`);
  }
  if (pluralMitEn.has(normalizedBase)) {
    return formen(normalizedBase, `${normalizedBase}en`);
  }
  if (schwacheFlexion.has(normalizedBase)) {
    return formen(normalizedBase, `${normalizedBase}en`, true);
  }
  return undefined;
}
