import type { GeneratedPersonForms } from "./generated-person-lexicon";

// Quellenneutraler, exakt freigegebener Zusatzbestand aus Welle 60.
// Die Mengen sind reine Allow-Lists und erzeugen keine generische Suffixfreigabe.
const unchangedForms: ReadonlySet<string> = new Set([
  "abteilungssteiger",
  "altbausanierer",
  "ansager",
  "antiquitätenschätzer",
  "autowäscher",
  "bandstahlhärter",
  "baumsanierer",
  "bautenbeschichter",
  "bernsteinschnitzer",
  "beschichter",
  "betonfertigteilemontierer",
  "betonsanierer",
  "betonstahlflechter",
  "bildschnitzer",
  "binnenschiffer",
  "bleilöter",
  "brandsteiger",
  "chemischwäscher",
  "drahtflechter",
  "drahtgeflechtstricker",
  "drahthärter",
  "drahtspinner",
  "drahtumspinner",
  "drahtverflechter",
  "einschmelzer",
  "eisenflechter",
  "eisenschmelzer",
  "elektrogerätemontierer",
  "elektrolöter",
  "elektromontierer",
  "elektronikteilemontierer",
  "elektroofenschmelzer",
  "elektroteilemontierer",
  "elfenbeinschnitzer",
  "fahrzeugwäscher",
  "fassadenwäscher",
  "federmontierer",
  "feinledergerber",
  "feinspinner",
  "feinstrumpfstricker",
  "fernsehansager",
  "fertigmontierer",
  "flachstricker",
  "flechter",
  "flugansager",
  "flussschiffer",
  "fotosatzmontierer",
  "fährschiffer",
  "gerber",
  "geschirrwäscher",
  "glacegerber",
  "glaceledergerber",
  "glasschmelzer",
  "glaswäscher",
  "glühlampenmontierer",
  "gummistrumpfstricker",
  "gummiumspinner",
  "handmaschinenstricker",
  "handschuhledergerber",
  "handstricker",
  "hartlöter",
  "hochofenschmelzer",
  "holzbildschnitzer",
  "holzschnitzer",
  "holzspielwarenschnitzer",
  "härter",
  "induktionshärter",
  "jacquardmaschinenstricker",
  "jacquardstricker",
  "kabelflechter",
  "kabellöter",
  "kalksandsteinhärter",
  "kammgarnspinner",
  "keramikschmelzer",
  "korbflechter",
  "korbmöbelflechter",
  "kraftfahrzeugwäscher",
  "kunstfaserspinner",
  "kunstschnitzer",
  "kunstschätzer",
  "kunststoffbeschichter",
  "küstenschiffer",
  "lagersteiger",
  "ledergerber",
  "leichenwäscher",
  "litzenflechter",
  "löter",
  "maschinen-reviersteiger",
  "maschinendrahtflechter",
  "messerhärter",
  "metallhärter",
  "metalloberflächenbeschichter",
  "metallschmelzer",
  "metallwäscher",
  "montierer",
  "möbelflechter",
  "nachrichtenansager",
  "netzmontierer",
  "oberflächenbeschichter",
  "objektbeschichter",
  "partikulierschiffer",
  "pfandschätzer",
  "portefeuilleledergerber",
  "radioansager",
  "repro-bogenmontierer",
  "riemenledergerber",
  "ringspinner",
  "rohrflechter",
  "rotgerber",
  "rundfunkansager",
  "rundjacquardstricker",
  "rundmaschinenstricker",
  "rundstricker",
  "röhrenmontierer",
  "sanierer",
  "sattlerledergerber",
  "scherenhärter",
  "schichtsteiger",
  "schießsteiger",
  "schmelzer",
  "schneidwarenhärter",
  "schnitzer",
  "schornsteinsanierer",
  "schätzer",
  "seeschiffer",
  "seitenmontierer",
  "sicherheitssteiger",
  "siebdruckmontierer",
  "sporthochseeschiffer",
  "stahlflechter",
  "stahlhärter",
  "staubschutzsteiger",
  "staubsteiger",
  "steiger",
  "stoffwäscher",
  "streichgarnspinner",
  "stricker",
  "strohwarenflechter",
  "strumpfstricker",
  "studioansager",
  "stuhlflechter",
  "sämischgerber",
  "tellerwäscher",
  "textilriemenflechter",
  "textilverflechter",
  "textilwäscher",
  "textmontierer",
  "universalhärter",
  "vakuumschmelzer",
  "vorgarnspinner",
  "vorspinner",
  "wagenwäscher",
  "weichlöter",
  "werkzeughärter",
  "zusammenmontierer",
  "zweizylinderspinner",
  "zwirnspinner"
]);
const weakEnForms: ReadonlySet<string> = new Set([
  "audiometrist",
  "diplom-choreograph",
  "diplom-geograph",
  "diplom-wirtschaftshispanist",
  "diplom-wirtschaftsromanist",
  "diplomethnograph",
  "diplomkristallograph",
  "eurythmist",
  "fingernagelmodellist",
  "fotokopist",
  "fremdsprachenkontorist",
  "gitarrist",
  "gräzist",
  "heileurythmist",
  "judaist",
  "kabarettist",
  "kontorist",
  "latinist",
  "lehreurythmist",
  "mediävist",
  "metallograph",
  "multimedia-konzeptionist",
  "nagelmodellist",
  "niederlandist",
  "nordist",
  "notenkopist",
  "optometrist",
  "orthopädist",
  "parodist",
  "philatelist",
  "polonist",
  "romanist",
  "russist",
  "semitist",
  "slawist",
  "sorabist",
  "stenokontorist",
  "telegraphist",
  "traktorist",
  "ugrist",
  "ukrainist",
  "vietnamist",
  "wirtschaftsanglist",
  "wirtschaftshispanist",
  "wirtschaftsromanist",
  "wirtschaftsrussist",
  "zirkusartist"
]);
const pluralEForms: ReadonlySet<string> = new Set([
  "bordwart",
  "bundessportwart",
  "energieanlagenwart",
  "fahrzeugwart",
  "feuerwehrgerätewart",
  "fischwart",
  "flugzeugwart",
  "garagenwart",
  "geflügelwart",
  "gerätewart",
  "hauswart",
  "heizwart",
  "lehrwart",
  "mischanlagenwart",
  "motorenwart",
  "naturschutzwart",
  "reitwart",
  "schankwart",
  "schießstandgerätewart",
  "straßentunnelwart",
  "tankstellenwart",
  "tankwart",
  "trockenwart",
  "tunnelwart",
  "waldwegewart",
  "wasserstraßenverkehrswart"
]);
const logeForms: ReadonlySet<string> = new Set([
  "bühnencosmetolog",
  "diplom-albanolog",
  "diplom-gerontolog",
  "diplom-hungarolog",
  "diplom-meteorolog",
  "diplom-mineralog",
  "diplom-motolog",
  "diplom-museolog",
  "diplom-sozialgerontolog",
  "diplom-wirtschaftsmalaiolog",
  "diplomhydrolog",
  "filmcosmetolog",
  "kohlepetrolog",
  "musikethnolog",
  "neuropatholog",
  "pflanzenvirolog",
  "phytopatholog",
  "psychoonkolog",
  "umweltmineralog",
  "veterinärpatholog"
]);

export const reviewedPersonFormCountWave60 =
  unchangedForms.size + weakEnForms.size + pluralEForms.size + logeForms.size;

function regularForms(
  base: string,
  plural: string,
  obliqueSingular = base,
  genitiveSingular = `${base}s`
): GeneratedPersonForms {
  return {
    plural,
    singular: base,
    feminineSingular: `${base}in`,
    obliqueSingular,
    genitiveSingular
  };
}

export function getReviewedPersonFormsWave60(
  normalizedBase: string
): GeneratedPersonForms | undefined {
  if (unchangedForms.has(normalizedBase)) {
    return regularForms(normalizedBase, normalizedBase);
  }

  if (weakEnForms.has(normalizedBase)) {
    const inflected = `${normalizedBase}en`;
    return regularForms(normalizedBase, inflected, inflected, inflected);
  }

  if (pluralEForms.has(normalizedBase)) {
    return regularForms(normalizedBase, `${normalizedBase}e`);
  }

  if (logeForms.has(normalizedBase)) {
    const singular = `${normalizedBase}e`;
    const inflected = `${normalizedBase}en`;
    return {
      plural: inflected,
      singular,
      feminineSingular: `${normalizedBase}in`,
      obliqueSingular: inflected,
      genitiveSingular: inflected
    };
  }

  return undefined;
}
