import { describe, expect, it } from "vitest";
import { mappedPluralSeparatorsRule } from "../src/rules/mapped-plural-separators";
import {
  mapMappedInflectedSingularPair,
  mapMappedSingular,
  mapMappedSingularPair
} from "../src/rules/person-lexicon";
import {
  getReviewedPersonForms,
  reviewedPersonFormCount
} from "../src/rules/reviewed-person-forms";

describe("achtundfünfzigste Lexikon-Ausbauwelle", () => {
  it("enthält genau den intern geprüften Exaktbestand", () => {
    expect(reviewedPersonFormCount).toBe(222);
    for (const base of ["robot", "alphabet", "oktober", "fantasieanalyst"]) {
      expect(getReviewedPersonForms(base), base).toBeUndefined();
    }
  });

  it.each([
    ["Grillköch:innen", "Grillköche"],
    ["Großküchenköch:innen", "Großküchenköche"],
    ["Gärtnergehilf:innen", "Gärtnergehilfen"],
    ["Gürtlergehilf:innen", "Gürtlergehilfen"],
    ["Handdrucker:innen", "Handdrucker"],
    ["Handlungsgehilf:innen", "Handlungsgehilfen"],
    ["Handpressendrucker:innen", "Handpressendrucker"],
    ["Harmoniumrestaurator:innen", "Harmoniumrestauratoren"],
    ["Hauswirtschaftsgehilf:innen", "Hauswirtschaftsgehilfen"],
    ["Hilfsköch:innen", "Hilfsköche"],
    ["Hilfsschlosser:innen", "Hilfsschlosser"],
    ["Hochdrucker:innen", "Hochdrucker"],
    ["Hochdruckrohrschlosser:innen", "Hochdruckrohrschlosser"],
    ["Holländergehilf:innen", "Holländergehilfen"],
    ["Holzmöbelrestaurator:innen", "Holzmöbelrestauratoren"],
    ["Holzrestaurator:innen", "Holzrestauratoren"],
    ["Hopfenbäuer:innen", "Hopfenbauern"],
    ["Hotelgehilf:innen", "Hotelgehilfen"],
    ["Hotelköch:innen", "Hotelköche"],
    ["Hydraulikschlosser:innen", "Hydraulikschlosser"],
    ["Illustrationsdrucker:innen", "Illustrationsdrucker"],
    ["Imkergehilf:innen", "Imkergehilfen"],
    ["Immobilienanalyst:innen", "Immobilienanalysten"],
    ["Industrieschreiner:innen", "Industrieschreiner"],
    ["Innenausbauschreiner:innen", "Innenausbauschreiner"],
    ["Innenrevisor:innen", "Innenrevisoren"],
    ["Intarsienschreiner:innen", "Intarsienschreiner"],
    ["Investmentanalyst:innen", "Investmentanalysten"],
    ["Jalousieschlosser:innen", "Jalousieschlosser"],
    ["Jungköch:innen", "Jungköche"],
    ["Kaltspeisenköch:innen", "Kaltspeisenköche"],
    ["Kantinengehilf:innen", "Kantinengehilfen"],
    ["Kantinenköch:innen", "Kantinenköche"],
    ["Karosserieschlosser:innen", "Karosserieschlosser"],
    ["Karpfenbäuer:innen", "Karpfenbauern"],
    ["Kasinoköch:innen", "Kasinoköche"],
    ["Kassengehilf:innen", "Kassengehilfen"],
    ["Kaufmannsgehilf:innen", "Kaufmannsgehilfen"],
    ["Kellereigehilf:innen", "Kellereigehilfen"],
    ["Keramikdrucker:innen", "Keramikdrucker"],
    ["Kesselschlosser:innen", "Kesselschlosser"],
    ["Kfz-schlosser:innen", "Kfz-schlosser"],
    ["Kleinoffsetdrucker:innen", "Kleinoffsetdrucker"],
    ["Kochgehilf:innen", "Kochgehilfen"],
    ["Kohlbäuer:innen", "Kohlbauern"],
    ["Konstruktionsschlosser:innen", "Konstruktionsschlosser"],
    ["Kraftfahrzeugmotorenschlosser:innen", "Kraftfahrzeugmotorenschlosser"],
    ["Kraftfahrzeugschlosser:innen", "Kraftfahrzeugschlosser"],
    ["Kraftfahrzeugwerkstattgehilf:innen", "Kraftfahrzeugwerkstattgehilfen"],
    ["Kranbauschlosser:innen", "Kranbauschlosser"],
    ["Krankenversicherungsrevisor:innen", "Krankenversicherungsrevisoren"],
    ["Kranschlosser:innen", "Kranschlosser"],
    ["Krautbäuer:innen", "Krautbauern"],
    ["Kreditanalyst:innen", "Kreditanalysten"],
    ["Kreditrevisor:innen", "Kreditrevisoren"],
    ["Kundendienstschreiner:innen", "Kundendienstschreiner"],
    ["Kunstdrucker:innen", "Kunstdrucker"],
    ["Kunstrestaurator:innen", "Kunstrestauratoren"],
    ["Kunstschlosser:innen", "Kunstschlosser"],
    ["Kunstschreiner:innen", "Kunstschreiner"],
    ["Kunststoffschlosser:innen", "Kunststoffschlosser"],
    ["Käsereigehilf:innen", "Käsereigehilfen"],
    ["Küchengehilf:innen", "Küchengehilfen"],
    ["Landkartendrucker:innen", "Landkartendrucker"],
    ["Landmaschinenschlosser:innen", "Landmaschinenschlosser"],
    ["Laufschlosser:innen", "Laufschlosser"],
    ["Lederdrucker:innen", "Lederdrucker"],
    ["Lederrestaurator:innen", "Lederrestauratoren"],
    ["Lichtdrucker:innen", "Lichtdrucker"],
    ["Lieferschreiner:innen", "Lieferschreiner"],
    ["Linoleumdrucker:innen", "Linoleumdrucker"],
    ["Lkw-schlosser:innen", "Lkw-schlosser"],
    ["Mannschaftsköch:innen", "Mannschaftsköche"],
    ["Maschinendrucker:innen", "Maschinendrucker"],
    ["Maschinenschlosser:innen", "Maschinenschlosser"],
    ["Melkergehilf:innen", "Melkergehilfen"],
    ["Messeköch:innen", "Messeköche"],
    ["Messeschreiner:innen", "Messeschreiner"],
    ["Metallbauschlosser:innen", "Metallbauschlosser"],
    ["Metallschlosser:innen", "Metallschlosser"],
    ["Metzgergehilf:innen", "Metzgergehilfen"],
    ["Modellschlosser:innen", "Modellschlosser"],
    ["Modellschreiner:innen", "Modellschreiner"],
    ["Montageschlosser:innen", "Montageschlosser"],
    ["Motorenschlosser:innen", "Motorenschlosser"],
    ["Motorradschlosser:innen", "Motorradschlosser"],
    ["Museumsrestaurator:innen", "Museumsrestauratoren"],
    ["Musterdrucker:innen", "Musterdrucker"],
    ["Möbelrestaurator:innen", "Möbelrestauratoren"],
    ["Möbelschlosser:innen", "Möbelschlosser"],
    ["Möbelschreiner:innen", "Möbelschreiner"],
    ["Mühlenbauschlosser:innen", "Mühlenbauschlosser"],
    ["Notargehilf:innen", "Notargehilfen"],
    ["Notendrucker:innen", "Notendrucker"],
    ["Obergärigbrauer:innen", "Obergärigbrauer"],
    ["Oberköch:innen", "Oberköche"],
    ["Obstbäuer:innen", "Obstbauern"],
    ["Offsetdrucker:innen", "Offsetdrucker"],
    ["Orientteppichrestaurator:innen", "Orientteppichrestauratoren"],
    ["Papierrestaurator:innen", "Papierrestauratoren"],
    ["Pappmaschinengehilf:innen", "Pappmaschinengehilfen"],
    ["Parkettrestaurator:innen", "Parkettrestauratoren"],
    ["Partyserviceköch:innen", "Partyserviceköche"],
    ["Patentanwaltsgehilf:innen", "Patentanwaltsgehilfen"],
    ["Pelztierzuchtgehilf:innen", "Pelztierzuchtgehilfen"],
    ["Pensionsgehilf:innen", "Pensionsgehilfen"],
    ["Pkw-schlosser:innen", "Pkw-schlosser"],
    ["Plastikrestaurator:innen", "Plastikrestauratoren"],
    ["Plattendrucker:innen", "Plattendrucker"],
    ["Pneumatikschlosser:innen", "Pneumatikschlosser"],
    ["Portfolioanalyst:innen", "Portfolioanalysten"],
    ["Porzellandrucker:innen", "Porzellandrucker"],
    ["Posaunenrestaurator:innen", "Posaunenrestauratoren"],
    ["Pressergehilf:innen", "Pressergehilfen"],
    ["Rahmenschlosser:innen", "Rahmenschlosser"],
    ["Rating-analyst:innen", "Rating-analysten"],
    ["Rebbäuer:innen", "Rebbauern"],
    ["Rechtsanwaltsgehilf:innen", "Rechtsanwaltsgehilfen"],
    ["Rechtsbeistandsgehilf:innen", "Rechtsbeistandsgehilfen"],
    ["Redaktionsgehilf:innen", "Redaktionsgehilfen"],
    ["Reliefdrucker:innen", "Reliefdrucker"],
    ["Rentenanalyst:innen", "Rentenanalysten"],
    ["Restaurantköch:innen", "Restaurantköche"],
    ["Revisor:innen", "Revisoren"],
    ["Risikoanalyst:innen", "Risikoanalysten"],
    ["Rohrnetzschlosser:innen", "Rohrnetzschlosser"],
    ["Rohrschlosser:innen", "Rohrschlosser"],
    ["Rollapparatgehilf:innen", "Rollapparatgehilfen"],
    ["Rollendrucker:innen", "Rollendrucker"],
    ["Rollensiebdrucker:innen", "Rollensiebdrucker"],
    ["Rollmaschinengehilf:innen", "Rollmaschinengehilfen"],
    ["Rolltorschlosser:innen", "Rolltorschlosser"],
    ["Rotaprintdrucker:innen", "Rotaprintdrucker"],
    ["Rotationsdrucker:innen", "Rotationsdrucker"],
    ["Rotationsillustrationsdrucker:innen", "Rotationsillustrationsdrucker"],
    ["Rotationssiebdrucker:innen", "Rotationssiebdrucker"],
    ["Rotationsstoffdrucker:innen", "Rotationsstoffdrucker"],
    ["Rotationstiefdrucker:innen", "Rotationstiefdrucker"],
    ["Rouleauxdrucker:innen", "Rouleauxdrucker"],
    ["Rundsiebmaschinengehilf:innen", "Rundsiebmaschinengehilfen"],
    ["Salatköch:innen", "Salatköche"],
    ["Sandsteinrestaurator:innen", "Sandsteinrestauratoren"],
    ["Sargschreiner:innen", "Sargschreiner"],
    ["Schaltungsdrucker:innen", "Schaltungsdrucker"],
    ["Schankgehilf:innen", "Schankgehilfen"],
    ["Schienenfahrzeugschlosser:innen", "Schienenfahrzeugschlosser"],
    ["Schiffbauschlosser:innen", "Schiffbauschlosser"],
    ["Schiffsbetriebsschlosser:innen", "Schiffsbetriebsschlosser"],
    ["Schiffsköch:innen", "Schiffsköche"],
    ["Schiffsmaschinenschlosser:innen", "Schiffsmaschinenschlosser"],
    ["Schlachtergehilf:innen", "Schlachtergehilfen"],
    ["Schleusengehilf:innen", "Schleusengehilfen"],
    ["Schlosser:innen", "Schlosser"],
    ["Schreiner:innen", "Schreiner"],
    ["Schwarzblechschlosser:innen", "Schwarzblechschlosser"],
    ["Schweinezuchtgehilf:innen", "Schweinezuchtgehilfen"],
    ["Schwimmmeistergehilf:innen", "Schwimmmeistergehilfen"],
    ["Siebdrucker:innen", "Siebdrucker"],
    ["Skulpturenrestaurator:innen", "Skulpturenrestauratoren"],
    ["Soßenköch:innen", "Soßenköche"],
    ["Sparkassenrevisor:innen", "Sparkassenrevisoren"],
    ["Speisewagenköch:innen", "Speisewagenköche"],
    ["Spezialdrucker:innen", "Spezialdrucker"],
    ["Spezialitätenköch:innen", "Spezialitätenköche"],
    ["Spezialwerkzeugschlosser:innen", "Spezialwerkzeugschlosser"],
    ["Sprengmeistergehilf:innen", "Sprengmeistergehilfen"],
    ["Stahlbauschlosser:innen", "Stahlbauschlosser"],
    ["Stahlbüromöbelschlosser:innen", "Stahlbüromöbelschlosser"],
    ["Stahldrucker:innen", "Stahldrucker"],
    ["Stahlkonstruktionsschlosser:innen", "Stahlkonstruktionsschlosser"],
    ["Stahlmöbelschlosser:innen", "Stahlmöbelschlosser"],
    ["Steindrucker:innen", "Steindrucker"],
    ["Stellwerkschlosser:innen", "Stellwerkschlosser"],
    ["Steuerberatergehilf:innen", "Steuerberatergehilfen"],
    ["Steuerberatungsgehilf:innen", "Steuerberatungsgehilfen"],
    ["Steuerfachgehilf:innen", "Steuerfachgehilfen"],
    ["Steuergehilf:innen", "Steuergehilfen"],
    ["Stuckrestaurator:innen", "Stuckrestauratoren"],
    ["Stuhlschreiner:innen", "Stuhlschreiner"],
    ["Süßspeisenköch:innen", "Süßspeisenköche"],
    ["Tapetendrucker:innen", "Tapetendrucker"],
    ["Tapetenmaschinendrucker:innen", "Tapetenmaschinendrucker"],
    ["Teichbäuer:innen", "Teichbauern"],
    ["Teilköch:innen", "Teilköche"],
    ["Textildrucker:innen", "Textildrucker"],
    ["Textilrestaurator:innen", "Textilrestauratoren"],
    ["Tiefdrucker:innen", "Tiefdrucker"],
    ["Tiefdruckrotationsdrucker:innen", "Tiefdruckrotationsdrucker"],
    ["Traktorenschlosser:innen", "Traktorenschlosser"],
    ["Transparentdrucker:innen", "Transparentdrucker"],
    ["Trockenmaschinengehilf:innen", "Trockenmaschinengehilfen"],
    ["Trompetenrestaurator:innen", "Trompetenrestauratoren"],
    ["Turbinenschlosser:innen", "Turbinenschlosser"],
    ["Uhrenrestaurator:innen", "Uhrenrestauratoren"],
    ["Umrollergehilf:innen", "Umrollergehilfen"],
    ["Verbandsrevisor:innen", "Verbandsrevisoren"],
    ["Vermessungsgehilf:innen", "Vermessungsgehilfen"],
    ["Verpackungsdrucker:innen", "Verpackungsdrucker"],
    ["Versicherungsrevisor:innen", "Versicherungsrevisoren"],
    ["Vertriebsgehilf:innen", "Vertriebsgehilfen"],
    ["Verwaltungsgehilf:innen", "Verwaltungsgehilfen"],
    ["Vollwertköch:innen", "Vollwertköche"],
    ["Vorspeisenköch:innen", "Vorspeisenköche"],
    ["Waagenbauschlosser:innen", "Waagenbauschlosser"],
    ["Wachstuchdrucker:innen", "Wachstuchdrucker"],
    ["Waggonbauschlosser:innen", "Waggonbauschlosser"],
    ["Weinbaugehilf:innen", "Weinbaugehilfen"],
    ["Weinbäuer:innen", "Weinbauern"],
    ["Weizenbierbrauer:innen", "Weizenbierbrauer"],
    ["Weißbierbrauer:innen", "Weißbierbrauer"],
    ["Werkgehilf:innen", "Werkgehilfen"],
    ["Wertpapieranalyst:innen", "Wertpapieranalysten"],
    ["Winzergehilf:innen", "Winzergehilfen"],
    ["Wärmestellengehilf:innen", "Wärmestellengehilfen"],
    ["Wäschereigehilf:innen", "Wäschereigehilfen"],
    ["Zeitschriftendrucker:innen", "Zeitschriftendrucker"],
    ["Zeitungsrotationsdrucker:innen", "Zeitungsrotationsdrucker"],
    ["Zellglasdrucker:innen", "Zellglasdrucker"],
    ["Zifferblattdrucker:innen", "Zifferblattdrucker"],
    ["Zinkdrucker:innen", "Zinkdrucker"],
    ["Ökobäuer:innen", "Ökobauern"],
    ["Ölfarbendrucker:innen", "Ölfarbendrucker"]
  ])("normalisiert den intern geprüften Personenstamm %s", (input, expected) => {
    expect(mappedPluralSeparatorsRule.apply(input)).toEqual({
      text: expected,
      replacements: 1
    });
  });

  it.each([
    ["Grillkoch", "Grillköchin", "Grillkoch"],
    ["Großküchenkoch", "Großküchenköchin", "Großküchenkoch"],
    ["Gärtnergehilfe", "Gärtnergehilfin", "Gärtnergehilfe"],
    ["Gürtlergehilfe", "Gürtlergehilfin", "Gürtlergehilfe"],
    ["Handdrucker", "Handdruckerin", "Handdrucker"],
    ["Handlungsgehilfe", "Handlungsgehilfin", "Handlungsgehilfe"],
    ["Handpressendrucker", "Handpressendruckerin", "Handpressendrucker"],
    ["Harmoniumrestaurator", "Harmoniumrestauratorin", "Harmoniumrestaurator"],
    ["Hauswirtschaftsgehilfe", "Hauswirtschaftsgehilfin", "Hauswirtschaftsgehilfe"],
    ["Hilfskoch", "Hilfsköchin", "Hilfskoch"],
    ["Hilfsschlosser", "Hilfsschlosserin", "Hilfsschlosser"],
    ["Hochdrucker", "Hochdruckerin", "Hochdrucker"],
    ["Hochdruckrohrschlosser", "Hochdruckrohrschlosserin", "Hochdruckrohrschlosser"],
    ["Holländergehilfe", "Holländergehilfin", "Holländergehilfe"],
    ["Holzmöbelrestaurator", "Holzmöbelrestauratorin", "Holzmöbelrestaurator"],
    ["Holzrestaurator", "Holzrestauratorin", "Holzrestaurator"],
    ["Hopfenbauer", "Hopfenbäuerin", "Hopfenbauer"],
    ["Hotelgehilfe", "Hotelgehilfin", "Hotelgehilfe"],
    ["Hotelkoch", "Hotelköchin", "Hotelkoch"],
    ["Hydraulikschlosser", "Hydraulikschlosserin", "Hydraulikschlosser"],
    ["Illustrationsdrucker", "Illustrationsdruckerin", "Illustrationsdrucker"],
    ["Imkergehilfe", "Imkergehilfin", "Imkergehilfe"],
    ["Immobilienanalyst", "Immobilienanalystin", "Immobilienanalyst"],
    ["Industrieschreiner", "Industrieschreinerin", "Industrieschreiner"],
    ["Innenausbauschreiner", "Innenausbauschreinerin", "Innenausbauschreiner"],
    ["Innenrevisor", "Innenrevisorin", "Innenrevisor"],
    ["Intarsienschreiner", "Intarsienschreinerin", "Intarsienschreiner"],
    ["Investmentanalyst", "Investmentanalystin", "Investmentanalyst"],
    ["Jalousieschlosser", "Jalousieschlosserin", "Jalousieschlosser"],
    ["Jungkoch", "Jungköchin", "Jungkoch"],
    ["Kaltspeisenkoch", "Kaltspeisenköchin", "Kaltspeisenkoch"],
    ["Kantinengehilfe", "Kantinengehilfin", "Kantinengehilfe"],
    ["Kantinenkoch", "Kantinenköchin", "Kantinenkoch"],
    ["Karosserieschlosser", "Karosserieschlosserin", "Karosserieschlosser"],
    ["Karpfenbauer", "Karpfenbäuerin", "Karpfenbauer"],
    ["Kasinokoch", "Kasinoköchin", "Kasinokoch"],
    ["Kassengehilfe", "Kassengehilfin", "Kassengehilfe"],
    ["Kaufmannsgehilfe", "Kaufmannsgehilfin", "Kaufmannsgehilfe"],
    ["Kellereigehilfe", "Kellereigehilfin", "Kellereigehilfe"],
    ["Keramikdrucker", "Keramikdruckerin", "Keramikdrucker"],
    ["Kesselschlosser", "Kesselschlosserin", "Kesselschlosser"],
    ["Kfz-schlosser", "Kfz-schlosserin", "Kfz-schlosser"],
    ["Kleinoffsetdrucker", "Kleinoffsetdruckerin", "Kleinoffsetdrucker"],
    ["Kochgehilfe", "Kochgehilfin", "Kochgehilfe"],
    ["Kohlbauer", "Kohlbäuerin", "Kohlbauer"],
    ["Konstruktionsschlosser", "Konstruktionsschlosserin", "Konstruktionsschlosser"],
    ["Kraftfahrzeugmotorenschlosser", "Kraftfahrzeugmotorenschlosserin", "Kraftfahrzeugmotorenschlosser"],
    ["Kraftfahrzeugschlosser", "Kraftfahrzeugschlosserin", "Kraftfahrzeugschlosser"],
    ["Kraftfahrzeugwerkstattgehilfe", "Kraftfahrzeugwerkstattgehilfin", "Kraftfahrzeugwerkstattgehilfe"],
    ["Kranbauschlosser", "Kranbauschlosserin", "Kranbauschlosser"],
    ["Krankenversicherungsrevisor", "Krankenversicherungsrevisorin", "Krankenversicherungsrevisor"],
    ["Kranschlosser", "Kranschlosserin", "Kranschlosser"],
    ["Krautbauer", "Krautbäuerin", "Krautbauer"],
    ["Kreditanalyst", "Kreditanalystin", "Kreditanalyst"],
    ["Kreditrevisor", "Kreditrevisorin", "Kreditrevisor"],
    ["Kundendienstschreiner", "Kundendienstschreinerin", "Kundendienstschreiner"],
    ["Kunstdrucker", "Kunstdruckerin", "Kunstdrucker"],
    ["Kunstrestaurator", "Kunstrestauratorin", "Kunstrestaurator"],
    ["Kunstschlosser", "Kunstschlosserin", "Kunstschlosser"],
    ["Kunstschreiner", "Kunstschreinerin", "Kunstschreiner"],
    ["Kunststoffschlosser", "Kunststoffschlosserin", "Kunststoffschlosser"],
    ["Käsereigehilfe", "Käsereigehilfin", "Käsereigehilfe"],
    ["Küchengehilfe", "Küchengehilfin", "Küchengehilfe"],
    ["Landkartendrucker", "Landkartendruckerin", "Landkartendrucker"],
    ["Landmaschinenschlosser", "Landmaschinenschlosserin", "Landmaschinenschlosser"],
    ["Laufschlosser", "Laufschlosserin", "Laufschlosser"],
    ["Lederdrucker", "Lederdruckerin", "Lederdrucker"],
    ["Lederrestaurator", "Lederrestauratorin", "Lederrestaurator"],
    ["Lichtdrucker", "Lichtdruckerin", "Lichtdrucker"],
    ["Lieferschreiner", "Lieferschreinerin", "Lieferschreiner"],
    ["Linoleumdrucker", "Linoleumdruckerin", "Linoleumdrucker"],
    ["Lkw-schlosser", "Lkw-schlosserin", "Lkw-schlosser"],
    ["Mannschaftskoch", "Mannschaftsköchin", "Mannschaftskoch"],
    ["Maschinendrucker", "Maschinendruckerin", "Maschinendrucker"],
    ["Maschinenschlosser", "Maschinenschlosserin", "Maschinenschlosser"],
    ["Melkergehilfe", "Melkergehilfin", "Melkergehilfe"],
    ["Messekoch", "Messeköchin", "Messekoch"],
    ["Messeschreiner", "Messeschreinerin", "Messeschreiner"],
    ["Metallbauschlosser", "Metallbauschlosserin", "Metallbauschlosser"],
    ["Metallschlosser", "Metallschlosserin", "Metallschlosser"],
    ["Metzgergehilfe", "Metzgergehilfin", "Metzgergehilfe"],
    ["Modellschlosser", "Modellschlosserin", "Modellschlosser"],
    ["Modellschreiner", "Modellschreinerin", "Modellschreiner"],
    ["Montageschlosser", "Montageschlosserin", "Montageschlosser"],
    ["Motorenschlosser", "Motorenschlosserin", "Motorenschlosser"],
    ["Motorradschlosser", "Motorradschlosserin", "Motorradschlosser"],
    ["Museumsrestaurator", "Museumsrestauratorin", "Museumsrestaurator"],
    ["Musterdrucker", "Musterdruckerin", "Musterdrucker"],
    ["Möbelrestaurator", "Möbelrestauratorin", "Möbelrestaurator"],
    ["Möbelschlosser", "Möbelschlosserin", "Möbelschlosser"],
    ["Möbelschreiner", "Möbelschreinerin", "Möbelschreiner"],
    ["Mühlenbauschlosser", "Mühlenbauschlosserin", "Mühlenbauschlosser"],
    ["Notargehilfe", "Notargehilfin", "Notargehilfe"],
    ["Notendrucker", "Notendruckerin", "Notendrucker"],
    ["Obergärigbrauer", "Obergärigbrauerin", "Obergärigbrauer"],
    ["Oberkoch", "Oberköchin", "Oberkoch"],
    ["Obstbauer", "Obstbäuerin", "Obstbauer"],
    ["Offsetdrucker", "Offsetdruckerin", "Offsetdrucker"],
    ["Orientteppichrestaurator", "Orientteppichrestauratorin", "Orientteppichrestaurator"],
    ["Papierrestaurator", "Papierrestauratorin", "Papierrestaurator"],
    ["Pappmaschinengehilfe", "Pappmaschinengehilfin", "Pappmaschinengehilfe"],
    ["Parkettrestaurator", "Parkettrestauratorin", "Parkettrestaurator"],
    ["Partyservicekoch", "Partyserviceköchin", "Partyservicekoch"],
    ["Patentanwaltsgehilfe", "Patentanwaltsgehilfin", "Patentanwaltsgehilfe"],
    ["Pelztierzuchtgehilfe", "Pelztierzuchtgehilfin", "Pelztierzuchtgehilfe"],
    ["Pensionsgehilfe", "Pensionsgehilfin", "Pensionsgehilfe"],
    ["Pkw-schlosser", "Pkw-schlosserin", "Pkw-schlosser"],
    ["Plastikrestaurator", "Plastikrestauratorin", "Plastikrestaurator"],
    ["Plattendrucker", "Plattendruckerin", "Plattendrucker"],
    ["Pneumatikschlosser", "Pneumatikschlosserin", "Pneumatikschlosser"],
    ["Portfolioanalyst", "Portfolioanalystin", "Portfolioanalyst"],
    ["Porzellandrucker", "Porzellandruckerin", "Porzellandrucker"],
    ["Posaunenrestaurator", "Posaunenrestauratorin", "Posaunenrestaurator"],
    ["Pressergehilfe", "Pressergehilfin", "Pressergehilfe"],
    ["Rahmenschlosser", "Rahmenschlosserin", "Rahmenschlosser"],
    ["Rating-analyst", "Rating-analystin", "Rating-analyst"],
    ["Rebbauer", "Rebbäuerin", "Rebbauer"],
    ["Rechtsanwaltsgehilfe", "Rechtsanwaltsgehilfin", "Rechtsanwaltsgehilfe"],
    ["Rechtsbeistandsgehilfe", "Rechtsbeistandsgehilfin", "Rechtsbeistandsgehilfe"],
    ["Redaktionsgehilfe", "Redaktionsgehilfin", "Redaktionsgehilfe"],
    ["Reliefdrucker", "Reliefdruckerin", "Reliefdrucker"],
    ["Rentenanalyst", "Rentenanalystin", "Rentenanalyst"],
    ["Restaurantkoch", "Restaurantköchin", "Restaurantkoch"],
    ["Revisor", "Revisorin", "Revisor"],
    ["Risikoanalyst", "Risikoanalystin", "Risikoanalyst"],
    ["Rohrnetzschlosser", "Rohrnetzschlosserin", "Rohrnetzschlosser"],
    ["Rohrschlosser", "Rohrschlosserin", "Rohrschlosser"],
    ["Rollapparatgehilfe", "Rollapparatgehilfin", "Rollapparatgehilfe"],
    ["Rollendrucker", "Rollendruckerin", "Rollendrucker"],
    ["Rollensiebdrucker", "Rollensiebdruckerin", "Rollensiebdrucker"],
    ["Rollmaschinengehilfe", "Rollmaschinengehilfin", "Rollmaschinengehilfe"],
    ["Rolltorschlosser", "Rolltorschlosserin", "Rolltorschlosser"],
    ["Rotaprintdrucker", "Rotaprintdruckerin", "Rotaprintdrucker"],
    ["Rotationsdrucker", "Rotationsdruckerin", "Rotationsdrucker"],
    ["Rotationsillustrationsdrucker", "Rotationsillustrationsdruckerin", "Rotationsillustrationsdrucker"],
    ["Rotationssiebdrucker", "Rotationssiebdruckerin", "Rotationssiebdrucker"],
    ["Rotationsstoffdrucker", "Rotationsstoffdruckerin", "Rotationsstoffdrucker"],
    ["Rotationstiefdrucker", "Rotationstiefdruckerin", "Rotationstiefdrucker"],
    ["Rouleauxdrucker", "Rouleauxdruckerin", "Rouleauxdrucker"],
    ["Rundsiebmaschinengehilfe", "Rundsiebmaschinengehilfin", "Rundsiebmaschinengehilfe"],
    ["Salatkoch", "Salatköchin", "Salatkoch"],
    ["Sandsteinrestaurator", "Sandsteinrestauratorin", "Sandsteinrestaurator"],
    ["Sargschreiner", "Sargschreinerin", "Sargschreiner"],
    ["Schaltungsdrucker", "Schaltungsdruckerin", "Schaltungsdrucker"],
    ["Schankgehilfe", "Schankgehilfin", "Schankgehilfe"],
    ["Schienenfahrzeugschlosser", "Schienenfahrzeugschlosserin", "Schienenfahrzeugschlosser"],
    ["Schiffbauschlosser", "Schiffbauschlosserin", "Schiffbauschlosser"],
    ["Schiffsbetriebsschlosser", "Schiffsbetriebsschlosserin", "Schiffsbetriebsschlosser"],
    ["Schiffskoch", "Schiffsköchin", "Schiffskoch"],
    ["Schiffsmaschinenschlosser", "Schiffsmaschinenschlosserin", "Schiffsmaschinenschlosser"],
    ["Schlachtergehilfe", "Schlachtergehilfin", "Schlachtergehilfe"],
    ["Schleusengehilfe", "Schleusengehilfin", "Schleusengehilfe"],
    ["Schlosser", "Schlosserin", "Schlosser"],
    ["Schreiner", "Schreinerin", "Schreiner"],
    ["Schwarzblechschlosser", "Schwarzblechschlosserin", "Schwarzblechschlosser"],
    ["Schweinezuchtgehilfe", "Schweinezuchtgehilfin", "Schweinezuchtgehilfe"],
    ["Schwimmmeistergehilfe", "Schwimmmeistergehilfin", "Schwimmmeistergehilfe"],
    ["Siebdrucker", "Siebdruckerin", "Siebdrucker"],
    ["Skulpturenrestaurator", "Skulpturenrestauratorin", "Skulpturenrestaurator"],
    ["Soßenkoch", "Soßenköchin", "Soßenkoch"],
    ["Sparkassenrevisor", "Sparkassenrevisorin", "Sparkassenrevisor"],
    ["Speisewagenkoch", "Speisewagenköchin", "Speisewagenkoch"],
    ["Spezialdrucker", "Spezialdruckerin", "Spezialdrucker"],
    ["Spezialitätenkoch", "Spezialitätenköchin", "Spezialitätenkoch"],
    ["Spezialwerkzeugschlosser", "Spezialwerkzeugschlosserin", "Spezialwerkzeugschlosser"],
    ["Sprengmeistergehilfe", "Sprengmeistergehilfin", "Sprengmeistergehilfe"],
    ["Stahlbauschlosser", "Stahlbauschlosserin", "Stahlbauschlosser"],
    ["Stahlbüromöbelschlosser", "Stahlbüromöbelschlosserin", "Stahlbüromöbelschlosser"],
    ["Stahldrucker", "Stahldruckerin", "Stahldrucker"],
    ["Stahlkonstruktionsschlosser", "Stahlkonstruktionsschlosserin", "Stahlkonstruktionsschlosser"],
    ["Stahlmöbelschlosser", "Stahlmöbelschlosserin", "Stahlmöbelschlosser"],
    ["Steindrucker", "Steindruckerin", "Steindrucker"],
    ["Stellwerkschlosser", "Stellwerkschlosserin", "Stellwerkschlosser"],
    ["Steuerberatergehilfe", "Steuerberatergehilfin", "Steuerberatergehilfe"],
    ["Steuerberatungsgehilfe", "Steuerberatungsgehilfin", "Steuerberatungsgehilfe"],
    ["Steuerfachgehilfe", "Steuerfachgehilfin", "Steuerfachgehilfe"],
    ["Steuergehilfe", "Steuergehilfin", "Steuergehilfe"],
    ["Stuckrestaurator", "Stuckrestauratorin", "Stuckrestaurator"],
    ["Stuhlschreiner", "Stuhlschreinerin", "Stuhlschreiner"],
    ["Süßspeisenkoch", "Süßspeisenköchin", "Süßspeisenkoch"],
    ["Tapetendrucker", "Tapetendruckerin", "Tapetendrucker"],
    ["Tapetenmaschinendrucker", "Tapetenmaschinendruckerin", "Tapetenmaschinendrucker"],
    ["Teichbauer", "Teichbäuerin", "Teichbauer"],
    ["Teilkoch", "Teilköchin", "Teilkoch"],
    ["Textildrucker", "Textildruckerin", "Textildrucker"],
    ["Textilrestaurator", "Textilrestauratorin", "Textilrestaurator"],
    ["Tiefdrucker", "Tiefdruckerin", "Tiefdrucker"],
    ["Tiefdruckrotationsdrucker", "Tiefdruckrotationsdruckerin", "Tiefdruckrotationsdrucker"],
    ["Traktorenschlosser", "Traktorenschlosserin", "Traktorenschlosser"],
    ["Transparentdrucker", "Transparentdruckerin", "Transparentdrucker"],
    ["Trockenmaschinengehilfe", "Trockenmaschinengehilfin", "Trockenmaschinengehilfe"],
    ["Trompetenrestaurator", "Trompetenrestauratorin", "Trompetenrestaurator"],
    ["Turbinenschlosser", "Turbinenschlosserin", "Turbinenschlosser"],
    ["Uhrenrestaurator", "Uhrenrestauratorin", "Uhrenrestaurator"],
    ["Umrollergehilfe", "Umrollergehilfin", "Umrollergehilfe"],
    ["Verbandsrevisor", "Verbandsrevisorin", "Verbandsrevisor"],
    ["Vermessungsgehilfe", "Vermessungsgehilfin", "Vermessungsgehilfe"],
    ["Verpackungsdrucker", "Verpackungsdruckerin", "Verpackungsdrucker"],
    ["Versicherungsrevisor", "Versicherungsrevisorin", "Versicherungsrevisor"],
    ["Vertriebsgehilfe", "Vertriebsgehilfin", "Vertriebsgehilfe"],
    ["Verwaltungsgehilfe", "Verwaltungsgehilfin", "Verwaltungsgehilfe"],
    ["Vollwertkoch", "Vollwertköchin", "Vollwertkoch"],
    ["Vorspeisenkoch", "Vorspeisenköchin", "Vorspeisenkoch"],
    ["Waagenbauschlosser", "Waagenbauschlosserin", "Waagenbauschlosser"],
    ["Wachstuchdrucker", "Wachstuchdruckerin", "Wachstuchdrucker"],
    ["Waggonbauschlosser", "Waggonbauschlosserin", "Waggonbauschlosser"],
    ["Weinbaugehilfe", "Weinbaugehilfin", "Weinbaugehilfe"],
    ["Weinbauer", "Weinbäuerin", "Weinbauer"],
    ["Weizenbierbrauer", "Weizenbierbrauerin", "Weizenbierbrauer"],
    ["Weißbierbrauer", "Weißbierbrauerin", "Weißbierbrauer"],
    ["Werkgehilfe", "Werkgehilfin", "Werkgehilfe"],
    ["Wertpapieranalyst", "Wertpapieranalystin", "Wertpapieranalyst"],
    ["Winzergehilfe", "Winzergehilfin", "Winzergehilfe"],
    ["Wärmestellengehilfe", "Wärmestellengehilfin", "Wärmestellengehilfe"],
    ["Wäschereigehilfe", "Wäschereigehilfin", "Wäschereigehilfe"],
    ["Zeitschriftendrucker", "Zeitschriftendruckerin", "Zeitschriftendrucker"],
    ["Zeitungsrotationsdrucker", "Zeitungsrotationsdruckerin", "Zeitungsrotationsdrucker"],
    ["Zellglasdrucker", "Zellglasdruckerin", "Zellglasdrucker"],
    ["Zifferblattdrucker", "Zifferblattdruckerin", "Zifferblattdrucker"],
    ["Zinkdrucker", "Zinkdruckerin", "Zinkdrucker"],
    ["Ökobauer", "Ökobäuerin", "Ökobauer"],
    ["Ölfarbendrucker", "Ölfarbendruckerin", "Ölfarbendrucker"]
  ])("erkennt das intern geprüfte Paar %s/%s", (masculine, feminine, expected) => {
    expect(mapMappedSingularPair(masculine, feminine)).toBe(expected);
  });

  it.each([
    ["grillköch", "genitive", "grillkochs"],
    ["gärtnergehilf", "dative", "gärtnergehilfen"],
    ["handdrucker", "genitive", "handdruckers"],
    ["harmoniumrestaurator", "genitive", "harmoniumrestaurators"],
    ["hopfenbäuer", "dative", "hopfenbauern"],
    ["immobilienanalyst", "dative", "immobilienanalysten"]
  ] as const)(
    "bildet die repräsentative Basis %s im Kasus %s korrekt ab",
    (base, grammaticalCase, expected) => {
      expect(mapMappedSingular(base, grammaticalCase)).toBe(expected);
    }
  );

  it.each([
    ["Grillköchin", "Grillkochs", "genitive", "Grillkochs"],
    ["Gärtnergehilfin", "Gärtnergehilfen", "dative", "Gärtnergehilfen"],
    ["Hopfenbäuerin", "Hopfenbauern", "dative", "Hopfenbauern"],
    ["Immobilienanalystin", "Immobilienanalysten", "dative", "Immobilienanalysten"]
  ] as const)(
    "erkennt das flektierte Paar %s/%s im Kasus %s",
    (feminine, masculine, grammaticalCase, expected) => {
      expect(
        mapMappedInflectedSingularPair(feminine, masculine, grammaticalCase)
      ).toBe(expected);
    }
  );
});
