import { describe, expect, it } from "vitest";
import { mappedPluralSeparatorsRule } from "../src/rules/mapped-plural-separators";
import {
  mapMappedSingular,
  mapMappedSingularPair
} from "../src/rules/person-lexicon";
import {
  getReviewedPersonFormsWave61,
  reviewedPersonFormCountWave61
} from "../src/rules/reviewed-person-forms-wave-61";

describe("einundsechzigste Lexikon-Ausbauwelle", () => {
  it("enthält genau den intern geprüften Exaktbestand", () => {
    expect(reviewedPersonFormCountWave61).toBe(250);
    for (const base of [
      "computervisualist",
      "eri-wart",
      "eutonist",
      "fennist",
      "mindermaschinenstricker",
      "modellist",
      "tapisserist",
      "verschmelzer",
      "wäscher",
      "kabelbinder",
      "gummikleber",
      "röster",
      "fantasiepacker"
    ]) {
      expect(getReviewedPersonFormsWave61(base), base).toBeUndefined();
    }
  });

  it.each([
    ["Abpacker:innen", "Abpacker"],
    ["Anknüpfer:innen", "Anknüpfer"],
    ["Appretierer:innen", "Appretierer"],
    ["Asphaltierer:innen", "Asphaltierer"],
    ["Auftragskoordinierer:innen", "Auftragskoordinierer"],
    ["Ausrüster:innen", "Ausrüster"],
    ["Außenputzer:innen", "Außenputzer"],
    ["Bandagierer:innen", "Bandagierer"],
    ["Bauflaschner:innen", "Bauflaschner"],
    ["Baumschmuckbläser:innen", "Baumschmuckbläser"],
    ["Bauspengler:innen", "Bauspengler"],
    ["Besenbinder:innen", "Besenbinder"],
    ["Betonstahlbieger:innen", "Betonstahlbieger"],
    ["Bezirkskaminkehrer:innen", "Bezirkskaminkehrer"],
    ["Blechemaillierer:innen", "Blechemaillierer"],
    ["Blechglüher:innen", "Blechglüher"],
    ["Blechnieter:innen", "Blechnieter"],
    ["Bleicher:innen", "Bleicher"],
    ["Blumenbinder:innen", "Blumenbinder"],
    ["Bossierer:innen", "Bossierer"],
    ["Brennhobler:innen", "Brennhobler"],
    ["Briefsortierer:innen", "Briefsortierer"],
    ["Buchteilbinder:innen", "Buchteilbinder"],
    ["Buntgewebeausrüster:innen", "Buntgewebeausrüster"],
    ["Böttcher:innen", "Böttcher"],
    ["Bügler:innen", "Bügler"],
    ["Bühnenplastiker:innen", "Bühnenplastiker"],
    ["Bürstenbinder:innen", "Bürstenbinder"],
    ["Büttner:innen", "Büttner"],
    ["Damenhutaufputzer:innen", "Damenhutaufputzer"],
    ["Damenhutgarnierer:innen", "Damenhutgarnierer"],
    ["Dekapierer:innen", "Dekapierer"],
    ["Dermoplastiker:innen", "Dermoplastiker"],
    ["Diamantsäger:innen", "Diamantsäger"],
    ["Drahterodierer:innen", "Drahterodierer"],
    ["Drahtglüher:innen", "Drahtglüher"],
    ["Drahtseiler:innen", "Drahtseiler"],
    ["Drahtverseiler:innen", "Drahtverseiler"],
    ["Edelmetallpräger:innen", "Edelmetallpräger"],
    ["Einpacker:innen", "Einpacker"],
    ["Eisenbieger:innen", "Eisenbieger"],
    ["Eloxierer:innen", "Eloxierer"],
    ["Emaillierer:innen", "Emaillierer"],
    ["Entschärfer:innen", "Entschärfer"],
    ["Erdölraffinierer:innen", "Erdölraffinierer"],
    ["Exportkreditfinanzierer:innen", "Exportkreditfinanzierer"],
    ["Facettierer:innen", "Facettierer"],
    ["Fachhumangenetiker:innen", "Fachhumangenetiker"],
    ["Fachpacker:innen", "Fachpacker"],
    ["Fahrhauer:innen", "Fahrhauer"],
    ["Fahrzeugkonservierer:innen", "Fahrzeugkonservierer"],
    ["Farbdruckpräger:innen", "Farbdruckpräger"],
    ["Fassadenputzer:innen", "Fassadenputzer"],
    ["Fassbinder:innen", "Fassbinder"],
    ["Feilenhauer:innen", "Feilenhauer"],
    ["Fensterputzer:innen", "Fensterputzer"],
    ["Fertigbügler:innen", "Fertigbügler"],
    ["Feuerverzinker:innen", "Feuerverzinker"],
    ["Filetierer:innen", "Filetierer"],
    ["Fischfiletierer:innen", "Fischfiletierer"],
    ["Fischkonservierer:innen", "Fischkonservierer"],
    ["Fischmarinierer:innen", "Fischmarinierer"],
    ["Flaschner:innen", "Flaschner"],
    ["Fleischbeschauer:innen", "Fleischbeschauer"],
    ["Fleischhauer:innen", "Fleischhauer"],
    ["Folienpräger:innen", "Folienpräger"],
    ["Fransenknüpfer:innen", "Fransenknüpfer"],
    ["Fugenhobler:innen", "Fugenhobler"],
    ["Funkenerodierer:innen", "Funkenerodierer"],
    ["Furnierer:innen", "Furnierer"],
    ["Furniersäger:innen", "Furniersäger"],
    ["Fürsorger:innen", "Fürsorger"],
    ["Galvanisierer:innen", "Galvanisierer"],
    ["Galvanoplastiker:innen", "Galvanoplastiker"],
    ["Galvanoverzinker:innen", "Galvanoverzinker"],
    ["Garderobenbügler:innen", "Garderobenbügler"],
    ["Garnierer:innen", "Garnierer"],
    ["Gattierer:innen", "Gattierer"],
    ["Geflügelfleischer:innen", "Geflügelfleischer"],
    ["Geflügelmäster:innen", "Geflügelmäster"],
    ["Gemüsekonservierer:innen", "Gemüsekonservierer"],
    ["Genetiker:innen", "Genetiker"],
    ["Genussmittelkoster:innen", "Genussmittelkoster"],
    ["Geovisualisierer:innen", "Geovisualisierer"],
    ["Geräteflaschner:innen", "Geräteflaschner"],
    ["Gerätenieter:innen", "Gerätenieter"],
    ["Gipsputzer:innen", "Gipsputzer"],
    ["Glasapparatebläser:innen", "Glasapparatebläser"],
    ["Glasapparatejustierer:innen", "Glasapparatejustierer"],
    ["Glasbeschauer:innen", "Glasbeschauer"],
    ["Glasfigurenbläser:innen", "Glasfigurenbläser"],
    ["Glasgerätejustierer:innen", "Glasgerätejustierer"],
    ["Glasinstrumentenjustierer:innen", "Glasinstrumentenjustierer"],
    ["Glassäger:innen", "Glassäger"],
    ["Glasverzierer:innen", "Glasverzierer"],
    ["Glüher:innen", "Glüher"],
    ["Glühstrumpfwirker:innen", "Glühstrumpfwirker"],
    ["Goldplattierer:innen", "Goldplattierer"],
    ["Goldpräger:innen", "Goldpräger"],
    ["Grabsteinhauer:innen", "Grabsteinhauer"],
    ["Grobnieter:innen", "Grobnieter"],
    ["Großnieter:innen", "Großnieter"],
    ["Gussasphaltierer:innen", "Gussasphaltierer"],
    ["Gänsemäster:innen", "Gänsemäster"],
    ["Haareinknüpfer:innen", "Haareinknüpfer"],
    ["Handelsfachpacker:innen", "Handelsfachpacker"],
    ["Handgarnierer:innen", "Handgarnierer"],
    ["Handpräger:innen", "Handpräger"],
    ["Hobler:innen", "Hobler"],
    ["Holzhobler:innen", "Holzhobler"],
    ["Holzimprägnierer:innen", "Holzimprägnierer"],
    ["Holzsäger:innen", "Holzsäger"],
    ["Humangenetiker:innen", "Humangenetiker"],
    ["Hundedressierer:innen", "Hundedressierer"],
    ["Imprägnierer:innen", "Imprägnierer"],
    ["Innenputzer:innen", "Innenputzer"],
    ["Isolierspengler:innen", "Isolierspengler"],
    ["Kabelarmierer:innen", "Kabelarmierer"],
    ["Kabelimprägnierer:innen", "Kabelimprägnierer"],
    ["Kabelkonfektionierer:innen", "Kabelkonfektionierer"],
    ["Kabelverseiler:innen", "Kabelverseiler"],
    ["Kaffeekoster:innen", "Kaffeekoster"],
    ["Kaltnieter:innen", "Kaltnieter"],
    ["Kaltpräger:innen", "Kaltpräger"],
    ["Kaminkehrer:innen", "Kaminkehrer"],
    ["Karosserieflaschner:innen", "Karosserieflaschner"],
    ["Karosseriespengler:innen", "Karosseriespengler"],
    ["Kartonnieter:innen", "Kartonnieter"],
    ["Kastrierer:innen", "Kastrierer"],
    ["Keramgravierer:innen", "Keramgravierer"],
    ["Kerzenverzierer:innen", "Kerzenverzierer"],
    ["Kesselblechbieger:innen", "Kesselblechbieger"],
    ["Kettenanknüpfer:innen", "Kettenanknüpfer"],
    ["Kettenwirker:innen", "Kettenwirker"],
    ["Kleiderbügler:innen", "Kleiderbügler"],
    ["Kleiderstopfer:innen", "Kleiderstopfer"],
    ["Kleinkinderfürsorger:innen", "Kleinkinderfürsorger"],
    ["Koster:innen", "Koster"],
    ["Krankenhausfürsorger:innen", "Krankenhausfürsorger"],
    ["Kranzbinder:innen", "Kranzbinder"],
    ["Kunstaugenbläser:innen", "Kunstaugenbläser"],
    ["Kunststopfer:innen", "Kunststopfer"],
    ["Küchenfleischer:innen", "Küchenfleischer"],
    ["Küchenmetzger:innen", "Küchenmetzger"],
    ["Kükensortierer:innen", "Kükensortierer"],
    ["Ladenfleischer:innen", "Ladenfleischer"],
    ["Langhobler:innen", "Langhobler"],
    ["Ledernieter:innen", "Ledernieter"],
    ["Lederschärfer:innen", "Lederschärfer"],
    ["Leinenbleicher:innen", "Leinenbleicher"],
    ["Leinenwarenbleicher:innen", "Leinenwarenbleicher"],
    ["Lohnverzinker:innen", "Lohnverzinker"],
    ["Lüftungsspengler:innen", "Lüftungsspengler"],
    ["Marmorsäger:innen", "Marmorsäger"],
    ["Maschinenbügler:innen", "Maschinenbügler"],
    ["Maschinenputzer:innen", "Maschinenputzer"],
    ["Maschinenteppichknüpfer:innen", "Maschinenteppichknüpfer"],
    ["Medaillenpräger:innen", "Medaillenpräger"],
    ["Metallbieger:innen", "Metallbieger"],
    ["Metallpräger:innen", "Metallpräger"],
    ["Metallsäger:innen", "Metallsäger"],
    ["Monogrammpräger:innen", "Monogrammpräger"],
    ["Mäster:innen", "Mäster"],
    ["Möbelpacker:innen", "Möbelpacker"],
    ["Münzpräger:innen", "Münzpräger"],
    ["Nahrungsmittelkoster:innen", "Nahrungsmittelkoster"],
    ["Natursteinsäger:innen", "Natursteinsäger"],
    ["Netzknüpfer:innen", "Netzknüpfer"],
    ["Nieter:innen", "Nieter"],
    ["Nähwirker:innen", "Nähwirker"],
    ["Packer:innen", "Packer"],
    ["Papierausrüster:innen", "Papierausrüster"],
    ["Papierpräger:innen", "Papierpräger"],
    ["Pappenpräger:innen", "Pappenpräger"],
    ["Pferdefleischer:innen", "Pferdefleischer"],
    ["Pferdemetzger:innen", "Pferdemetzger"],
    ["Phylogenetiker:innen", "Phylogenetiker"],
    ["Plastiker:innen", "Plastiker"],
    ["Populationsgenetiker:innen", "Populationsgenetiker"],
    ["Präger:innen", "Präger"],
    ["Rauchfangkehrer:innen", "Rauchfangkehrer"],
    ["Rekristallisationsglüher:innen", "Rekristallisationsglüher"],
    ["Rindermäster:innen", "Rindermäster"],
    ["Rohrglüher:innen", "Rohrglüher"],
    ["Rossfleischer:innen", "Rossfleischer"],
    ["Rundkettenwirker:innen", "Rundkettenwirker"],
    ["Rundstuhlwirker:innen", "Rundstuhlwirker"],
    ["Rundwirker:innen", "Rundwirker"],
    ["Sandsteinhauer:innen", "Sandsteinhauer"],
    ["Sandstrahlbläser:innen", "Sandstrahlbläser"],
    ["Schachtfahrhauer:innen", "Schachtfahrhauer"],
    ["Schachthauer:innen", "Schachthauer"],
    ["Schiefersäger:innen", "Schiefersäger"],
    ["Schmuckpräger:innen", "Schmuckpräger"],
    ["Schriftenhauer:innen", "Schriftenhauer"],
    ["Schwarzböttcher:innen", "Schwarzböttcher"],
    ["Schwarzbüttner:innen", "Schwarzbüttner"],
    ["Schweinemäster:innen", "Schweinemäster"],
    ["Schärfer:innen", "Schärfer"],
    ["Seiler:innen", "Seiler"],
    ["Sozialfürsorger:innen", "Sozialfürsorger"],
    ["Spannungsarmglüher:innen", "Spannungsarmglüher"],
    ["Spengler:innen", "Spengler"],
    ["Spritzverzinker:innen", "Spritzverzinker"],
    ["Stahlfederglüher:innen", "Stahlfederglüher"],
    ["Stahlstichpräger:innen", "Stahlstichpräger"],
    ["Steinhobler:innen", "Steinhobler"],
    ["Steinputzer:innen", "Steinputzer"],
    ["Steinsäger:innen", "Steinsäger"],
    ["Stollenhauer:innen", "Stollenhauer"],
    ["Stranggarnbleicher:innen", "Stranggarnbleicher"],
    ["Straußbinder:innen", "Straußbinder"],
    ["Straßenkehrer:innen", "Straßenkehrer"],
    ["Strumpfwirker:innen", "Strumpfwirker"],
    ["Stückbleicher:innen", "Stückbleicher"],
    ["Szenenplastiker:innen", "Szenenplastiker"],
    ["Tapetenpräger:innen", "Tapetenpräger"],
    ["Teekoster:innen", "Teekoster"],
    ["Teppichhandknüpfer:innen", "Teppichhandknüpfer"],
    ["Teppichknüpfer:innen", "Teppichknüpfer"],
    ["Teppichstopfer:innen", "Teppichstopfer"],
    ["Textilausrüster:innen", "Textilausrüster"],
    ["Textilstopfer:innen", "Textilstopfer"],
    ["Textilwarenbeschauer:innen", "Textilwarenbeschauer"],
    ["Theaterplastiker:innen", "Theaterplastiker"],
    ["Thermometerbläser:innen", "Thermometerbläser"],
    ["Tierausstopfer:innen", "Tierausstopfer"],
    ["Trauerbinder:innen", "Trauerbinder"],
    ["Trichinenschauer:innen", "Trichinenschauer"],
    ["Trikotwirker:innen", "Trikotwirker"],
    ["Tuchausrüster:innen", "Tuchausrüster"],
    ["Tuchstopfer:innen", "Tuchstopfer"],
    ["Universalhobler:innen", "Universalhobler"],
    ["Untersohlenschärfer:innen", "Untersohlenschärfer"],
    ["Verkaufsmetzger:innen", "Verkaufsmetzger"],
    ["Verpacker:innen", "Verpacker"],
    ["Verputzer:innen", "Verputzer"],
    ["Verseiler:innen", "Verseiler"],
    ["Verzinker:innen", "Verzinker"],
    ["Wareneinpacker:innen", "Wareneinpacker"],
    ["Warenpacker:innen", "Warenpacker"],
    ["Warenschauer:innen", "Warenschauer"],
    ["Warmnieter:innen", "Warmnieter"],
    ["Webeblattbinder:innen", "Webeblattbinder"],
    ["Weichglüher:innen", "Weichglüher"],
    ["Weinkoster:innen", "Weinkoster"],
    ["Weißbinder:innen", "Weißbinder"],
    ["Werbeblattbinder:innen", "Werbeblattbinder"],
    ["Wirker:innen", "Wirker"],
    ["Zahnradhobler:innen", "Zahnradhobler"]
  ])("normalisiert den intern geprüften Personenstamm %s", (input, expected) => {
    expect(mappedPluralSeparatorsRule.apply(input)).toEqual({
      text: expected,
      replacements: 1
    });
  });

  it.each([
    ["Abpacker", "Abpackerin", "Abpacker"],
    ["Anknüpfer", "Anknüpferin", "Anknüpfer"],
    ["Appretierer", "Appretiererin", "Appretierer"],
    ["Asphaltierer", "Asphaltiererin", "Asphaltierer"],
    ["Auftragskoordinierer", "Auftragskoordiniererin", "Auftragskoordinierer"],
    ["Ausrüster", "Ausrüsterin", "Ausrüster"],
    ["Außenputzer", "Außenputzerin", "Außenputzer"],
    ["Bandagierer", "Bandagiererin", "Bandagierer"],
    ["Bauflaschner", "Bauflaschnerin", "Bauflaschner"],
    ["Baumschmuckbläser", "Baumschmuckbläserin", "Baumschmuckbläser"],
    ["Bauspengler", "Bauspenglerin", "Bauspengler"],
    ["Besenbinder", "Besenbinderin", "Besenbinder"],
    ["Betonstahlbieger", "Betonstahlbiegerin", "Betonstahlbieger"],
    ["Bezirkskaminkehrer", "Bezirkskaminkehrerin", "Bezirkskaminkehrer"],
    ["Blechemaillierer", "Blechemailliererin", "Blechemaillierer"],
    ["Blechglüher", "Blechglüherin", "Blechglüher"],
    ["Blechnieter", "Blechnieterin", "Blechnieter"],
    ["Bleicher", "Bleicherin", "Bleicher"],
    ["Blumenbinder", "Blumenbinderin", "Blumenbinder"],
    ["Bossierer", "Bossiererin", "Bossierer"],
    ["Brennhobler", "Brennhoblerin", "Brennhobler"],
    ["Briefsortierer", "Briefsortiererin", "Briefsortierer"],
    ["Buchteilbinder", "Buchteilbinderin", "Buchteilbinder"],
    ["Buntgewebeausrüster", "Buntgewebeausrüsterin", "Buntgewebeausrüster"],
    ["Böttcher", "Böttcherin", "Böttcher"],
    ["Bügler", "Büglerin", "Bügler"],
    ["Bühnenplastiker", "Bühnenplastikerin", "Bühnenplastiker"],
    ["Bürstenbinder", "Bürstenbinderin", "Bürstenbinder"],
    ["Büttner", "Büttnerin", "Büttner"],
    ["Damenhutaufputzer", "Damenhutaufputzerin", "Damenhutaufputzer"],
    ["Damenhutgarnierer", "Damenhutgarniererin", "Damenhutgarnierer"],
    ["Dekapierer", "Dekapiererin", "Dekapierer"],
    ["Dermoplastiker", "Dermoplastikerin", "Dermoplastiker"],
    ["Diamantsäger", "Diamantsägerin", "Diamantsäger"],
    ["Drahterodierer", "Drahterodiererin", "Drahterodierer"],
    ["Drahtglüher", "Drahtglüherin", "Drahtglüher"],
    ["Drahtseiler", "Drahtseilerin", "Drahtseiler"],
    ["Drahtverseiler", "Drahtverseilerin", "Drahtverseiler"],
    ["Edelmetallpräger", "Edelmetallprägerin", "Edelmetallpräger"],
    ["Einpacker", "Einpackerin", "Einpacker"],
    ["Eisenbieger", "Eisenbiegerin", "Eisenbieger"],
    ["Eloxierer", "Eloxiererin", "Eloxierer"],
    ["Emaillierer", "Emailliererin", "Emaillierer"],
    ["Entschärfer", "Entschärferin", "Entschärfer"],
    ["Erdölraffinierer", "Erdölraffiniererin", "Erdölraffinierer"],
    ["Exportkreditfinanzierer", "Exportkreditfinanziererin", "Exportkreditfinanzierer"],
    ["Facettierer", "Facettiererin", "Facettierer"],
    ["Fachhumangenetiker", "Fachhumangenetikerin", "Fachhumangenetiker"],
    ["Fachpacker", "Fachpackerin", "Fachpacker"],
    ["Fahrhauer", "Fahrhauerin", "Fahrhauer"],
    ["Fahrzeugkonservierer", "Fahrzeugkonserviererin", "Fahrzeugkonservierer"],
    ["Farbdruckpräger", "Farbdruckprägerin", "Farbdruckpräger"],
    ["Fassadenputzer", "Fassadenputzerin", "Fassadenputzer"],
    ["Fassbinder", "Fassbinderin", "Fassbinder"],
    ["Feilenhauer", "Feilenhauerin", "Feilenhauer"],
    ["Fensterputzer", "Fensterputzerin", "Fensterputzer"],
    ["Fertigbügler", "Fertigbüglerin", "Fertigbügler"],
    ["Feuerverzinker", "Feuerverzinkerin", "Feuerverzinker"],
    ["Filetierer", "Filetiererin", "Filetierer"],
    ["Fischfiletierer", "Fischfiletiererin", "Fischfiletierer"],
    ["Fischkonservierer", "Fischkonserviererin", "Fischkonservierer"],
    ["Fischmarinierer", "Fischmariniererin", "Fischmarinierer"],
    ["Flaschner", "Flaschnerin", "Flaschner"],
    ["Fleischbeschauer", "Fleischbeschauerin", "Fleischbeschauer"],
    ["Fleischhauer", "Fleischhauerin", "Fleischhauer"],
    ["Folienpräger", "Folienprägerin", "Folienpräger"],
    ["Fransenknüpfer", "Fransenknüpferin", "Fransenknüpfer"],
    ["Fugenhobler", "Fugenhoblerin", "Fugenhobler"],
    ["Funkenerodierer", "Funkenerodiererin", "Funkenerodierer"],
    ["Furnierer", "Furniererin", "Furnierer"],
    ["Furniersäger", "Furniersägerin", "Furniersäger"],
    ["Fürsorger", "Fürsorgerin", "Fürsorger"],
    ["Galvanisierer", "Galvanisiererin", "Galvanisierer"],
    ["Galvanoplastiker", "Galvanoplastikerin", "Galvanoplastiker"],
    ["Galvanoverzinker", "Galvanoverzinkerin", "Galvanoverzinker"],
    ["Garderobenbügler", "Garderobenbüglerin", "Garderobenbügler"],
    ["Garnierer", "Garniererin", "Garnierer"],
    ["Gattierer", "Gattiererin", "Gattierer"],
    ["Geflügelfleischer", "Geflügelfleischerin", "Geflügelfleischer"],
    ["Geflügelmäster", "Geflügelmästerin", "Geflügelmäster"],
    ["Gemüsekonservierer", "Gemüsekonserviererin", "Gemüsekonservierer"],
    ["Genetiker", "Genetikerin", "Genetiker"],
    ["Genussmittelkoster", "Genussmittelkosterin", "Genussmittelkoster"],
    ["Geovisualisierer", "Geovisualisiererin", "Geovisualisierer"],
    ["Geräteflaschner", "Geräteflaschnerin", "Geräteflaschner"],
    ["Gerätenieter", "Gerätenieterin", "Gerätenieter"],
    ["Gipsputzer", "Gipsputzerin", "Gipsputzer"],
    ["Glasapparatebläser", "Glasapparatebläserin", "Glasapparatebläser"],
    ["Glasapparatejustierer", "Glasapparatejustiererin", "Glasapparatejustierer"],
    ["Glasbeschauer", "Glasbeschauerin", "Glasbeschauer"],
    ["Glasfigurenbläser", "Glasfigurenbläserin", "Glasfigurenbläser"],
    ["Glasgerätejustierer", "Glasgerätejustiererin", "Glasgerätejustierer"],
    ["Glasinstrumentenjustierer", "Glasinstrumentenjustiererin", "Glasinstrumentenjustierer"],
    ["Glassäger", "Glassägerin", "Glassäger"],
    ["Glasverzierer", "Glasverziererin", "Glasverzierer"],
    ["Glüher", "Glüherin", "Glüher"],
    ["Glühstrumpfwirker", "Glühstrumpfwirkerin", "Glühstrumpfwirker"],
    ["Goldplattierer", "Goldplattiererin", "Goldplattierer"],
    ["Goldpräger", "Goldprägerin", "Goldpräger"],
    ["Grabsteinhauer", "Grabsteinhauerin", "Grabsteinhauer"],
    ["Grobnieter", "Grobnieterin", "Grobnieter"],
    ["Großnieter", "Großnieterin", "Großnieter"],
    ["Gussasphaltierer", "Gussasphaltiererin", "Gussasphaltierer"],
    ["Gänsemäster", "Gänsemästerin", "Gänsemäster"],
    ["Haareinknüpfer", "Haareinknüpferin", "Haareinknüpfer"],
    ["Handelsfachpacker", "Handelsfachpackerin", "Handelsfachpacker"],
    ["Handgarnierer", "Handgarniererin", "Handgarnierer"],
    ["Handpräger", "Handprägerin", "Handpräger"],
    ["Hobler", "Hoblerin", "Hobler"],
    ["Holzhobler", "Holzhoblerin", "Holzhobler"],
    ["Holzimprägnierer", "Holzimprägniererin", "Holzimprägnierer"],
    ["Holzsäger", "Holzsägerin", "Holzsäger"],
    ["Humangenetiker", "Humangenetikerin", "Humangenetiker"],
    ["Hundedressierer", "Hundedressiererin", "Hundedressierer"],
    ["Imprägnierer", "Imprägniererin", "Imprägnierer"],
    ["Innenputzer", "Innenputzerin", "Innenputzer"],
    ["Isolierspengler", "Isolierspenglerin", "Isolierspengler"],
    ["Kabelarmierer", "Kabelarmiererin", "Kabelarmierer"],
    ["Kabelimprägnierer", "Kabelimprägniererin", "Kabelimprägnierer"],
    ["Kabelkonfektionierer", "Kabelkonfektioniererin", "Kabelkonfektionierer"],
    ["Kabelverseiler", "Kabelverseilerin", "Kabelverseiler"],
    ["Kaffeekoster", "Kaffeekosterin", "Kaffeekoster"],
    ["Kaltnieter", "Kaltnieterin", "Kaltnieter"],
    ["Kaltpräger", "Kaltprägerin", "Kaltpräger"],
    ["Kaminkehrer", "Kaminkehrerin", "Kaminkehrer"],
    ["Karosserieflaschner", "Karosserieflaschnerin", "Karosserieflaschner"],
    ["Karosseriespengler", "Karosseriespenglerin", "Karosseriespengler"],
    ["Kartonnieter", "Kartonnieterin", "Kartonnieter"],
    ["Kastrierer", "Kastriererin", "Kastrierer"],
    ["Keramgravierer", "Keramgraviererin", "Keramgravierer"],
    ["Kerzenverzierer", "Kerzenverziererin", "Kerzenverzierer"],
    ["Kesselblechbieger", "Kesselblechbiegerin", "Kesselblechbieger"],
    ["Kettenanknüpfer", "Kettenanknüpferin", "Kettenanknüpfer"],
    ["Kettenwirker", "Kettenwirkerin", "Kettenwirker"],
    ["Kleiderbügler", "Kleiderbüglerin", "Kleiderbügler"],
    ["Kleiderstopfer", "Kleiderstopferin", "Kleiderstopfer"],
    ["Kleinkinderfürsorger", "Kleinkinderfürsorgerin", "Kleinkinderfürsorger"],
    ["Koster", "Kosterin", "Koster"],
    ["Krankenhausfürsorger", "Krankenhausfürsorgerin", "Krankenhausfürsorger"],
    ["Kranzbinder", "Kranzbinderin", "Kranzbinder"],
    ["Kunstaugenbläser", "Kunstaugenbläserin", "Kunstaugenbläser"],
    ["Kunststopfer", "Kunststopferin", "Kunststopfer"],
    ["Küchenfleischer", "Küchenfleischerin", "Küchenfleischer"],
    ["Küchenmetzger", "Küchenmetzgerin", "Küchenmetzger"],
    ["Kükensortierer", "Kükensortiererin", "Kükensortierer"],
    ["Ladenfleischer", "Ladenfleischerin", "Ladenfleischer"],
    ["Langhobler", "Langhoblerin", "Langhobler"],
    ["Ledernieter", "Ledernieterin", "Ledernieter"],
    ["Lederschärfer", "Lederschärferin", "Lederschärfer"],
    ["Leinenbleicher", "Leinenbleicherin", "Leinenbleicher"],
    ["Leinenwarenbleicher", "Leinenwarenbleicherin", "Leinenwarenbleicher"],
    ["Lohnverzinker", "Lohnverzinkerin", "Lohnverzinker"],
    ["Lüftungsspengler", "Lüftungsspenglerin", "Lüftungsspengler"],
    ["Marmorsäger", "Marmorsägerin", "Marmorsäger"],
    ["Maschinenbügler", "Maschinenbüglerin", "Maschinenbügler"],
    ["Maschinenputzer", "Maschinenputzerin", "Maschinenputzer"],
    ["Maschinenteppichknüpfer", "Maschinenteppichknüpferin", "Maschinenteppichknüpfer"],
    ["Medaillenpräger", "Medaillenprägerin", "Medaillenpräger"],
    ["Metallbieger", "Metallbiegerin", "Metallbieger"],
    ["Metallpräger", "Metallprägerin", "Metallpräger"],
    ["Metallsäger", "Metallsägerin", "Metallsäger"],
    ["Monogrammpräger", "Monogrammprägerin", "Monogrammpräger"],
    ["Mäster", "Mästerin", "Mäster"],
    ["Möbelpacker", "Möbelpackerin", "Möbelpacker"],
    ["Münzpräger", "Münzprägerin", "Münzpräger"],
    ["Nahrungsmittelkoster", "Nahrungsmittelkosterin", "Nahrungsmittelkoster"],
    ["Natursteinsäger", "Natursteinsägerin", "Natursteinsäger"],
    ["Netzknüpfer", "Netzknüpferin", "Netzknüpfer"],
    ["Nieter", "Nieterin", "Nieter"],
    ["Nähwirker", "Nähwirkerin", "Nähwirker"],
    ["Packer", "Packerin", "Packer"],
    ["Papierausrüster", "Papierausrüsterin", "Papierausrüster"],
    ["Papierpräger", "Papierprägerin", "Papierpräger"],
    ["Pappenpräger", "Pappenprägerin", "Pappenpräger"],
    ["Pferdefleischer", "Pferdefleischerin", "Pferdefleischer"],
    ["Pferdemetzger", "Pferdemetzgerin", "Pferdemetzger"],
    ["Phylogenetiker", "Phylogenetikerin", "Phylogenetiker"],
    ["Plastiker", "Plastikerin", "Plastiker"],
    ["Populationsgenetiker", "Populationsgenetikerin", "Populationsgenetiker"],
    ["Präger", "Prägerin", "Präger"],
    ["Rauchfangkehrer", "Rauchfangkehrerin", "Rauchfangkehrer"],
    ["Rekristallisationsglüher", "Rekristallisationsglüherin", "Rekristallisationsglüher"],
    ["Rindermäster", "Rindermästerin", "Rindermäster"],
    ["Rohrglüher", "Rohrglüherin", "Rohrglüher"],
    ["Rossfleischer", "Rossfleischerin", "Rossfleischer"],
    ["Rundkettenwirker", "Rundkettenwirkerin", "Rundkettenwirker"],
    ["Rundstuhlwirker", "Rundstuhlwirkerin", "Rundstuhlwirker"],
    ["Rundwirker", "Rundwirkerin", "Rundwirker"],
    ["Sandsteinhauer", "Sandsteinhauerin", "Sandsteinhauer"],
    ["Sandstrahlbläser", "Sandstrahlbläserin", "Sandstrahlbläser"],
    ["Schachtfahrhauer", "Schachtfahrhauerin", "Schachtfahrhauer"],
    ["Schachthauer", "Schachthauerin", "Schachthauer"],
    ["Schiefersäger", "Schiefersägerin", "Schiefersäger"],
    ["Schmuckpräger", "Schmuckprägerin", "Schmuckpräger"],
    ["Schriftenhauer", "Schriftenhauerin", "Schriftenhauer"],
    ["Schwarzböttcher", "Schwarzböttcherin", "Schwarzböttcher"],
    ["Schwarzbüttner", "Schwarzbüttnerin", "Schwarzbüttner"],
    ["Schweinemäster", "Schweinemästerin", "Schweinemäster"],
    ["Schärfer", "Schärferin", "Schärfer"],
    ["Seiler", "Seilerin", "Seiler"],
    ["Sozialfürsorger", "Sozialfürsorgerin", "Sozialfürsorger"],
    ["Spannungsarmglüher", "Spannungsarmglüherin", "Spannungsarmglüher"],
    ["Spengler", "Spenglerin", "Spengler"],
    ["Spritzverzinker", "Spritzverzinkerin", "Spritzverzinker"],
    ["Stahlfederglüher", "Stahlfederglüherin", "Stahlfederglüher"],
    ["Stahlstichpräger", "Stahlstichprägerin", "Stahlstichpräger"],
    ["Steinhobler", "Steinhoblerin", "Steinhobler"],
    ["Steinputzer", "Steinputzerin", "Steinputzer"],
    ["Steinsäger", "Steinsägerin", "Steinsäger"],
    ["Stollenhauer", "Stollenhauerin", "Stollenhauer"],
    ["Stranggarnbleicher", "Stranggarnbleicherin", "Stranggarnbleicher"],
    ["Straußbinder", "Straußbinderin", "Straußbinder"],
    ["Straßenkehrer", "Straßenkehrerin", "Straßenkehrer"],
    ["Strumpfwirker", "Strumpfwirkerin", "Strumpfwirker"],
    ["Stückbleicher", "Stückbleicherin", "Stückbleicher"],
    ["Szenenplastiker", "Szenenplastikerin", "Szenenplastiker"],
    ["Tapetenpräger", "Tapetenprägerin", "Tapetenpräger"],
    ["Teekoster", "Teekosterin", "Teekoster"],
    ["Teppichhandknüpfer", "Teppichhandknüpferin", "Teppichhandknüpfer"],
    ["Teppichknüpfer", "Teppichknüpferin", "Teppichknüpfer"],
    ["Teppichstopfer", "Teppichstopferin", "Teppichstopfer"],
    ["Textilausrüster", "Textilausrüsterin", "Textilausrüster"],
    ["Textilstopfer", "Textilstopferin", "Textilstopfer"],
    ["Textilwarenbeschauer", "Textilwarenbeschauerin", "Textilwarenbeschauer"],
    ["Theaterplastiker", "Theaterplastikerin", "Theaterplastiker"],
    ["Thermometerbläser", "Thermometerbläserin", "Thermometerbläser"],
    ["Tierausstopfer", "Tierausstopferin", "Tierausstopfer"],
    ["Trauerbinder", "Trauerbinderin", "Trauerbinder"],
    ["Trichinenschauer", "Trichinenschauerin", "Trichinenschauer"],
    ["Trikotwirker", "Trikotwirkerin", "Trikotwirker"],
    ["Tuchausrüster", "Tuchausrüsterin", "Tuchausrüster"],
    ["Tuchstopfer", "Tuchstopferin", "Tuchstopfer"],
    ["Universalhobler", "Universalhoblerin", "Universalhobler"],
    ["Untersohlenschärfer", "Untersohlenschärferin", "Untersohlenschärfer"],
    ["Verkaufsmetzger", "Verkaufsmetzgerin", "Verkaufsmetzger"],
    ["Verpacker", "Verpackerin", "Verpacker"],
    ["Verputzer", "Verputzerin", "Verputzer"],
    ["Verseiler", "Verseilerin", "Verseiler"],
    ["Verzinker", "Verzinkerin", "Verzinker"],
    ["Wareneinpacker", "Wareneinpackerin", "Wareneinpacker"],
    ["Warenpacker", "Warenpackerin", "Warenpacker"],
    ["Warenschauer", "Warenschauerin", "Warenschauer"],
    ["Warmnieter", "Warmnieterin", "Warmnieter"],
    ["Webeblattbinder", "Webeblattbinderin", "Webeblattbinder"],
    ["Weichglüher", "Weichglüherin", "Weichglüher"],
    ["Weinkoster", "Weinkosterin", "Weinkoster"],
    ["Weißbinder", "Weißbinderin", "Weißbinder"],
    ["Werbeblattbinder", "Werbeblattbinderin", "Werbeblattbinder"],
    ["Wirker", "Wirkerin", "Wirker"],
    ["Zahnradhobler", "Zahnradhoblerin", "Zahnradhobler"]
  ])("erkennt das intern geprüfte Paar %s/%s", (masculine, feminine, expected) => {
    expect(mapMappedSingularPair(masculine, feminine)).toBe(expected);
  });

  it.each([
    ["abpacker", "genitive", "abpackers"],
    ["böttcher", "genitive", "böttchers"],
    ["fürsorger", "genitive", "fürsorgers"],
    ["trichinenschauer", "genitive", "trichinenschauers"]
  ] as const)(
    "bildet die repräsentative Basis %s im Kasus %s korrekt ab",
    (base, grammaticalCase, expected) => {
      expect(mapMappedSingular(base, grammaticalCase)).toBe(expected);
    }
  );
});
