import { describe, expect, it } from "vitest";
import { mappedPluralSeparatorsRule } from "../src/rules/mapped-plural-separators";
import {
  mapMappedSingular,
  mapMappedSingularPair
} from "../src/rules/person-lexicon";
import {
  getReviewedPersonFormsWave78,
  reviewedPersonFormCountWave78
} from "../src/rules/reviewed-person-forms-wave-78";

describe("achtundsiebzigste Lexikon-Ausbauwelle", () => {
  it("enthält alle 155 intern und morphologisch geprüften Wikidata-Exaktmappings", () => {
    expect(reviewedPersonFormCountWave78).toBe(155);

    for (const [base, plural, singular, feminine, oblique, genitive] of [
    ["abolitionist", "abolitionisten", "abolitionist", "abolitionistin", "abolitionisten", "abolitionisten"],
    ["abweichler", "abweichler", "abweichler", "abweichlerin", "abweichler", "abweichlers"],
    ["acarolog", "acarologen", "acarologe", "acarologin", "acarologen", "acarologen"],
    ["agronom", "agronomen", "agronom", "agronomin", "agronomen", "agronomen"],
    ["akkordeonist", "akkordeonisten", "akkordeonist", "akkordeonistin", "akkordeonisten", "akkordeonisten"],
    ["alchemist", "alchemisten", "alchemist", "alchemistin", "alchemisten", "alchemisten"],
    ["älpler", "älpler", "älpler", "älplerin", "älpler", "älplers"],
    ["anarchosyndikalist", "anarchosyndikalisten", "anarchosyndikalist", "anarchosyndikalistin", "anarchosyndikalisten", "anarchosyndikalisten"],
    ["aquarellist", "aquarellisten", "aquarellist", "aquarellistin", "aquarellisten", "aquarellisten"],
    ["aristokrat", "aristokraten", "aristokrat", "aristokratin", "aristokraten", "aristokraten"],
    ["autobiograf", "autobiografen", "autobiograf", "autobiografin", "autobiografen", "autobiografen"],
    ["autobiograph", "autobiographen", "autobiograph", "autobiographin", "autobiographen", "autobiographen"],
    ["bandit", "banditen", "bandit", "banditin", "banditen", "banditen"],
    ["bankier", "bankiers", "bankier", "bankierin", "bankier", "bankiers"],
    ["bankräuber", "bankräuber", "bankräuber", "bankräuberin", "bankräuber", "bankräubers"],
    ["barbier", "barbiere", "barbier", "barbierin", "barbier", "barbiers"],
    ["baumschuler", "baumschuler", "baumschuler", "baumschulerin", "baumschuler", "baumschulers"],
    ["bergretter", "bergretter", "bergretter", "bergretterin", "bergretter", "bergretters"],
    ["bettler", "bettler", "bettler", "bettlerin", "bettler", "bettlers"],
    ["biograf", "biografen", "biograf", "biografin", "biografen", "biografen"],
    ["biograph", "biographen", "biograph", "biographin", "biographen", "biographen"],
    ["bläser", "bläser", "bläser", "bläserin", "bläser", "bläsers"],
    ["blechbläser", "blechbläser", "blechbläser", "blechbläserin", "blechbläser", "blechbläsers"],
    ["briefmarkenfälscher", "briefmarkenfälscher", "briefmarkenfälscher", "briefmarkenfälscherin", "briefmarkenfälscher", "briefmarkenfälschers"],
    ["burggräf", "burggrafen", "burggraf", "burggräfin", "burggrafen", "burggrafen"],
    ["cembalist", "cembalisten", "cembalist", "cembalistin", "cembalisten", "cembalisten"],
    ["choreograph", "choreographen", "choreograph", "choreographin", "choreographen", "choreographen"],
    ["chorist", "choristen", "chorist", "choristin", "choristen", "choristen"],
    ["chroniker", "chroniker", "chroniker", "chronikerin", "chroniker", "chronikers"],
    ["coiffeur", "coiffeure", "coiffeur", "coiffeurin", "coiffeur", "coiffeurs"],
    ["cosplayer", "cosplayer", "cosplayer", "cosplayerin", "cosplayer", "cosplayers"],
    ["debütant", "debütanten", "debütant", "debütantin", "debütanten", "debütanten"],
    ["delinquent", "delinquenten", "delinquent", "delinquentin", "delinquenten", "delinquenten"],
    ["didaktiker", "didaktiker", "didaktiker", "didaktikerin", "didaktiker", "didaktikers"],
    ["dokumentarfilmer", "dokumentarfilmer", "dokumentarfilmer", "dokumentarfilmerin", "dokumentarfilmer", "dokumentarfilmers"],
    ["drogendealer", "drogendealer", "drogendealer", "drogendealerin", "drogendealer", "drogendealers"],
    ["ehebrecher", "ehebrecher", "ehebrecher", "ehebrecherin", "ehebrecher", "ehebrechers"],
    ["erpresser", "erpresser", "erpresser", "erpresserin", "erpresser", "erpressers"],
    ["esperantist", "esperantisten", "esperantist", "esperantistin", "esperantisten", "esperantisten"],
    ["ethnograph", "ethnographen", "ethnograph", "ethnographin", "ethnographen", "ethnographen"],
    ["farmer", "farmer", "farmer", "farmerin", "farmer", "farmers"],
    ["faustballer", "faustballer", "faustballer", "faustballerin", "faustballer", "faustballers"],
    ["feuilletonist", "feuilletonisten", "feuilletonist", "feuilletonistin", "feuilletonisten", "feuilletonisten"],
    ["finanzier", "finanziers", "finanzier", "finanzierin", "finanzier", "finanziers"],
    ["flötist", "flötisten", "flötist", "flötistin", "flötisten", "flötisten"],
    ["frauenrechtler", "frauenrechtler", "frauenrechtler", "frauenrechtlerin", "frauenrechtler", "frauenrechtlers"],
    ["freiheitskämpfer", "freiheitskämpfer", "freiheitskämpfer", "freiheitskämpferin", "freiheitskämpfer", "freiheitskämpfers"],
    ["freischärler", "freischärler", "freischärler", "freischärlerin", "freischärler", "freischärlers"],
    ["gangster", "gangster", "gangster", "gangsterin", "gangster", "gangsters"],
    ["gerichtsstenograph", "gerichtsstenographen", "gerichtsstenograph", "gerichtsstenographin", "gerichtsstenographen", "gerichtsstenographen"],
    ["gewerkschaftler", "gewerkschaftler", "gewerkschaftler", "gewerkschaftlerin", "gewerkschaftler", "gewerkschaftlers"],
    ["gewichtheber", "gewichtheber", "gewichtheber", "gewichtheberin", "gewichtheber", "gewichthebers"],
    ["ghostwriter", "ghostwriter", "ghostwriter", "ghostwriterin", "ghostwriter", "ghostwriters"],
    ["gleitschirmflieger", "gleitschirmflieger", "gleitschirmflieger", "gleitschirmfliegerin", "gleitschirmflieger", "gleitschirmfliegers"],
    ["glöckner", "glöckner", "glöckner", "glöcknerin", "glöckner", "glöckners"],
    ["golfer", "golfer", "golfer", "golferin", "golfer", "golfers"],
    ["grammatiker", "grammatiker", "grammatiker", "grammatikerin", "grammatiker", "grammatikers"],
    ["häfner", "häfner", "häfner", "häfnerin", "häfner", "häfners"],
    ["hair-stylist", "hair-stylisten", "hair-stylist", "hair-stylistin", "hair-stylisten", "hair-stylisten"],
    ["halter", "halter", "halter", "halterin", "halter", "halters"],
    ["häretiker", "häretiker", "häretiker", "häretikerin", "häretiker", "häretikers"],
    ["harfenist", "harfenisten", "harfenist", "harfenistin", "harfenisten", "harfenisten"],
    ["hausbesorger", "hausbesorger", "hausbesorger", "hausbesorgerin", "hausbesorger", "hausbesorgers"],
    ["hausierer", "hausierer", "hausierer", "hausiererin", "hausierer", "hausierers"],
    ["honorarkonsul", "honorarkonsuln", "honorarkonsul", "honorarkonsulin", "honorarkonsul", "honorarkonsuls"],
    ["hopfenpflanzer", "hopfenpflanzer", "hopfenpflanzer", "hopfenpflanzerin", "hopfenpflanzer", "hopfenpflanzers"],
    ["hornist", "hornisten", "hornist", "hornistin", "hornisten", "hornisten"],
    ["hotelier", "hoteliers", "hotelier", "hotelierin", "hotelier", "hoteliers"],
    ["hüter", "hüter", "hüter", "hüterin", "hüter", "hüters"],
    ["idist", "idisten", "idist", "idistin", "idisten", "idisten"],
    ["insektenkundler", "insektenkundler", "insektenkundler", "insektenkundlerin", "insektenkundler", "insektenkundlers"],
    ["jagdflieger", "jagdflieger", "jagdflieger", "jagdfliegerin", "jagdflieger", "jagdfliegers"],
    ["kaiser", "kaiser", "kaiser", "kaiserin", "kaiser", "kaisers"],
    ["kalligraf", "kalligrafen", "kalligraf", "kalligrafin", "kalligrafen", "kalligrafen"],
    ["kalligraph", "kalligraphen", "kalligraph", "kalligraphin", "kalligraphen", "kalligraphen"],
    ["kanoniker", "kanoniker", "kanoniker", "kanonikerin", "kanoniker", "kanonikers"],
    ["kanonist", "kanonisten", "kanonist", "kanonistin", "kanonisten", "kanonisten"],
    ["karatekämpfer", "karatekämpfer", "karatekämpfer", "karatekämpferin", "karatekämpfer", "karatekämpfers"],
    ["ketzer", "ketzer", "ketzer", "ketzerin", "ketzer", "ketzers"],
    ["kickboxer", "kickboxer", "kickboxer", "kickboxerin", "kickboxer", "kickboxers"],
    ["killer", "killer", "killer", "killerin", "killer", "killers"],
    ["kirchenrechtler", "kirchenrechtler", "kirchenrechtler", "kirchenrechtlerin", "kirchenrechtler", "kirchenrechtlers"],
    ["klimaleugner", "klimaleugner", "klimaleugner", "klimaleugnerin", "klimaleugner", "klimaleugners"],
    ["klimawandelleugner", "klimawandelleugner", "klimawandelleugner", "klimawandelleugnerin", "klimawandelleugner", "klimawandelleugners"],
    ["kolonist", "kolonisten", "kolonist", "kolonistin", "kolonisten", "kolonisten"],
    ["kommandeur", "kommandeure", "kommandeur", "kommandeurin", "kommandeur", "kommandeurs"],
    ["komödiant", "komödianten", "komödiant", "komödiantin", "komödianten", "komödianten"],
    ["kompilator", "kompilatoren", "kompilator", "kompilatorin", "kompilator", "kompilators"],
    ["komtur", "komture", "komtur", "komturin", "komtur", "komturs"],
    ["kontrabassist", "kontrabassisten", "kontrabassist", "kontrabassistin", "kontrabassisten", "kontrabassisten"],
    ["konvertit", "konvertiten", "konvertit", "konvertitin", "konvertiten", "konvertiten"],
    ["kopist", "kopisten", "kopist", "kopistin", "kopisten", "kopisten"],
    ["kornettist", "kornettisten", "kornettist", "kornettistin", "kornettisten", "kornettisten"],
    ["kosmonaut", "kosmonauten", "kosmonaut", "kosmonautin", "kosmonauten", "kosmonauten"],
    ["kunstflieger", "kunstflieger", "kunstflieger", "kunstfliegerin", "kunstflieger", "kunstfliegers"],
    ["kunstturner", "kunstturner", "kunstturner", "kunstturnerin", "kunstturner", "kunstturners"],
    ["lepidopterolog", "lepidopterologen", "lepidopterologe", "lepidopterologin", "lepidopterologen", "lepidopterologen"],
    ["magnat", "magnaten", "magnat", "magnatin", "magnaten", "magnaten"],
    ["mammalog", "mammalogen", "mammaloge", "mammalogin", "mammalogen", "mammalogen"],
    ["marineflieger", "marineflieger", "marineflieger", "marinefliegerin", "marineflieger", "marinefliegers"],
    ["mentalist", "mentalisten", "mentalist", "mentalistin", "mentalisten", "mentalisten"],
    ["methodist", "methodisten", "methodist", "methodistin", "methodisten", "methodisten"],
    ["milchbäuer", "milchbauer", "milchbauer", "milchbäuerin", "milchbauer", "milchbauers"],
    ["milizionär", "milizionäre", "milizionär", "milizionärin", "milizionär", "milizionärs"],
    ["mountainbiker", "mountainbiker", "mountainbiker", "mountainbikerin", "mountainbiker", "mountainbikers"],
    ["mudjahed", "mudjaheddin", "mudjahed", "mudjahedin", "mudjahed", "mudjahed"],
    ["mudschahid", "mudschahidin", "mudschahid", "mudschahidin", "mudschahid", "mudschahids"],
    ["müllsucher", "müllsucher", "müllsucher", "müllsucherin", "müllsucher", "müllsuchers"],
    ["mystiker", "mystiker", "mystiker", "mystikerin", "mystiker", "mystikers"],
    ["navigator", "navigatoren", "navigator", "navigatorin", "navigator", "navigators"],
    ["nonkonformist", "nonkonformisten", "nonkonformist", "nonkonformistin", "nonkonformisten", "nonkonformisten"],
    ["oboist", "oboisten", "oboist", "oboistin", "oboisten", "oboisten"],
    ["okkultist", "okkultisten", "okkultist", "okkultistin", "okkultisten", "okkultisten"],
    ["olympionik", "olympioniken", "olympionike", "olympionikin", "olympioniken", "olympioniken"],
    ["patriot", "patrioten", "patriot", "patriotin", "patrioten", "patrioten"],
    ["pauker", "pauker", "pauker", "paukerin", "pauker", "paukers"],
    ["photograph", "photographen", "photograph", "photographin", "photographen", "photographen"],
    ["podcaster", "podcaster", "podcaster", "podcasterin", "podcaster", "podcasters"],
    ["polemiker", "polemiker", "polemiker", "polemikerin", "polemiker", "polemikers"],
    ["pomolog", "pomologen", "pomologe", "pomologin", "pomologen", "pomologen"],
    ["privatbankier", "privatbankiers", "privatbankier", "privatbankierin", "privatbankier", "privatbankiers"],
    ["räuber", "räuber", "räuber", "räuberin", "räuber", "räubers"],
    ["redaktor", "redaktoren", "redaktor", "redaktorin", "redaktor", "redaktors"],
    ["religionsstifter", "religionsstifter", "religionsstifter", "religionsstifterin", "religionsstifter", "religionsstifters"],
    ["saxofonist", "saxofonisten", "saxofonist", "saxofonistin", "saxofonisten", "saxofonisten"],
    ["saxophonist", "saxophonisten", "saxophonist", "saxophonistin", "saxophonisten", "saxophonisten"],
    ["schatzsucher", "schatzsucher", "schatzsucher", "schatzsucherin", "schatzsucher", "schatzsuchers"],
    ["schmuggler", "schmuggler", "schmuggler", "schmugglerin", "schmuggler", "schmugglers"],
    ["schwertschlucker", "schwertschlucker", "schwertschlucker", "schwertschluckerin", "schwertschlucker", "schwertschluckers"],
    ["segelflieger", "segelflieger", "segelflieger", "segelfliegerin", "segelflieger", "segelfliegers"],
    ["singer-songwriter", "singer-songwriter", "singer-songwriter", "singer-songwriterin", "singer-songwriter", "singer-songwriters"],
    ["skateboarder", "skateboarder", "skateboarder", "skateboarderin", "skateboarder", "skateboarders"],
    ["skispringer", "skispringer", "skispringer", "skispringerin", "skispringer", "skispringers"],
    ["skribent", "skribenten", "skribent", "skribentin", "skribenten", "skribenten"],
    ["snowboarder", "snowboarder", "snowboarder", "snowboarderin", "snowboarder", "snowboarders"],
    ["speerwerfer", "speerwerfer", "speerwerfer", "speerwerferin", "speerwerfer", "speerwerfers"],
    ["stalker", "stalker", "stalker", "stalkerin", "stalker", "stalkers"],
    ["stenograph", "stenographen", "stenograph", "stenographin", "stenographen", "stenographen"],
    ["textolog", "textologen", "textologe", "textologin", "textologen", "textologen"],
    ["toreut", "toreuten", "toreut", "toreutin", "toreuten", "toreuten"],
    ["tramper", "tramper", "tramper", "tramperin", "tramper", "trampers"],
    ["trucker", "trucker", "trucker", "truckerin", "trucker", "truckers"],
    ["tubist", "tubisten", "tubist", "tubistin", "tubisten", "tubisten"],
    ["typograph", "typographen", "typograph", "typographin", "typographen", "typographen"],
    ["untergrundkämpfer", "untergrundkämpfer", "untergrundkämpfer", "untergrundkämpferin", "untergrundkämpfer", "untergrundkämpfers"],
    ["viehhüter", "viehhüter", "viehhüter", "viehhüterin", "viehhüter", "viehhüters"],
    ["virtuose", "virtuosen", "virtuose", "virtuosein", "virtuosen", "virtuosen"],
    ["vogelfänger", "vogelfänger", "vogelfänger", "vogelfängerin", "vogelfänger", "vogelfängers"],
    ["vogelkundler", "vogelkundler", "vogelkundler", "vogelkundlerin", "vogelkundler", "vogelkundlers"],
    ["volksmusikant", "volksmusikanten", "volksmusikant", "volksmusikantin", "volksmusikanten", "volksmusikanten"],
    ["walfänger", "walfänger", "walfänger", "walfängerin", "walfänger", "walfängers"],
    ["widerständler", "widerständler", "widerständler", "widerständlerin", "widerständler", "widerständlers"],
    ["wrestler", "wrestler", "wrestler", "wrestlerin", "wrestler", "wrestlers"],
    ["zeidler", "zeidler", "zeidler", "zeidlerin", "zeidler", "zeidlers"],
    ["zinkenist", "zinkenisten", "zinkenist", "zinkenistin", "zinkenisten", "zinkenisten"]
    ] as const) {
      expect(getReviewedPersonFormsWave78(base), base).toEqual({
        plural,
        singular,
        feminineSingular: feminine,
        obliqueSingular: oblique,
        genitiveSingular: genitive
      });
    }
  });

  it("lässt die 195 noch nicht abgeschlossenen Wikidata-Neufunde offen", () => {
    for (const base of [
      "abfallsortierer",
      "abwart",
      "akarolog",
      "algenkundler",
      "alphornbläser",
      "anthroposoph",
      "anti-nazi-widerstandskämpfer",
      "arachnolog",
      "arbeitsagog",
      "arborist",
      "asketiker",
      "bahnbrecher",
      "bandoneonist",
      "bassgitarrist",
      "bassklarinettist",
      "berührer",
      "blockflötist",
      "booktuber",
      "brentler",
      "bundesstenograf",
      "bundesstenograph",
      "cnidariolog",
      "concertinist",
      "concholog",
      "contorsionist",
      "contortionist",
      "cracker",
      "der",
      "deutschdidaktiker",
      "dipterolog",
      "dokumentalist",
      "driver",
      "drummer",
      "dudler",
      "e-bassist",
      "eisenplastiker",
      "eishockeytorwart",
      "energetiker",
      "ethnobotaniker",
      "fachdidaktiker",
      "fachmänn",
      "fernsehkolumnist",
      "fernsehköch",
      "flexograph",
      "floss-kontributor",
      "foss-kontributor",
      "fotograph",
      "freiheitsrechtler",
      "gemahl",
      "gemüsepflücker",
      "gerichtsstenograf",
      "geräteturner",
      "giftmischer",
      "handbiker",
      "hefner",
      "heimatkundler",
      "holocaustleugner",
      "holograf",
      "holzkundler",
      "humanenergetiker",
      "hymenopterolog",
      "ideengeschichtler",
      "informationsethiker",
      "jazz-gitarrist",
      "jazz-posaunist",
      "jazzposaunist",
      "kabinenwart",
      "kanoniss",
      "kastlan",
      "katalogisierer",
      "keltist",
      "klassizist",
      "klatschkolumnist",
      "kleinplastiker",
      "klimawissenschaftsleugner",
      "klingonist",
      "kodikolog",
      "kolchosbäuer",
      "kolchosebäuer",
      "kombinierer",
      "kontorsionist",
      "krankenbehandler",
      "krippenschnitzer",
      "kritzler",
      "kulturolog",
      "kunstgewerbler",
      "kunstmäzen",
      "kunstpfeifer",
      "küschner",
      "lautenist",
      "liturgiker",
      "llullist",
      "ludolog",
      "lullist",
      "mandolinist",
      "mehrkämpfer",
      "messerschlucker",
      "metallplastiker",
      "methodolog",
      "militant",
      "militärkartograph",
      "miniaturist",
      "modestylist",
      "mudschahed",
      "multiinstrumentalist",
      "musikrezensent",
      "myriapodolog",
      "mäzenat",
      "münzkundler",
      "nematolog",
      "notariatsgehilf",
      "obstbaukundler",
      "oecotropholog",
      "okulist",
      "onomastiker",
      "ordenskundler",
      "ortschronist",
      "paläomammalog",
      "paläornitholog",
      "parlamentsstenograph",
      "partisan",
      "pedell",
      "peertuber",
      "pelzer",
      "perkussionist",
      "phalerist",
      "phykolog",
      "pianostimmer",
      "piccoloflötist",
      "pietist",
      "polit-karikaturist",
      "portier",
      "protistolog",
      "prädikant",
      "pröpst",
      "rancher",
      "rangierer",
      "reisebürogehilf",
      "reißer",
      "remixer",
      "rennradler",
      "republikanist",
      "reviewer",
      "rhodolog",
      "rock-gitarrist",
      "rockgitarrist",
      "rollstuhlcurler",
      "rollstuhlfechter",
      "schikanierer",
      "schmierer",
      "schoaleugner",
      "seiteneinsteiger",
      "semiolog",
      "sexkolumnist",
      "sexolog",
      "shavianist",
      "siegelkundler",
      "skater",
      "sphragistiker",
      "spongiolog",
      "sport-cartoonist",
      "sportanalyst",
      "sportcartoonist",
      "sportkolumnist",
      "stierkampfrancher",
      "stuckator",
      "stukkateur",
      "stukkator",
      "subdiakon",
      "tamburinist",
      "telegrafist",
      "teqballballer",
      "tertiar",
      "tertiarier",
      "terziar",
      "thaiboxer",
      "tierrechtler",
      "transliterator",
      "typograf",
      "unterhalter",
      "urbanolog",
      "verhandlungsstenograph",
      "verkehrszeichenaufsteller",
      "vexillograph",
      "vibrafonist",
      "vibraphonist",
      "vorsitzender",
      "waschsalongehilf",
      "wettervorhersager",
      "wikimedianer",
      "wikisourceler",
      "xylolog",
      "zusammensteller",
      "ökofeminist",
      "ökumeniker"
    ]) {
      expect(getReviewedPersonFormsWave78(base), base).toBeUndefined();
    }
  });

  it.each([
    ["Abolitionist:innen", "Abolitionisten"],
    ["Bandit:innen", "Banditen"],
    ["Burggräf:innen", "Burggrafen"],
    ["Ehebrecher:innen", "Ehebrecher"],
    ["Gangster:innen", "Gangster"],
    ["Häretiker:innen", "Häretiker"],
    ["Kaiser:innen", "Kaiser"],
    ["Kolonist:innen", "Kolonisten"],
    ["Lepidopterolog:innen", "Lepidopterologen"],
    ["Mystiker:innen", "Mystiker"],
    ["Privatbankier:innen", "Privatbankiers"],
    ["Skispringer:innen", "Skispringer"]
  ])("ersetzt repräsentative geprüfte Plurale %s", (input, expected) => {
    expect(mappedPluralSeparatorsRule.apply(input)).toEqual({
      text: expected,
      replacements: 1
    });
  });

  it.each([
    ["Abolitionist", "Abolitionistin", "Abolitionist"],
    ["Bandit", "Banditin", "Bandit"],
    ["Burggraf", "Burggräfin", "Burggraf"],
    ["Ehebrecher", "Ehebrecherin", "Ehebrecher"],
    ["Gangster", "Gangsterin", "Gangster"],
    ["Häretiker", "Häretikerin", "Häretiker"],
    ["Kaiser", "Kaiserin", "Kaiser"],
    ["Kolonist", "Kolonistin", "Kolonist"]
  ])("erkennt repräsentative geprüfte Paare %s/%s", (masculine, feminine, expected) => {
    expect(mapMappedSingularPair(masculine, feminine)).toBe(expected);
  });

  it.each([
    ["abolitionist", "nominative", "abolitionist"],
    ["abolitionist", "genitive", "abolitionisten"],
    ["bandit", "nominative", "bandit"],
    ["bandit", "genitive", "banditen"],
    ["burggräf", "nominative", "burggraf"],
    ["burggräf", "genitive", "burggrafen"],
    ["ehebrecher", "nominative", "ehebrecher"],
    ["ehebrecher", "genitive", "ehebrechers"],
    ["gangster", "nominative", "gangster"],
    ["gangster", "genitive", "gangsters"],
    ["häretiker", "nominative", "häretiker"],
    ["häretiker", "genitive", "häretikers"],
    ["kaiser", "nominative", "kaiser"],
    ["kaiser", "genitive", "kaisers"],
    ["kolonist", "nominative", "kolonist"],
    ["kolonist", "genitive", "kolonisten"]
  ] as const)(
    "bildet repräsentative Basis %s im Kasus %s korrekt ab",
    (base, grammaticalCase, expected) => {
      expect(mapMappedSingular(base, grammaticalCase)).toBe(expected);
    }
  );
});
