import { describe, expect, it } from "vitest";
import { mappedPluralSeparatorsRule } from "../src/rules/mapped-plural-separators";
import {
  mapMappedInflectedSingularPair,
  mapMappedSingular,
  mapMappedSingularPair
} from "../src/rules/person-lexicon";

describe("siebenundfünfzigste konservative Lexikon-Ausbauwelle", () => {
  it.each([
    ["Digitaldrucker:innen", "Digitaldrucker"],
    ["Diplom-restaurator:innen", "Diplom-restauratoren"],
    ["Diätköch:innen", "Diätköche"],
    ["Drahtschlosser:innen", "Drahtschlosser"],
    ["Drahtseilakrobat:innen", "Drahtseilakrobaten"],
    ["Drucker:innen", "Drucker"],
    ["Druckereirevisor:innen", "Druckereirevisoren"],
    ["Dv-revisor:innen", "Dv-revisoren"],
    ["Edv-revisor:innen", "Edv-revisoren"],
    ["Einfarbenoffsetdrucker:innen", "Einfarbenoffsetdrucker"],
    ["Eisenbahnschlosser:innen", "Eisenbahnschlosser"],
    ["Eisenbauschlosser:innen", "Eisenbauschlosser"],
    ["Eisenmöbelschlosser:innen", "Eisenmöbelschlosser"],
    ["Elektrofahrzeugschlosser:innen", "Elektrofahrzeugschlosser"],
    ["Elektrosignalschlosser:innen", "Elektrosignalschlosser"],
    ["Fachgehilf:innen", "Fachgehilfen"],
    ["Fahrzeugschlosser:innen", "Fahrzeugschlosser"],
    ["Fehleranalyst:innen", "Fehleranalysten"],
    ["Feinblechschlosser:innen", "Feinblechschlosser"],
    ["Feldgemüsebäuer:innen", "Feldgemüsebauern"],
    ["Fensterschreiner:innen", "Fensterschreiner"],
    ["Fernmelderevisor:innen", "Fernmelderevisoren"],
    ["Filmlichtdrucker:innen", "Filmlichtdrucker"],
    ["Filmrestaurator:innen", "Filmrestauratoren"],
    ["Finanzanalyst:innen", "Finanzanalysten"],
    ["Fischergehilf:innen", "Fischergehilfen"],
    ["Fischköch:innen", "Fischköche"],
    ["Fischzuchtgehilf:innen", "Fischzuchtgehilfen"],
    ["Flachdrucker:innen", "Flachdrucker"],
    ["Fleischergehilf:innen", "Fleischergehilfen"],
    ["Flexodrucker:innen", "Flexodrucker"],
    ["Foliendrucker:innen", "Foliendrucker"],
    ["Fondsanalyst:innen", "Fondsanalysten"],
    ["Fotomatongehilf:innen", "Fotomatongehilfen"],
    ["Fotorestaurator:innen", "Fotorestauratoren"],
    ["Fraud-analyst:innen", "Fraud-analysten"],
    ["Funkgehilf:innen", "Funkgehilfen"],
    ["Fährgehilf:innen", "Fährgehilfen"],
    ["Gasthofgehilf:innen", "Gasthofgehilfen"],
    ["Gaststättengehilf:innen", "Gaststättengehilfen"],
    ["Geflügelzuchtgehilf:innen", "Geflügelzuchtgehilfen"],
    ["Gemälderestaurator:innen", "Gemälderestauratoren"],
    ["Gemüsebäuer:innen", "Gemüsebauern"],
    ["Gestellbauschlosser:innen", "Gestellbauschlosser"],
    ["Gestütsgehilf:innen", "Gestütsgehilfen"],
    ["Getriebeschlosser:innen", "Getriebeschlosser"],
    ["Gewerbegehilf:innen", "Gewerbegehilfen"],
    ["Glasbedrucker:innen", "Glasbedrucker"],
    ["Goldschmiedegehilf:innen", "Goldschmiedegehilfen"],
    ["Grafikrestaurator:innen", "Grafikrestauratoren"],
  ])("normalisiert den abgesicherten Personenstamm %s", (input, expected) => {
    expect(mappedPluralSeparatorsRule.apply(input)).toEqual({
      text: expected,
      replacements: 1
    });
  });

  it.each([
    ["Digitaldrucker", "Digitaldruckerin", "Digitaldrucker"],
    ["Diplom-restaurator", "Diplom-restauratorin", "Diplom-restaurator"],
    ["Diätkoch", "Diätköchin", "Diätkoch"],
    ["Drahtschlosser", "Drahtschlosserin", "Drahtschlosser"],
    ["Drahtseilakrobat", "Drahtseilakrobatin", "Drahtseilakrobat"],
    ["Drucker", "Druckerin", "Drucker"],
    ["Druckereirevisor", "Druckereirevisorin", "Druckereirevisor"],
    ["Dv-revisor", "Dv-revisorin", "Dv-revisor"],
    ["Edv-revisor", "Edv-revisorin", "Edv-revisor"],
    ["Einfarbenoffsetdrucker", "Einfarbenoffsetdruckerin", "Einfarbenoffsetdrucker"],
    ["Eisenbahnschlosser", "Eisenbahnschlosserin", "Eisenbahnschlosser"],
    ["Eisenbauschlosser", "Eisenbauschlosserin", "Eisenbauschlosser"],
    ["Eisenmöbelschlosser", "Eisenmöbelschlosserin", "Eisenmöbelschlosser"],
    ["Elektrofahrzeugschlosser", "Elektrofahrzeugschlosserin", "Elektrofahrzeugschlosser"],
    ["Elektrosignalschlosser", "Elektrosignalschlosserin", "Elektrosignalschlosser"],
    ["Fachgehilfe", "Fachgehilfin", "Fachgehilfe"],
    ["Fahrzeugschlosser", "Fahrzeugschlosserin", "Fahrzeugschlosser"],
    ["Fehleranalyst", "Fehleranalystin", "Fehleranalyst"],
    ["Feinblechschlosser", "Feinblechschlosserin", "Feinblechschlosser"],
    ["Feldgemüsebauer", "Feldgemüsebäuerin", "Feldgemüsebauer"],
    ["Fensterschreiner", "Fensterschreinerin", "Fensterschreiner"],
    ["Fernmelderevisor", "Fernmelderevisorin", "Fernmelderevisor"],
    ["Filmlichtdrucker", "Filmlichtdruckerin", "Filmlichtdrucker"],
    ["Filmrestaurator", "Filmrestauratorin", "Filmrestaurator"],
    ["Finanzanalyst", "Finanzanalystin", "Finanzanalyst"],
    ["Fischergehilfe", "Fischergehilfin", "Fischergehilfe"],
    ["Fischkoch", "Fischköchin", "Fischkoch"],
    ["Fischzuchtgehilfe", "Fischzuchtgehilfin", "Fischzuchtgehilfe"],
    ["Flachdrucker", "Flachdruckerin", "Flachdrucker"],
    ["Fleischergehilfe", "Fleischergehilfin", "Fleischergehilfe"],
    ["Flexodrucker", "Flexodruckerin", "Flexodrucker"],
    ["Foliendrucker", "Foliendruckerin", "Foliendrucker"],
    ["Fondsanalyst", "Fondsanalystin", "Fondsanalyst"],
    ["Fotomatongehilfe", "Fotomatongehilfin", "Fotomatongehilfe"],
    ["Fotorestaurator", "Fotorestauratorin", "Fotorestaurator"],
    ["Fraud-analyst", "Fraud-analystin", "Fraud-analyst"],
    ["Funkgehilfe", "Funkgehilfin", "Funkgehilfe"],
    ["Fährgehilfe", "Fährgehilfin", "Fährgehilfe"],
    ["Gasthofgehilfe", "Gasthofgehilfin", "Gasthofgehilfe"],
    ["Gaststättengehilfe", "Gaststättengehilfin", "Gaststättengehilfe"],
    ["Geflügelzuchtgehilfe", "Geflügelzuchtgehilfin", "Geflügelzuchtgehilfe"],
    ["Gemälderestaurator", "Gemälderestauratorin", "Gemälderestaurator"],
    ["Gemüsebauer", "Gemüsebäuerin", "Gemüsebauer"],
    ["Gestellbauschlosser", "Gestellbauschlosserin", "Gestellbauschlosser"],
    ["Gestütsgehilfe", "Gestütsgehilfin", "Gestütsgehilfe"],
    ["Getriebeschlosser", "Getriebeschlosserin", "Getriebeschlosser"],
    ["Gewerbegehilfe", "Gewerbegehilfin", "Gewerbegehilfe"],
    ["Glasbedrucker", "Glasbedruckerin", "Glasbedrucker"],
    ["Goldschmiedegehilfe", "Goldschmiedegehilfin", "Goldschmiedegehilfe"],
    ["Grafikrestaurator", "Grafikrestauratorin", "Grafikrestaurator"],
  ])("erkennt das abgesicherte Paar %s/%s", (masculine, feminine, expected) => {
    expect(mapMappedSingularPair(masculine, feminine)).toBe(expected);
  });

  it.each([
    ["digitaldrucker", "genitive", "digitaldruckers"],
    ["diplom-restaurator", "genitive", "diplom-restaurators"],
    ["diätköch", "genitive", "diätkochs"],
    ["drahtschlosser", "genitive", "drahtschlossers"],
    ["drahtseilakrobat", "dative", "drahtseilakrobaten"],
    ["drucker", "genitive", "druckers"],
    ["druckereirevisor", "genitive", "druckereirevisors"],
    ["dv-revisor", "genitive", "dv-revisors"],
    ["edv-revisor", "genitive", "edv-revisors"],
    ["einfarbenoffsetdrucker", "genitive", "einfarbenoffsetdruckers"],
    ["eisenbahnschlosser", "genitive", "eisenbahnschlossers"],
    ["eisenbauschlosser", "genitive", "eisenbauschlossers"],
    ["eisenmöbelschlosser", "genitive", "eisenmöbelschlossers"],
    ["elektrofahrzeugschlosser", "genitive", "elektrofahrzeugschlossers"],
    ["elektrosignalschlosser", "genitive", "elektrosignalschlossers"],
    ["fachgehilf", "dative", "fachgehilfen"],
    ["fahrzeugschlosser", "genitive", "fahrzeugschlossers"],
    ["fehleranalyst", "dative", "fehleranalysten"],
    ["feinblechschlosser", "genitive", "feinblechschlossers"],
    ["feldgemüsebäuer", "dative", "feldgemüsebauern"],
    ["fensterschreiner", "genitive", "fensterschreiners"],
    ["fernmelderevisor", "genitive", "fernmelderevisors"],
    ["filmlichtdrucker", "genitive", "filmlichtdruckers"],
    ["filmrestaurator", "genitive", "filmrestaurators"],
    ["finanzanalyst", "dative", "finanzanalysten"],
    ["fischergehilf", "dative", "fischergehilfen"],
    ["fischköch", "genitive", "fischkochs"],
    ["fischzuchtgehilf", "dative", "fischzuchtgehilfen"],
    ["flachdrucker", "genitive", "flachdruckers"],
    ["fleischergehilf", "dative", "fleischergehilfen"],
    ["flexodrucker", "genitive", "flexodruckers"],
    ["foliendrucker", "genitive", "foliendruckers"],
    ["fondsanalyst", "dative", "fondsanalysten"],
    ["fotomatongehilf", "dative", "fotomatongehilfen"],
    ["fotorestaurator", "genitive", "fotorestaurators"],
    ["fraud-analyst", "dative", "fraud-analysten"],
    ["funkgehilf", "dative", "funkgehilfen"],
    ["fährgehilf", "dative", "fährgehilfen"],
    ["gasthofgehilf", "dative", "gasthofgehilfen"],
    ["gaststättengehilf", "dative", "gaststättengehilfen"],
    ["geflügelzuchtgehilf", "dative", "geflügelzuchtgehilfen"],
    ["gemälderestaurator", "genitive", "gemälderestaurators"],
    ["gemüsebäuer", "dative", "gemüsebauern"],
    ["gestellbauschlosser", "genitive", "gestellbauschlossers"],
    ["gestütsgehilf", "dative", "gestütsgehilfen"],
    ["getriebeschlosser", "genitive", "getriebeschlossers"],
    ["gewerbegehilf", "dative", "gewerbegehilfen"],
    ["glasbedrucker", "genitive", "glasbedruckers"],
    ["goldschmiedegehilf", "dative", "goldschmiedegehilfen"],
    ["grafikrestaurator", "genitive", "grafikrestaurators"],
  ] as const)(
    "bildet %s im Kasus %s korrekt ab",
    (base, grammaticalCase, expected) => {
      expect(mapMappedSingular(base, grammaticalCase)).toBe(expected);
    }
  );

  it.each([
    ["Feldgemüsebäuerin", "Feldgemüsebauern", "dative", "Feldgemüsebauern"],
    ["Fachgehilfin", "Fachgehilfen", "accusative", "Fachgehilfen"],
    ["Diätköchin", "Diätkochs", "genitive", "Diätkochs"],
    ["Gemüsebäuerin", "Gemüsebauern", "genitive", "Gemüsebauern"],
    ["Fischköchin", "Fischkochs", "genitive", "Fischkochs"],
  ] as const)(
    "erkennt das flektierte Paar %s/%s im Kasus %s",
    (feminine, masculine, grammaticalCase, expected) => {
      expect(
        mapMappedInflectedSingularPair(feminine, masculine, grammaticalCase)
      ).toBe(expected);
    }
  );
});
