import { describe, expect, it } from "vitest";
import { mappedPluralSeparatorsRule } from "../src/rules/mapped-plural-separators";
import {
  mapMappedSingular,
  mapMappedSingularPair
} from "../src/rules/person-lexicon";
import {
  getReviewedPersonFormsWave60,
  reviewedPersonFormCountWave60
} from "../src/rules/reviewed-person-forms-wave-60";

describe("sechzigste Lexikon-Ausbauwelle", () => {
  it("enthält genau den intern geprüften Exaktbestand", () => {
    expect(reviewedPersonFormCountWave60).toBe(250);
    for (const base of [
      "computervisualist",
      "eri-wart",
      "eutonist",
      "fennist",
      "mindermaschinenstricker",
      "modellist",
      "tapisserist",
      "verschmelzer",
      "wäscher",
      "fantasiewart"
    ]) {
      expect(getReviewedPersonFormsWave60(base), base).toBeUndefined();
    }
  });

  it.each([
    ["Abteilungssteiger:innen", "Abteilungssteiger"],
    ["Altbausanierer:innen", "Altbausanierer"],
    ["Ansager:innen", "Ansager"],
    ["Antiquitätenschätzer:innen", "Antiquitätenschätzer"],
    ["Audiometrist:innen", "Audiometristen"],
    ["Autowäscher:innen", "Autowäscher"],
    ["Bandstahlhärter:innen", "Bandstahlhärter"],
    ["Baumsanierer:innen", "Baumsanierer"],
    ["Bautenbeschichter:innen", "Bautenbeschichter"],
    ["Bernsteinschnitzer:innen", "Bernsteinschnitzer"],
    ["Beschichter:innen", "Beschichter"],
    ["Betonfertigteilemontierer:innen", "Betonfertigteilemontierer"],
    ["Betonsanierer:innen", "Betonsanierer"],
    ["Betonstahlflechter:innen", "Betonstahlflechter"],
    ["Bildschnitzer:innen", "Bildschnitzer"],
    ["Binnenschiffer:innen", "Binnenschiffer"],
    ["Bleilöter:innen", "Bleilöter"],
    ["Bordwart:innen", "Bordwarte"],
    ["Brandsteiger:innen", "Brandsteiger"],
    ["Bundessportwart:innen", "Bundessportwarte"],
    ["Bühnencosmetolog:innen", "Bühnencosmetologen"],
    ["Chemischwäscher:innen", "Chemischwäscher"],
    ["Diplom-albanolog:innen", "Diplom-albanologen"],
    ["Diplom-choreograph:innen", "Diplom-choreographen"],
    ["Diplom-geograph:innen", "Diplom-geographen"],
    ["Diplom-gerontolog:innen", "Diplom-gerontologen"],
    ["Diplom-hungarolog:innen", "Diplom-hungarologen"],
    ["Diplom-meteorolog:innen", "Diplom-meteorologen"],
    ["Diplom-mineralog:innen", "Diplom-mineralogen"],
    ["Diplom-motolog:innen", "Diplom-motologen"],
    ["Diplom-museolog:innen", "Diplom-museologen"],
    ["Diplom-sozialgerontolog:innen", "Diplom-sozialgerontologen"],
    ["Diplom-wirtschaftshispanist:innen", "Diplom-wirtschaftshispanisten"],
    ["Diplom-wirtschaftsmalaiolog:innen", "Diplom-wirtschaftsmalaiologen"],
    ["Diplom-wirtschaftsromanist:innen", "Diplom-wirtschaftsromanisten"],
    ["Diplomethnograph:innen", "Diplomethnographen"],
    ["Diplomhydrolog:innen", "Diplomhydrologen"],
    ["Diplomkristallograph:innen", "Diplomkristallographen"],
    ["Drahtflechter:innen", "Drahtflechter"],
    ["Drahtgeflechtstricker:innen", "Drahtgeflechtstricker"],
    ["Drahthärter:innen", "Drahthärter"],
    ["Drahtspinner:innen", "Drahtspinner"],
    ["Drahtumspinner:innen", "Drahtumspinner"],
    ["Drahtverflechter:innen", "Drahtverflechter"],
    ["Einschmelzer:innen", "Einschmelzer"],
    ["Eisenflechter:innen", "Eisenflechter"],
    ["Eisenschmelzer:innen", "Eisenschmelzer"],
    ["Elektrogerätemontierer:innen", "Elektrogerätemontierer"],
    ["Elektrolöter:innen", "Elektrolöter"],
    ["Elektromontierer:innen", "Elektromontierer"],
    ["Elektronikteilemontierer:innen", "Elektronikteilemontierer"],
    ["Elektroofenschmelzer:innen", "Elektroofenschmelzer"],
    ["Elektroteilemontierer:innen", "Elektroteilemontierer"],
    ["Elfenbeinschnitzer:innen", "Elfenbeinschnitzer"],
    ["Energieanlagenwart:innen", "Energieanlagenwarte"],
    ["Eurythmist:innen", "Eurythmisten"],
    ["Fahrzeugwart:innen", "Fahrzeugwarte"],
    ["Fahrzeugwäscher:innen", "Fahrzeugwäscher"],
    ["Fassadenwäscher:innen", "Fassadenwäscher"],
    ["Federmontierer:innen", "Federmontierer"],
    ["Feinledergerber:innen", "Feinledergerber"],
    ["Feinspinner:innen", "Feinspinner"],
    ["Feinstrumpfstricker:innen", "Feinstrumpfstricker"],
    ["Fernsehansager:innen", "Fernsehansager"],
    ["Fertigmontierer:innen", "Fertigmontierer"],
    ["Feuerwehrgerätewart:innen", "Feuerwehrgerätewarte"],
    ["Filmcosmetolog:innen", "Filmcosmetologen"],
    ["Fingernagelmodellist:innen", "Fingernagelmodellisten"],
    ["Fischwart:innen", "Fischwarte"],
    ["Flachstricker:innen", "Flachstricker"],
    ["Flechter:innen", "Flechter"],
    ["Flugansager:innen", "Flugansager"],
    ["Flugzeugwart:innen", "Flugzeugwarte"],
    ["Flussschiffer:innen", "Flussschiffer"],
    ["Fotokopist:innen", "Fotokopisten"],
    ["Fotosatzmontierer:innen", "Fotosatzmontierer"],
    ["Fremdsprachenkontorist:innen", "Fremdsprachenkontoristen"],
    ["Fährschiffer:innen", "Fährschiffer"],
    ["Garagenwart:innen", "Garagenwarte"],
    ["Geflügelwart:innen", "Geflügelwarte"],
    ["Gerber:innen", "Gerber"],
    ["Gerätewart:innen", "Gerätewarte"],
    ["Geschirrwäscher:innen", "Geschirrwäscher"],
    ["Gitarrist:innen", "Gitarristen"],
    ["Glacegerber:innen", "Glacegerber"],
    ["Glaceledergerber:innen", "Glaceledergerber"],
    ["Glasschmelzer:innen", "Glasschmelzer"],
    ["Glaswäscher:innen", "Glaswäscher"],
    ["Glühlampenmontierer:innen", "Glühlampenmontierer"],
    ["Gräzist:innen", "Gräzisten"],
    ["Gummistrumpfstricker:innen", "Gummistrumpfstricker"],
    ["Gummiumspinner:innen", "Gummiumspinner"],
    ["Handmaschinenstricker:innen", "Handmaschinenstricker"],
    ["Handschuhledergerber:innen", "Handschuhledergerber"],
    ["Handstricker:innen", "Handstricker"],
    ["Hartlöter:innen", "Hartlöter"],
    ["Hauswart:innen", "Hauswarte"],
    ["Heileurythmist:innen", "Heileurythmisten"],
    ["Heizwart:innen", "Heizwarte"],
    ["Hochofenschmelzer:innen", "Hochofenschmelzer"],
    ["Holzbildschnitzer:innen", "Holzbildschnitzer"],
    ["Holzschnitzer:innen", "Holzschnitzer"],
    ["Holzspielwarenschnitzer:innen", "Holzspielwarenschnitzer"],
    ["Härter:innen", "Härter"],
    ["Induktionshärter:innen", "Induktionshärter"],
    ["Jacquardmaschinenstricker:innen", "Jacquardmaschinenstricker"],
    ["Jacquardstricker:innen", "Jacquardstricker"],
    ["Judaist:innen", "Judaisten"],
    ["Kabarettist:innen", "Kabarettisten"],
    ["Kabelflechter:innen", "Kabelflechter"],
    ["Kabellöter:innen", "Kabellöter"],
    ["Kalksandsteinhärter:innen", "Kalksandsteinhärter"],
    ["Kammgarnspinner:innen", "Kammgarnspinner"],
    ["Keramikschmelzer:innen", "Keramikschmelzer"],
    ["Kohlepetrolog:innen", "Kohlepetrologen"],
    ["Kontorist:innen", "Kontoristen"],
    ["Korbflechter:innen", "Korbflechter"],
    ["Korbmöbelflechter:innen", "Korbmöbelflechter"],
    ["Kraftfahrzeugwäscher:innen", "Kraftfahrzeugwäscher"],
    ["Kunstfaserspinner:innen", "Kunstfaserspinner"],
    ["Kunstschnitzer:innen", "Kunstschnitzer"],
    ["Kunstschätzer:innen", "Kunstschätzer"],
    ["Kunststoffbeschichter:innen", "Kunststoffbeschichter"],
    ["Küstenschiffer:innen", "Küstenschiffer"],
    ["Lagersteiger:innen", "Lagersteiger"],
    ["Latinist:innen", "Latinisten"],
    ["Ledergerber:innen", "Ledergerber"],
    ["Lehreurythmist:innen", "Lehreurythmisten"],
    ["Lehrwart:innen", "Lehrwarte"],
    ["Leichenwäscher:innen", "Leichenwäscher"],
    ["Litzenflechter:innen", "Litzenflechter"],
    ["Löter:innen", "Löter"],
    ["Maschinen-reviersteiger:innen", "Maschinen-reviersteiger"],
    ["Maschinendrahtflechter:innen", "Maschinendrahtflechter"],
    ["Mediävist:innen", "Mediävisten"],
    ["Messerhärter:innen", "Messerhärter"],
    ["Metallhärter:innen", "Metallhärter"],
    ["Metalloberflächenbeschichter:innen", "Metalloberflächenbeschichter"],
    ["Metallograph:innen", "Metallographen"],
    ["Metallschmelzer:innen", "Metallschmelzer"],
    ["Metallwäscher:innen", "Metallwäscher"],
    ["Mischanlagenwart:innen", "Mischanlagenwarte"],
    ["Montierer:innen", "Montierer"],
    ["Motorenwart:innen", "Motorenwarte"],
    ["Multimedia-konzeptionist:innen", "Multimedia-konzeptionisten"],
    ["Musikethnolog:innen", "Musikethnologen"],
    ["Möbelflechter:innen", "Möbelflechter"],
    ["Nachrichtenansager:innen", "Nachrichtenansager"],
    ["Nagelmodellist:innen", "Nagelmodellisten"],
    ["Naturschutzwart:innen", "Naturschutzwarte"],
    ["Netzmontierer:innen", "Netzmontierer"],
    ["Neuropatholog:innen", "Neuropathologen"],
    ["Niederlandist:innen", "Niederlandisten"],
    ["Nordist:innen", "Nordisten"],
    ["Notenkopist:innen", "Notenkopisten"],
    ["Oberflächenbeschichter:innen", "Oberflächenbeschichter"],
    ["Objektbeschichter:innen", "Objektbeschichter"],
    ["Optometrist:innen", "Optometristen"],
    ["Orthopädist:innen", "Orthopädisten"],
    ["Parodist:innen", "Parodisten"],
    ["Partikulierschiffer:innen", "Partikulierschiffer"],
    ["Pfandschätzer:innen", "Pfandschätzer"],
    ["Pflanzenvirolog:innen", "Pflanzenvirologen"],
    ["Philatelist:innen", "Philatelisten"],
    ["Phytopatholog:innen", "Phytopathologen"],
    ["Polonist:innen", "Polonisten"],
    ["Portefeuilleledergerber:innen", "Portefeuilleledergerber"],
    ["Psychoonkolog:innen", "Psychoonkologen"],
    ["Radioansager:innen", "Radioansager"],
    ["Reitwart:innen", "Reitwarte"],
    ["Repro-bogenmontierer:innen", "Repro-bogenmontierer"],
    ["Riemenledergerber:innen", "Riemenledergerber"],
    ["Ringspinner:innen", "Ringspinner"],
    ["Rohrflechter:innen", "Rohrflechter"],
    ["Romanist:innen", "Romanisten"],
    ["Rotgerber:innen", "Rotgerber"],
    ["Rundfunkansager:innen", "Rundfunkansager"],
    ["Rundjacquardstricker:innen", "Rundjacquardstricker"],
    ["Rundmaschinenstricker:innen", "Rundmaschinenstricker"],
    ["Rundstricker:innen", "Rundstricker"],
    ["Russist:innen", "Russisten"],
    ["Röhrenmontierer:innen", "Röhrenmontierer"],
    ["Sanierer:innen", "Sanierer"],
    ["Sattlerledergerber:innen", "Sattlerledergerber"],
    ["Schankwart:innen", "Schankwarte"],
    ["Scherenhärter:innen", "Scherenhärter"],
    ["Schichtsteiger:innen", "Schichtsteiger"],
    ["Schießstandgerätewart:innen", "Schießstandgerätewarte"],
    ["Schießsteiger:innen", "Schießsteiger"],
    ["Schmelzer:innen", "Schmelzer"],
    ["Schneidwarenhärter:innen", "Schneidwarenhärter"],
    ["Schnitzer:innen", "Schnitzer"],
    ["Schornsteinsanierer:innen", "Schornsteinsanierer"],
    ["Schätzer:innen", "Schätzer"],
    ["Seeschiffer:innen", "Seeschiffer"],
    ["Seitenmontierer:innen", "Seitenmontierer"],
    ["Semitist:innen", "Semitisten"],
    ["Sicherheitssteiger:innen", "Sicherheitssteiger"],
    ["Siebdruckmontierer:innen", "Siebdruckmontierer"],
    ["Slawist:innen", "Slawisten"],
    ["Sorabist:innen", "Sorabisten"],
    ["Sporthochseeschiffer:innen", "Sporthochseeschiffer"],
    ["Stahlflechter:innen", "Stahlflechter"],
    ["Stahlhärter:innen", "Stahlhärter"],
    ["Staubschutzsteiger:innen", "Staubschutzsteiger"],
    ["Staubsteiger:innen", "Staubsteiger"],
    ["Steiger:innen", "Steiger"],
    ["Stenokontorist:innen", "Stenokontoristen"],
    ["Stoffwäscher:innen", "Stoffwäscher"],
    ["Straßentunnelwart:innen", "Straßentunnelwarte"],
    ["Streichgarnspinner:innen", "Streichgarnspinner"],
    ["Stricker:innen", "Stricker"],
    ["Strohwarenflechter:innen", "Strohwarenflechter"],
    ["Strumpfstricker:innen", "Strumpfstricker"],
    ["Studioansager:innen", "Studioansager"],
    ["Stuhlflechter:innen", "Stuhlflechter"],
    ["Sämischgerber:innen", "Sämischgerber"],
    ["Tankstellenwart:innen", "Tankstellenwarte"],
    ["Tankwart:innen", "Tankwarte"],
    ["Telegraphist:innen", "Telegraphisten"],
    ["Tellerwäscher:innen", "Tellerwäscher"],
    ["Textilriemenflechter:innen", "Textilriemenflechter"],
    ["Textilverflechter:innen", "Textilverflechter"],
    ["Textilwäscher:innen", "Textilwäscher"],
    ["Textmontierer:innen", "Textmontierer"],
    ["Traktorist:innen", "Traktoristen"],
    ["Trockenwart:innen", "Trockenwarte"],
    ["Tunnelwart:innen", "Tunnelwarte"],
    ["Ugrist:innen", "Ugristen"],
    ["Ukrainist:innen", "Ukrainisten"],
    ["Umweltmineralog:innen", "Umweltmineralogen"],
    ["Universalhärter:innen", "Universalhärter"],
    ["Vakuumschmelzer:innen", "Vakuumschmelzer"],
    ["Veterinärpatholog:innen", "Veterinärpathologen"],
    ["Vietnamist:innen", "Vietnamisten"],
    ["Vorgarnspinner:innen", "Vorgarnspinner"],
    ["Vorspinner:innen", "Vorspinner"],
    ["Wagenwäscher:innen", "Wagenwäscher"],
    ["Waldwegewart:innen", "Waldwegewarte"],
    ["Wasserstraßenverkehrswart:innen", "Wasserstraßenverkehrswarte"],
    ["Weichlöter:innen", "Weichlöter"],
    ["Werkzeughärter:innen", "Werkzeughärter"],
    ["Wirtschaftsanglist:innen", "Wirtschaftsanglisten"],
    ["Wirtschaftshispanist:innen", "Wirtschaftshispanisten"],
    ["Wirtschaftsromanist:innen", "Wirtschaftsromanisten"],
    ["Wirtschaftsrussist:innen", "Wirtschaftsrussisten"],
    ["Zirkusartist:innen", "Zirkusartisten"],
    ["Zusammenmontierer:innen", "Zusammenmontierer"],
    ["Zweizylinderspinner:innen", "Zweizylinderspinner"],
    ["Zwirnspinner:innen", "Zwirnspinner"]
  ])("normalisiert den intern geprüften Personenstamm %s", (input, expected) => {
    expect(mappedPluralSeparatorsRule.apply(input)).toEqual({
      text: expected,
      replacements: 1
    });
  });

  it.each([
    ["Abteilungssteiger", "Abteilungssteigerin", "Abteilungssteiger"],
    ["Altbausanierer", "Altbausaniererin", "Altbausanierer"],
    ["Ansager", "Ansagerin", "Ansager"],
    ["Antiquitätenschätzer", "Antiquitätenschätzerin", "Antiquitätenschätzer"],
    ["Audiometrist", "Audiometristin", "Audiometrist"],
    ["Autowäscher", "Autowäscherin", "Autowäscher"],
    ["Bandstahlhärter", "Bandstahlhärterin", "Bandstahlhärter"],
    ["Baumsanierer", "Baumsaniererin", "Baumsanierer"],
    ["Bautenbeschichter", "Bautenbeschichterin", "Bautenbeschichter"],
    ["Bernsteinschnitzer", "Bernsteinschnitzerin", "Bernsteinschnitzer"],
    ["Beschichter", "Beschichterin", "Beschichter"],
    ["Betonfertigteilemontierer", "Betonfertigteilemontiererin", "Betonfertigteilemontierer"],
    ["Betonsanierer", "Betonsaniererin", "Betonsanierer"],
    ["Betonstahlflechter", "Betonstahlflechterin", "Betonstahlflechter"],
    ["Bildschnitzer", "Bildschnitzerin", "Bildschnitzer"],
    ["Binnenschiffer", "Binnenschifferin", "Binnenschiffer"],
    ["Bleilöter", "Bleilöterin", "Bleilöter"],
    ["Bordwart", "Bordwartin", "Bordwart"],
    ["Brandsteiger", "Brandsteigerin", "Brandsteiger"],
    ["Bundessportwart", "Bundessportwartin", "Bundessportwart"],
    ["Bühnencosmetologe", "Bühnencosmetologin", "Bühnencosmetologe"],
    ["Chemischwäscher", "Chemischwäscherin", "Chemischwäscher"],
    ["Diplom-albanologe", "Diplom-albanologin", "Diplom-albanologe"],
    ["Diplom-choreograph", "Diplom-choreographin", "Diplom-choreograph"],
    ["Diplom-geograph", "Diplom-geographin", "Diplom-geograph"],
    ["Diplom-gerontologe", "Diplom-gerontologin", "Diplom-gerontologe"],
    ["Diplom-hungarologe", "Diplom-hungarologin", "Diplom-hungarologe"],
    ["Diplom-meteorologe", "Diplom-meteorologin", "Diplom-meteorologe"],
    ["Diplom-mineraloge", "Diplom-mineralogin", "Diplom-mineraloge"],
    ["Diplom-motologe", "Diplom-motologin", "Diplom-motologe"],
    ["Diplom-museologe", "Diplom-museologin", "Diplom-museologe"],
    ["Diplom-sozialgerontologe", "Diplom-sozialgerontologin", "Diplom-sozialgerontologe"],
    ["Diplom-wirtschaftshispanist", "Diplom-wirtschaftshispanistin", "Diplom-wirtschaftshispanist"],
    ["Diplom-wirtschaftsmalaiologe", "Diplom-wirtschaftsmalaiologin", "Diplom-wirtschaftsmalaiologe"],
    ["Diplom-wirtschaftsromanist", "Diplom-wirtschaftsromanistin", "Diplom-wirtschaftsromanist"],
    ["Diplomethnograph", "Diplomethnographin", "Diplomethnograph"],
    ["Diplomhydrologe", "Diplomhydrologin", "Diplomhydrologe"],
    ["Diplomkristallograph", "Diplomkristallographin", "Diplomkristallograph"],
    ["Drahtflechter", "Drahtflechterin", "Drahtflechter"],
    ["Drahtgeflechtstricker", "Drahtgeflechtstrickerin", "Drahtgeflechtstricker"],
    ["Drahthärter", "Drahthärterin", "Drahthärter"],
    ["Drahtspinner", "Drahtspinnerin", "Drahtspinner"],
    ["Drahtumspinner", "Drahtumspinnerin", "Drahtumspinner"],
    ["Drahtverflechter", "Drahtverflechterin", "Drahtverflechter"],
    ["Einschmelzer", "Einschmelzerin", "Einschmelzer"],
    ["Eisenflechter", "Eisenflechterin", "Eisenflechter"],
    ["Eisenschmelzer", "Eisenschmelzerin", "Eisenschmelzer"],
    ["Elektrogerätemontierer", "Elektrogerätemontiererin", "Elektrogerätemontierer"],
    ["Elektrolöter", "Elektrolöterin", "Elektrolöter"],
    ["Elektromontierer", "Elektromontiererin", "Elektromontierer"],
    ["Elektronikteilemontierer", "Elektronikteilemontiererin", "Elektronikteilemontierer"],
    ["Elektroofenschmelzer", "Elektroofenschmelzerin", "Elektroofenschmelzer"],
    ["Elektroteilemontierer", "Elektroteilemontiererin", "Elektroteilemontierer"],
    ["Elfenbeinschnitzer", "Elfenbeinschnitzerin", "Elfenbeinschnitzer"],
    ["Energieanlagenwart", "Energieanlagenwartin", "Energieanlagenwart"],
    ["Eurythmist", "Eurythmistin", "Eurythmist"],
    ["Fahrzeugwart", "Fahrzeugwartin", "Fahrzeugwart"],
    ["Fahrzeugwäscher", "Fahrzeugwäscherin", "Fahrzeugwäscher"],
    ["Fassadenwäscher", "Fassadenwäscherin", "Fassadenwäscher"],
    ["Federmontierer", "Federmontiererin", "Federmontierer"],
    ["Feinledergerber", "Feinledergerberin", "Feinledergerber"],
    ["Feinspinner", "Feinspinnerin", "Feinspinner"],
    ["Feinstrumpfstricker", "Feinstrumpfstrickerin", "Feinstrumpfstricker"],
    ["Fernsehansager", "Fernsehansagerin", "Fernsehansager"],
    ["Fertigmontierer", "Fertigmontiererin", "Fertigmontierer"],
    ["Feuerwehrgerätewart", "Feuerwehrgerätewartin", "Feuerwehrgerätewart"],
    ["Filmcosmetologe", "Filmcosmetologin", "Filmcosmetologe"],
    ["Fingernagelmodellist", "Fingernagelmodellistin", "Fingernagelmodellist"],
    ["Fischwart", "Fischwartin", "Fischwart"],
    ["Flachstricker", "Flachstrickerin", "Flachstricker"],
    ["Flechter", "Flechterin", "Flechter"],
    ["Flugansager", "Flugansagerin", "Flugansager"],
    ["Flugzeugwart", "Flugzeugwartin", "Flugzeugwart"],
    ["Flussschiffer", "Flussschifferin", "Flussschiffer"],
    ["Fotokopist", "Fotokopistin", "Fotokopist"],
    ["Fotosatzmontierer", "Fotosatzmontiererin", "Fotosatzmontierer"],
    ["Fremdsprachenkontorist", "Fremdsprachenkontoristin", "Fremdsprachenkontorist"],
    ["Fährschiffer", "Fährschifferin", "Fährschiffer"],
    ["Garagenwart", "Garagenwartin", "Garagenwart"],
    ["Geflügelwart", "Geflügelwartin", "Geflügelwart"],
    ["Gerber", "Gerberin", "Gerber"],
    ["Gerätewart", "Gerätewartin", "Gerätewart"],
    ["Geschirrwäscher", "Geschirrwäscherin", "Geschirrwäscher"],
    ["Gitarrist", "Gitarristin", "Gitarrist"],
    ["Glacegerber", "Glacegerberin", "Glacegerber"],
    ["Glaceledergerber", "Glaceledergerberin", "Glaceledergerber"],
    ["Glasschmelzer", "Glasschmelzerin", "Glasschmelzer"],
    ["Glaswäscher", "Glaswäscherin", "Glaswäscher"],
    ["Glühlampenmontierer", "Glühlampenmontiererin", "Glühlampenmontierer"],
    ["Gräzist", "Gräzistin", "Gräzist"],
    ["Gummistrumpfstricker", "Gummistrumpfstrickerin", "Gummistrumpfstricker"],
    ["Gummiumspinner", "Gummiumspinnerin", "Gummiumspinner"],
    ["Handmaschinenstricker", "Handmaschinenstrickerin", "Handmaschinenstricker"],
    ["Handschuhledergerber", "Handschuhledergerberin", "Handschuhledergerber"],
    ["Handstricker", "Handstrickerin", "Handstricker"],
    ["Hartlöter", "Hartlöterin", "Hartlöter"],
    ["Hauswart", "Hauswartin", "Hauswart"],
    ["Heileurythmist", "Heileurythmistin", "Heileurythmist"],
    ["Heizwart", "Heizwartin", "Heizwart"],
    ["Hochofenschmelzer", "Hochofenschmelzerin", "Hochofenschmelzer"],
    ["Holzbildschnitzer", "Holzbildschnitzerin", "Holzbildschnitzer"],
    ["Holzschnitzer", "Holzschnitzerin", "Holzschnitzer"],
    ["Holzspielwarenschnitzer", "Holzspielwarenschnitzerin", "Holzspielwarenschnitzer"],
    ["Härter", "Härterin", "Härter"],
    ["Induktionshärter", "Induktionshärterin", "Induktionshärter"],
    ["Jacquardmaschinenstricker", "Jacquardmaschinenstrickerin", "Jacquardmaschinenstricker"],
    ["Jacquardstricker", "Jacquardstrickerin", "Jacquardstricker"],
    ["Judaist", "Judaistin", "Judaist"],
    ["Kabarettist", "Kabarettistin", "Kabarettist"],
    ["Kabelflechter", "Kabelflechterin", "Kabelflechter"],
    ["Kabellöter", "Kabellöterin", "Kabellöter"],
    ["Kalksandsteinhärter", "Kalksandsteinhärterin", "Kalksandsteinhärter"],
    ["Kammgarnspinner", "Kammgarnspinnerin", "Kammgarnspinner"],
    ["Keramikschmelzer", "Keramikschmelzerin", "Keramikschmelzer"],
    ["Kohlepetrologe", "Kohlepetrologin", "Kohlepetrologe"],
    ["Kontorist", "Kontoristin", "Kontorist"],
    ["Korbflechter", "Korbflechterin", "Korbflechter"],
    ["Korbmöbelflechter", "Korbmöbelflechterin", "Korbmöbelflechter"],
    ["Kraftfahrzeugwäscher", "Kraftfahrzeugwäscherin", "Kraftfahrzeugwäscher"],
    ["Kunstfaserspinner", "Kunstfaserspinnerin", "Kunstfaserspinner"],
    ["Kunstschnitzer", "Kunstschnitzerin", "Kunstschnitzer"],
    ["Kunstschätzer", "Kunstschätzerin", "Kunstschätzer"],
    ["Kunststoffbeschichter", "Kunststoffbeschichterin", "Kunststoffbeschichter"],
    ["Küstenschiffer", "Küstenschifferin", "Küstenschiffer"],
    ["Lagersteiger", "Lagersteigerin", "Lagersteiger"],
    ["Latinist", "Latinistin", "Latinist"],
    ["Ledergerber", "Ledergerberin", "Ledergerber"],
    ["Lehreurythmist", "Lehreurythmistin", "Lehreurythmist"],
    ["Lehrwart", "Lehrwartin", "Lehrwart"],
    ["Leichenwäscher", "Leichenwäscherin", "Leichenwäscher"],
    ["Litzenflechter", "Litzenflechterin", "Litzenflechter"],
    ["Löter", "Löterin", "Löter"],
    ["Maschinen-reviersteiger", "Maschinen-reviersteigerin", "Maschinen-reviersteiger"],
    ["Maschinendrahtflechter", "Maschinendrahtflechterin", "Maschinendrahtflechter"],
    ["Mediävist", "Mediävistin", "Mediävist"],
    ["Messerhärter", "Messerhärterin", "Messerhärter"],
    ["Metallhärter", "Metallhärterin", "Metallhärter"],
    ["Metalloberflächenbeschichter", "Metalloberflächenbeschichterin", "Metalloberflächenbeschichter"],
    ["Metallograph", "Metallographin", "Metallograph"],
    ["Metallschmelzer", "Metallschmelzerin", "Metallschmelzer"],
    ["Metallwäscher", "Metallwäscherin", "Metallwäscher"],
    ["Mischanlagenwart", "Mischanlagenwartin", "Mischanlagenwart"],
    ["Montierer", "Montiererin", "Montierer"],
    ["Motorenwart", "Motorenwartin", "Motorenwart"],
    ["Multimedia-konzeptionist", "Multimedia-konzeptionistin", "Multimedia-konzeptionist"],
    ["Musikethnologe", "Musikethnologin", "Musikethnologe"],
    ["Möbelflechter", "Möbelflechterin", "Möbelflechter"],
    ["Nachrichtenansager", "Nachrichtenansagerin", "Nachrichtenansager"],
    ["Nagelmodellist", "Nagelmodellistin", "Nagelmodellist"],
    ["Naturschutzwart", "Naturschutzwartin", "Naturschutzwart"],
    ["Netzmontierer", "Netzmontiererin", "Netzmontierer"],
    ["Neuropathologe", "Neuropathologin", "Neuropathologe"],
    ["Niederlandist", "Niederlandistin", "Niederlandist"],
    ["Nordist", "Nordistin", "Nordist"],
    ["Notenkopist", "Notenkopistin", "Notenkopist"],
    ["Oberflächenbeschichter", "Oberflächenbeschichterin", "Oberflächenbeschichter"],
    ["Objektbeschichter", "Objektbeschichterin", "Objektbeschichter"],
    ["Optometrist", "Optometristin", "Optometrist"],
    ["Orthopädist", "Orthopädistin", "Orthopädist"],
    ["Parodist", "Parodistin", "Parodist"],
    ["Partikulierschiffer", "Partikulierschifferin", "Partikulierschiffer"],
    ["Pfandschätzer", "Pfandschätzerin", "Pfandschätzer"],
    ["Pflanzenvirologe", "Pflanzenvirologin", "Pflanzenvirologe"],
    ["Philatelist", "Philatelistin", "Philatelist"],
    ["Phytopathologe", "Phytopathologin", "Phytopathologe"],
    ["Polonist", "Polonistin", "Polonist"],
    ["Portefeuilleledergerber", "Portefeuilleledergerberin", "Portefeuilleledergerber"],
    ["Psychoonkologe", "Psychoonkologin", "Psychoonkologe"],
    ["Radioansager", "Radioansagerin", "Radioansager"],
    ["Reitwart", "Reitwartin", "Reitwart"],
    ["Repro-bogenmontierer", "Repro-bogenmontiererin", "Repro-bogenmontierer"],
    ["Riemenledergerber", "Riemenledergerberin", "Riemenledergerber"],
    ["Ringspinner", "Ringspinnerin", "Ringspinner"],
    ["Rohrflechter", "Rohrflechterin", "Rohrflechter"],
    ["Romanist", "Romanistin", "Romanist"],
    ["Rotgerber", "Rotgerberin", "Rotgerber"],
    ["Rundfunkansager", "Rundfunkansagerin", "Rundfunkansager"],
    ["Rundjacquardstricker", "Rundjacquardstrickerin", "Rundjacquardstricker"],
    ["Rundmaschinenstricker", "Rundmaschinenstrickerin", "Rundmaschinenstricker"],
    ["Rundstricker", "Rundstrickerin", "Rundstricker"],
    ["Russist", "Russistin", "Russist"],
    ["Röhrenmontierer", "Röhrenmontiererin", "Röhrenmontierer"],
    ["Sanierer", "Saniererin", "Sanierer"],
    ["Sattlerledergerber", "Sattlerledergerberin", "Sattlerledergerber"],
    ["Schankwart", "Schankwartin", "Schankwart"],
    ["Scherenhärter", "Scherenhärterin", "Scherenhärter"],
    ["Schichtsteiger", "Schichtsteigerin", "Schichtsteiger"],
    ["Schießstandgerätewart", "Schießstandgerätewartin", "Schießstandgerätewart"],
    ["Schießsteiger", "Schießsteigerin", "Schießsteiger"],
    ["Schmelzer", "Schmelzerin", "Schmelzer"],
    ["Schneidwarenhärter", "Schneidwarenhärterin", "Schneidwarenhärter"],
    ["Schnitzer", "Schnitzerin", "Schnitzer"],
    ["Schornsteinsanierer", "Schornsteinsaniererin", "Schornsteinsanierer"],
    ["Schätzer", "Schätzerin", "Schätzer"],
    ["Seeschiffer", "Seeschifferin", "Seeschiffer"],
    ["Seitenmontierer", "Seitenmontiererin", "Seitenmontierer"],
    ["Semitist", "Semitistin", "Semitist"],
    ["Sicherheitssteiger", "Sicherheitssteigerin", "Sicherheitssteiger"],
    ["Siebdruckmontierer", "Siebdruckmontiererin", "Siebdruckmontierer"],
    ["Slawist", "Slawistin", "Slawist"],
    ["Sorabist", "Sorabistin", "Sorabist"],
    ["Sporthochseeschiffer", "Sporthochseeschifferin", "Sporthochseeschiffer"],
    ["Stahlflechter", "Stahlflechterin", "Stahlflechter"],
    ["Stahlhärter", "Stahlhärterin", "Stahlhärter"],
    ["Staubschutzsteiger", "Staubschutzsteigerin", "Staubschutzsteiger"],
    ["Staubsteiger", "Staubsteigerin", "Staubsteiger"],
    ["Steiger", "Steigerin", "Steiger"],
    ["Stenokontorist", "Stenokontoristin", "Stenokontorist"],
    ["Stoffwäscher", "Stoffwäscherin", "Stoffwäscher"],
    ["Straßentunnelwart", "Straßentunnelwartin", "Straßentunnelwart"],
    ["Streichgarnspinner", "Streichgarnspinnerin", "Streichgarnspinner"],
    ["Stricker", "Strickerin", "Stricker"],
    ["Strohwarenflechter", "Strohwarenflechterin", "Strohwarenflechter"],
    ["Strumpfstricker", "Strumpfstrickerin", "Strumpfstricker"],
    ["Studioansager", "Studioansagerin", "Studioansager"],
    ["Stuhlflechter", "Stuhlflechterin", "Stuhlflechter"],
    ["Sämischgerber", "Sämischgerberin", "Sämischgerber"],
    ["Tankstellenwart", "Tankstellenwartin", "Tankstellenwart"],
    ["Tankwart", "Tankwartin", "Tankwart"],
    ["Telegraphist", "Telegraphistin", "Telegraphist"],
    ["Tellerwäscher", "Tellerwäscherin", "Tellerwäscher"],
    ["Textilriemenflechter", "Textilriemenflechterin", "Textilriemenflechter"],
    ["Textilverflechter", "Textilverflechterin", "Textilverflechter"],
    ["Textilwäscher", "Textilwäscherin", "Textilwäscher"],
    ["Textmontierer", "Textmontiererin", "Textmontierer"],
    ["Traktorist", "Traktoristin", "Traktorist"],
    ["Trockenwart", "Trockenwartin", "Trockenwart"],
    ["Tunnelwart", "Tunnelwartin", "Tunnelwart"],
    ["Ugrist", "Ugristin", "Ugrist"],
    ["Ukrainist", "Ukrainistin", "Ukrainist"],
    ["Umweltmineraloge", "Umweltmineralogin", "Umweltmineraloge"],
    ["Universalhärter", "Universalhärterin", "Universalhärter"],
    ["Vakuumschmelzer", "Vakuumschmelzerin", "Vakuumschmelzer"],
    ["Veterinärpathologe", "Veterinärpathologin", "Veterinärpathologe"],
    ["Vietnamist", "Vietnamistin", "Vietnamist"],
    ["Vorgarnspinner", "Vorgarnspinnerin", "Vorgarnspinner"],
    ["Vorspinner", "Vorspinnerin", "Vorspinner"],
    ["Wagenwäscher", "Wagenwäscherin", "Wagenwäscher"],
    ["Waldwegewart", "Waldwegewartin", "Waldwegewart"],
    ["Wasserstraßenverkehrswart", "Wasserstraßenverkehrswartin", "Wasserstraßenverkehrswart"],
    ["Weichlöter", "Weichlöterin", "Weichlöter"],
    ["Werkzeughärter", "Werkzeughärterin", "Werkzeughärter"],
    ["Wirtschaftsanglist", "Wirtschaftsanglistin", "Wirtschaftsanglist"],
    ["Wirtschaftshispanist", "Wirtschaftshispanistin", "Wirtschaftshispanist"],
    ["Wirtschaftsromanist", "Wirtschaftsromanistin", "Wirtschaftsromanist"],
    ["Wirtschaftsrussist", "Wirtschaftsrussistin", "Wirtschaftsrussist"],
    ["Zirkusartist", "Zirkusartistin", "Zirkusartist"],
    ["Zusammenmontierer", "Zusammenmontiererin", "Zusammenmontierer"],
    ["Zweizylinderspinner", "Zweizylinderspinnerin", "Zweizylinderspinner"],
    ["Zwirnspinner", "Zwirnspinnerin", "Zwirnspinner"]
  ])("erkennt das intern geprüfte Paar %s/%s", (masculine, feminine, expected) => {
    expect(mapMappedSingularPair(masculine, feminine)).toBe(expected);
  });

  it.each([
    ["abteilungssteiger", "genitive", "abteilungssteigers"],
    ["audiometrist", "dative", "audiometristen"],
    ["bordwart", "genitive", "bordwarts"],
    ["bühnencosmetolog", "dative", "bühnencosmetologen"]
  ] as const)(
    "bildet die repräsentative Basis %s im Kasus %s korrekt ab",
    (base, grammaticalCase, expected) => {
      expect(mapMappedSingular(base, grammaticalCase)).toBe(expected);
    }
  );

  it.each([
    ["Diplom-Choreograph:innen", "Diplom-Choreographen"],
    ["Maschinen-Reviersteiger:innen", "Maschinen-Reviersteiger"],
    ["Multimedia-Konzeptionist:innen", "Multimedia-Konzeptionisten"],
    ["Repro-Bogenmontierer:innen", "Repro-Bogenmontierer"],
    ["Straßentunnelwart:innen", "Straßentunnelwarte"]
  ])("erhält die Segmentgroßschreibung für %s", (input, expected) => {
    expect(mappedPluralSeparatorsRule.apply(input)).toEqual({
      text: expected,
      replacements: 1
    });
  });
});
