import { describe, expect, it } from "vitest";
import { mappedPluralSeparatorsRule } from "../src/rules/mapped-plural-separators";
import { mapMappedSingular, mapMappedSingularPair } from "../src/rules/person-lexicon";
import {
  getReviewedPersonFormsWave87,
  reviewedPersonFormCountWave87
} from "../src/rules/reviewed-person-forms-wave-87";

// Unabhängiger Positivbestand zum Schutz vor versehentlichem Löschen oder Umbenennen.
const basen = [
  "ötztaler",
  "radevormwalder",
  "raesfelder",
  "ragusaner",
  "ramsauer",
  "ramsteiner",
  "rantumer",
  "ravensberger",
  "reckendorfer",
  "refrather",
  "rehauer",
  "reichenauer",
  "reichenbacher",
  "reichenhaller",
  "reimser",
  "reinsfelder",
  "rekener",
  "remagener",
  "reutershagener",
  "rheiderländer",
  "rheindorfer",
  "rhöndorfer",
  "riedenburger",
  "riegelsberger",
  "rietheimer",
  "rimburger",
  "rippiner",
  "röderländer",
  "roetgener",
  "rommerskirchener",
  "rosporter",
  "rösrather",
  "rosslauer",
  "rüdersdorfer",
  "rüdesheimer",
  "rudolstädter",
  "rüganer",
  "ruhlaer",
  "sabiner",
  "salentiner",
  "salier",
  "salmrohrer",
  "samaritaner",
  "sanitzer",
  "sassenberger",
  "sassnitzer",
  "saterländer",
  "savoyer",
  "schaager",
  "schärdinger",
  "scheidegger",
  "schellenberger",
  "schengener",
  "schenklengsfelder",
  "schermbecker",
  "schiersteiner",
  "schirgiswalder",
  "schleidener",
  "schlochauer",
  "schmallenberger",
  "schneidemühler",
  "schönaicher",
  "schönauer",
  "schönebecker",
  "schöneberger",
  "schöneburger",
  "schönefelder",
  "schopfheimer",
  "schwalbacher",
  "schwalmtaler",
  "schwandorfer",
  "schwartauer",
  "schwarzenbacher",
  "schwarzenberger",
  "schweicher",
  "schwelmer",
  "schwenninger",
  "schwetzinger",
  "seeländer",
  "selfkanter",
  "seligenstädter",
  "selzthaler",
  "senftenberger",
  "seouler",
  "seubersdorfer",
  "sewastopoler",
  "sibirier",
  "siegerländer",
  "simmerather",
  "simpelvelder",
  "singener",
  "sittarder",
  "slawonier",
  "smolensker",
  "söflinger",
  "söldener",
  "sommerauer",
  "spiekerooger",
  "stadtallendorfer",
  "stahnsdorfer",
  "stargarder",
  "steinenbronner",
  "steinhagener",
  "stendaler",
  "steyrer",
  "stockacher",
  "straelener",
  "strausberger",
  "stukenbrocker",
  "styrumer",
  "süchtelner",
  "süderlügumer",
  "südländer",
  "sugambrer",
  "sulzbacher",
  "sumerer",
  "tahitianer",
  "talheimer",
  "tangermünder",
  "tarentiner",
  "taunussteiner",
  "tecklenburger",
  "tegernseer",
  "teltower",
  "tenkterer",
  "teutschenthaler",
  "thessalier",
  "thiergartener",
  "thorner",
  "thraker",
  "tikriter",
  "tirschenreuther",
  "toskaner",
  "transatlantiker",
  "traundorfer",
  "trefflinger",
  "trendelburger",
  "treptower",
  "trienter",
  "trinitarier",
  "troisdorfer",
  "türkheimer",
  "tutzinger",
  "überlinger",
  "ubier",
  "unitarier",
  "unterauer",
  "unterhachinger",
  "uruker",
  "usinger",
  "vaalser",
  "veitshöchheimer",
  "velburger",
  "versmolder",
  "vetschauer",
  "viandener",
  "vinetaer",
  "voerder",
  "vöhinger",
  "völklinger",
  "vorchdorfer",
  "wachtendonker",
  "wackersdorfer",
  "wagrier",
  "währinger",
  "walddorfhäslacher",
  "waldenbucher",
  "waldnieler",
  "waldracher",
  "waldshuter",
  "walheimer",
  "walldorfer",
  "wallenhorster",
  "wallufer",
  "wangener",
  "warsteiner",
  "washingtoner",
  "wassenberger",
  "wasserburger",
  "wattenscheider",
  "weerter",
  "wegberger",
  "weilburger",
  "weilheimer",
  "weimerskircher",
  "weissacher",
  "weissenbacher",
  "wellingtoner",
  "welschschweizer",
  "wemdinger",
  "werdohler",
  "werler",
  "wermelskirchener",
  "wernigeroder",
  "werstener",
  "weseler",
  "wesselinger",
  "westerburger",
  "westerländer",
  "westerwälder",
  "westeuropäer",
  "wetterauer",
  "wiedenbrücker",
  "wiehler",
  "wiesenbronner",
  "wiesmoorer",
  "wildenrather",
  "wilhelmsburger",
  "wimpfener",
  "wittdüner",
  "wittgensteiner",
  "wittstocker",
  "woffelsbacher",
  "wolbecker",
  "womrather",
  "wörlitzer",
  "wünnenberger",
  "würgendorfer",
  "würselner",
  "wurzacher",
  "wyker",
  "zähringer",
  "zeitzer",
  "zermatter",
  "zgorzelecer",
  "zisterzienser",
  "zizlauer",
  "züdorfer",
  "zurlaubener",
  "zweibrückener",
  "zwischenahner"
] as const;

// Hier ist ein reines Personenmapping ausdrücklich nicht freigegeben.
const negativeBasen = [
  "edamer",
  "bernhardiner",
  "bettwärmer",
  "hammer",
  "bestseller",
  "regenschauer",
  "zauber",
  "buhler",
  "neunziger",
  "neunundvierziger",
  "hindenburger",
  "radevormwalderfirma",
  "nutzniesser"
] as const;

describe("Lexikon-Welle 87: 231 geprüfte Herkunfts- und Einwohnerbezeichnungen", () => {
  it("enthält den deduplizierten Exaktbestand", () => {
    expect(basen).toHaveLength(231);
    expect(new Set(basen).size).toBe(231);
    expect(reviewedPersonFormCountWave87).toBe(231);
  });

  it.each(basen)("prüft für %s Singular, Plural, Femininform und Kasus", (basis) => {
    const feminin = `${basis}in`;
    expect(getReviewedPersonFormsWave87(basis)).toEqual({
      plural: basis,
      singular: basis,
      feminineSingular: feminin,
      obliqueSingular: basis,
      genitiveSingular: `${basis}s`
    });
    expect(mappedPluralSeparatorsRule.apply(`${basis}:innen`)).toEqual({
      text: basis,
      replacements: 1
    });
    expect(mapMappedSingularPair(basis, feminin)).toBe(basis);
    expect(mapMappedSingularPair(feminin, basis)).toBe(basis);
    for (const kasus of ["nominative", "accusative", "dative"] as const) {
      expect(mapMappedSingular(basis, kasus)).toBe(basis);
    }
    expect(mapMappedSingular(basis, "genitive")).toBe(`${basis}s`);
  });

  it.each(negativeBasen)("schließt die zweifelhafte Basis %s aus", (basis) => {
    expect(getReviewedPersonFormsWave87(basis)).toBeUndefined();
  });

  it("lässt normale, unmarkierte Wörter unverändert", () => {
    expect(mappedPluralSeparatorsRule.apply("Radevormwalder")).toEqual({
      text: "Radevormwalder",
      replacements: 0
    });
    expect(getReviewedPersonFormsWave87("radevormwalderfirma")).toBeUndefined();
  });
});