import { describe, expect, it } from "vitest";
import { mappedPluralSeparatorsRule } from "../src/rules/mapped-plural-separators";
import {
  mapMappedSingular,
  mapMappedSingularPair
} from "../src/rules/person-lexicon";
import {
  getReviewedPersonFormsWave74,
  reviewedPersonFormCountWave74
} from "../src/rules/reviewed-person-forms-wave-74";

describe("vierundsiebzigste Lexikon-Ausbauwelle", () => {
  it("enthält alle 148 intern geprüften Exaktmappings vollständig", () => {
    expect(reviewedPersonFormCountWave74).toBe(148);

    for (const base of [
      "abkantpresser",
      "automatenbohrer",
      "automatenspritzer",
      "baustellenrechner",
      "bildmischer",
      "brunnenbohrer",
      "chipbestücker",
      "chipsröster",
      "diamantziehsteinbohrer",
      "dnc-bohrer",
      "edelsteinbohrer",
      "einpresser",
      "elektrobrenner",
      "fettmischer",
      "fischfroster",
      "fleischfroster",
      "folienpresser",
      "folienwalzer",
      "folienzieher",
      "gewindewalzer",
      "grobdrahtzieher",
      "großstanzer",
      "gummimischer",
      "gummiwalzer",
      "handmaschinenbohrer",
      "handpresser",
      "handschuhlederstanzer",
      "honigkocher",
      "horizontalbohrer",
      "kabelspuler",
      "kakaobohnenröster",
      "kakaopresser",
      "kaltpresser",
      "kaltwalzer",
      "kaltzieher",
      "kappenstanzer",
      "kartoffelchipsröster",
      "kartoffelflocker",
      "kerambrenner",
      "kerampresser",
      "kernschießer",
      "kokillenspritzer",
      "konservierungsguterhitzer",
      "konservierungsgutfroster",
      "konservierungsgutkocher",
      "kostenrechner",
      "kostenstellenrechner",
      "kostenträgerrechner",
      "kunststoffpresser",
      "kunststoffspritzer",
      "kunststofftiefzieher",
      "kuvertstanzer",
      "ledersohlenstanzer",
      "lederstanzer",
      "leiterplattenbestücker",
      "marmeladenkocher",
      "maschinenbestücker",
      "maschinenbrenner",
      "maschinenglätter",
      "maschinenhefter",
      "maschinenkopierer",
      "maschinenplätter",
      "maschinenpresser",
      "maschinenstanzer",
      "metallbohrer",
      "metallbrenner",
      "metalldrahtzieher",
      "metallpresser",
      "metallrohrzieher",
      "metallspritzer",
      "metallstanzer",
      "metalltiefzieher",
      "metallwalzer",
      "milchproduktmischer",
      "mineralbrenner",
      "müllsortierer",
      "nc-bohrer",
      "nc-stanzer",
      "nietenpresser",
      "oberlederstanzer",
      "ofenbrenner",
      "offsetplattenkopierer",
      "paketsortierer",
      "papierpresser",
      "papiersortierer",
      "papierstanzer",
      "pappenglätter",
      "parkettabzieher",
      "platinenbestücker",
      "plattenpresser",
      "plisseebrenner",
      "plisseepresser",
      "plätter",
      "postsortierer",
      "profildrahtzieher",
      "profilwalzer",
      "präzisionszieher",
      "radialbohrer",
      "recycler",
      "reprokopierer",
      "rohrwalzer",
      "rohrzieher",
      "rotationsroller",
      "röhrenzieher",
      "schmiedepresser",
      "schneidbrenner",
      "schottermischer",
      "schraubenpresser",
      "sohlenstanzer",
      "sortenrechner",
      "springer",
      "spuler",
      "stabzieher",
      "stahlblechstanzer",
      "stahlbohrer",
      "stahldrahtzieher",
      "stahlwalzer",
      "stangenzieher",
      "steinbruchbohrer",
      "steinmischer",
      "steinsortierer",
      "steinspalter",
      "steinzeugsortierer",
      "sterilisierer",
      "teerkocher",
      "teigmischer",
      "tiefbohrer",
      "tiefdruckkopierer",
      "tiefzieher",
      "toleranzbohrer",
      "trickkopierer",
      "umspuler",
      "umwalzer",
      "vertikalbohrer",
      "verzahner",
      "vorroller",
      "vorstecker",
      "wareneinsortierer",
      "warensortierer",
      "warmpresser",
      "warmwalzer",
      "wasserentsorger",
      "wasserversorger",
      "wellblechwalzer",
      "zahnradstoßer",
      "ziehsteinbohrer",
      "zuckerkocher",
      "ölpresser"
    ]) {
      expect(getReviewedPersonFormsWave74(base), base).toEqual({
        plural: base,
        singular: base,
        feminineSingular: `${base}in`,
        obliqueSingular: base,
        genitiveSingular: `${base}s`
      });
    }
  });

  it("lässt die 65 schwierigen Restformen weiterhin offen", () => {
    for (const base of [
      "betonbohrer",
      "bohrer",
      "brecher",
      "brenner",
      "cnc-bohrer",
      "commercialmanger",
      "computervisualist",
      "devisenrechner",
      "eri-wart",
      "euromaster",
      "eutonist",
      "fennist",
      "fiaker",
      "gefriertrockner",
      "gegenhalter",
      "geldzähler",
      "geschirrspüler",
      "geschirrviz",
      "getränkemixer",
      "griller",
      "handbohrer",
      "holztrockner",
      "ingenier",
      "kabelbinder",
      "kernbohrer",
      "kopierer",
      "lader",
      "lastverteiler",
      "liegerviz",
      "mindermaschinenstricker",
      "mischer",
      "mixer",
      "modellist",
      "monitor",
      "nehmer",
      "oralchirug",
      "pfahlrammer",
      "pflasterrammer",
      "planierer",
      "printer",
      "rammer",
      "reiber",
      "reiher",
      "roller",
      "röster",
      "schaber",
      "schlacker",
      "sortierer",
      "spalter",
      "spüler",
      "stanzer",
      "steinbohrer",
      "stoßer",
      "tapetenkleber",
      "tapisserist",
      "vermessinger",
      "verschmelzer",
      "vervielfältiger",
      "walker",
      "walzer",
      "wickler",
      "wäscher",
      "xerograf",
      "zieher",
      "zwicker"
    ]) {
      expect(getReviewedPersonFormsWave74(base), base).toBeUndefined();
    }
  });

  it.each([
    ["Abkantpresser:innen", "Abkantpresser"],
    ["Dnc-bohrer:innen", "Dnc-bohrer"],
    ["Konservierungsguterhitzer:innen", "Konservierungsguterhitzer"],
    ["Kunststoffspritzer:innen", "Kunststoffspritzer"],
    ["Leiterplattenbestücker:innen", "Leiterplattenbestücker"],
    ["Metallrohrzieher:innen", "Metallrohrzieher"],
    ["Müllsortierer:innen", "Müllsortierer"],
    ["Plätter:innen", "Plätter"],
    ["Recycler:innen", "Recycler"],
    ["Springer:innen", "Springer"],
    ["Tiefdruckkopierer:innen", "Tiefdruckkopierer"],
    ["Wasserentsorger:innen", "Wasserentsorger"],
    ["Ölpresser:innen", "Ölpresser"]
  ])("ersetzt repräsentative geprüfte Plurale %s", (input, expected) => {
    expect(mappedPluralSeparatorsRule.apply(input)).toEqual({
      text: expected,
      replacements: 1
    });
  });

  it.each([
    ["Abkantpresser", "Abkantpresserin", "Abkantpresser"],
    ["Dnc-bohrer", "Dnc-bohrerin", "Dnc-bohrer"],
    ["Konservierungsguterhitzer", "Konservierungsguterhitzerin", "Konservierungsguterhitzer"],
    ["Kunststoffspritzer", "Kunststoffspritzerin", "Kunststoffspritzer"],
    ["Leiterplattenbestücker", "Leiterplattenbestückerin", "Leiterplattenbestücker"],
    ["Metallrohrzieher", "Metallrohrzieherin", "Metallrohrzieher"],
    ["Müllsortierer", "Müllsortiererin", "Müllsortierer"],
    ["Plätter", "Plätterin", "Plätter"]
  ])("erkennt repräsentative geprüfte Paare %s/%s", (masculine, feminine, expected) => {
    expect(mapMappedSingularPair(masculine, feminine)).toBe(expected);
  });

  it.each([
    ["abkantpresser", "nominative", "abkantpresser"],
    ["abkantpresser", "genitive", "abkantpressers"],
    ["dnc-bohrer", "nominative", "dnc-bohrer"],
    ["dnc-bohrer", "genitive", "dnc-bohrers"],
    ["konservierungsguterhitzer", "nominative", "konservierungsguterhitzer"],
    ["konservierungsguterhitzer", "genitive", "konservierungsguterhitzers"],
    ["kunststoffspritzer", "nominative", "kunststoffspritzer"],
    ["kunststoffspritzer", "genitive", "kunststoffspritzers"],
    ["leiterplattenbestücker", "nominative", "leiterplattenbestücker"],
    ["leiterplattenbestücker", "genitive", "leiterplattenbestückers"],
    ["metallrohrzieher", "nominative", "metallrohrzieher"],
    ["metallrohrzieher", "genitive", "metallrohrziehers"],
    ["müllsortierer", "nominative", "müllsortierer"],
    ["müllsortierer", "genitive", "müllsortierers"],
    ["plätter", "nominative", "plätter"],
    ["plätter", "genitive", "plätters"]
  ] as const)(
    "bildet repräsentative Basis %s im Kasus %s korrekt ab",
    (base, grammaticalCase, expected) => {
      expect(mapMappedSingular(base, grammaticalCase)).toBe(expected);
    }
  );
});
