import { describe, expect, it } from "vitest";
import { mappedPluralSeparatorsRule } from "../src/rules/mapped-plural-separators";
import { mapMappedSingular, mapMappedSingularPair } from "../src/rules/person-lexicon";
import {
  getReviewedPersonFormsWave90,
  reviewedPersonFormCountWave90
} from "../src/rules/reviewed-person-forms-wave-90";

// Eigenständiger Sollkatalog für vier Flexionsklassen; keine automatischen Endungstreffer.
const erwarteteBasen = {
  "unveraendert": [
  "abgrater",
  "ablader",
  "ablänger",
  "alkoholmischer",
  "anodisierer",
  "anspruchsschätzer",
  "autoverwerter",
  "bandsäger",
  "baugeräteschlosser",
  "behältermontierer",
  "berufsfussballer",
  "besamer",
  "betongiesser",
  "betonierer",
  "bevölkerungsstatistiker",
  "bildungsstatistiker",
  "blattbinder",
  "bodypainter",
  "bodypiercer",
  "bohrhäuer",
  "bootsausrüster",
  "brennereiaufseher",
  "bronzierer",
  "broschürenverteiler",
  "brückenaufseher",
  "chemiefaserspinner",
  "chemischbügler",
  "cnc-stanzer",
  "cocktailbarmixer",
  "dämpfer",
  "desktop-publisher",
  "devisenbroker",
  "dokumentencontroller",
  "düngermischer",
  "eb-schweisser",
  "eisenentroster",
  "elektronenstrahlschweisser",
  "elektroplattierer",
  "extrudierer",
  "fact-checker",
  "fadenspinner",
  "faserspritzer",
  "fassadendecker",
  "fassader",
  "feiler",
  "fellgerber",
  "fellsortierer",
  "feuerschlucker",
  "film-toncutter",
  "finanzbroker",
  "finanzstatistiker",
  "formengiesser",
  "fotografiedrucker",
  "garnspuler",
  "garnzwirner",
  "gebäudeschätzer",
  "gefahrgutlenker",
  "geflügelgeschlechtsfinder",
  "gehaltsverrechner",
  "gerüster",
  "gesellschaftsstatistiker",
  "gesundheitsstatistiker",
  "glasurbrenner",
  "glaszieher",
  "granitbohrer",
  "granithauer",
  "granulatmischer",
  "greissler",
  "groundrigger",
  "gummistanzer",
  "gussputzer",
  "halal-fleischer",
  "halal-fleischhauer",
  "halal-metzger",
  "halal-schlachter",
  "handgiesser",
  "heeresflieger",
  "heissfoliendrucker",
  "holzfeiler",
  "hörfunkproducer",
  "hühnerfänger",
  "industrieschlosser",
  "inkassogebühreneinheber",
  "investmentbroker",
  "jagdaufseher",
  "jagdhüter",
  "kaffeebrenner",
  "kakaobohnenbrater",
  "kakaobohnenbrenner",
  "kalfaterer",
  "kanalräumer",
  "katastergeometer",
  "katastervermesser",
  "keilriemenausrüster",
  "keilriemenbeschichter",
  "keramgiesser",
  "keramikgiesser",
  "keramikpresser",
  "kfz-wäscher",
  "kiesstrahlbläser",
  "kokillengiesser",
  "koscher-fleischer",
  "koscher-metzger",
  "koscher-schlachter",
  "kostenschätzer",
  "kostümentwerfer",
  "kunststoffextrudierer",
  "kunststofffeiler",
  "kunststoffspritzmaschineneinsteller",
  "kunststofftemperer",
  "kupferschlosser",
  "lackmischer",
  "ladner",
  "lagerwirtschafter",
  "landwirtschaftsstatistiker",
  "laserschweisser",
  "lederwarenfinisher",
  "leichtmetallgiesser",
  "liegenschaftsschätzer",
  "lohnverrechner",
  "mälzereiaufseher",
  "marmorhauer",
  "maschinenöler",
  "maschinenzwicker",
  "massenberechner",
  "massengutfüller",
  "meeresbotaniker",
  "messerwerfer",
  "metallfeiler",
  "metallgiesser",
  "metalllöter",
  "metallschweisser",
  "metallsortierer",
  "militärfürsorger",
  "minenräumer",
  "möbelmontierer",
  "mülllader",
  "mülltrenner",
  "multimedia-storyboarder",
  "oberlederschärfer",
  "öler",
  "otoplastiker",
  "parkaufseher",
  "pflastersteinspalter",
  "physikstatistiker",
  "plastikspritzer",
  "plattenbrecher",
  "porzellangiesser",
  "profifussballer",
  "prospektzusteller",
  "prothetiker",
  "punktschweisser",
  "rechnungseintreiber",
  "reduzierwalzer",
  "regaleinräumer",
  "reifenreparierer",
  "rostentferner",
  "sandstrahlmattierer",
  "schächter",
  "schadensabschätzer",
  "schadstoffsanierer",
  "schafhüter",
  "schieferbohrer",
  "schieferhauer",
  "schiffsstauer",
  "schiffstakler",
  "schmuckentwerfer",
  "schneeräumer",
  "schnittgradierer",
  "schuhverpacker",
  "schulstatistiker",
  "schwenker",
  "seifentrockner",
  "sprachheilkundler",
  "stand-up-komiker",
  "steinbossierer",
  "steingutbrenner",
  "steinschärfer",
  "steuervollzieher",
  "stoffverpacker",
  "storyboarder",
  "strahler",
  "strassenfeger",
  "strassenkehrer",
  "synchroncutter",
  "synthetikspinner",
  "tabakblattbinder",
  "tabakblattknüpfer",
  "tabakblattsortierer",
  "taschner",
  "tauchmetallisierer",
  "textilentwerfer",
  "textilflechter",
  "tieraufpasser",
  "toncutter",
  "tonmischer",
  "tonwarenbrenner",
  "touristenunterhalter",
  "tütenkleber",
  "verkupferer",
  "vermesser",
  "vermessungsstatistiker",
  "verschieber",
  "verschleisser",
  "versicherungsstatistiker",
  "versilberer",
  "wahlstatistiker",
  "waldhüter",
  "wassermesser",
  "web-master",
  "werbemittelverteiler",
  "werkstattschlosser",
  "wetteransager",
  "winder",
  "wollgarnspinner",
  "wollgarnspuler",
  "wollgarnzwirner",
  "zahnprothetiker",
  "zellgenetiker",
  "zementierer",
  "ziegelgiesser",
  "zugfertigsteller"
  ],
  "plusE": [
  "appreteur",
  "auslagendekorateur",
  "bataillonskommandeur",
  "dekontaminateur",
  "elektrolysezellenfabrikateur",
  "emailleur",
  "extrudeur",
  "flugzeugtankwart",
  "forstwart",
  "fussjongleur",
  "geschwaderkommandeur",
  "hundedresseur",
  "instrumentenwart",
  "klärwart",
  "lederappreteur",
  "magazineur",
  "reifenvulkaniseur",
  "schaufensterdekorateur",
  "schiefermischanlagenwart",
  "stoffappreteur",
  "tiertransporteur",
  "verifikateur",
  "viehtransporteur",
  "voltigeur",
  "zentralbankgouverneur"
  ],
  "plusEn": [
  "antiquitätenrestaurator",
  "anwendungskonfigurator",
  "autofahrinstruktor",
  "autoinstruktor",
  "computer-animator",
  "epilator",
  "exekutor",
  "fahrschulinstruktor",
  "fahrtechnikinstruktor",
  "fahrzeugrestaurator",
  "hausautomationsintegrator",
  "immobilientaxator",
  "it-anwendungskonfigurator",
  "kfz-fahrinstruktor",
  "lichtpult-operator",
  "metall-am-operator",
  "motorradinstruktor",
  "musikinstrumentenrestaurator",
  "oldtimer-restaurator",
  "oldtimerrestaurator",
  "prägepresse-operator",
  "scan-operator",
  "steadicam-operator",
  "stop-motion-animator",
  "systemkonfigurator",
  "translator"
  ],
  "schwachEn": [
  "advokat",
  "anthropogeograf",
  "antipodist",
  "buchhaltungsanalyst",
  "bühneninspizient",
  "bühnenkampfchoreograph",
  "call-center-analyst",
  "dividendenanalyst",
  "energieanalyst",
  "equilibrist",
  "fakturist",
  "figurant",
  "fingernagel-stylist",
  "gambist",
  "grossist",
  "haarstylist",
  "handstandartist",
  "haushaltsanalyst",
  "hochseilartist",
  "humangeograf",
  "hydrograf",
  "infanterist",
  "inkassant",
  "kartolithograf",
  "klarinettist",
  "kraftakrobat",
  "kuponanalyst",
  "lexikograf",
  "librettist",
  "logistik-analyst",
  "luftverschmutzungsanalyst",
  "make-up-artist",
  "markforschungsanalyst",
  "marktforschungsanalyst",
  "mergers-and-acquisitions-analyst",
  "nachhaltigkeitsanalyst",
  "nachkalkulant",
  "orthodontist",
  "percussionist",
  "pharmakovigilant",
  "physiogeograf",
  "prosthodontist",
  "querflötist",
  "rechtskonsulent",
  "schönheits-stylist",
  "software-analyst",
  "softwareanalyst",
  "spiritist",
  "strassenartist",
  "telekommunikationsanalyst",
  "telepath",
  "textilkolorist",
  "tier-osteopath",
  "tierosteopath",
  "trafikant",
  "unternehmensanalyst",
  "ventriloquist",
  "vergütungsanalyst",
  "verteidigungsanalyst",
  "vokalist",
  "wirtschaftskonsulent",
  "zeitungskolumnist",
  "zolldeklarant"
  ]
} as const;
const testfaelle = [
  ...erwarteteBasen.unveraendert.map((basis) => ({ basis, plural: basis, schwach: false })),
  ...erwarteteBasen.plusE.map((basis) => ({ basis, plural: `${basis}e`, schwach: false })),
  ...erwarteteBasen.plusEn.map((basis) => ({ basis, plural: `${basis}en`, schwach: false })),
  ...erwarteteBasen.schwachEn.map((basis) => ({ basis, plural: `${basis}en`, schwach: true }))
];

describe("Lexikonwelle 90: exakte Personenformen verschiedener Flexionsklassen", () => {
  it("umfasst exakt 336 verschiedene freigegebene Personenbasen", () => {
    expect(testfaelle).toHaveLength(336);
    expect(new Set(testfaelle.map(({basis}) => basis)).size).toBe(336);
    expect(reviewedPersonFormCountWave90).toBe(336);
  });

  it.each(testfaelle)("$basis: Plural, Singular, Kasus und Paarform stimmen", ({ basis, plural, schwach }) => {
    const feminin = `${basis}in`;
    const obliqu = schwach ? plural : basis;
    const genitiv = schwach ? plural : `${basis}s`;
    expect(getReviewedPersonFormsWave90(basis)).toEqual({
      plural,
      singular: basis,
      feminineSingular: feminin,
      obliqueSingular: obliqu,
      genitiveSingular: genitiv
    });
    expect(mappedPluralSeparatorsRule.apply(`${basis}:innen`)).toEqual({
      text: plural,
      replacements: 1
    });
    expect(mapMappedSingularPair(basis, feminin)).toBe(basis);
    expect(mapMappedSingularPair(feminin, basis)).toBe(basis);
    expect(mapMappedSingular(basis, "nominative")).toBe(basis);
    expect(mapMappedSingular(basis, "accusative")).toBe(obliqu);
    expect(mapMappedSingular(basis, "dative")).toBe(obliqu);
    expect(mapMappedSingular(basis, "genitive")).toBe(genitiv);
  });

  it.each(["general", "brigadegeneral", "konsul", "major", "generalleutnant", "hotelportier", "stallknecht", "gummimischerfirma", "abgraterteam"])(
    "leitet für die nicht freigegebene Basis %s keine neue Form ab",
    (basis) => {
      expect(getReviewedPersonFormsWave90(basis)).toBeUndefined();
    }
  );
  it("verändert normale unbezeichnete Wörter nicht", () => {
    expect(mappedPluralSeparatorsRule.apply("Der Betonierer untersucht die Anlage.")).toEqual({
      text: "Der Betonierer untersucht die Anlage.",
      replacements: 0
    });
  });
});
