import { describe, expect, it } from "vitest";
import { mappedPluralSeparatorsRule } from "../src/rules/mapped-plural-separators";
import {
  mapMappedSingular,
  mapMappedSingularPair
} from "../src/rules/person-lexicon";

describe("sechsundfünfzigste konservative Lexikon-Ausbauwelle", () => {
  it.each([
    ["Archivrestaurator:innen", "Archivrestauratoren"],
    ["Auftragsakquisiteur:innen", "Auftragsakquisiteure"],
    ["Aufzugschlosser:innen", "Aufzugschlosser"],
    ["Augenarztgehilf:innen", "Augenarztgehilfen"],
    ["Augenoptikergehilf:innen", "Augenoptikergehilfen"],
    ["Ausstellungsschreiner:innen", "Ausstellungsschreiner"],
    ["Autoreparaturschlosser:innen", "Autoreparaturschlosser"],
    ["Autoschlosser:innen", "Autoschlosser"],
    ["Bahnbetriebsschlosser:innen", "Bahnbetriebsschlosser"],
    ["Bandagist:innen", "Bandagisten"],
    ["Bankenanalyst:innen", "Bankenanalysten"],
    ["Bankrevisor:innen", "Bankrevisoren"],
    ["Bargehilf:innen", "Bargehilfen"],
    ["Baumaschinenschlosser:innen", "Baumaschinenschlosser"],
    ["Bauschlosser:innen", "Bauschlosser"],
    ["Bauschreiner:innen", "Bauschreiner"],
    ["Bausparkassenrevisor:innen", "Bausparkassenrevisoren"],
    ["Beilagenköch:innen", "Beilagenköche"],
    ["Bestattungsgehilf:innen", "Bestattungsgehilfen"],
    ["Betriebsschlosser:innen", "Betriebsschlosser"],
    ["Betriebsschreiner:innen", "Betriebsschreiner"],
    ["Bienenzuchtgehilf:innen", "Bienenzuchtgehilfen"],
    ["Bierbrauer:innen", "Bierbrauer"],
    ["Blaudrucker:innen", "Blaudrucker"],
    ["Blechdrucker:innen", "Blechdrucker"],
    ["Blechschlosser:innen", "Blechschlosser"],
    ["Blindenschriftdrucker:innen", "Blindenschriftdrucker"],
    ["Bodenakrobat:innen", "Bodenakrobaten"],
    ["Bohrgehilf:innen", "Bohrgehilfen"],
    ["Bonitätsanalyst:innen", "Bonitätsanalysten"],
    ["Bratenköch:innen", "Bratenköche"],
    ["Brauer:innen", "Brauer"],
    ["Brückenbauschlosser:innen", "Brückenbauschlosser"],
    ["Buchdrucker:innen", "Buchdrucker"],
    ["Buchrestaurator:innen", "Buchrestauratoren"],
    ["Buntdrucker:innen", "Buntdrucker"],
    ["Business-analyst:innen", "Business-analysten"],
    ["Bäckergehilf:innen", "Bäckergehilfen"],
    ["Büchereigehilf:innen", "Büchereigehilfen"],
    ["Büfettgehilf:innen", "Büfettgehilfen"],
    ["Bühnenakrobat:innen", "Bühnenakrobaten"],
    ["Bühnenschreiner:innen", "Bühnenschreiner"],
    ["Bürogehilf:innen", "Bürogehilfen"],
    ["Cash-flow-analyst:innen", "Cash-flow-analysten"],
    ["Chefköch:innen", "Chefköche"],
    ["Data-analyst:innen", "Data-analysten"],
    ["Data-warehouse-analyst:innen", "Data-warehouse-analysten"],
    ["Denkmalrestaurator:innen", "Denkmalrestauratoren"],
    ["Dieselmotorenschlosser:innen", "Dieselmotorenschlosser"],
    ["Digital-analyst:innen", "Digital-analysten"],
  ])("normalisiert den abgesicherten Personenstamm %s", (input, expected) => {
    expect(mappedPluralSeparatorsRule.apply(input)).toEqual({
      text: expected,
      replacements: 1
    });
  });

  it.each([
    ["Archivrestaurator", "Archivrestauratorin", "Archivrestaurator"],
    ["Auftragsakquisiteur", "Auftragsakquisiteurin", "Auftragsakquisiteur"],
    ["Aufzugschlosser", "Aufzugschlosserin", "Aufzugschlosser"],
    ["Augenarztgehilfe", "Augenarztgehilfin", "Augenarztgehilfe"],
    ["Augenoptikergehilfe", "Augenoptikergehilfin", "Augenoptikergehilfe"],
    ["Ausstellungsschreiner", "Ausstellungsschreinerin", "Ausstellungsschreiner"],
    ["Autoreparaturschlosser", "Autoreparaturschlosserin", "Autoreparaturschlosser"],
    ["Autoschlosser", "Autoschlosserin", "Autoschlosser"],
    ["Bahnbetriebsschlosser", "Bahnbetriebsschlosserin", "Bahnbetriebsschlosser"],
    ["Bandagist", "Bandagistin", "Bandagist"],
    ["Bankenanalyst", "Bankenanalystin", "Bankenanalyst"],
    ["Bankrevisor", "Bankrevisorin", "Bankrevisor"],
    ["Bargehilfe", "Bargehilfin", "Bargehilfe"],
    ["Baumaschinenschlosser", "Baumaschinenschlosserin", "Baumaschinenschlosser"],
    ["Bauschlosser", "Bauschlosserin", "Bauschlosser"],
    ["Bauschreiner", "Bauschreinerin", "Bauschreiner"],
    ["Bausparkassenrevisor", "Bausparkassenrevisorin", "Bausparkassenrevisor"],
    ["Beilagenkoch", "Beilagenköchin", "Beilagenkoch"],
    ["Bestattungsgehilfe", "Bestattungsgehilfin", "Bestattungsgehilfe"],
    ["Betriebsschlosser", "Betriebsschlosserin", "Betriebsschlosser"],
    ["Betriebsschreiner", "Betriebsschreinerin", "Betriebsschreiner"],
    ["Bienenzuchtgehilfe", "Bienenzuchtgehilfin", "Bienenzuchtgehilfe"],
    ["Bierbrauer", "Bierbrauerin", "Bierbrauer"],
    ["Blaudrucker", "Blaudruckerin", "Blaudrucker"],
    ["Blechdrucker", "Blechdruckerin", "Blechdrucker"],
    ["Blechschlosser", "Blechschlosserin", "Blechschlosser"],
    ["Blindenschriftdrucker", "Blindenschriftdruckerin", "Blindenschriftdrucker"],
    ["Bodenakrobat", "Bodenakrobatin", "Bodenakrobat"],
    ["Bohrgehilfe", "Bohrgehilfin", "Bohrgehilfe"],
    ["Bonitätsanalyst", "Bonitätsanalystin", "Bonitätsanalyst"],
    ["Bratenkoch", "Bratenköchin", "Bratenkoch"],
    ["Brauer", "Brauerin", "Brauer"],
    ["Brückenbauschlosser", "Brückenbauschlosserin", "Brückenbauschlosser"],
    ["Buchdrucker", "Buchdruckerin", "Buchdrucker"],
    ["Buchrestaurator", "Buchrestauratorin", "Buchrestaurator"],
    ["Buntdrucker", "Buntdruckerin", "Buntdrucker"],
    ["Business-analyst", "Business-analystin", "Business-analyst"],
    ["Bäckergehilfe", "Bäckergehilfin", "Bäckergehilfe"],
    ["Büchereigehilfe", "Büchereigehilfin", "Büchereigehilfe"],
    ["Büfettgehilfe", "Büfettgehilfin", "Büfettgehilfe"],
    ["Bühnenakrobat", "Bühnenakrobatin", "Bühnenakrobat"],
    ["Bühnenschreiner", "Bühnenschreinerin", "Bühnenschreiner"],
    ["Bürogehilfe", "Bürogehilfin", "Bürogehilfe"],
    ["Cash-flow-analyst", "Cash-flow-analystin", "Cash-flow-analyst"],
    ["Chefkoch", "Chefköchin", "Chefkoch"],
    ["Data-analyst", "Data-analystin", "Data-analyst"],
    ["Data-warehouse-analyst", "Data-warehouse-analystin", "Data-warehouse-analyst"],
    ["Denkmalrestaurator", "Denkmalrestauratorin", "Denkmalrestaurator"],
    ["Dieselmotorenschlosser", "Dieselmotorenschlosserin", "Dieselmotorenschlosser"],
    ["Digital-analyst", "Digital-analystin", "Digital-analyst"],
  ])("erkennt das abgesicherte Paar %s/%s", (masculine, feminine, expected) => {
    expect(mapMappedSingularPair(masculine, feminine)).toBe(expected);
  });

  it.each([
    ["archivrestaurator", "genitive", "archivrestaurators"],
    ["auftragsakquisiteur", "genitive", "auftragsakquisiteurs"],
    ["aufzugschlosser", "genitive", "aufzugschlossers"],
    ["augenarztgehilf", "dative", "augenarztgehilfen"],
    ["bandagist", "accusative", "bandagisten"],
    ["bankenanalyst", "genitive", "bankenanalysten"],
    ["beilagenköch", "genitive", "beilagenkochs"],
    ["bierbrauer", "genitive", "bierbrauers"],
    ["bodenakrobat", "dative", "bodenakrobaten"],
    ["chefköch", "accusative", "chefkoch"],
  ] as const)(
    "bildet %s im Kasus %s korrekt ab",
    (base, grammaticalCase, expected) => {
      expect(mapMappedSingular(base, grammaticalCase)).toBe(expected);
    }
  );
});
