import { describe, expect, it } from "vitest";
import { mappedPluralSeparatorsRule } from "../src/rules/mapped-plural-separators";
import {
  mapMappedSingular,
  mapMappedSingularPair
} from "../src/rules/person-lexicon";
import {
  getReviewedPersonFormsWave62,
  reviewedPersonFormCountWave62
} from "../src/rules/reviewed-person-forms-wave-62";

describe("zweiundsechzigste Lexikon-Ausbauwelle", () => {
  it("enthält genau den intern geprüften Exaktbestand", () => {
    expect(reviewedPersonFormCountWave62).toBe(250);
    for (const base of [
      "computervisualist",
      "eri-wart",
      "eutonist",
      "fennist",
      "mindermaschinenstricker",
      "modellist",
      "tapisserist",
      "verschmelzer",
      "wäscher",
      "automatenbohrer",
      "bandstanzer",
      "bandwalzer",
      "branntsteinbrenner",
      "ankerwickler",
      "sortierer",
      "kopierer",
      "kostenrechner",
      "fantasieierer"
    ]) {
      expect(getReviewedPersonFormsWave62(base), base).toBeUndefined();
    }
  });

  it.each([
    ["Abfallbeseitiger:innen", "Abfallbeseitiger"],
    ["Alleinunterhalter:innen", "Alleinunterhalter"],
    ["Ankleider:innen", "Ankleider"],
    ["Annehmer:innen", "Annehmer"],
    ["Anorganiker:innen", "Anorganiker"],
    ["Anstreicher:innen", "Anstreicher"],
    ["Auftragsannehmer:innen", "Auftragsannehmer"],
    ["Ausbeiner:innen", "Ausbeiner"],
    ["Auskleider:innen", "Auskleider"],
    ["Auskunfterteiler:innen", "Auskunfterteiler"],
    ["Auszahler:innen", "Auszahler"],
    ["Automatenauffüller:innen", "Automatenauffüller"],
    ["Automatenaufsteller:innen", "Automatenaufsteller"],
    ["Automatenbefüller:innen", "Automatenbefüller"],
    ["Automateneinsteller:innen", "Automateneinsteller"],
    ["Baublechner:innen", "Baublechner"],
    ["Baumfäller:innen", "Baumfäller"],
    ["Bausparkassenvertragswerber:innen", "Bausparkassenvertragswerber"],
    ["Beizer:innen", "Beizer"],
    ["Belader:innen", "Belader"],
    ["Bergvermesser:innen", "Bergvermesser"],
    ["Beschrifter:innen", "Beschrifter"],
    ["Besohler:innen", "Besohler"],
    ["Bienenhalter:innen", "Bienenhalter"],
    ["Bierzapfer:innen", "Bierzapfer"],
    ["Bildeinrahmer:innen", "Bildeinrahmer"],
    ["Biosthetiker:innen", "Biosthetiker"],
    ["Blechner:innen", "Blechner"],
    ["Bodenprobennehmer:innen", "Bodenprobennehmer"],
    ["Bratwurstbrater:innen", "Bratwurstbrater"],
    ["Brechwerksteuerer:innen", "Brechwerksteuerer"],
    ["Bremser:innen", "Bremser"],
    ["Broschürer:innen", "Broschürer"],
    ["Bäumer:innen", "Bäumer"],
    ["Cafe-servierer:innen", "Cafe-servierer"],
    ["Carbonisierer:innen", "Carbonisierer"],
    ["Cnc-maschineneinsteller:innen", "Cnc-maschineneinsteller"],
    ["Damaszierer:innen", "Damaszierer"],
    ["Darrbeschicker:innen", "Darrbeschicker"],
    ["Darrer:innen", "Darrer"],
    ["Dekorentwerfer:innen", "Dekorentwerfer"],
    ["Depositenverwahrer:innen", "Depositenverwahrer"],
    ["Diamantreiber:innen", "Diamantreiber"],
    ["Drahtseilspleißer:innen", "Drahtseilspleißer"],
    ["Drahtstrecker:innen", "Drahtstrecker"],
    ["Drehmaschineneinsteller:innen", "Drehmaschineneinsteller"],
    ["Druckmaschineneinsteller:innen", "Druckmaschineneinsteller"],
    ["Egalisierer:innen", "Egalisierer"],
    ["Eicher:innen", "Eicher"],
    ["Einholer:innen", "Einholer"],
    ["Einschaler:innen", "Einschaler"],
    ["Einsteller:innen", "Einsteller"],
    ["Elektrolytisierer:innen", "Elektrolytisierer"],
    ["Entbaster:innen", "Entbaster"],
    ["Entgrater:innen", "Entgrater"],
    ["Entlader:innen", "Entlader"],
    ["Entroster:innen", "Entroster"],
    ["Entsorger:innen", "Entsorger"],
    ["Entsäurer:innen", "Entsäurer"],
    ["Entzunderer:innen", "Entzunderer"],
    ["Erodierer:innen", "Erodierer"],
    ["Fahrbetriebsregler:innen", "Fahrbetriebsregler"],
    ["Falkner:innen", "Falkner"],
    ["Fassadenverkleider:innen", "Fassadenverkleider"],
    ["Fehlersucher:innen", "Fehlersucher"],
    ["Feinblechner:innen", "Feinblechner"],
    ["Feinglänzer:innen", "Feinglänzer"],
    ["Fernmeldeaufklärer:innen", "Fernmeldeaufklärer"],
    ["Fernmelder:innen", "Fernmelder"],
    ["Fertiggerichtekonservierer:innen", "Fertiggerichtekonservierer"],
    ["Fertigsteller:innen", "Fertigsteller"],
    ["Filmcutter:innen", "Filmcutter"],
    ["Finierer:innen", "Finierer"],
    ["Fischhalter:innen", "Fischhalter"],
    ["Fixierer:innen", "Fixierer"],
    ["Flugdienstregler:innen", "Flugdienstregler"],
    ["Flugunfalluntersucher:innen", "Flugunfalluntersucher"],
    ["Flugzeughydrauliker:innen", "Flugzeughydrauliker"],
    ["Flugzeugpneumatiker:innen", "Flugzeugpneumatiker"],
    ["Folienbeschrifter:innen", "Folienbeschrifter"],
    ["Formenentwerfer:innen", "Formenentwerfer"],
    ["Fundraiser:innen", "Fundraiser"],
    ["Funktionsdiagnostiker:innen", "Funktionsdiagnostiker"],
    ["Furnierschäler:innen", "Furnierschäler"],
    ["Fördergurtinstandhalter:innen", "Fördergurtinstandhalter"],
    ["Galvanoverzinner:innen", "Galvanoverzinner"],
    ["Gebrauchsgraphiker:innen", "Gebrauchsgraphiker"],
    ["Geflügelfarmer:innen", "Geflügelfarmer"],
    ["Geflügelhalter:innen", "Geflügelhalter"],
    ["Geflügelschlachter:innen", "Geflügelschlachter"],
    ["Gefrierkonservierer:innen", "Gefrierkonservierer"],
    ["Geiger:innen", "Geiger"],
    ["Geldauszahler:innen", "Geldauszahler"],
    ["Geldeinnehmer:innen", "Geldeinnehmer"],
    ["Geldwechsler:innen", "Geldwechsler"],
    ["Geobotaniker:innen", "Geobotaniker"],
    ["Getränkeautomatenauffüller:innen", "Getränkeautomatenauffüller"],
    ["Getränkeautomatenbefüller:innen", "Getränkeautomatenbefüller"],
    ["Gewehrschäfter:innen", "Gewehrschäfter"],
    ["Gipser:innen", "Gipser"],
    ["Glasierer:innen", "Glasierer"],
    ["Glühlampenregenerierer:innen", "Glühlampenregenerierer"],
    ["Granulierer:innen", "Granulierer"],
    ["Greenkeeper:innen", "Greenkeeper"],
    ["Großwagner:innen", "Großwagner"],
    ["Hafner:innen", "Hafner"],
    ["Handharmonikastimmer:innen", "Handharmonikastimmer"],
    ["Handklöppler:innen", "Handklöppler"],
    ["Hartverchromer:innen", "Hartverchromer"],
    ["Hausentrümpeler:innen", "Hausentrümpeler"],
    ["Head-greenkeeper:innen", "Head-greenkeeper"],
    ["Heiler:innen", "Heiler"],
    ["Hellseher:innen", "Hellseher"],
    ["Heraldiker:innen", "Heraldiker"],
    ["Holzblasinstrumentenstimmer:innen", "Holzblasinstrumentenstimmer"],
    ["Holzmechnaniker:innen", "Holzmechnaniker"],
    ["Holzrücker:innen", "Holzrücker"],
    ["Huttrimmer:innen", "Huttrimmer"],
    ["Hydrauliker:innen", "Hydrauliker"],
    ["Industrieanstreicher:innen", "Industrieanstreicher"],
    ["Jagdheger:innen", "Jagdheger"],
    ["Jazzer:innen", "Jazzer"],
    ["Jodler:innen", "Jodler"],
    ["Kaminfeger:innen", "Kaminfeger"],
    ["Kampfmittelbeseitiger:innen", "Kampfmittelbeseitiger"],
    ["Karpfenhalter:innen", "Karpfenhalter"],
    ["Kaschierer:innen", "Kaschierer"],
    ["Kesselblechtreiber:innen", "Kesselblechtreiber"],
    ["Klöppler:innen", "Klöppler"],
    ["Knoter:innen", "Knoter"],
    ["Kodierer:innen", "Kodierer"],
    ["Kontaktierer:innen", "Kontaktierer"],
    ["Kontaktlinsenanpasser:innen", "Kontaktlinsenanpasser"],
    ["Kunstdidaktiker:innen", "Kunstdidaktiker"],
    ["Kunstgeschichtler:innen", "Kunstgeschichtler"],
    ["Kunststoffauskleider:innen", "Kunststoffauskleider"],
    ["Käser:innen", "Käser"],
    ["Köhler:innen", "Köhler"],
    ["Kübler:innen", "Kübler"],
    ["Lamellenschichter:innen", "Lamellenschichter"],
    ["Lascher:innen", "Lascher"],
    ["Leckageorter:innen", "Leckageorter"],
    ["Lederkleber:innen", "Lederkleber"],
    ["Lederübernehmer:innen", "Lederübernehmer"],
    ["Liegenschaftsvermesser:innen", "Liegenschaftsvermesser"],
    ["Lohnverzinner:innen", "Lohnverzinner"],
    ["Lotterieannehmer:innen", "Lotterieannehmer"],
    ["Lüftungsfeinblechner:innen", "Lüftungsfeinblechner"],
    ["Maischer:innen", "Maischer"],
    ["Malzdarrer:innen", "Malzdarrer"],
    ["Maschinenfalzer:innen", "Maschinenfalzer"],
    ["Maschinenrüster:innen", "Maschinenrüster"],
    ["Maschinenschmierer:innen", "Maschinenschmierer"],
    ["Maschinenspaner:innen", "Maschinenspaner"],
    ["Medienproduktioner:innen", "Medienproduktioner"],
    ["Meier:innen", "Meier"],
    ["Melker:innen", "Melker"],
    ["Merchandiser:innen", "Merchandiser"],
    ["Metallbeizer:innen", "Metallbeizer"],
    ["Metallbinder:innen", "Metallbinder"],
    ["Metallbrünierer:innen", "Metallbrünierer"],
    ["Metallisierer:innen", "Metallisierer"],
    ["Metalloberflächenvergüter:innen", "Metalloberflächenvergüter"],
    ["Metallplattierer:innen", "Metallplattierer"],
    ["Metallverbinder:innen", "Metallverbinder"],
    ["Metallvergüter:innen", "Metallvergüter"],
    ["Metallverzierer:innen", "Metallverzierer"],
    ["Milchprobenehmer:innen", "Milchprobenehmer"],
    ["Minensucher:innen", "Minensucher"],
    ["Multimedia-konzepter:innen", "Multimedia-konzepter"],
    ["Munitionsberger:innen", "Munitionsberger"],
    ["Munitionsräumer:innen", "Munitionsräumer"],
    ["Mälzer:innen", "Mälzer"],
    ["Müllbeseitiger:innen", "Müllbeseitiger"],
    ["Nc-maschineneinsteller:innen", "Nc-maschineneinsteller"],
    ["Nuancierer:innen", "Nuancierer"],
    ["Numismatiker:innen", "Numismatiker"],
    ["Nährmittelmaschinensteuerer:innen", "Nährmittelmaschinensteuerer"],
    ["Oberflächenbehandler:innen", "Oberflächenbehandler"],
    ["Obstkonservierer:innen", "Obstkonservierer"],
    ["Obstpflücker:innen", "Obstpflücker"],
    ["Organiker:innen", "Organiker"],
    ["Orgelstimmer:innen", "Orgelstimmer"],
    ["Oxydierer:innen", "Oxydierer"],
    ["Paginierer:innen", "Paginierer"],
    ["Paläobotaniker:innen", "Paläobotaniker"],
    ["Pappensatinierer:innen", "Pappensatinierer"],
    ["Parkettversiegler:innen", "Parkettversiegler"],
    ["Pasteurisierer:innen", "Pasteurisierer"],
    ["Patinierer:innen", "Patinierer"],
    ["Pelztierhalter:innen", "Pelztierhalter"],
    ["Pfandleiher:innen", "Pfandleiher"],
    ["Pflüger:innen", "Pflüger"],
    ["Philharmoniker:innen", "Philharmoniker"],
    ["Phonetiker:innen", "Phonetiker"],
    ["Piercer:innen", "Piercer"],
    ["Plakatierer:innen", "Plakatierer"],
    ["Plakatkleber:innen", "Plakatkleber"],
    ["Platzanweiser:innen", "Platzanweiser"],
    ["Plissierer:innen", "Plissierer"],
    ["Pneumatiker:innen", "Pneumatiker"],
    ["Polstergarnierer:innen", "Polstergarnierer"],
    ["Portefeuiller:innen", "Portefeuiller"],
    ["Posamentierer:innen", "Posamentierer"],
    ["Postverteiler:innen", "Postverteiler"],
    ["Presseneinsteller:innen", "Presseneinsteller"],
    ["Produktioner:innen", "Produktioner"],
    ["Promoter:innen", "Promoter"],
    ["Prospektverteiler:innen", "Prospektverteiler"],
    ["Prozessengineer:innen", "Prozessengineer"],
    ["Prüfstatiker:innen", "Prüfstatiker"],
    ["Purser:innen", "Purser"],
    ["Quizmaster:innen", "Quizmaster"],
    ["Raffinierer:innen", "Raffinierer"],
    ["Regalauffüller:innen", "Regalauffüller"],
    ["Reifenerneuer:innen", "Reifenerneuer"],
    ["Reinstimmer:innen", "Reinstimmer"],
    ["Religionsgeschichtler:innen", "Religionsgeschichtler"],
    ["Repassierer:innen", "Repassierer"],
    ["Rhythmiker:innen", "Rhythmiker"],
    ["Riemer:innen", "Riemer"],
    ["Rinderbesamer:innen", "Rinderbesamer"],
    ["Rinderhalter:innen", "Rinderhalter"],
    ["Rohrleitungsorter:innen", "Rohrleitungsorter"],
    ["Rohöldestillierer:innen", "Rohöldestillierer"],
    ["Rutengänger:innen", "Rutengänger"],
    ["Salespromoter:innen", "Salespromoter"],
    ["Samariter:innen", "Samariter"],
    ["Sanforisierer:innen", "Sanforisierer"],
    ["Satinierer:innen", "Satinierer"],
    ["Schablonierer:innen", "Schablonierer"],
    ["Schadensregulierer:innen", "Schadensregulierer"],
    ["Schafhalter:innen", "Schafhalter"],
    ["Schaltanlagenverdrahter:innen", "Schaltanlagenverdrahter"],
    ["Schiffsbesichtiger:innen", "Schiffsbesichtiger"],
    ["Schiffsentlader:innen", "Schiffsentlader"],
    ["Schiffsklarierer:innen", "Schiffsklarierer"],
    ["Schiffsreeder:innen", "Schiffsreeder"],
    ["Schlachter:innen", "Schlachter"],
    ["Schlotfeger:innen", "Schlotfeger"],
    ["Schuhbesohler:innen", "Schuhbesohler"],
    ["Schweinehalter:innen", "Schweinehalter"],
    ["Schädlingsbekämpfer:innen", "Schädlingsbekämpfer"],
    ["Schäffler:innen", "Schäffler"],
    ["Seilbahnbetriebsregler:innen", "Seilbahnbetriebsregler"],
    ["Selcher:innen", "Selcher"],
    ["Semantiker:innen", "Semantiker"],
    ["Senner:innen", "Senner"],
    ["Servierer:innen", "Servierer"],
    ["Softwarelokalisierer:innen", "Softwarelokalisierer"]
  ])("normalisiert den intern geprüften Personenstamm %s", (input, expected) => {
    expect(mappedPluralSeparatorsRule.apply(input)).toEqual({
      text: expected,
      replacements: 1
    });
  });

  it.each([
    ["Abfallbeseitiger", "Abfallbeseitigerin", "Abfallbeseitiger"],
    ["Alleinunterhalter", "Alleinunterhalterin", "Alleinunterhalter"],
    ["Ankleider", "Ankleiderin", "Ankleider"],
    ["Annehmer", "Annehmerin", "Annehmer"],
    ["Anorganiker", "Anorganikerin", "Anorganiker"],
    ["Anstreicher", "Anstreicherin", "Anstreicher"],
    ["Auftragsannehmer", "Auftragsannehmerin", "Auftragsannehmer"],
    ["Ausbeiner", "Ausbeinerin", "Ausbeiner"],
    ["Auskleider", "Auskleiderin", "Auskleider"],
    ["Auskunfterteiler", "Auskunfterteilerin", "Auskunfterteiler"],
    ["Auszahler", "Auszahlerin", "Auszahler"],
    ["Automatenauffüller", "Automatenauffüllerin", "Automatenauffüller"],
    ["Automatenaufsteller", "Automatenaufstellerin", "Automatenaufsteller"],
    ["Automatenbefüller", "Automatenbefüllerin", "Automatenbefüller"],
    ["Automateneinsteller", "Automateneinstellerin", "Automateneinsteller"],
    ["Baublechner", "Baublechnerin", "Baublechner"],
    ["Baumfäller", "Baumfällerin", "Baumfäller"],
    ["Bausparkassenvertragswerber", "Bausparkassenvertragswerberin", "Bausparkassenvertragswerber"],
    ["Beizer", "Beizerin", "Beizer"],
    ["Belader", "Beladerin", "Belader"],
    ["Bergvermesser", "Bergvermesserin", "Bergvermesser"],
    ["Beschrifter", "Beschrifterin", "Beschrifter"],
    ["Besohler", "Besohlerin", "Besohler"],
    ["Bienenhalter", "Bienenhalterin", "Bienenhalter"],
    ["Bierzapfer", "Bierzapferin", "Bierzapfer"],
    ["Bildeinrahmer", "Bildeinrahmerin", "Bildeinrahmer"],
    ["Biosthetiker", "Biosthetikerin", "Biosthetiker"],
    ["Blechner", "Blechnerin", "Blechner"],
    ["Bodenprobennehmer", "Bodenprobennehmerin", "Bodenprobennehmer"],
    ["Bratwurstbrater", "Bratwurstbraterin", "Bratwurstbrater"],
    ["Brechwerksteuerer", "Brechwerksteuererin", "Brechwerksteuerer"],
    ["Bremser", "Bremserin", "Bremser"],
    ["Broschürer", "Broschürerin", "Broschürer"],
    ["Bäumer", "Bäumerin", "Bäumer"],
    ["Cafe-servierer", "Cafe-serviererin", "Cafe-servierer"],
    ["Carbonisierer", "Carbonisiererin", "Carbonisierer"],
    ["Cnc-maschineneinsteller", "Cnc-maschineneinstellerin", "Cnc-maschineneinsteller"],
    ["Damaszierer", "Damasziererin", "Damaszierer"],
    ["Darrbeschicker", "Darrbeschickerin", "Darrbeschicker"],
    ["Darrer", "Darrerin", "Darrer"],
    ["Dekorentwerfer", "Dekorentwerferin", "Dekorentwerfer"],
    ["Depositenverwahrer", "Depositenverwahrerin", "Depositenverwahrer"],
    ["Diamantreiber", "Diamantreiberin", "Diamantreiber"],
    ["Drahtseilspleißer", "Drahtseilspleißerin", "Drahtseilspleißer"],
    ["Drahtstrecker", "Drahtstreckerin", "Drahtstrecker"],
    ["Drehmaschineneinsteller", "Drehmaschineneinstellerin", "Drehmaschineneinsteller"],
    ["Druckmaschineneinsteller", "Druckmaschineneinstellerin", "Druckmaschineneinsteller"],
    ["Egalisierer", "Egalisiererin", "Egalisierer"],
    ["Eicher", "Eicherin", "Eicher"],
    ["Einholer", "Einholerin", "Einholer"],
    ["Einschaler", "Einschalerin", "Einschaler"],
    ["Einsteller", "Einstellerin", "Einsteller"],
    ["Elektrolytisierer", "Elektrolytisiererin", "Elektrolytisierer"],
    ["Entbaster", "Entbasterin", "Entbaster"],
    ["Entgrater", "Entgraterin", "Entgrater"],
    ["Entlader", "Entladerin", "Entlader"],
    ["Entroster", "Entrosterin", "Entroster"],
    ["Entsorger", "Entsorgerin", "Entsorger"],
    ["Entsäurer", "Entsäurerin", "Entsäurer"],
    ["Entzunderer", "Entzundererin", "Entzunderer"],
    ["Erodierer", "Erodiererin", "Erodierer"],
    ["Fahrbetriebsregler", "Fahrbetriebsreglerin", "Fahrbetriebsregler"],
    ["Falkner", "Falknerin", "Falkner"],
    ["Fassadenverkleider", "Fassadenverkleiderin", "Fassadenverkleider"],
    ["Fehlersucher", "Fehlersucherin", "Fehlersucher"],
    ["Feinblechner", "Feinblechnerin", "Feinblechner"],
    ["Feinglänzer", "Feinglänzerin", "Feinglänzer"],
    ["Fernmeldeaufklärer", "Fernmeldeaufklärerin", "Fernmeldeaufklärer"],
    ["Fernmelder", "Fernmelderin", "Fernmelder"],
    ["Fertiggerichtekonservierer", "Fertiggerichtekonserviererin", "Fertiggerichtekonservierer"],
    ["Fertigsteller", "Fertigstellerin", "Fertigsteller"],
    ["Filmcutter", "Filmcutterin", "Filmcutter"],
    ["Finierer", "Finiererin", "Finierer"],
    ["Fischhalter", "Fischhalterin", "Fischhalter"],
    ["Fixierer", "Fixiererin", "Fixierer"],
    ["Flugdienstregler", "Flugdienstreglerin", "Flugdienstregler"],
    ["Flugunfalluntersucher", "Flugunfalluntersucherin", "Flugunfalluntersucher"],
    ["Flugzeughydrauliker", "Flugzeughydraulikerin", "Flugzeughydrauliker"],
    ["Flugzeugpneumatiker", "Flugzeugpneumatikerin", "Flugzeugpneumatiker"],
    ["Folienbeschrifter", "Folienbeschrifterin", "Folienbeschrifter"],
    ["Formenentwerfer", "Formenentwerferin", "Formenentwerfer"],
    ["Fundraiser", "Fundraiserin", "Fundraiser"],
    ["Funktionsdiagnostiker", "Funktionsdiagnostikerin", "Funktionsdiagnostiker"],
    ["Furnierschäler", "Furnierschälerin", "Furnierschäler"],
    ["Fördergurtinstandhalter", "Fördergurtinstandhalterin", "Fördergurtinstandhalter"],
    ["Galvanoverzinner", "Galvanoverzinnerin", "Galvanoverzinner"],
    ["Gebrauchsgraphiker", "Gebrauchsgraphikerin", "Gebrauchsgraphiker"],
    ["Geflügelfarmer", "Geflügelfarmerin", "Geflügelfarmer"],
    ["Geflügelhalter", "Geflügelhalterin", "Geflügelhalter"],
    ["Geflügelschlachter", "Geflügelschlachterin", "Geflügelschlachter"],
    ["Gefrierkonservierer", "Gefrierkonserviererin", "Gefrierkonservierer"],
    ["Geiger", "Geigerin", "Geiger"],
    ["Geldauszahler", "Geldauszahlerin", "Geldauszahler"],
    ["Geldeinnehmer", "Geldeinnehmerin", "Geldeinnehmer"],
    ["Geldwechsler", "Geldwechslerin", "Geldwechsler"],
    ["Geobotaniker", "Geobotanikerin", "Geobotaniker"],
    ["Getränkeautomatenauffüller", "Getränkeautomatenauffüllerin", "Getränkeautomatenauffüller"],
    ["Getränkeautomatenbefüller", "Getränkeautomatenbefüllerin", "Getränkeautomatenbefüller"],
    ["Gewehrschäfter", "Gewehrschäfterin", "Gewehrschäfter"],
    ["Gipser", "Gipserin", "Gipser"],
    ["Glasierer", "Glasiererin", "Glasierer"],
    ["Glühlampenregenerierer", "Glühlampenregeneriererin", "Glühlampenregenerierer"],
    ["Granulierer", "Granuliererin", "Granulierer"],
    ["Greenkeeper", "Greenkeeperin", "Greenkeeper"],
    ["Großwagner", "Großwagnerin", "Großwagner"],
    ["Hafner", "Hafnerin", "Hafner"],
    ["Handharmonikastimmer", "Handharmonikastimmerin", "Handharmonikastimmer"],
    ["Handklöppler", "Handklöpplerin", "Handklöppler"],
    ["Hartverchromer", "Hartverchromerin", "Hartverchromer"],
    ["Hausentrümpeler", "Hausentrümpelerin", "Hausentrümpeler"],
    ["Head-greenkeeper", "Head-greenkeeperin", "Head-greenkeeper"],
    ["Heiler", "Heilerin", "Heiler"],
    ["Hellseher", "Hellseherin", "Hellseher"],
    ["Heraldiker", "Heraldikerin", "Heraldiker"],
    ["Holzblasinstrumentenstimmer", "Holzblasinstrumentenstimmerin", "Holzblasinstrumentenstimmer"],
    ["Holzmechnaniker", "Holzmechnanikerin", "Holzmechnaniker"],
    ["Holzrücker", "Holzrückerin", "Holzrücker"],
    ["Huttrimmer", "Huttrimmerin", "Huttrimmer"],
    ["Hydrauliker", "Hydraulikerin", "Hydrauliker"],
    ["Industrieanstreicher", "Industrieanstreicherin", "Industrieanstreicher"],
    ["Jagdheger", "Jagdhegerin", "Jagdheger"],
    ["Jazzer", "Jazzerin", "Jazzer"],
    ["Jodler", "Jodlerin", "Jodler"],
    ["Kaminfeger", "Kaminfegerin", "Kaminfeger"],
    ["Kampfmittelbeseitiger", "Kampfmittelbeseitigerin", "Kampfmittelbeseitiger"],
    ["Karpfenhalter", "Karpfenhalterin", "Karpfenhalter"],
    ["Kaschierer", "Kaschiererin", "Kaschierer"],
    ["Kesselblechtreiber", "Kesselblechtreiberin", "Kesselblechtreiber"],
    ["Klöppler", "Klöpplerin", "Klöppler"],
    ["Knoter", "Knoterin", "Knoter"],
    ["Kodierer", "Kodiererin", "Kodierer"],
    ["Kontaktierer", "Kontaktiererin", "Kontaktierer"],
    ["Kontaktlinsenanpasser", "Kontaktlinsenanpasserin", "Kontaktlinsenanpasser"],
    ["Kunstdidaktiker", "Kunstdidaktikerin", "Kunstdidaktiker"],
    ["Kunstgeschichtler", "Kunstgeschichtlerin", "Kunstgeschichtler"],
    ["Kunststoffauskleider", "Kunststoffauskleiderin", "Kunststoffauskleider"],
    ["Käser", "Käserin", "Käser"],
    ["Köhler", "Köhlerin", "Köhler"],
    ["Kübler", "Küblerin", "Kübler"],
    ["Lamellenschichter", "Lamellenschichterin", "Lamellenschichter"],
    ["Lascher", "Lascherin", "Lascher"],
    ["Leckageorter", "Leckageorterin", "Leckageorter"],
    ["Lederkleber", "Lederkleberin", "Lederkleber"],
    ["Lederübernehmer", "Lederübernehmerin", "Lederübernehmer"],
    ["Liegenschaftsvermesser", "Liegenschaftsvermesserin", "Liegenschaftsvermesser"],
    ["Lohnverzinner", "Lohnverzinnerin", "Lohnverzinner"],
    ["Lotterieannehmer", "Lotterieannehmerin", "Lotterieannehmer"],
    ["Lüftungsfeinblechner", "Lüftungsfeinblechnerin", "Lüftungsfeinblechner"],
    ["Maischer", "Maischerin", "Maischer"],
    ["Malzdarrer", "Malzdarrerin", "Malzdarrer"],
    ["Maschinenfalzer", "Maschinenfalzerin", "Maschinenfalzer"],
    ["Maschinenrüster", "Maschinenrüsterin", "Maschinenrüster"],
    ["Maschinenschmierer", "Maschinenschmiererin", "Maschinenschmierer"],
    ["Maschinenspaner", "Maschinenspanerin", "Maschinenspaner"],
    ["Medienproduktioner", "Medienproduktionerin", "Medienproduktioner"],
    ["Meier", "Meierin", "Meier"],
    ["Melker", "Melkerin", "Melker"],
    ["Merchandiser", "Merchandiserin", "Merchandiser"],
    ["Metallbeizer", "Metallbeizerin", "Metallbeizer"],
    ["Metallbinder", "Metallbinderin", "Metallbinder"],
    ["Metallbrünierer", "Metallbrüniererin", "Metallbrünierer"],
    ["Metallisierer", "Metallisiererin", "Metallisierer"],
    ["Metalloberflächenvergüter", "Metalloberflächenvergüterin", "Metalloberflächenvergüter"],
    ["Metallplattierer", "Metallplattiererin", "Metallplattierer"],
    ["Metallverbinder", "Metallverbinderin", "Metallverbinder"],
    ["Metallvergüter", "Metallvergüterin", "Metallvergüter"],
    ["Metallverzierer", "Metallverziererin", "Metallverzierer"],
    ["Milchprobenehmer", "Milchprobenehmerin", "Milchprobenehmer"],
    ["Minensucher", "Minensucherin", "Minensucher"],
    ["Multimedia-konzepter", "Multimedia-konzepterin", "Multimedia-konzepter"],
    ["Munitionsberger", "Munitionsbergerin", "Munitionsberger"],
    ["Munitionsräumer", "Munitionsräumerin", "Munitionsräumer"],
    ["Mälzer", "Mälzerin", "Mälzer"],
    ["Müllbeseitiger", "Müllbeseitigerin", "Müllbeseitiger"],
    ["Nc-maschineneinsteller", "Nc-maschineneinstellerin", "Nc-maschineneinsteller"],
    ["Nuancierer", "Nuanciererin", "Nuancierer"],
    ["Numismatiker", "Numismatikerin", "Numismatiker"],
    ["Nährmittelmaschinensteuerer", "Nährmittelmaschinensteuererin", "Nährmittelmaschinensteuerer"],
    ["Oberflächenbehandler", "Oberflächenbehandlerin", "Oberflächenbehandler"],
    ["Obstkonservierer", "Obstkonserviererin", "Obstkonservierer"],
    ["Obstpflücker", "Obstpflückerin", "Obstpflücker"],
    ["Organiker", "Organikerin", "Organiker"],
    ["Orgelstimmer", "Orgelstimmerin", "Orgelstimmer"],
    ["Oxydierer", "Oxydiererin", "Oxydierer"],
    ["Paginierer", "Paginiererin", "Paginierer"],
    ["Paläobotaniker", "Paläobotanikerin", "Paläobotaniker"],
    ["Pappensatinierer", "Pappensatiniererin", "Pappensatinierer"],
    ["Parkettversiegler", "Parkettversieglerin", "Parkettversiegler"],
    ["Pasteurisierer", "Pasteurisiererin", "Pasteurisierer"],
    ["Patinierer", "Patiniererin", "Patinierer"],
    ["Pelztierhalter", "Pelztierhalterin", "Pelztierhalter"],
    ["Pfandleiher", "Pfandleiherin", "Pfandleiher"],
    ["Pflüger", "Pflügerin", "Pflüger"],
    ["Philharmoniker", "Philharmonikerin", "Philharmoniker"],
    ["Phonetiker", "Phonetikerin", "Phonetiker"],
    ["Piercer", "Piercerin", "Piercer"],
    ["Plakatierer", "Plakatiererin", "Plakatierer"],
    ["Plakatkleber", "Plakatkleberin", "Plakatkleber"],
    ["Platzanweiser", "Platzanweiserin", "Platzanweiser"],
    ["Plissierer", "Plissiererin", "Plissierer"],
    ["Pneumatiker", "Pneumatikerin", "Pneumatiker"],
    ["Polstergarnierer", "Polstergarniererin", "Polstergarnierer"],
    ["Portefeuiller", "Portefeuillerin", "Portefeuiller"],
    ["Posamentierer", "Posamentiererin", "Posamentierer"],
    ["Postverteiler", "Postverteilerin", "Postverteiler"],
    ["Presseneinsteller", "Presseneinstellerin", "Presseneinsteller"],
    ["Produktioner", "Produktionerin", "Produktioner"],
    ["Promoter", "Promoterin", "Promoter"],
    ["Prospektverteiler", "Prospektverteilerin", "Prospektverteiler"],
    ["Prozessengineer", "Prozessengineerin", "Prozessengineer"],
    ["Prüfstatiker", "Prüfstatikerin", "Prüfstatiker"],
    ["Purser", "Purserin", "Purser"],
    ["Quizmaster", "Quizmasterin", "Quizmaster"],
    ["Raffinierer", "Raffiniererin", "Raffinierer"],
    ["Regalauffüller", "Regalauffüllerin", "Regalauffüller"],
    ["Reifenerneuer", "Reifenerneuerin", "Reifenerneuer"],
    ["Reinstimmer", "Reinstimmerin", "Reinstimmer"],
    ["Religionsgeschichtler", "Religionsgeschichtlerin", "Religionsgeschichtler"],
    ["Repassierer", "Repassiererin", "Repassierer"],
    ["Rhythmiker", "Rhythmikerin", "Rhythmiker"],
    ["Riemer", "Riemerin", "Riemer"],
    ["Rinderbesamer", "Rinderbesamerin", "Rinderbesamer"],
    ["Rinderhalter", "Rinderhalterin", "Rinderhalter"],
    ["Rohrleitungsorter", "Rohrleitungsorterin", "Rohrleitungsorter"],
    ["Rohöldestillierer", "Rohöldestilliererin", "Rohöldestillierer"],
    ["Rutengänger", "Rutengängerin", "Rutengänger"],
    ["Salespromoter", "Salespromoterin", "Salespromoter"],
    ["Samariter", "Samariterin", "Samariter"],
    ["Sanforisierer", "Sanforisiererin", "Sanforisierer"],
    ["Satinierer", "Satiniererin", "Satinierer"],
    ["Schablonierer", "Schabloniererin", "Schablonierer"],
    ["Schadensregulierer", "Schadensreguliererin", "Schadensregulierer"],
    ["Schafhalter", "Schafhalterin", "Schafhalter"],
    ["Schaltanlagenverdrahter", "Schaltanlagenverdrahterin", "Schaltanlagenverdrahter"],
    ["Schiffsbesichtiger", "Schiffsbesichtigerin", "Schiffsbesichtiger"],
    ["Schiffsentlader", "Schiffsentladerin", "Schiffsentlader"],
    ["Schiffsklarierer", "Schiffsklariererin", "Schiffsklarierer"],
    ["Schiffsreeder", "Schiffsreederin", "Schiffsreeder"],
    ["Schlachter", "Schlachterin", "Schlachter"],
    ["Schlotfeger", "Schlotfegerin", "Schlotfeger"],
    ["Schuhbesohler", "Schuhbesohlerin", "Schuhbesohler"],
    ["Schweinehalter", "Schweinehalterin", "Schweinehalter"],
    ["Schädlingsbekämpfer", "Schädlingsbekämpferin", "Schädlingsbekämpfer"],
    ["Schäffler", "Schäfflerin", "Schäffler"],
    ["Seilbahnbetriebsregler", "Seilbahnbetriebsreglerin", "Seilbahnbetriebsregler"],
    ["Selcher", "Selcherin", "Selcher"],
    ["Semantiker", "Semantikerin", "Semantiker"],
    ["Senner", "Sennerin", "Senner"],
    ["Servierer", "Serviererin", "Servierer"],
    ["Softwarelokalisierer", "Softwarelokalisiererin", "Softwarelokalisierer"]
  ])("erkennt das intern geprüfte Paar %s/%s", (masculine, feminine, expected) => {
    expect(mapMappedSingularPair(masculine, feminine)).toBe(expected);
  });

  it.each([
    ["abfallbeseitiger", "genitive", "abfallbeseitigers"],
    ["flugunfalluntersucher", "genitive", "flugunfalluntersuchers"],
    ["schadensregulierer", "genitive", "schadensregulierers"],
    ["softwarelokalisierer", "genitive", "softwarelokalisierers"]
  ] as const)(
    "bildet die repräsentative Basis %s im Kasus %s korrekt ab",
    (base, grammaticalCase, expected) => {
      expect(mapMappedSingular(base, grammaticalCase)).toBe(expected);
    }
  );
});
