import { describe, expect, it } from "vitest";
import { mappedPluralSeparatorsRule } from "../src/rules/mapped-plural-separators";
import { mapMappedSingular, mapMappedSingularPair } from "../src/rules/person-lexicon";
import { getReviewedPersonFormsWave92, reviewedPersonFormCountWave92 } from "../src/rules/reviewed-person-forms-wave-92";

// Unabhängige Zieltabellen statt unkontrollierter Wortendungsableitung.
const erwartete = {
  unchanged: [
  "3d-computer-aided-design-entwickler",
  "3d-designer",
  "3d-produktentwickler",
  "abfüllanlagenbediener",
  "abfüllanlagenfahrer",
  "aktionskünstler",
  "altgriechischlehrer",
  "anlagenbediener",
  "anlagenführer",
  "anlagenmechaniker",
  "anlagentechniker",
  "apparatebauer",
  "aquakulturtechniker",
  "arbeitsplaner",
  "aufbereitungsmechaniker",
  "aufsteller",
  "aufzuchttechniker",
  "ausbildungsoffizier",
  "bankettmanager",
  "bankettplaner",
  "bauleiter",
  "baustoffhändler",
  "bauwerksmechaniker",
  "bediener",
  "begutachter",
  "bekleidungstechniker",
  "berufskraftfahrer",
  "bildbeschreiber",
  "binnenfischer",
  "cad-musterdesigner",
  "cad-techniker",
  "cad-zeichner",
  "cheftierpfleger",
  "chembalobauer",
  "chemietechniker",
  "chemikalienhändler",
  "deckshelfer",
  "dienstleistungsmanager",
  "drogenberater",
  "drucker",
  "drucktechniker",
  "einkaufsbegleiter",
  "einrichter",
  "einsatzleiter",
  "endbearbeiter",
  "entwicklungsleiter",
  "entwicklungsmanager",
  "erntearbeiter",
  "exportmanager",
  "exportsachbearbeiter",
  "fachberater",
  "facherzieher",
  "fachinformatiker",
  "fachkrankenpfleger",
  "fachleiter",
  "fahrzeugbaumechaniker",
  "fahrzeugführer",
  "familienpfleger",
  "feldvermesser",
  "fernsehsprecher",
  "fernsehtechniker",
  "fertigungskontrolltechniker",
  "fertigungsleiter",
  "filialkundenberater",
  "fischerntetechniker",
  "fitnessberater",
  "flaschenabfüllanlagenbediener",
  "fluggerätemechaniker",
  "frachtarbeiter",
  "frachtführer",
  "funkbediener",
  "gemüseabfüller",
  "gemüsehändler",
  "gemüseverarbeiter",
  "gemüseverkäufer",
  "generalunternehmer",
  "geschlechtsbestimmer",
  "glasveredler",
  "glaswarenhändler",
  "hair-designer",
  "haltungstechniker",
  "hardware-designer",
  "harmoniumbauer",
  "hartwarenverkäufer",
  "hauswirtschaftsleiter",
  "helpdesk-mitarbeiter",
  "hilfsarbeiter",
  "hilfstrainer",
  "holzmechaniker",
  "holztechniker",
  "hubschraubervermieter",
  "ikt-lehrer",
  "individualkundenberater",
  "industrieelektriker",
  "industriekeramiker",
  "industriemeister",
  "installationstechniker",
  "instandhaltungsmechaniker",
  "instandhaltungstechniker",
  "it-lehrer",
  "kapazitätsplaner",
  "kaschiermaschinenführer",
  "kfz-techniker",
  "kleintransporter-lieferfahrer",
  "klimamechaniker",
  "knowledge-manager",
  "kochwärter",
  "konstruktionsmechaniker",
  "konstruktionsmitarbeiter",
  "kostümschneider",
  "kraftfahrzeugmechatroniker",
  "kreislaufanlagentechniker",
  "kundendienstleiter",
  "kunsterzieher",
  "labortechniker",
  "lacktechniker",
  "lateinlehrer",
  "leitstandsfahrer",
  "lichtdesigner",
  "logistikleiter",
  "logistikmanager",
  "lüftungsanlagenbauer",
  "maschinenaufseher",
  "materialdesigner",
  "materialverwalter",
  "mathematiklehrer",
  "mediengestalter",
  "medienverkäufer",
  "metallarbeiter",
  "metalldesigner",
  "metalltechniker",
  "modellbaumechaniker",
  "modenäher",
  "montagearbeiter",
  "motorenmechaniker",
  "munitionshändler",
  "musterdesigner",
  "nachhaltigkeits-servicemanager",
  "netzkäfigtechniker",
  "ordner",
  "outdoor-trainer",
  "perforierer",
  "pflanzenhändler",
  "pharmawerker",
  "pinselmacher",
  "praxisanleiter",
  "presser",
  "produktentwickler",
  "produktionsarbeiter",
  "produktionsberater",
  "produktionsmanager",
  "produktionsmitarbeiter",
  "produktionsteamleiter",
  "produktprüfer",
  "programmgestalter",
  "protokollführer",
  "prozesssteuerungstechniker",
  "pyrotechnik-aufseher",
  "qualitätssicherungsmanager",
  "qualitätstechniker",
  "regionalplaner",
  "reparaturtechniker",
  "risikoanalytiker",
  "risikomanager",
  "risk-manager",
  "rollenmaschinenarbeiter",
  "rostschutztechniker",
  "saiteninstrumentenbauer",
  "sammlungsmanager",
  "sanitärtechniker",
  "sattler",
  "schaltungsdesigner",
  "schichtleiter",
  "schiffsführer",
  "schiffsoffizier",
  "schlächter",
  "schlüsselmacher",
  "schreibwarenverkäufer",
  "schuhtechniker",
  "serviceleiter",
  "servicetechniker",
  "sicherheitsmanager",
  "sicherheitstechniker",
  "spezialeffekt-künstler",
  "spezialeffekt-techniker",
  "steuerer",
  "stoffprüfer",
  "straßenarbeiter",
  "systemtechniker",
  "tabakwarenhändler",
  "telefonberater",
  "textilgestalter",
  "theorielehrer",
  "tierzuchttechniker",
  "tourbegleiter",
  "trader",
  "trickfilmzeichner",
  "uhrenverkäufer",
  "umweltmanagementbeauftragter",
  "umweltprojektleiter",
  "underwriter",
  "verankerungstechniker",
  "verfahrenstechniker",
  "vermögensberater",
  "video-techniker",
  "vollstreckungssachbearbeiter",
  "warenzusteller",
  "wartungsplaner",
  "wartungstechniker",
  "weiterbildner",
  "wirkstoffchemiker",
  "zahnarzthelfer",
  "zerspanungsfacharbeiter",
  "zoomitarbeiter",
  "zuchtmanager",
  "zuchttechniker",
  "zupfinstrumentenmacher",
  "zuschneider"
  ],
  pluralE: [
  "berufschauffeur",
  "cad-modelleur",
  "damenfriseur",
  "drainageingenieur",
  "elektroingenieur",
  "erdgasingenieur",
  "fachingenieur",
  "hardware-ingenieur",
  "inbetriebnahmeingenieur",
  "leasingfachwirt",
  "lüftungsanlageninstallateur",
  "maßekontrolleur",
  "motoreningenieur",
  "planungsingenieur",
  "polier",
  "projektingenieur",
  "qualitätssicherungsingenieur",
  "raumfahrtingenieur",
  "sicherheitsingenieur",
  "sicherheitskontrolleur",
  "softwareingenieur",
  "systemingenieur",
  "werkstoffingenieur",
  "zivilingenieur"
  ],
  pluralEn: [
  "animator",
  "compliance-koordinator",
  "containerkoordinator",
  "fachautor",
  "kälteinspektor",
  "klimaanlageninspektor",
  "logistikkoordinator",
  "planungsinspektor",
  "produktionskoordinator",
  "programm-koordinator",
  "sicherheitsinspektor",
  "transkriptor",
  "transportkoordinator",
  "verkehrskoordinator"
  ],
  weakEn: [
  "applikationsspezialist",
  "bewegungstherapeut",
  "evaluationsspezialist",
  "fachassistent",
  "fachlagerist",
  "fernsehproduzent",
  "finanzreferent",
  "gesichtschirurg",
  "hochschuldozent",
  "jugendlichenpsychotherapeut",
  "laborassistent",
  "laboratoriumsassistent",
  "lehrassistent",
  "praxisassistent",
  "radiologieassistent",
  "reporting-analyst",
  "sprachtherapeut",
  "teamassistent",
  "telefonist",
  "tv-produzent",
  "videolaborant",
  "wachmaschinist",
  "zuchtassistent"
  ]
} as const;
const cases = [
  ...erwartete.unchanged.map(basis => ({ basis, plural: basis, weak: false })),
  ...erwartete.pluralE.map(basis => ({ basis, plural: `${basis}e`, weak: false })),
  ...erwartete.pluralEn.map(basis => ({ basis, plural: `${basis}en`, weak: false })),
  ...erwartete.weakEn.map(basis => ({ basis, plural: `${basis}en`, weak: true }))
];

describe("Lexikonwelle 92: Exaktformen aus mehrteiligen Berufsbezeichnungen", () => {
  it("zählt 279 eindeutige, ausdrücklich freigegebene Personenbasen", () => {
    expect(cases).toHaveLength(279);
    expect(new Set(cases.map(({ basis }) => basis)).size).toBe(279);
    expect(reviewedPersonFormCountWave92).toBe(279);
  });

  it.each(cases)("$basis: Plural, Singular, Paar und vier Fälle stimmen", ({basis, plural, weak}) => {
    const feminine = `${basis}in`;
    const oblique = weak ? plural : basis;
    const genitive = weak ? plural : `${basis}s`;
    expect(getReviewedPersonFormsWave92(basis)).toEqual({
      plural, singular: basis, feminineSingular: feminine,
      obliqueSingular: oblique, genitiveSingular: genitive
    });
    expect(mappedPluralSeparatorsRule.apply(`${basis}:innen`)).toEqual({ text: plural, replacements: 1 });
    expect(mapMappedSingularPair(basis, feminine)).toBe(basis);
    expect(mapMappedSingularPair(feminine, basis)).toBe(basis);
    expect(mapMappedSingular(basis, "nominative")).toBe(basis);
    expect(mapMappedSingular(basis, "accusative")).toBe(oblique);
    expect(mapMappedSingular(basis, "dative")).toBe(oblique);
    expect(mapMappedSingular(basis, "genitive")).toBe(genitive);
  });

  it.each(["vormund", "maschienenbediener", "fertigungsingenieuringenieur", "general", "stallknecht", "ordnerfirma", "anlagenmechanikerteam"])(
    "leitet für %s keine neue Form ab", (basis) => {
      expect(getReviewedPersonFormsWave92(basis)).toBeUndefined();
    }
  );
  it("bewahrt normale nicht markierte Schreibweisen", () => {
    expect(mappedPluralSeparatorsRule.apply("Der Polier überprüft die Anlage.")).toEqual({
      text: "Der Polier überprüft die Anlage.", replacements: 0
    });
  });
});
