import { describe, expect, it } from "vitest";
import { mappedPluralSeparatorsRule } from "../src/rules/mapped-plural-separators";
import {
  mapMappedSingular,
  mapMappedSingularPair
} from "../src/rules/person-lexicon";
import {
  getReviewedPersonFormsWave63,
  reviewedPersonFormCountWave63
} from "../src/rules/reviewed-person-forms-wave-63";

describe("dreiundsechzigste Lexikon-Ausbauwelle", () => {
  it("enthält genau den intern geprüften Exaktbestand", () => {
    expect(reviewedPersonFormCountWave63).toBe(246);
    for (const base of [
      "computervisualist",
      "eri-wart",
      "eutonist",
      "fennist",
      "mindermaschinenstricker",
      "modellist",
      "tapisserist",
      "verschmelzer",
      "wäscher",
      "bildmischer",
      "bohrer",
      "blechpresser",
      "bandstanzer",
      "bandwalzer",
      "drahtwickler",
      "branntweinbrenner",
      "briefsortierer",
      "offsetplattenkopierer",
      "devisenrechner",
      "geldzähler",
      "aluminiumspritzer",
      "vorroller",
      "tiefzieher",
      "fantasieperson"
]) {
      expect(getReviewedPersonFormsWave63(base), base).toBeUndefined();
    }
  });

  it.each([
    ["Abgleicher:innen", "Abgleicher"],
    ["Absprenger:innen", "Absprenger"],
    ["Abspüler:innen", "Abspüler"],
    ["Abwieger:innen", "Abwieger"],
    ["Akupunkteur:innen", "Akupunkteure"],
    ["Akzidenzstereotypeur:innen", "Akzidenzstereotypeure"],
    ["Albenportefeuiller:innen", "Albenportefeuiller"],
    ["Aluminiumschläger:innen", "Aluminiumschläger"],
    ["Amtsbot:innen", "Amtsboten"],
    ["Annonceur:innen", "Annonceure"],
    ["Anreißer:innen", "Anreißer"],
    ["Anschläger:innen", "Anschläger"],
    ["Arbitrageur:innen", "Arbitrageure"],
    ["Artothekar:innen", "Artothekare"],
    ["Asphalteur:innen", "Asphalteure"],
    ["Atmungsorthopäd:innen", "Atmungsorthopäden"],
    ["Aufbäumer:innen", "Aufbäumer"],
    ["Aufdampfer:innen", "Aufdampfer"],
    ["Aufreiber:innen", "Aufreiber"],
    ["Aufreißer:innen", "Aufreißer"],
    ["Aufschläger:innen", "Aufschläger"],
    ["Aufspanner:innen", "Aufspanner"],
    ["Auswieger:innen", "Auswieger"],
    ["Bauisoleur:innen", "Bauisoleure"],
    ["Bauwerkserhalter:innen", "Bauwerkserhalter"],
    ["Berufskollegiat:innen", "Berufskollegiaten"],
    ["Besteckeinkitter:innen", "Besteckeinkitter"],
    ["Bestücker:innen", "Bestücker"],
    ["Bimser:innen", "Bimser"],
    ["Blockgesell:innen", "Blockgesellen"],
    ["Bolzenwärmer:innen", "Bolzenwärmer"],
    ["Bridierer:innen", "Bridierer"],
    ["Bürsteneinzieher:innen", "Bürsteneinzieher"],
    ["Büttgesell:innen", "Büttgesellen"],
    ["Cascadeur:innen", "Cascadeure"],
    ["Catwalker:innen", "Catwalker"],
    ["Cembalointoneur:innen", "Cembalointoneure"],
    ["Chirogymnast:innen", "Chirogymnasten"],
    ["Color-matcher:innen", "Color-matcher"],
    ["Degorgeur:innen", "Degorgeure"],
    ["Dekateur:innen", "Dekateure"],
    ["Destillateur:innen", "Destillateure"],
    ["Detacheur:innen", "Detacheure"],
    ["Distributor:innen", "Distributoren"],
    ["Drageur:innen", "Drageure"],
    ["Dresseur:innen", "Dresseure"],
    ["Druckstereotypeur:innen", "Druckstereotypeure"],
    ["Duplexätzer:innen", "Duplexätzer"],
    ["Elefantendompteur:innen", "Elefantendompteure"],
    ["Enthefer:innen", "Enthefer"],
    ["Entrahmer:innen", "Entrahmer"],
    ["Epithetiker:innen", "Epithetiker"],
    ["Erstgesell:innen", "Erstgesellen"],
    ["Exporteur:innen", "Exporteure"],
    ["Facher:innen", "Facher"],
    ["Figurenmodelleur:innen", "Figurenmodelleure"],
    ["Flämmer:innen", "Flämmer"],
    ["Fliesenmodelleur:innen", "Fliesenmodelleure"],
    ["Flößer:innen", "Flößer"],
    ["Flugnavigator:innen", "Flugnavigatoren"],
    ["Frimmler:innen", "Frimmler"],
    ["Frisurendemonstrator:innen", "Frisurendemonstratoren"],
    ["Fuger:innen", "Fuger"],
    ["Geodät:innen", "Geodäten"],
    ["Geometer:innen", "Geometer"],
    ["Gichter:innen", "Gichter"],
    ["Gipsmodelleur:innen", "Gipsmodelleure"],
    ["Glänzer:innen", "Glänzer"],
    ["Glanzstößer:innen", "Glanzstößer"],
    ["Glasätzer:innen", "Glasätzer"],
    ["Grilleur:innen", "Grilleure"],
    ["Gruppenkantor:innen", "Gruppenkantoren"],
    ["Guillocheur:innen", "Guillocheure"],
    ["Gummikleber:innen", "Gummikleber"],
    ["Hafenlots:innen", "Hafenlotsen"],
    ["Handschärer:innen", "Handschärer"],
    ["Harker:innen", "Harker"],
    ["Haspler:innen", "Haspler"],
    ["Heilgymnast:innen", "Heilgymnasten"],
    ["Holzkitter:innen", "Holzkitter"],
    ["Homogeniseur:innen", "Homogeniseure"],
    ["Homöopath:innen", "Homöopathen"],
    ["Hypnotiseur:innen", "Hypnotiseure"],
    ["Imitator:innen", "Imitatoren"],
    ["Informator:innen", "Informatoren"],
    ["Inspizient:innen", "Inspizienten"],
    ["Instanteur:innen", "Instanteure"],
    ["Intonateur:innen", "Intonateure"],
    ["Intoneur:innen", "Intoneure"],
    ["Jongleur:innen", "Jongleure"],
    ["Kanallots:innen", "Kanallotsen"],
    ["Kantor:innen", "Kantoren"],
    ["Kartenschläger:innen", "Kartenschläger"],
    ["Kascheur:innen", "Kascheure"],
    ["Keramikmodelleur:innen", "Keramikmodelleure"],
    ["Kerammodelleur:innen", "Kerammodelleure"],
    ["Kerzenzieher:innen", "Kerzenzieher"],
    ["Kieferorthopäd:innen", "Kieferorthopäden"],
    ["Kleiderhefter:innen", "Kleiderhefter"],
    ["Konduktor:innen", "Konduktoren"],
    ["Kontakter:innen", "Kontakter"],
    ["Krankengymnast:innen", "Krankengymnasten"],
    ["Krankentransporteur:innen", "Krankentransporteure"],
    ["Kunststoffstereotypeur:innen", "Kunststoffstereotypeure"],
    ["Laminierer:innen", "Laminierer"],
    ["Läpper:innen", "Läpper"],
    ["Lederwalker:innen", "Lederwalker"],
    ["Liquidator:innen", "Liquidatoren"],
    ["Lombardierer:innen", "Lombardierer"],
    ["Löwendompteur:innen", "Löwendompteure"],
    ["Lystrierer:innen", "Lystrierer"],
    ["Mechanisator:innen", "Mechanisatoren"],
    ["Merceriseur:innen", "Merceriseure"],
    ["Metteur:innen", "Metteure"],
    ["Mineur:innen", "Mineure"],
    ["Möbeltransporteur:innen", "Möbeltransporteure"],
    ["Modelleur:innen", "Modelleure"],
    ["Mouleur:innen", "Mouleure"],
    ["Musikclown:innen", "Musikclowns"],
    ["Nopper:innen", "Nopper"],
    ["Objektaquisiteur:innen", "Objektaquisiteure"],
    ["Ökonometriker:innen", "Ökonometriker"],
    ["Ölraffinierer:innen", "Ölraffinierer"],
    ["Orgelintonateur:innen", "Orgelintonateure"],
    ["Osteopath:innen", "Osteopathen"],
    ["Pädiater:innen", "Pädiater"],
    ["Partikulierer:innen", "Partikulierer"],
    ["Passierer:innen", "Passierer"],
    ["Patroneur:innen", "Patroneure"],
    ["Pferdedompteur:innen", "Pferdedompteure"],
    ["Postjungbot:innen", "Postjungboten"],
    ["Postulant:innen", "Postulanten"],
    ["Prospektor:innen", "Prospektoren"],
    ["Rahmer:innen", "Rahmer"],
    ["Raschler:innen", "Raschler"],
    ["Rasterätzer:innen", "Rasterätzer"],
    ["Rauher:innen", "Rauher"],
    ["Reeder:innen", "Reeder"],
    ["Reepschläger:innen", "Reepschläger"],
    ["Reifendienstvulkaniseur:innen", "Reifendienstvulkaniseure"],
    ["Revierlots:innen", "Revierlotsen"],
    ["Rotationsstereotypeur:innen", "Rotationsstereotypeure"],
    ["Sakristan:innen", "Sakristane"],
    ["Schärer:innen", "Schärer"],
    ["Scheibenmodelleur:innen", "Scheibenmodelleure"],
    ["Schiffslots:innen", "Schiffslotsen"],
    ["Schlauchvulkaniseur:innen", "Schlauchvulkaniseure"],
    ["Schuhmodelleur:innen", "Schuhmodelleure"],
    ["Schuhzwicker:innen", "Schuhzwicker"],
    ["Schwabbler:innen", "Schwabbler"],
    ["Seelots:innen", "Seelotsen"],
    ["Seilschläger:innen", "Seilschläger"],
    ["Senkererodierer:innen", "Senkererodierer"],
    ["Sohlenmodelleur:innen", "Sohlenmodelleure"],
    ["Solarteur:innen", "Solarteure"],
    ["Sondengänger:innen", "Sondengänger"],
    ["Sozialrechtler:innen", "Sozialrechtler"],
    ["Spitzenklöppler:innen", "Spitzenklöppler"],
    ["Spleißer:innen", "Spleißer"],
    ["Sprenger:innen", "Sprenger"],
    ["Statiker:innen", "Statiker"],
    ["Stereotypeur:innen", "Stereotypeure"],
    ["Streetworker:innen", "Streetworker"],
    ["Stückappreteur:innen", "Stückappreteure"],
    ["Stückpassierer:innen", "Stückpassierer"],
    ["Symphoniker:innen", "Symphoniker"],
    ["Tabakfermentierer:innen", "Tabakfermentierer"],
    ["Tabletteur:innen", "Tabletteure"],
    ["Tafeldecker:innen", "Tafeldecker"],
    ["Talkmaster:innen", "Talkmaster"],
    ["Taxator:innen", "Taxatoren"],
    ["Taxonom:innen", "Taxonomen"],
    ["Technologiekollegiat:innen", "Technologiekollegiaten"],
    ["Teerer:innen", "Teerer"],
    ["Tektoniker:innen", "Tektoniker"],
    ["Texturierer:innen", "Texturierer"],
    ["Theaterinspizient:innen", "Theaterinspizienten"],
    ["Thermiker:innen", "Thermiker"],
    ["Thermometerjustierer:innen", "Thermometerjustierer"],
    ["Tiefkühlkonservierer:innen", "Tiefkühlkonservierer"],
    ["Tierfänger:innen", "Tierfänger"],
    ["Tierhomöopath:innen", "Tierhomöopathen"],
    ["Totengräber:innen", "Totengräber"],
    ["Traiteur:innen", "Traiteure"],
    ["Trick-cutter:innen", "Trick-cutter"],
    ["Tuchappreteur:innen", "Tuchappreteure"],
    ["Tuchwalker:innen", "Tuchwalker"],
    ["Tüncher:innen", "Tüncher"],
    ["Tuscher:innen", "Tuscher"],
    ["Überholer:innen", "Überholer"],
    ["Umwelt-zertifizierer:innen", "Umwelt-zertifizierer"],
    ["Unternehmensethiker:innen", "Unternehmensethiker"],
    ["Untertitler:innen", "Untertitler"],
    ["Ux-researcher:innen", "Ux-researcher"],
    ["Verbleier:innen", "Verbleier"],
    ["Verchromer:innen", "Verchromer"],
    ["Verfuger:innen", "Verfuger"],
    ["Verkehrslots:innen", "Verkehrslotsen"],
    ["Verkehrsüberwacher:innen", "Verkehrsüberwacher"],
    ["Verlader:innen", "Verlader"],
    ["Verlagswerber:innen", "Verlagswerber"],
    ["Verleimer:innen", "Verleimer"],
    ["Versicherungswerber:innen", "Versicherungswerber"],
    ["Verstemmer:innen", "Verstemmer"],
    ["Vertäfler:innen", "Vertäfler"],
    ["Vertragswerber:innen", "Vertragswerber"],
    ["Verzinner:innen", "Verzinner"],
    ["Videothekar:innen", "Videothekare"],
    ["Viehhalter:innen", "Viehhalter"],
    ["Vikar:innen", "Vikare"],
    ["Vitametiker:innen", "Vitametiker"],
    ["Volksmissionar:innen", "Volksmissionare"],
    ["Vorbeter:innen", "Vorbeter"],
    ["Vulkaniseur:innen", "Vulkaniseure"],
    ["Wachsmodelleur:innen", "Wachsmodelleure"],
    ["Wagenuntersucher:innen", "Wagenuntersucher"],
    ["Wäger:innen", "Wäger"],
    ["Wagner:innen", "Wagner"],
    ["Wahrsager:innen", "Wahrsager"],
    ["Walzwerkthermiker:innen", "Walzwerkthermiker"],
    ["Warenannehmer:innen", "Warenannehmer"],
    ["Wärmedämmer:innen", "Wärmedämmer"],
    ["Weichkäser:innen", "Weichkäser"],
    ["Weinbehandler:innen", "Weinbehandler"],
    ["Weißriemer:innen", "Weißriemer"],
    ["Werkstereotypeur:innen", "Werkstereotypeure"],
    ["Werkzeugjustierer:innen", "Werkzeugjustierer"],
    ["Werkzeugmaschinenspaner:innen", "Werkzeugmaschinenspaner"],
    ["Wieger:innen", "Wieger"],
    ["Wildhüter:innen", "Wildhüter"],
    ["Wirtschaftsethiker:innen", "Wirtschaftsethiker"],
    ["Wirtschaftsgeschichtler:innen", "Wirtschaftsgeschichtler"],
    ["Wirtschaftsrechtler:innen", "Wirtschaftsrechtler"],
    ["Writer:innen", "Writer"],
    ["Wünschelrutengänger:innen", "Wünschelrutengänger"],
    ["Zeitgeschichtler:innen", "Zeitgeschichtler"],
    ["Zeitungsmetteur:innen", "Zeitungsmetteure"],
    ["Zerspaner:innen", "Zerspaner"],
    ["Zertifizierer:innen", "Zertifizierer"],
    ["Zettler:innen", "Zettler"],
    ["Ziegler:innen", "Ziegler"],
    ["Zirkusclown:innen", "Zirkusclowns"],
    ["Ziseleur:innen", "Ziseleure"],
    ["Zollfahnder:innen", "Zollfahnder"],
    ["Zuckerraffinierer:innen", "Zuckerraffinierer"],
    ["Zwirner:innen", "Zwirner"]
  ])("normalisiert den intern geprüften Personenstamm %s", (input, expected) => {
    expect(mappedPluralSeparatorsRule.apply(input)).toEqual({
      text: expected,
      replacements: 1
    });
  });

  it.each([
    ["Abgleicher", "Abgleicherin", "Abgleicher"],
    ["Absprenger", "Absprengerin", "Absprenger"],
    ["Abspüler", "Abspülerin", "Abspüler"],
    ["Abwieger", "Abwiegerin", "Abwieger"],
    ["Akupunkteur", "Akupunkteurin", "Akupunkteur"],
    ["Akzidenzstereotypeur", "Akzidenzstereotypeurin", "Akzidenzstereotypeur"],
    ["Albenportefeuiller", "Albenportefeuillerin", "Albenportefeuiller"],
    ["Aluminiumschläger", "Aluminiumschlägerin", "Aluminiumschläger"],
    ["Amtsbote", "Amtsbotin", "Amtsbote"],
    ["Annonceur", "Annonceurin", "Annonceur"],
    ["Anreißer", "Anreißerin", "Anreißer"],
    ["Anschläger", "Anschlägerin", "Anschläger"],
    ["Arbitrageur", "Arbitrageurin", "Arbitrageur"],
    ["Artothekar", "Artothekarin", "Artothekar"],
    ["Asphalteur", "Asphalteurin", "Asphalteur"],
    ["Atmungsorthopäde", "Atmungsorthopädin", "Atmungsorthopäde"],
    ["Aufbäumer", "Aufbäumerin", "Aufbäumer"],
    ["Aufdampfer", "Aufdampferin", "Aufdampfer"],
    ["Aufreiber", "Aufreiberin", "Aufreiber"],
    ["Aufreißer", "Aufreißerin", "Aufreißer"],
    ["Aufschläger", "Aufschlägerin", "Aufschläger"],
    ["Aufspanner", "Aufspannerin", "Aufspanner"],
    ["Auswieger", "Auswiegerin", "Auswieger"],
    ["Bauisoleur", "Bauisoleurin", "Bauisoleur"],
    ["Bauwerkserhalter", "Bauwerkserhalterin", "Bauwerkserhalter"],
    ["Berufskollegiat", "Berufskollegiatin", "Berufskollegiat"],
    ["Besteckeinkitter", "Besteckeinkitterin", "Besteckeinkitter"],
    ["Bestücker", "Bestückerin", "Bestücker"],
    ["Bimser", "Bimserin", "Bimser"],
    ["Blockgeselle", "Blockgesellin", "Blockgeselle"],
    ["Bolzenwärmer", "Bolzenwärmerin", "Bolzenwärmer"],
    ["Bridierer", "Bridiererin", "Bridierer"],
    ["Bürsteneinzieher", "Bürsteneinzieherin", "Bürsteneinzieher"],
    ["Büttgeselle", "Büttgesellin", "Büttgeselle"],
    ["Cascadeur", "Cascadeurin", "Cascadeur"],
    ["Catwalker", "Catwalkerin", "Catwalker"],
    ["Cembalointoneur", "Cembalointoneurin", "Cembalointoneur"],
    ["Chirogymnast", "Chirogymnastin", "Chirogymnast"],
    ["Color-matcher", "Color-matcherin", "Color-matcher"],
    ["Degorgeur", "Degorgeurin", "Degorgeur"],
    ["Dekateur", "Dekateurin", "Dekateur"],
    ["Destillateur", "Destillateurin", "Destillateur"],
    ["Detacheur", "Detacheurin", "Detacheur"],
    ["Distributor", "Distributorin", "Distributor"],
    ["Drageur", "Drageurin", "Drageur"],
    ["Dresseur", "Dresseurin", "Dresseur"],
    ["Druckstereotypeur", "Druckstereotypeurin", "Druckstereotypeur"],
    ["Duplexätzer", "Duplexätzerin", "Duplexätzer"],
    ["Elefantendompteur", "Elefantendompteurin", "Elefantendompteur"],
    ["Enthefer", "Entheferin", "Enthefer"],
    ["Entrahmer", "Entrahmerin", "Entrahmer"],
    ["Epithetiker", "Epithetikerin", "Epithetiker"],
    ["Erstgeselle", "Erstgesellin", "Erstgeselle"],
    ["Exporteur", "Exporteurin", "Exporteur"],
    ["Facher", "Facherin", "Facher"],
    ["Figurenmodelleur", "Figurenmodelleurin", "Figurenmodelleur"],
    ["Flämmer", "Flämmerin", "Flämmer"],
    ["Fliesenmodelleur", "Fliesenmodelleurin", "Fliesenmodelleur"],
    ["Flößer", "Flößerin", "Flößer"],
    ["Flugnavigator", "Flugnavigatorin", "Flugnavigator"],
    ["Frimmler", "Frimmlerin", "Frimmler"],
    ["Frisurendemonstrator", "Frisurendemonstratorin", "Frisurendemonstrator"],
    ["Fuger", "Fugerin", "Fuger"],
    ["Geodät", "Geodätin", "Geodät"],
    ["Geometer", "Geometerin", "Geometer"],
    ["Gichter", "Gichterin", "Gichter"],
    ["Gipsmodelleur", "Gipsmodelleurin", "Gipsmodelleur"],
    ["Glänzer", "Glänzerin", "Glänzer"],
    ["Glanzstößer", "Glanzstößerin", "Glanzstößer"],
    ["Glasätzer", "Glasätzerin", "Glasätzer"],
    ["Grilleur", "Grilleurin", "Grilleur"],
    ["Gruppenkantor", "Gruppenkantorin", "Gruppenkantor"],
    ["Guillocheur", "Guillocheurin", "Guillocheur"],
    ["Gummikleber", "Gummikleberin", "Gummikleber"],
    ["Hafenlotse", "Hafenlotsin", "Hafenlotse"],
    ["Handschärer", "Handschärerin", "Handschärer"],
    ["Harker", "Harkerin", "Harker"],
    ["Haspler", "Hasplerin", "Haspler"],
    ["Heilgymnast", "Heilgymnastin", "Heilgymnast"],
    ["Holzkitter", "Holzkitterin", "Holzkitter"],
    ["Homogeniseur", "Homogeniseurin", "Homogeniseur"],
    ["Homöopath", "Homöopathin", "Homöopath"],
    ["Hypnotiseur", "Hypnotiseurin", "Hypnotiseur"],
    ["Imitator", "Imitatorin", "Imitator"],
    ["Informator", "Informatorin", "Informator"],
    ["Inspizient", "Inspizientin", "Inspizient"],
    ["Instanteur", "Instanteurin", "Instanteur"],
    ["Intonateur", "Intonateurin", "Intonateur"],
    ["Intoneur", "Intoneurin", "Intoneur"],
    ["Jongleur", "Jongleurin", "Jongleur"],
    ["Kanallotse", "Kanallotsin", "Kanallotse"],
    ["Kantor", "Kantorin", "Kantor"],
    ["Kartenschläger", "Kartenschlägerin", "Kartenschläger"],
    ["Kascheur", "Kascheurin", "Kascheur"],
    ["Keramikmodelleur", "Keramikmodelleurin", "Keramikmodelleur"],
    ["Kerammodelleur", "Kerammodelleurin", "Kerammodelleur"],
    ["Kerzenzieher", "Kerzenzieherin", "Kerzenzieher"],
    ["Kieferorthopäde", "Kieferorthopädin", "Kieferorthopäde"],
    ["Kleiderhefter", "Kleiderhefterin", "Kleiderhefter"],
    ["Konduktor", "Konduktorin", "Konduktor"],
    ["Kontakter", "Kontakterin", "Kontakter"],
    ["Krankengymnast", "Krankengymnastin", "Krankengymnast"],
    ["Krankentransporteur", "Krankentransporteurin", "Krankentransporteur"],
    ["Kunststoffstereotypeur", "Kunststoffstereotypeurin", "Kunststoffstereotypeur"],
    ["Laminierer", "Laminiererin", "Laminierer"],
    ["Läpper", "Läpperin", "Läpper"],
    ["Lederwalker", "Lederwalkerin", "Lederwalker"],
    ["Liquidator", "Liquidatorin", "Liquidator"],
    ["Lombardierer", "Lombardiererin", "Lombardierer"],
    ["Löwendompteur", "Löwendompteurin", "Löwendompteur"],
    ["Lystrierer", "Lystriererin", "Lystrierer"],
    ["Mechanisator", "Mechanisatorin", "Mechanisator"],
    ["Merceriseur", "Merceriseurin", "Merceriseur"],
    ["Metteur", "Metteurin", "Metteur"],
    ["Mineur", "Mineurin", "Mineur"],
    ["Möbeltransporteur", "Möbeltransporteurin", "Möbeltransporteur"],
    ["Modelleur", "Modelleurin", "Modelleur"],
    ["Mouleur", "Mouleurin", "Mouleur"],
    ["Musikclown", "Musikclownin", "Musikclown"],
    ["Nopper", "Nopperin", "Nopper"],
    ["Objektaquisiteur", "Objektaquisiteurin", "Objektaquisiteur"],
    ["Ökonometriker", "Ökonometrikerin", "Ökonometriker"],
    ["Ölraffinierer", "Ölraffiniererin", "Ölraffinierer"],
    ["Orgelintonateur", "Orgelintonateurin", "Orgelintonateur"],
    ["Osteopath", "Osteopathin", "Osteopath"],
    ["Pädiater", "Pädiaterin", "Pädiater"],
    ["Partikulierer", "Partikuliererin", "Partikulierer"],
    ["Passierer", "Passiererin", "Passierer"],
    ["Patroneur", "Patroneurin", "Patroneur"],
    ["Pferdedompteur", "Pferdedompteurin", "Pferdedompteur"],
    ["Postjungbote", "Postjungbotin", "Postjungbote"],
    ["Postulant", "Postulantin", "Postulant"],
    ["Prospektor", "Prospektorin", "Prospektor"],
    ["Rahmer", "Rahmerin", "Rahmer"],
    ["Raschler", "Raschlerin", "Raschler"],
    ["Rasterätzer", "Rasterätzerin", "Rasterätzer"],
    ["Rauher", "Rauherin", "Rauher"],
    ["Reeder", "Reederin", "Reeder"],
    ["Reepschläger", "Reepschlägerin", "Reepschläger"],
    ["Reifendienstvulkaniseur", "Reifendienstvulkaniseurin", "Reifendienstvulkaniseur"],
    ["Revierlotse", "Revierlotsin", "Revierlotse"],
    ["Rotationsstereotypeur", "Rotationsstereotypeurin", "Rotationsstereotypeur"],
    ["Sakristan", "Sakristanin", "Sakristan"],
    ["Schärer", "Schärerin", "Schärer"],
    ["Scheibenmodelleur", "Scheibenmodelleurin", "Scheibenmodelleur"],
    ["Schiffslotse", "Schiffslotsin", "Schiffslotse"],
    ["Schlauchvulkaniseur", "Schlauchvulkaniseurin", "Schlauchvulkaniseur"],
    ["Schuhmodelleur", "Schuhmodelleurin", "Schuhmodelleur"],
    ["Schuhzwicker", "Schuhzwickerin", "Schuhzwicker"],
    ["Schwabbler", "Schwabblerin", "Schwabbler"],
    ["Seelotse", "Seelotsin", "Seelotse"],
    ["Seilschläger", "Seilschlägerin", "Seilschläger"],
    ["Senkererodierer", "Senkererodiererin", "Senkererodierer"],
    ["Sohlenmodelleur", "Sohlenmodelleurin", "Sohlenmodelleur"],
    ["Solarteur", "Solarteurin", "Solarteur"],
    ["Sondengänger", "Sondengängerin", "Sondengänger"],
    ["Sozialrechtler", "Sozialrechtlerin", "Sozialrechtler"],
    ["Spitzenklöppler", "Spitzenklöpplerin", "Spitzenklöppler"],
    ["Spleißer", "Spleißerin", "Spleißer"],
    ["Sprenger", "Sprengerin", "Sprenger"],
    ["Statiker", "Statikerin", "Statiker"],
    ["Stereotypeur", "Stereotypeurin", "Stereotypeur"],
    ["Streetworker", "Streetworkerin", "Streetworker"],
    ["Stückappreteur", "Stückappreteurin", "Stückappreteur"],
    ["Stückpassierer", "Stückpassiererin", "Stückpassierer"],
    ["Symphoniker", "Symphonikerin", "Symphoniker"],
    ["Tabakfermentierer", "Tabakfermentiererin", "Tabakfermentierer"],
    ["Tabletteur", "Tabletteurin", "Tabletteur"],
    ["Tafeldecker", "Tafeldeckerin", "Tafeldecker"],
    ["Talkmaster", "Talkmasterin", "Talkmaster"],
    ["Taxator", "Taxatorin", "Taxator"],
    ["Taxonom", "Taxonomin", "Taxonom"],
    ["Technologiekollegiat", "Technologiekollegiatin", "Technologiekollegiat"],
    ["Teerer", "Teererin", "Teerer"],
    ["Tektoniker", "Tektonikerin", "Tektoniker"],
    ["Texturierer", "Texturiererin", "Texturierer"],
    ["Theaterinspizient", "Theaterinspizientin", "Theaterinspizient"],
    ["Thermiker", "Thermikerin", "Thermiker"],
    ["Thermometerjustierer", "Thermometerjustiererin", "Thermometerjustierer"],
    ["Tiefkühlkonservierer", "Tiefkühlkonserviererin", "Tiefkühlkonservierer"],
    ["Tierfänger", "Tierfängerin", "Tierfänger"],
    ["Tierhomöopath", "Tierhomöopathin", "Tierhomöopath"],
    ["Totengräber", "Totengräberin", "Totengräber"],
    ["Traiteur", "Traiteurin", "Traiteur"],
    ["Trick-cutter", "Trick-cutterin", "Trick-cutter"],
    ["Tuchappreteur", "Tuchappreteurin", "Tuchappreteur"],
    ["Tuchwalker", "Tuchwalkerin", "Tuchwalker"],
    ["Tüncher", "Tüncherin", "Tüncher"],
    ["Tuscher", "Tuscherin", "Tuscher"],
    ["Überholer", "Überholerin", "Überholer"],
    ["Umwelt-zertifizierer", "Umwelt-zertifiziererin", "Umwelt-zertifizierer"],
    ["Unternehmensethiker", "Unternehmensethikerin", "Unternehmensethiker"],
    ["Untertitler", "Untertitlerin", "Untertitler"],
    ["Ux-researcher", "Ux-researcherin", "Ux-researcher"],
    ["Verbleier", "Verbleierin", "Verbleier"],
    ["Verchromer", "Verchromerin", "Verchromer"],
    ["Verfuger", "Verfugerin", "Verfuger"],
    ["Verkehrslotse", "Verkehrslotsin", "Verkehrslotse"],
    ["Verkehrsüberwacher", "Verkehrsüberwacherin", "Verkehrsüberwacher"],
    ["Verlader", "Verladerin", "Verlader"],
    ["Verlagswerber", "Verlagswerberin", "Verlagswerber"],
    ["Verleimer", "Verleimerin", "Verleimer"],
    ["Versicherungswerber", "Versicherungswerberin", "Versicherungswerber"],
    ["Verstemmer", "Verstemmerin", "Verstemmer"],
    ["Vertäfler", "Vertäflerin", "Vertäfler"],
    ["Vertragswerber", "Vertragswerberin", "Vertragswerber"],
    ["Verzinner", "Verzinnerin", "Verzinner"],
    ["Videothekar", "Videothekarin", "Videothekar"],
    ["Viehhalter", "Viehhalterin", "Viehhalter"],
    ["Vikar", "Vikarin", "Vikar"],
    ["Vitametiker", "Vitametikerin", "Vitametiker"],
    ["Volksmissionar", "Volksmissionarin", "Volksmissionar"],
    ["Vorbeter", "Vorbeterin", "Vorbeter"],
    ["Vulkaniseur", "Vulkaniseurin", "Vulkaniseur"],
    ["Wachsmodelleur", "Wachsmodelleurin", "Wachsmodelleur"],
    ["Wagenuntersucher", "Wagenuntersucherin", "Wagenuntersucher"],
    ["Wäger", "Wägerin", "Wäger"],
    ["Wagner", "Wagnerin", "Wagner"],
    ["Wahrsager", "Wahrsagerin", "Wahrsager"],
    ["Walzwerkthermiker", "Walzwerkthermikerin", "Walzwerkthermiker"],
    ["Warenannehmer", "Warenannehmerin", "Warenannehmer"],
    ["Wärmedämmer", "Wärmedämmerin", "Wärmedämmer"],
    ["Weichkäser", "Weichkäserin", "Weichkäser"],
    ["Weinbehandler", "Weinbehandlerin", "Weinbehandler"],
    ["Weißriemer", "Weißriemerin", "Weißriemer"],
    ["Werkstereotypeur", "Werkstereotypeurin", "Werkstereotypeur"],
    ["Werkzeugjustierer", "Werkzeugjustiererin", "Werkzeugjustierer"],
    ["Werkzeugmaschinenspaner", "Werkzeugmaschinenspanerin", "Werkzeugmaschinenspaner"],
    ["Wieger", "Wiegerin", "Wieger"],
    ["Wildhüter", "Wildhüterin", "Wildhüter"],
    ["Wirtschaftsethiker", "Wirtschaftsethikerin", "Wirtschaftsethiker"],
    ["Wirtschaftsgeschichtler", "Wirtschaftsgeschichtlerin", "Wirtschaftsgeschichtler"],
    ["Wirtschaftsrechtler", "Wirtschaftsrechtlerin", "Wirtschaftsrechtler"],
    ["Writer", "Writerin", "Writer"],
    ["Wünschelrutengänger", "Wünschelrutengängerin", "Wünschelrutengänger"],
    ["Zeitgeschichtler", "Zeitgeschichtlerin", "Zeitgeschichtler"],
    ["Zeitungsmetteur", "Zeitungsmetteurin", "Zeitungsmetteur"],
    ["Zerspaner", "Zerspanerin", "Zerspaner"],
    ["Zertifizierer", "Zertifiziererin", "Zertifizierer"],
    ["Zettler", "Zettlerin", "Zettler"],
    ["Ziegler", "Zieglerin", "Ziegler"],
    ["Zirkusclown", "Zirkusclownin", "Zirkusclown"],
    ["Ziseleur", "Ziseleurin", "Ziseleur"],
    ["Zollfahnder", "Zollfahnderin", "Zollfahnder"],
    ["Zuckerraffinierer", "Zuckerraffiniererin", "Zuckerraffinierer"],
    ["Zwirner", "Zwirnerin", "Zwirner"]
  ])("erkennt das intern geprüfte Paar %s/%s", (masculine, feminine, expected) => {
    expect(mapMappedSingularPair(masculine, feminine)).toBe(expected);
  });

  it.each([
    ["abgleicher", "genitive", "abgleichers"],
    ["akupunkteur", "genitive", "akupunkteurs"],
    ["amtsbot", "dative", "amtsboten"],
    ["berufskollegiat", "dative", "berufskollegiaten"],
    ["distributor", "genitive", "distributors"],
    ["musikclown", "genitive", "musikclowns"]
  ] as const)(
    "bildet die repräsentative Basis %s im Kasus %s korrekt ab",
    (base, grammaticalCase, expected) => {
      expect(mapMappedSingular(base, grammaticalCase)).toBe(expected);
    }
  );

  it.each([
    ["Color-Matcher:innen", "Color-Matcher"],
    ["Trick-Cutter:innen", "Trick-Cutter"],
    ["Umwelt-Zertifizierer:innen", "Umwelt-Zertifizierer"],
    ["UX-Researcher:innen", "UX-Researcher"]
  ])("erhält die Segmentgroßschreibung für %s", (input, expected) => {
    expect(mappedPluralSeparatorsRule.apply(input)).toEqual({
      text: expected,
      replacements: 1
    });
  });
});
