import { describe, expect, it } from "vitest";
import { mappedPluralSeparatorsRule } from "../src/rules/mapped-plural-separators";
import {
  mapMappedSingular,
  mapMappedSingularPair
} from "../src/rules/person-lexicon";
import {
  getReviewedPersonFormsWave59,
  reviewedPersonFormCountWave59
} from "../src/rules/reviewed-person-forms-wave-59";

describe("neunundfünfzigste Lexikon-Ausbauwelle", () => {
  it("enthält genau den intern geprüften Exaktbestand", () => {
    expect(reviewedPersonFormCountWave59).toBe(250);
    for (const base of [
      "mikrograf",
      "xerograf",
      "modelleur",
      "elefantendompteur",
      "choralmagister",
      "fantasiecontroller"
    ]) {
      expect(getReviewedPersonFormsWave59(base), base).toBeUndefined();
    }
  });

  it.each([
    ["Agrarwirtschafter:innen", "Agrarwirtschafter"],
    ["Agrarwirtschaftler:innen", "Agrarwirtschaftler"],
    ["Altertumskundler:innen", "Altertumskundler"],
    ["Altphilolog:innen", "Altphilologen"],
    ["Arzneimittelzusteller:innen", "Arzneimittelzusteller"],
    ["Audio-producer:innen", "Audio-producer"],
    ["Aufseher:innen", "Aufseher"],
    ["Auktionator:innen", "Auktionatoren"],
    ["Außenwirtschaftler:innen", "Außenwirtschaftler"],
    ["Avioniker:innen", "Avioniker"],
    ["Badeaufseher:innen", "Badeaufseher"],
    ["Bandaufseher:innen", "Bandaufseher"],
    ["Barmixer:innen", "Barmixer"],
    ["Bauaufseher:innen", "Bauaufseher"],
    ["Beauty-stylist:innen", "Beauty-stylisten"],
    ["Berufskundler:innen", "Berufskundler"],
    ["Bibliotheksaufseher:innen", "Bibliotheksaufseher"],
    ["Binnenschifffahrtskapitän:innen", "Binnenschifffahrtskapitäne"],
    ["Biokosmetiker:innen", "Biokosmetiker"],
    ["Biokybernetiker:innen", "Biokybernetiker"],
    ["Biometriker:innen", "Biometriker"],
    ["Bioniker:innen", "Bioniker"],
    ["Biostatistiker:innen", "Biostatistiker"],
    ["Bodenkundler:innen", "Bodenkundler"],
    ["Bohemist:innen", "Bohemisten"],
    ["Briefverteiler:innen", "Briefverteiler"],
    ["Briefzusteller:innen", "Briefzusteller"],
    ["Broker:innen", "Broker"],
    ["Byzantinist:innen", "Byzantinisten"],
    ["Börsenbroker:innen", "Börsenbroker"],
    ["Callcentercontroller:innen", "Callcentercontroller"],
    ["Campaigner:innen", "Campaigner"],
    ["Cartoonist:innen", "Cartoonisten"],
    ["Checkkapitän:innen", "Checkkapitäne"],
    ["Chefdramaturg:innen", "Chefdramaturgen"],
    ["Chronist:innen", "Chronisten"],
    ["Confiseur:innen", "Confiseure"],
    ["Controller:innen", "Controller"],
    ["Deklarant:innen", "Deklaranten"],
    ["Dekorierer:innen", "Dekorierer"],
    ["Demograf:innen", "Demografen"],
    ["Dentist:innen", "Dentisten"],
    ["Diakon:innen", "Diakone"],
    ["Diplom-kriminalist:innen", "Diplom-kriminalisten"],
    ["Diplom-logistiker:innen", "Diplom-logistiker"],
    ["Diplom-nautiker:innen", "Diplom-nautiker"],
    ["Diplom-oecotropholog:innen", "Diplom-oecotrophologen"],
    ["Diplom-statistiker:innen", "Diplom-statistiker"],
    ["Diplom-wirtschaftsjapanolog:innen", "Diplom-wirtschaftsjapanologen"],
    ["Diplom-wirtschaftssinolog:innen", "Diplom-wirtschaftssinologen"],
    ["Diplom-ökotropholog:innen", "Diplom-ökotrophologen"],
    ["Diplomafrikanist:innen", "Diplomafrikanisten"],
    ["Diplomarabist:innen", "Diplomarabisten"],
    ["Diplombaltist:innen", "Diplombaltisten"],
    ["Diplomfernsehwirtschaftler:innen", "Diplomfernsehwirtschaftler"],
    ["Diplomfilmwirtschaftler:innen", "Diplomfilmwirtschaftler"],
    ["Diplomindolog:innen", "Diplomindologen"],
    ["Diplomindonesist:innen", "Diplomindonesisten"],
    ["Diplomiranist:innen", "Diplomiranisten"],
    ["Diplomjapanolog:innen", "Diplomjapanologen"],
    ["Diplomkoreanist:innen", "Diplomkoreanisten"],
    ["Diplommongolist:innen", "Diplommongolisten"],
    ["Diplomneogräzist:innen", "Diplomneogräzisten"],
    ["Diplomsinolog:innen", "Diplomsinologen"],
    ["Diplomturkolog:innen", "Diplomturkologen"],
    ["Dv-controller:innen", "Dv-controller"],
    ["Dv-instruktor:innen", "Dv-instruktoren"],
    ["Ebv-operator:innen", "Ebv-operatoren"],
    ["Edv-controller:innen", "Edv-controller"],
    ["Edv-instruktor:innen", "Edv-instruktoren"],
    ["Edv-operator:innen", "Edv-operatoren"],
    ["Effektencontroller:innen", "Effektencontroller"],
    ["Eilzusteller:innen", "Eilzusteller"],
    ["Einkaufslogistiker:innen", "Einkaufslogistiker"],
    ["Energiewirtschaftler:innen", "Energiewirtschaftler"],
    ["Ethnograf:innen", "Ethnografen"],
    ["Fachhauswirtschafter:innen", "Fachhauswirtschafter"],
    ["Fachkosmetiker:innen", "Fachkosmetiker"],
    ["Farblithograf:innen", "Farblithografen"],
    ["Federlithograf:innen", "Federlithografen"],
    ["Feldaufseher:innen", "Feldaufseher"],
    ["Fernsehdramaturg:innen", "Fernsehdramaturgen"],
    ["Fiction-producer:innen", "Fiction-producer"],
    ["Filmdramaturg:innen", "Filmdramaturgen"],
    ["Filmsatz-operator:innen", "Filmsatz-operatoren"],
    ["Finanzcontroller:innen", "Finanzcontroller"],
    ["Fingernagelkosmetiker:innen", "Fingernagelkosmetiker"],
    ["Fischereiaufseher:innen", "Fischereiaufseher"],
    ["Floristikwirtschafter:innen", "Floristikwirtschafter"],
    ["Flugkapitän:innen", "Flugkapitäne"],
    ["Foodstylist:innen", "Foodstylisten"],
    ["Forensiker:innen", "Forensiker"],
    ["Forstwirtschafter:innen", "Forstwirtschafter"],
    ["Fotogalvanograf:innen", "Fotogalvanografen"],
    ["Fotolithograf:innen", "Fotolithografen"],
    ["Friedhofsaufseher:innen", "Friedhofsaufseher"],
    ["Friseur-kosmetiker:innen", "Friseur-kosmetiker"],
    ["Fuhrhofaufseher:innen", "Fuhrhofaufseher"],
    ["Fuhrparkaufseher:innen", "Fuhrparkaufseher"],
    ["Förderaufseher:innen", "Förderaufseher"],
    ["Galerieaufseher:innen", "Galerieaufseher"],
    ["Game-producer:innen", "Game-producer"],
    ["Garderobenaufseher:innen", "Garderobenaufseher"],
    ["Gardinendekorateur:innen", "Gardinendekorateure"],
    ["Gartenbauwirtschafter:innen", "Gartenbauwirtschafter"],
    ["Gemeindediakon:innen", "Gemeindediakone"],
    ["Geograf:innen", "Geografen"],
    ["Gesteinskundler:innen", "Gesteinskundler"],
    ["Gewerbeaufseher:innen", "Gewerbeaufseher"],
    ["Glasdekorierer:innen", "Glasdekorierer"],
    ["Gletscherkundler:innen", "Gletscherkundler"],
    ["Grubenaufseher:innen", "Grubenaufseher"],
    ["Hafenaufseher:innen", "Hafenaufseher"],
    ["Hafenkapitän:innen", "Hafenkapitäne"],
    ["Hairstylist:innen", "Hairstylisten"],
    ["Hauswirtschafter:innen", "Hauswirtschafter"],
    ["Humanphysiolog:innen", "Humanphysiologen"],
    ["Hörfunkdramaturg:innen", "Hörfunkdramaturgen"],
    ["Indonesist:innen", "Indonesisten"],
    ["Industriegeograf:innen", "Industriegeografen"],
    ["Infobroker:innen", "Infobroker"],
    ["Informations-broker:innen", "Informations-broker"],
    ["Innendekorateur:innen", "Innendekorateure"],
    ["Iranist:innen", "Iranisten"],
    ["Irankundler:innen", "Irankundler"],
    ["It-controller:innen", "It-controller"],
    ["It-forensiker:innen", "It-forensiker"],
    ["Junior-controller:innen", "Junior-controller"],
    ["Kamera-operator:innen", "Kamera-operatoren"],
    ["Kampfchoreograf:innen", "Kampfchoreografen"],
    ["Keramdekorateur:innen", "Keramdekorateure"],
    ["Keramdekorierer:innen", "Keramdekorierer"],
    ["Keramiklithograf:innen", "Keramiklithografen"],
    ["Keramikretuscheur:innen", "Keramikretuscheure"],
    ["Konfektionär:innen", "Konfektionäre"],
    ["Koreanist:innen", "Koreanisten"],
    ["Korrekturlithograf:innen", "Korrekturlithografen"],
    ["Kreidelithograf:innen", "Kreidelithografen"],
    ["Krematoriumsaufseher:innen", "Krematoriumsaufseher"],
    ["Kulturgeograf:innen", "Kulturgeografen"],
    ["Kunststoffkonfektionär:innen", "Kunststoffkonfektionäre"],
    ["Kybernetiker:innen", "Kybernetiker"],
    ["Ladeaufseher:innen", "Ladeaufseher"],
    ["Landbauwirtschafter:innen", "Landbauwirtschafter"],
    ["Landzusteller:innen", "Landzusteller"],
    ["Laserdruck-operator:innen", "Laserdruck-operatoren"],
    ["Leitungsaufseher:innen", "Leitungsaufseher"],
    ["Lichtdruckretuscheur:innen", "Lichtdruckretuscheure"],
    ["Lithograf:innen", "Lithografen"],
    ["Logistiker:innen", "Logistiker"],
    ["Lotsenkapitän:innen", "Lotsenkapitäne"],
    ["Make-up-stylist:innen", "Make-up-stylisten"],
    ["Marketing-controller:innen", "Marketing-controller"],
    ["Marktaufseher:innen", "Marktaufseher"],
    ["Marktwirtschaftler:innen", "Marktwirtschaftler"],
    ["Mediendramaturg:innen", "Mediendramaturgen"],
    ["Medienoperator:innen", "Medienoperatoren"],
    ["Medienwirtschafter:innen", "Medienwirtschafter"],
    ["Medizincontroller:innen", "Medizincontroller"],
    ["Meereskundler:innen", "Meereskundler"],
    ["Mikrofilmoperator:innen", "Mikrofilmoperatoren"],
    ["Mikrooperator:innen", "Mikrooperatoren"],
    ["Minilab-operator:innen", "Minilab-operatoren"],
    ["Molkereiinstruktor:innen", "Molkereiinstruktoren"],
    ["Molkereiwirtschafter:innen", "Molkereiwirtschafter"],
    ["Mongolist:innen", "Mongolisten"],
    ["Museumsaufseher:innen", "Museumsaufseher"],
    ["Museumskundler:innen", "Museumskundler"],
    ["Musikdramaturg:innen", "Musikdramaturgen"],
    ["Möbeldekorateur:innen", "Möbeldekorateure"],
    ["Nagel-kosmetiker:innen", "Nagel-kosmetiker"],
    ["Nagelstylist:innen", "Nagelstylisten"],
    ["Naturheilkundler:innen", "Naturheilkundler"],
    ["Nautiker:innen", "Nautiker"],
    ["Nc-operator:innen", "Nc-operatoren"],
    ["Neogräzist:innen", "Neogräzisten"],
    ["Neurophysiolog:innen", "Neurophysiologen"],
    ["Notenlithograf:innen", "Notenlithografen"],
    ["Offsetretuscheur:innen", "Offsetretuscheure"],
    ["Ozeanograf:innen", "Ozeanografen"],
    ["Parlamentsstenograf:innen", "Parlamentsstenografen"],
    ["Pferdewirtschafter:innen", "Pferdewirtschafter"],
    ["Pflanzenphysiolog:innen", "Pflanzenphysiologen"],
    ["Planenkonfektionär:innen", "Planenkonfektionäre"],
    ["Positivretuscheur:innen", "Positivretuscheure"],
    ["Postzusteller:innen", "Postzusteller"],
    ["Printoperator:innen", "Printoperatoren"],
    ["Producer:innen", "Producer"],
    ["Produktionsdramaturg:innen", "Produktionsdramaturgen"],
    ["Projektcontroller:innen", "Projektcontroller"],
    ["Reitinstruktor:innen", "Reitinstruktoren"],
    ["Reprolithograf:innen", "Reprolithografen"],
    ["Reproretuscheur:innen", "Reproretuscheure"],
    ["Retuscheur:innen", "Retuscheure"],
    ["Scanner-operator:innen", "Scanner-operatoren"],
    ["Schauspieldramaturg:innen", "Schauspieldramaturgen"],
    ["Schiffsbrückenaufseher:innen", "Schiffsbrückenaufseher"],
    ["Schiffskapitän:innen", "Schiffskapitäne"],
    ["Schlachthofaufseher:innen", "Schlachthofaufseher"],
    ["Schlossaufseher:innen", "Schlossaufseher"],
    ["Schriftlithograf:innen", "Schriftlithografen"],
    ["Schwergewebekonfektionär:innen", "Schwergewebekonfektionäre"],
    ["Seilbahnaufseher:innen", "Seilbahnaufseher"],
    ["Serigraf:innen", "Serigrafen"],
    ["Siedlungsgeograf:innen", "Siedlungsgeografen"],
    ["Sozialgeograf:innen", "Sozialgeografen"],
    ["Sozialstatistiker:innen", "Sozialstatistiker"],
    ["Spielhallenaufseher:innen", "Spielhallenaufseher"],
    ["Spielplatzaufseher:innen", "Spielplatzaufseher"],
    ["Sprengstoffaufseher:innen", "Sprengstoffaufseher"],
    ["Statistiker:innen", "Statistiker"],
    ["Stenograf:innen", "Stenografen"],
    ["Step-aerobic-instruktor:innen", "Step-aerobic-instruktoren"],
    ["Stylist:innen", "Stylisten"],
    ["Systemoperator:innen", "Systemoperatoren"],
    ["Szenograf:innen", "Szenografen"],
    ["Tanzdramaturg:innen", "Tanzdramaturgen"],
    ["Theaterdekorateur:innen", "Theaterdekorateure"],
    ["Theaterdramaturg:innen", "Theaterdramaturgen"],
    ["Tiefdruckretuscheur:innen", "Tiefdruckretuscheure"],
    ["Tierphysiolog:innen", "Tierphysiologen"],
    ["Trailer-producer:innen", "Trailer-producer"],
    ["Vegetationskundler:innen", "Vegetationskundler"],
    ["Verhandlungsstenograf:innen", "Verhandlungsstenografen"],
    ["Verkehrsgeograf:innen", "Verkehrsgeografen"],
    ["Verkehrswirtschaftler:innen", "Verkehrswirtschaftler"],
    ["Verladeaufseher:innen", "Verladeaufseher"],
    ["Vertriebscontroller:innen", "Vertriebscontroller"],
    ["Video-operator:innen", "Video-operatoren"],
    ["Volkskundler:innen", "Volkskundler"],
    ["Vorlagenretuscheur:innen", "Vorlagenretuscheure"],
    ["Völkerkundler:innen", "Völkerkundler"],
    ["Waldwirtschafter:innen", "Waldwirtschafter"],
    ["Wasserkundler:innen", "Wasserkundler"],
    ["Weinbauwirtschafter:innen", "Weinbauwirtschafter"],
    ["Werbewirtschaftler:innen", "Werbewirtschaftler"],
    ["Werkscontroller:innen", "Werkscontroller"],
    ["Wirtschafter:innen", "Wirtschafter"],
    ["Wirtschaftler:innen", "Wirtschaftler"],
    ["Wirtschaftsarabist:innen", "Wirtschaftsarabisten"],
    ["Wirtschaftsgeograf:innen", "Wirtschaftsgeografen"],
    ["Wirtschaftskundler:innen", "Wirtschaftskundler"],
    ["Wirtschaftslogistiker:innen", "Wirtschaftslogistiker"],
    ["Wirtschaftsstatistiker:innen", "Wirtschaftsstatistiker"],
    ["Zeichnungscontroller:innen", "Zeichnungscontroller"],
    ["Zeitungszusteller:innen", "Zeitungszusteller"],
    ["Zellphysiolog:innen", "Zellphysiologen"],
    ["Zeltkonfektionär:innen", "Zeltkonfektionäre"],
    ["Zinkretuscheur:innen", "Zinkretuscheure"],
    ["Zoophysiolog:innen", "Zoophysiologen"]
  ])("normalisiert den intern geprüften Personenstamm %s", (input, expected) => {
    expect(mappedPluralSeparatorsRule.apply(input)).toEqual({
      text: expected,
      replacements: 1
    });
  });

  it.each([
    ["Agrarwirtschafter", "Agrarwirtschafterin", "Agrarwirtschafter"],
    ["Agrarwirtschaftler", "Agrarwirtschaftlerin", "Agrarwirtschaftler"],
    ["Altertumskundler", "Altertumskundlerin", "Altertumskundler"],
    ["Altphilologe", "Altphilologin", "Altphilologe"],
    ["Arzneimittelzusteller", "Arzneimittelzustellerin", "Arzneimittelzusteller"],
    ["Audio-producer", "Audio-producerin", "Audio-producer"],
    ["Aufseher", "Aufseherin", "Aufseher"],
    ["Auktionator", "Auktionatorin", "Auktionator"],
    ["Außenwirtschaftler", "Außenwirtschaftlerin", "Außenwirtschaftler"],
    ["Avioniker", "Avionikerin", "Avioniker"],
    ["Badeaufseher", "Badeaufseherin", "Badeaufseher"],
    ["Bandaufseher", "Bandaufseherin", "Bandaufseher"],
    ["Barmixer", "Barmixerin", "Barmixer"],
    ["Bauaufseher", "Bauaufseherin", "Bauaufseher"],
    ["Beauty-stylist", "Beauty-stylistin", "Beauty-stylist"],
    ["Berufskundler", "Berufskundlerin", "Berufskundler"],
    ["Bibliotheksaufseher", "Bibliotheksaufseherin", "Bibliotheksaufseher"],
    ["Binnenschifffahrtskapitän", "Binnenschifffahrtskapitänin", "Binnenschifffahrtskapitän"],
    ["Biokosmetiker", "Biokosmetikerin", "Biokosmetiker"],
    ["Biokybernetiker", "Biokybernetikerin", "Biokybernetiker"],
    ["Biometriker", "Biometrikerin", "Biometriker"],
    ["Bioniker", "Bionikerin", "Bioniker"],
    ["Biostatistiker", "Biostatistikerin", "Biostatistiker"],
    ["Bodenkundler", "Bodenkundlerin", "Bodenkundler"],
    ["Bohemist", "Bohemistin", "Bohemist"],
    ["Briefverteiler", "Briefverteilerin", "Briefverteiler"],
    ["Briefzusteller", "Briefzustellerin", "Briefzusteller"],
    ["Broker", "Brokerin", "Broker"],
    ["Byzantinist", "Byzantinistin", "Byzantinist"],
    ["Börsenbroker", "Börsenbrokerin", "Börsenbroker"],
    ["Callcentercontroller", "Callcentercontrollerin", "Callcentercontroller"],
    ["Campaigner", "Campaignerin", "Campaigner"],
    ["Cartoonist", "Cartoonistin", "Cartoonist"],
    ["Checkkapitän", "Checkkapitänin", "Checkkapitän"],
    ["Chefdramaturg", "Chefdramaturgin", "Chefdramaturg"],
    ["Chronist", "Chronistin", "Chronist"],
    ["Confiseur", "Confiseurin", "Confiseur"],
    ["Controller", "Controllerin", "Controller"],
    ["Deklarant", "Deklarantin", "Deklarant"],
    ["Dekorierer", "Dekoriererin", "Dekorierer"],
    ["Demograf", "Demografin", "Demograf"],
    ["Dentist", "Dentistin", "Dentist"],
    ["Diakon", "Diakonin", "Diakon"],
    ["Diplom-kriminalist", "Diplom-kriminalistin", "Diplom-kriminalist"],
    ["Diplom-logistiker", "Diplom-logistikerin", "Diplom-logistiker"],
    ["Diplom-nautiker", "Diplom-nautikerin", "Diplom-nautiker"],
    ["Diplom-oecotrophologe", "Diplom-oecotrophologin", "Diplom-oecotrophologe"],
    ["Diplom-statistiker", "Diplom-statistikerin", "Diplom-statistiker"],
    ["Diplom-wirtschaftsjapanologe", "Diplom-wirtschaftsjapanologin", "Diplom-wirtschaftsjapanologe"],
    ["Diplom-wirtschaftssinologe", "Diplom-wirtschaftssinologin", "Diplom-wirtschaftssinologe"],
    ["Diplom-ökotrophologe", "Diplom-ökotrophologin", "Diplom-ökotrophologe"],
    ["Diplomafrikanist", "Diplomafrikanistin", "Diplomafrikanist"],
    ["Diplomarabist", "Diplomarabistin", "Diplomarabist"],
    ["Diplombaltist", "Diplombaltistin", "Diplombaltist"],
    ["Diplomfernsehwirtschaftler", "Diplomfernsehwirtschaftlerin", "Diplomfernsehwirtschaftler"],
    ["Diplomfilmwirtschaftler", "Diplomfilmwirtschaftlerin", "Diplomfilmwirtschaftler"],
    ["Diplomindologe", "Diplomindologin", "Diplomindologe"],
    ["Diplomindonesist", "Diplomindonesistin", "Diplomindonesist"],
    ["Diplomiranist", "Diplomiranistin", "Diplomiranist"],
    ["Diplomjapanologe", "Diplomjapanologin", "Diplomjapanologe"],
    ["Diplomkoreanist", "Diplomkoreanistin", "Diplomkoreanist"],
    ["Diplommongolist", "Diplommongolistin", "Diplommongolist"],
    ["Diplomneogräzist", "Diplomneogräzistin", "Diplomneogräzist"],
    ["Diplomsinologe", "Diplomsinologin", "Diplomsinologe"],
    ["Diplomturkologe", "Diplomturkologin", "Diplomturkologe"],
    ["Dv-controller", "Dv-controllerin", "Dv-controller"],
    ["Dv-instruktor", "Dv-instruktorin", "Dv-instruktor"],
    ["Ebv-operator", "Ebv-operatorin", "Ebv-operator"],
    ["Edv-controller", "Edv-controllerin", "Edv-controller"],
    ["Edv-instruktor", "Edv-instruktorin", "Edv-instruktor"],
    ["Edv-operator", "Edv-operatorin", "Edv-operator"],
    ["Effektencontroller", "Effektencontrollerin", "Effektencontroller"],
    ["Eilzusteller", "Eilzustellerin", "Eilzusteller"],
    ["Einkaufslogistiker", "Einkaufslogistikerin", "Einkaufslogistiker"],
    ["Energiewirtschaftler", "Energiewirtschaftlerin", "Energiewirtschaftler"],
    ["Ethnograf", "Ethnografin", "Ethnograf"],
    ["Fachhauswirtschafter", "Fachhauswirtschafterin", "Fachhauswirtschafter"],
    ["Fachkosmetiker", "Fachkosmetikerin", "Fachkosmetiker"],
    ["Farblithograf", "Farblithografin", "Farblithograf"],
    ["Federlithograf", "Federlithografin", "Federlithograf"],
    ["Feldaufseher", "Feldaufseherin", "Feldaufseher"],
    ["Fernsehdramaturg", "Fernsehdramaturgin", "Fernsehdramaturg"],
    ["Fiction-producer", "Fiction-producerin", "Fiction-producer"],
    ["Filmdramaturg", "Filmdramaturgin", "Filmdramaturg"],
    ["Filmsatz-operator", "Filmsatz-operatorin", "Filmsatz-operator"],
    ["Finanzcontroller", "Finanzcontrollerin", "Finanzcontroller"],
    ["Fingernagelkosmetiker", "Fingernagelkosmetikerin", "Fingernagelkosmetiker"],
    ["Fischereiaufseher", "Fischereiaufseherin", "Fischereiaufseher"],
    ["Floristikwirtschafter", "Floristikwirtschafterin", "Floristikwirtschafter"],
    ["Flugkapitän", "Flugkapitänin", "Flugkapitän"],
    ["Foodstylist", "Foodstylistin", "Foodstylist"],
    ["Forensiker", "Forensikerin", "Forensiker"],
    ["Forstwirtschafter", "Forstwirtschafterin", "Forstwirtschafter"],
    ["Fotogalvanograf", "Fotogalvanografin", "Fotogalvanograf"],
    ["Fotolithograf", "Fotolithografin", "Fotolithograf"],
    ["Friedhofsaufseher", "Friedhofsaufseherin", "Friedhofsaufseher"],
    ["Friseur-kosmetiker", "Friseur-kosmetikerin", "Friseur-kosmetiker"],
    ["Fuhrhofaufseher", "Fuhrhofaufseherin", "Fuhrhofaufseher"],
    ["Fuhrparkaufseher", "Fuhrparkaufseherin", "Fuhrparkaufseher"],
    ["Förderaufseher", "Förderaufseherin", "Förderaufseher"],
    ["Galerieaufseher", "Galerieaufseherin", "Galerieaufseher"],
    ["Game-producer", "Game-producerin", "Game-producer"],
    ["Garderobenaufseher", "Garderobenaufseherin", "Garderobenaufseher"],
    ["Gardinendekorateur", "Gardinendekorateurin", "Gardinendekorateur"],
    ["Gartenbauwirtschafter", "Gartenbauwirtschafterin", "Gartenbauwirtschafter"],
    ["Gemeindediakon", "Gemeindediakonin", "Gemeindediakon"],
    ["Geograf", "Geografin", "Geograf"],
    ["Gesteinskundler", "Gesteinskundlerin", "Gesteinskundler"],
    ["Gewerbeaufseher", "Gewerbeaufseherin", "Gewerbeaufseher"],
    ["Glasdekorierer", "Glasdekoriererin", "Glasdekorierer"],
    ["Gletscherkundler", "Gletscherkundlerin", "Gletscherkundler"],
    ["Grubenaufseher", "Grubenaufseherin", "Grubenaufseher"],
    ["Hafenaufseher", "Hafenaufseherin", "Hafenaufseher"],
    ["Hafenkapitän", "Hafenkapitänin", "Hafenkapitän"],
    ["Hairstylist", "Hairstylistin", "Hairstylist"],
    ["Hauswirtschafter", "Hauswirtschafterin", "Hauswirtschafter"],
    ["Humanphysiologe", "Humanphysiologin", "Humanphysiologe"],
    ["Hörfunkdramaturg", "Hörfunkdramaturgin", "Hörfunkdramaturg"],
    ["Indonesist", "Indonesistin", "Indonesist"],
    ["Industriegeograf", "Industriegeografin", "Industriegeograf"],
    ["Infobroker", "Infobrokerin", "Infobroker"],
    ["Informations-broker", "Informations-brokerin", "Informations-broker"],
    ["Innendekorateur", "Innendekorateurin", "Innendekorateur"],
    ["Iranist", "Iranistin", "Iranist"],
    ["Irankundler", "Irankundlerin", "Irankundler"],
    ["It-controller", "It-controllerin", "It-controller"],
    ["It-forensiker", "It-forensikerin", "It-forensiker"],
    ["Junior-controller", "Junior-controllerin", "Junior-controller"],
    ["Kamera-operator", "Kamera-operatorin", "Kamera-operator"],
    ["Kampfchoreograf", "Kampfchoreografin", "Kampfchoreograf"],
    ["Keramdekorateur", "Keramdekorateurin", "Keramdekorateur"],
    ["Keramdekorierer", "Keramdekoriererin", "Keramdekorierer"],
    ["Keramiklithograf", "Keramiklithografin", "Keramiklithograf"],
    ["Keramikretuscheur", "Keramikretuscheurin", "Keramikretuscheur"],
    ["Konfektionär", "Konfektionärin", "Konfektionär"],
    ["Koreanist", "Koreanistin", "Koreanist"],
    ["Korrekturlithograf", "Korrekturlithografin", "Korrekturlithograf"],
    ["Kreidelithograf", "Kreidelithografin", "Kreidelithograf"],
    ["Krematoriumsaufseher", "Krematoriumsaufseherin", "Krematoriumsaufseher"],
    ["Kulturgeograf", "Kulturgeografin", "Kulturgeograf"],
    ["Kunststoffkonfektionär", "Kunststoffkonfektionärin", "Kunststoffkonfektionär"],
    ["Kybernetiker", "Kybernetikerin", "Kybernetiker"],
    ["Ladeaufseher", "Ladeaufseherin", "Ladeaufseher"],
    ["Landbauwirtschafter", "Landbauwirtschafterin", "Landbauwirtschafter"],
    ["Landzusteller", "Landzustellerin", "Landzusteller"],
    ["Laserdruck-operator", "Laserdruck-operatorin", "Laserdruck-operator"],
    ["Leitungsaufseher", "Leitungsaufseherin", "Leitungsaufseher"],
    ["Lichtdruckretuscheur", "Lichtdruckretuscheurin", "Lichtdruckretuscheur"],
    ["Lithograf", "Lithografin", "Lithograf"],
    ["Logistiker", "Logistikerin", "Logistiker"],
    ["Lotsenkapitän", "Lotsenkapitänin", "Lotsenkapitän"],
    ["Make-up-stylist", "Make-up-stylistin", "Make-up-stylist"],
    ["Marketing-controller", "Marketing-controllerin", "Marketing-controller"],
    ["Marktaufseher", "Marktaufseherin", "Marktaufseher"],
    ["Marktwirtschaftler", "Marktwirtschaftlerin", "Marktwirtschaftler"],
    ["Mediendramaturg", "Mediendramaturgin", "Mediendramaturg"],
    ["Medienoperator", "Medienoperatorin", "Medienoperator"],
    ["Medienwirtschafter", "Medienwirtschafterin", "Medienwirtschafter"],
    ["Medizincontroller", "Medizincontrollerin", "Medizincontroller"],
    ["Meereskundler", "Meereskundlerin", "Meereskundler"],
    ["Mikrofilmoperator", "Mikrofilmoperatorin", "Mikrofilmoperator"],
    ["Mikrooperator", "Mikrooperatorin", "Mikrooperator"],
    ["Minilab-operator", "Minilab-operatorin", "Minilab-operator"],
    ["Molkereiinstruktor", "Molkereiinstruktorin", "Molkereiinstruktor"],
    ["Molkereiwirtschafter", "Molkereiwirtschafterin", "Molkereiwirtschafter"],
    ["Mongolist", "Mongolistin", "Mongolist"],
    ["Museumsaufseher", "Museumsaufseherin", "Museumsaufseher"],
    ["Museumskundler", "Museumskundlerin", "Museumskundler"],
    ["Musikdramaturg", "Musikdramaturgin", "Musikdramaturg"],
    ["Möbeldekorateur", "Möbeldekorateurin", "Möbeldekorateur"],
    ["Nagel-kosmetiker", "Nagel-kosmetikerin", "Nagel-kosmetiker"],
    ["Nagelstylist", "Nagelstylistin", "Nagelstylist"],
    ["Naturheilkundler", "Naturheilkundlerin", "Naturheilkundler"],
    ["Nautiker", "Nautikerin", "Nautiker"],
    ["Nc-operator", "Nc-operatorin", "Nc-operator"],
    ["Neogräzist", "Neogräzistin", "Neogräzist"],
    ["Neurophysiologe", "Neurophysiologin", "Neurophysiologe"],
    ["Notenlithograf", "Notenlithografin", "Notenlithograf"],
    ["Offsetretuscheur", "Offsetretuscheurin", "Offsetretuscheur"],
    ["Ozeanograf", "Ozeanografin", "Ozeanograf"],
    ["Parlamentsstenograf", "Parlamentsstenografin", "Parlamentsstenograf"],
    ["Pferdewirtschafter", "Pferdewirtschafterin", "Pferdewirtschafter"],
    ["Pflanzenphysiologe", "Pflanzenphysiologin", "Pflanzenphysiologe"],
    ["Planenkonfektionär", "Planenkonfektionärin", "Planenkonfektionär"],
    ["Positivretuscheur", "Positivretuscheurin", "Positivretuscheur"],
    ["Postzusteller", "Postzustellerin", "Postzusteller"],
    ["Printoperator", "Printoperatorin", "Printoperator"],
    ["Producer", "Producerin", "Producer"],
    ["Produktionsdramaturg", "Produktionsdramaturgin", "Produktionsdramaturg"],
    ["Projektcontroller", "Projektcontrollerin", "Projektcontroller"],
    ["Reitinstruktor", "Reitinstruktorin", "Reitinstruktor"],
    ["Reprolithograf", "Reprolithografin", "Reprolithograf"],
    ["Reproretuscheur", "Reproretuscheurin", "Reproretuscheur"],
    ["Retuscheur", "Retuscheurin", "Retuscheur"],
    ["Scanner-operator", "Scanner-operatorin", "Scanner-operator"],
    ["Schauspieldramaturg", "Schauspieldramaturgin", "Schauspieldramaturg"],
    ["Schiffsbrückenaufseher", "Schiffsbrückenaufseherin", "Schiffsbrückenaufseher"],
    ["Schiffskapitän", "Schiffskapitänin", "Schiffskapitän"],
    ["Schlachthofaufseher", "Schlachthofaufseherin", "Schlachthofaufseher"],
    ["Schlossaufseher", "Schlossaufseherin", "Schlossaufseher"],
    ["Schriftlithograf", "Schriftlithografin", "Schriftlithograf"],
    ["Schwergewebekonfektionär", "Schwergewebekonfektionärin", "Schwergewebekonfektionär"],
    ["Seilbahnaufseher", "Seilbahnaufseherin", "Seilbahnaufseher"],
    ["Serigraf", "Serigrafin", "Serigraf"],
    ["Siedlungsgeograf", "Siedlungsgeografin", "Siedlungsgeograf"],
    ["Sozialgeograf", "Sozialgeografin", "Sozialgeograf"],
    ["Sozialstatistiker", "Sozialstatistikerin", "Sozialstatistiker"],
    ["Spielhallenaufseher", "Spielhallenaufseherin", "Spielhallenaufseher"],
    ["Spielplatzaufseher", "Spielplatzaufseherin", "Spielplatzaufseher"],
    ["Sprengstoffaufseher", "Sprengstoffaufseherin", "Sprengstoffaufseher"],
    ["Statistiker", "Statistikerin", "Statistiker"],
    ["Stenograf", "Stenografin", "Stenograf"],
    ["Step-aerobic-instruktor", "Step-aerobic-instruktorin", "Step-aerobic-instruktor"],
    ["Stylist", "Stylistin", "Stylist"],
    ["Systemoperator", "Systemoperatorin", "Systemoperator"],
    ["Szenograf", "Szenografin", "Szenograf"],
    ["Tanzdramaturg", "Tanzdramaturgin", "Tanzdramaturg"],
    ["Theaterdekorateur", "Theaterdekorateurin", "Theaterdekorateur"],
    ["Theaterdramaturg", "Theaterdramaturgin", "Theaterdramaturg"],
    ["Tiefdruckretuscheur", "Tiefdruckretuscheurin", "Tiefdruckretuscheur"],
    ["Tierphysiologe", "Tierphysiologin", "Tierphysiologe"],
    ["Trailer-producer", "Trailer-producerin", "Trailer-producer"],
    ["Vegetationskundler", "Vegetationskundlerin", "Vegetationskundler"],
    ["Verhandlungsstenograf", "Verhandlungsstenografin", "Verhandlungsstenograf"],
    ["Verkehrsgeograf", "Verkehrsgeografin", "Verkehrsgeograf"],
    ["Verkehrswirtschaftler", "Verkehrswirtschaftlerin", "Verkehrswirtschaftler"],
    ["Verladeaufseher", "Verladeaufseherin", "Verladeaufseher"],
    ["Vertriebscontroller", "Vertriebscontrollerin", "Vertriebscontroller"],
    ["Video-operator", "Video-operatorin", "Video-operator"],
    ["Volkskundler", "Volkskundlerin", "Volkskundler"],
    ["Vorlagenretuscheur", "Vorlagenretuscheurin", "Vorlagenretuscheur"],
    ["Völkerkundler", "Völkerkundlerin", "Völkerkundler"],
    ["Waldwirtschafter", "Waldwirtschafterin", "Waldwirtschafter"],
    ["Wasserkundler", "Wasserkundlerin", "Wasserkundler"],
    ["Weinbauwirtschafter", "Weinbauwirtschafterin", "Weinbauwirtschafter"],
    ["Werbewirtschaftler", "Werbewirtschaftlerin", "Werbewirtschaftler"],
    ["Werkscontroller", "Werkscontrollerin", "Werkscontroller"],
    ["Wirtschafter", "Wirtschafterin", "Wirtschafter"],
    ["Wirtschaftler", "Wirtschaftlerin", "Wirtschaftler"],
    ["Wirtschaftsarabist", "Wirtschaftsarabistin", "Wirtschaftsarabist"],
    ["Wirtschaftsgeograf", "Wirtschaftsgeografin", "Wirtschaftsgeograf"],
    ["Wirtschaftskundler", "Wirtschaftskundlerin", "Wirtschaftskundler"],
    ["Wirtschaftslogistiker", "Wirtschaftslogistikerin", "Wirtschaftslogistiker"],
    ["Wirtschaftsstatistiker", "Wirtschaftsstatistikerin", "Wirtschaftsstatistiker"],
    ["Zeichnungscontroller", "Zeichnungscontrollerin", "Zeichnungscontroller"],
    ["Zeitungszusteller", "Zeitungszustellerin", "Zeitungszusteller"],
    ["Zellphysiologe", "Zellphysiologin", "Zellphysiologe"],
    ["Zeltkonfektionär", "Zeltkonfektionärin", "Zeltkonfektionär"],
    ["Zinkretuscheur", "Zinkretuscheurin", "Zinkretuscheur"],
    ["Zoophysiologe", "Zoophysiologin", "Zoophysiologe"]
  ])("erkennt das intern geprüfte Paar %s/%s", (masculine, feminine, expected) => {
    expect(mapMappedSingularPair(masculine, feminine)).toBe(expected);
  });

  it.each([
    ["agrarwirtschafter", "genitive", "agrarwirtschafters"],
    ["altphilolog", "dative", "altphilologen"],
    ["auktionator", "genitive", "auktionators"],
    ["beauty-stylist", "dative", "beauty-stylisten"],
    ["binnenschifffahrtskapitän", "genitive", "binnenschifffahrtskapitäns"]
  ] as const)(
    "bildet die repräsentative Basis %s im Kasus %s korrekt ab",
    (base, grammaticalCase, expected) => {
      expect(mapMappedSingular(base, grammaticalCase)).toBe(expected);
    }
  );

  it.each([
    ["Audio-Producer:innen", "Audio-Producer"],
    ["Beauty-Stylist:innen", "Beauty-Stylisten"],
    ["DV-Controller:innen", "DV-Controller"],
    ["EDV-Instruktor:innen", "EDV-Instruktoren"],
    ["IT-Forensiker:innen", "IT-Forensiker"]
  ])("erhält die Segmentgroßschreibung für %s", (input, expected) => {
    expect(mappedPluralSeparatorsRule.apply(input)).toEqual({
      text: expected,
      replacements: 1
    });
  });
});
