import { describe, expect, it } from "vitest";
import { mappedPluralSeparatorsRule } from "../src/rules/mapped-plural-separators";
import {
  mapMappedSingular,
  mapMappedSingularPair
} from "../src/rules/person-lexicon";
import {
  getReviewedPersonFormsWave82,
  reviewedPersonFormCountWave82
} from "../src/rules/reviewed-person-forms-wave-82";

const cases = [
  [
    "äquilibrist",
    "äquilibristen",
    "äquilibrist",
    "äquilibristin",
    "äquilibristen",
    "äquilibristen"
  ],
  [
    "ästhet",
    "ästheten",
    "ästhet",
    "ästhetin",
    "ästheten",
    "ästheten"
  ],
  [
    "närr",
    "narren",
    "narr",
    "närrin",
    "narren",
    "narren"
  ],
  [
    "nichtmuttersprachler",
    "nichtmuttersprachler",
    "nichtmuttersprachler",
    "nichtmuttersprachlerin",
    "nichtmuttersprachler",
    "nichtmuttersprachlers"
  ],
  [
    "niedersächs",
    "niedersachsen",
    "niedersachse",
    "niedersächsin",
    "niedersachsen",
    "niedersachsen"
  ],
  [
    "nihilist",
    "nihilisten",
    "nihilist",
    "nihilistin",
    "nihilisten",
    "nihilisten"
  ],
  [
    "nomad",
    "nomaden",
    "nomade",
    "nomadin",
    "nomaden",
    "nomaden"
  ],
  [
    "nominalist",
    "nominalisten",
    "nominalist",
    "nominalistin",
    "nominalisten",
    "nominalisten"
  ],
  [
    "nörgler",
    "nörgler",
    "nörgler",
    "nörglerin",
    "nörgler",
    "nörglers"
  ],
  [
    "nudist",
    "nudisten",
    "nudist",
    "nudistin",
    "nudisten",
    "nudisten"
  ],
  [
    "nürnberger",
    "nürnberger",
    "nürnberger",
    "nürnbergerin",
    "nürnberger",
    "nürnbergers"
  ],
  [
    "obduzent",
    "obduzenten",
    "obduzent",
    "obduzentin",
    "obduzenten",
    "obduzenten"
  ],
  [
    "oberbefehlshaber",
    "oberbefehlshaber",
    "oberbefehlshaber",
    "oberbefehlshaberin",
    "oberbefehlshaber",
    "oberbefehlshabers"
  ],
  [
    "oberprimaner",
    "oberprimaner",
    "oberprimaner",
    "oberprimanerin",
    "oberprimaner",
    "oberprimaners"
  ],
  [
    "obersekundaner",
    "obersekundaner",
    "obersekundaner",
    "obersekundanerin",
    "obersekundaner",
    "obersekundaners"
  ],
  [
    "okkupant",
    "okkupanten",
    "okkupant",
    "okkupantin",
    "okkupanten",
    "okkupanten"
  ],
  [
    "okkupator",
    "okkupatoren",
    "okkupator",
    "okkupatorin",
    "okkupator",
    "okkupators"
  ],
  [
    "oligarch",
    "oligarchen",
    "oligarch",
    "oligarchin",
    "oligarchen",
    "oligarchen"
  ],
  [
    "onkolog",
    "onkologen",
    "onkologe",
    "onkologin",
    "onkologen",
    "onkologen"
  ],
  [
    "onlinebroker",
    "onlinebroker",
    "onlinebroker",
    "onlinebrokerin",
    "onlinebroker",
    "onlinebrokers"
  ],
  [
    "opponent",
    "opponenten",
    "opponent",
    "opponentin",
    "opponenten",
    "opponenten"
  ],
  [
    "osloer",
    "osloer",
    "osloer",
    "osloerin",
    "osloer",
    "osloers"
  ],
  [
    "osman",
    "osmanen",
    "osmane",
    "osmanin",
    "osmanen",
    "osmanen"
  ],
  [
    "osteolog",
    "osteologen",
    "osteologe",
    "osteologin",
    "osteologen",
    "osteologen"
  ],
  [
    "ozeanaut",
    "ozeanauten",
    "ozeanaut",
    "ozeanautin",
    "ozeanauten",
    "ozeanauten"
  ],
  [
    "ozeanist",
    "ozeanisten",
    "ozeanist",
    "ozeanistin",
    "ozeanisten",
    "ozeanisten"
  ],
  [
    "ozeanolog",
    "ozeanologen",
    "ozeanologe",
    "ozeanologin",
    "ozeanologen",
    "ozeanologen"
  ],
  [
    "pandeist",
    "pandeisten",
    "pandeist",
    "pandeistin",
    "pandeisten",
    "pandeisten"
  ],
  [
    "pantheist",
    "pantheisten",
    "pantheist",
    "pantheistin",
    "pantheisten",
    "pantheisten"
  ],
  [
    "paraplegiker",
    "paraplegiker",
    "paraplegiker",
    "paraplegikerin",
    "paraplegiker",
    "paraplegikers"
  ],
  [
    "pariser",
    "pariser",
    "pariser",
    "pariserin",
    "pariser",
    "parisers"
  ],
  [
    "parömiolog",
    "parömiologen",
    "parömiologe",
    "parömiologin",
    "parömiologen",
    "parömiologen"
  ],
  [
    "pars",
    "parsen",
    "parse",
    "parsin",
    "parsen",
    "parsen"
  ],
  [
    "patrizier",
    "patrizier",
    "patrizier",
    "patrizierin",
    "patrizier",
    "patriziers"
  ],
  [
    "patrolog",
    "patrologen",
    "patrologe",
    "patrologin",
    "patrologen",
    "patrologen"
  ],
  [
    "patron",
    "patrone",
    "patron",
    "patronin",
    "patron",
    "patrons"
  ],
  [
    "paukist",
    "paukisten",
    "paukist",
    "paukistin",
    "paukisten",
    "paukisten"
  ],
  [
    "pegidist",
    "pegidisten",
    "pegidist",
    "pegidistin",
    "pegidisten",
    "pegidisten"
  ],
  [
    "perfektionist",
    "perfektionisten",
    "perfektionist",
    "perfektionistin",
    "perfektionisten",
    "perfektionisten"
  ],
  [
    "pfeifer",
    "pfeifer",
    "pfeifer",
    "pfeiferin",
    "pfeifer",
    "pfeifers"
  ],
  [
    "pflücker",
    "pflücker",
    "pflücker",
    "pflückerin",
    "pflücker",
    "pflückers"
  ],
  [
    "phäak",
    "phäaken",
    "phäake",
    "phäakin",
    "phäaken",
    "phäaken"
  ],
  [
    "phänomenolog",
    "phänomenologen",
    "phänomenologe",
    "phänomenologin",
    "phänomenologen",
    "phänomenologen"
  ],
  [
    "pharisäer",
    "pharisäer",
    "pharisäer",
    "pharisäerin",
    "pharisäer",
    "pharisäers"
  ],
  [
    "philhellen",
    "philhellenen",
    "philhellene",
    "philhellenin",
    "philhellenen",
    "philhellenen"
  ],
  [
    "philokartist",
    "philokartisten",
    "philokartist",
    "philokartistin",
    "philokartisten",
    "philokartisten"
  ],
  [
    "phlegmatiker",
    "phlegmatiker",
    "phlegmatiker",
    "phlegmatikerin",
    "phlegmatiker",
    "phlegmatikers"
  ],
  [
    "phobiker",
    "phobiker",
    "phobiker",
    "phobikerin",
    "phobiker",
    "phobikers"
  ],
  [
    "phonolog",
    "phonologen",
    "phonologe",
    "phonologin",
    "phonologen",
    "phonologen"
  ],
  [
    "physiognomiker",
    "physiognomiker",
    "physiognomiker",
    "physiognomikerin",
    "physiognomiker",
    "physiognomikers"
  ],
  [
    "plagiator",
    "plagiatoren",
    "plagiator",
    "plagiatorin",
    "plagiator",
    "plagiators"
  ],
  [
    "polygamist",
    "polygamisten",
    "polygamist",
    "polygamistin",
    "polygamisten",
    "polygamisten"
  ],
  [
    "porträtist",
    "porträtisten",
    "porträtist",
    "porträtistin",
    "porträtisten",
    "porträtisten"
  ],
  [
    "posaunist",
    "posaunisten",
    "posaunist",
    "posaunistin",
    "posaunisten",
    "posaunisten"
  ],
  [
    "potsdamer",
    "potsdamer",
    "potsdamer",
    "potsdamerin",
    "potsdamer",
    "potsdamers"
  ],
  [
    "prager",
    "prager",
    "prager",
    "pragerin",
    "prager",
    "pragers"
  ],
  [
    "preuß",
    "preußen",
    "preuße",
    "preußin",
    "preußen",
    "preußen"
  ],
  [
    "primatolog",
    "primatologen",
    "primatologe",
    "primatologin",
    "primatologen",
    "primatologen"
  ],
  [
    "profiteur",
    "profiteure",
    "profiteur",
    "profiteurin",
    "profiteur",
    "profiteurs"
  ],
  [
    "proktolog",
    "proktologen",
    "proktologe",
    "proktologin",
    "proktologen",
    "proktologen"
  ],
  [
    "promovend",
    "promovenden",
    "promovend",
    "promovendin",
    "promovenden",
    "promovenden"
  ],
  [
    "propagandist",
    "propagandisten",
    "propagandist",
    "propagandistin",
    "propagandisten",
    "propagandisten"
  ],
  [
    "prosument",
    "prosumenten",
    "prosument",
    "prosumentin",
    "prosumenten",
    "prosumenten"
  ],
  [
    "protestierer",
    "protestierer",
    "protestierer",
    "protestiererin",
    "protestierer",
    "protestierers"
  ],
  [
    "protestler",
    "protestler",
    "protestler",
    "protestlerin",
    "protestler",
    "protestlers"
  ],
  [
    "protokollant",
    "protokollanten",
    "protokollant",
    "protokollantin",
    "protokollanten",
    "protokollanten"
  ],
  [
    "provokateur",
    "provokateure",
    "provokateur",
    "provokateurin",
    "provokateur",
    "provokateurs"
  ],
  [
    "psychopath",
    "psychopathen",
    "psychopath",
    "psychopathin",
    "psychopathen",
    "psychopathen"
  ],
  [
    "psychotiker",
    "psychotiker",
    "psychotiker",
    "psychotikerin",
    "psychotiker",
    "psychotikers"
  ],
  [
    "pulmolog",
    "pulmologen",
    "pulmologe",
    "pulmologin",
    "pulmologen",
    "pulmologen"
  ],
  [
    "punker",
    "punker",
    "punker",
    "punkerin",
    "punker",
    "punkers"
  ],
  [
    "purist",
    "puristen",
    "purist",
    "puristin",
    "puristen",
    "puristen"
  ],
  [
    "puritaner",
    "puritaner",
    "puritaner",
    "puritanerin",
    "puritaner",
    "puritaners"
  ],
  [
    "putschist",
    "putschisten",
    "putschist",
    "putschistin",
    "putschisten",
    "putschisten"
  ],
  [
    "pygmä",
    "pygmäen",
    "pygmäe",
    "pygmäin",
    "pygmäen",
    "pygmäen"
  ],
  [
    "pyroman",
    "pyromanen",
    "pyromane",
    "pyromanin",
    "pyromanen",
    "pyromanen"
  ],
  [
    "quäker",
    "quäker",
    "quäker",
    "quäkerin",
    "quäker",
    "quäkers"
  ],
  [
    "quästor",
    "quästoren",
    "quästor",
    "quästorin",
    "quästor",
    "quästors"
  ],
  [
    "rabulist",
    "rabulisten",
    "rabulist",
    "rabulistin",
    "rabulisten",
    "rabulisten"
  ],
  [
    "rächer",
    "rächer",
    "rächer",
    "rächerin",
    "rächer",
    "rächers"
  ],
  [
    "randalierer",
    "randalierer",
    "randalierer",
    "randaliererin",
    "randalierer",
    "randalierers"
  ],
  [
    "rater",
    "rater",
    "rater",
    "raterin",
    "rater",
    "raters"
  ],
  [
    "realist",
    "realisten",
    "realist",
    "realistin",
    "realisten",
    "realisten"
  ],
  [
    "rechercheur",
    "rechercheure",
    "rechercheur",
    "rechercheurin",
    "rechercheur",
    "rechercheurs"
  ],
  [
    "reformator",
    "reformatoren",
    "reformator",
    "reformatorin",
    "reformator",
    "reformators"
  ],
  [
    "regent",
    "regenten",
    "regent",
    "regentin",
    "regenten",
    "regenten"
  ],
  [
    "republikaner",
    "republikaner",
    "republikaner",
    "republikanerin",
    "republikaner",
    "republikaners"
  ],
  [
    "resident",
    "residenten",
    "resident",
    "residentin",
    "residenten",
    "residenten"
  ],
  [
    "restaurateur",
    "restaurateure",
    "restaurateur",
    "restaurateurin",
    "restaurateur",
    "restaurateurs"
  ],
  [
    "rezitator",
    "rezitatoren",
    "rezitator",
    "rezitatorin",
    "rezitator",
    "rezitators"
  ],
  [
    "rheinland-pfälzer",
    "rheinland-pfälzer",
    "rheinland-pfälzer",
    "rheinland-pfälzerin",
    "rheinland-pfälzer",
    "rheinland-pfälzers"
  ],
  [
    "rheinländer",
    "rheinländer",
    "rheinländer",
    "rheinländerin",
    "rheinländer",
    "rheinländers"
  ],
  [
    "rheumatolog",
    "rheumatologen",
    "rheumatologe",
    "rheumatologin",
    "rheumatologen",
    "rheumatologen"
  ],
  [
    "rocker",
    "rocker",
    "rocker",
    "rockerin",
    "rocker",
    "rockers"
  ],
  [
    "rodler",
    "rodler",
    "rodler",
    "rodlerin",
    "rodler",
    "rodlers"
  ],
  [
    "rostocker",
    "rostocker",
    "rostocker",
    "rostockerin",
    "rostocker",
    "rostockers"
  ],
  [
    "rotarier",
    "rotarier",
    "rotarier",
    "rotarierin",
    "rotarier",
    "rotariers"
  ],
  [
    "rottweiler",
    "rottweiler",
    "rottweiler",
    "rottweilerin",
    "rottweiler",
    "rottweilers"
  ],
  [
    "roubaiser",
    "roubaiser",
    "roubaiser",
    "roubaiserin",
    "roubaiser",
    "roubaisers"
  ],
  [
    "royalist",
    "royalisten",
    "royalist",
    "royalistin",
    "royalisten",
    "royalisten"
  ],
  [
    "rückwander",
    "rückwanderer",
    "rückwanderer",
    "rückwanderin",
    "rückwanderer",
    "rückwanderers"
  ],
  [
    "ruder",
    "ruderer",
    "ruderer",
    "ruderin",
    "ruderer",
    "ruderers"
  ],
  [
    "rügener",
    "rügener",
    "rügener",
    "rügenerin",
    "rügener",
    "rügeners"
  ],
  [
    "ruheständler",
    "ruheständler",
    "ruheständler",
    "ruheständlerin",
    "ruheständler",
    "ruheständlers"
  ],
  [
    "runolog",
    "runologen",
    "runologe",
    "runologin",
    "runologen",
    "runologen"
  ],
  [
    "saarländer",
    "saarländer",
    "saarländer",
    "saarländerin",
    "saarländer",
    "saarländers"
  ],
  [
    "saarlouiser",
    "saarlouiser",
    "saarlouiser",
    "saarlouiserin",
    "saarlouiser",
    "saarlouisers"
  ],
  [
    "säbelfechter",
    "säbelfechter",
    "säbelfechter",
    "säbelfechterin",
    "säbelfechter",
    "säbelfechters"
  ],
  [
    "sächs",
    "sachsen",
    "sachse",
    "sächsin",
    "sachsen",
    "sachsen"
  ],
  [
    "sachsen-anhalter",
    "sachsen-anhalter",
    "sachsen-anhalter",
    "sachsen-anhalterin",
    "sachsen-anhalter",
    "sachsen-anhalters"
  ],
  [
    "sachsen-anhaltiner",
    "sachsen-anhaltiner",
    "sachsen-anhaltiner",
    "sachsen-anhaltinerin",
    "sachsen-anhaltiner",
    "sachsen-anhaltiners"
  ],
  [
    "salzburger",
    "salzburger",
    "salzburger",
    "salzburgerin",
    "salzburger",
    "salzburgers"
  ],
  [
    "salzwedeler",
    "salzwedeler",
    "salzwedeler",
    "salzwedelerin",
    "salzwedeler",
    "salzwedelers"
  ],
  [
    "sanguiniker",
    "sanguiniker",
    "sanguiniker",
    "sanguinikerin",
    "sanguiniker",
    "sanguinikers"
  ],
  [
    "sard",
    "sarden",
    "sarde",
    "sardin",
    "sarden",
    "sarden"
  ],
  [
    "satanist",
    "satanisten",
    "satanist",
    "satanistin",
    "satanisten",
    "satanisten"
  ],
  [
    "schaman",
    "schamanen",
    "schamane",
    "schamanin",
    "schamanen",
    "schamanen"
  ],
  [
    "schenker",
    "schenker",
    "schenker",
    "schenkerin",
    "schenker",
    "schenkers"
  ],
  [
    "scherg",
    "schergen",
    "scherge",
    "schergin",
    "schergen",
    "schergen"
  ],
  [
    "schiffer",
    "schiffer",
    "schiffer",
    "schifferin",
    "schiffer",
    "schiffers"
  ],
  [
    "schiit",
    "schiiten",
    "schiit",
    "schiitin",
    "schiiten",
    "schiiten"
  ],
  [
    "schintoist",
    "schintoisten",
    "schintoist",
    "schintoistin",
    "schintoisten",
    "schintoisten"
  ],
  [
    "schismatiker",
    "schismatiker",
    "schismatiker",
    "schismatikerin",
    "schismatiker",
    "schismatikers"
  ],
  [
    "schläfer",
    "schläfer",
    "schläfer",
    "schläferin",
    "schläfer",
    "schläfers"
  ],
  [
    "schlafwandler",
    "schlafwandler",
    "schlafwandler",
    "schlafwandlerin",
    "schlafwandler",
    "schlafwandlers"
  ],
  [
    "schläger",
    "schläger",
    "schläger",
    "schlägerin",
    "schläger",
    "schlägers"
  ],
  [
    "schmeichler",
    "schmeichler",
    "schmeichler",
    "schmeichlerin",
    "schmeichler",
    "schmeichlers"
  ],
  [
    "schnorrer",
    "schnorrer",
    "schnorrer",
    "schnorrerin",
    "schnorrer",
    "schnorrers"
  ],
  [
    "schurk",
    "schurken",
    "schurke",
    "schurkin",
    "schurken",
    "schurken"
  ],
  [
    "schutzpatron",
    "schutzpatrone",
    "schutzpatron",
    "schutzpatronin",
    "schutzpatron",
    "schutzpatrons"
  ],
  [
    "schwäb",
    "schwaben",
    "schwabe",
    "schwäbin",
    "schwaben",
    "schwaben"
  ],
  [
    "schweriner",
    "schweriner",
    "schweriner",
    "schwerinerin",
    "schweriner",
    "schweriners"
  ],
  [
    "schwindler",
    "schwindler",
    "schwindler",
    "schwindlerin",
    "schwindler",
    "schwindlers"
  ],
  [
    "scientolog",
    "scientologen",
    "scientologe",
    "scientologin",
    "scientologen",
    "scientologen"
  ],
  [
    "seismolog",
    "seismologen",
    "seismologe",
    "seismologin",
    "seismologen",
    "seismologen"
  ],
  [
    "selenograph",
    "selenographen",
    "selenograph",
    "selenographin",
    "selenographen",
    "selenographen"
  ],
  [
    "semiotiker",
    "semiotiker",
    "semiotiker",
    "semiotikerin",
    "semiotiker",
    "semiotikers"
  ],
  [
    "senkrechtstarter",
    "senkrechtstarter",
    "senkrechtstarter",
    "senkrechtstarterin",
    "senkrechtstarter",
    "senkrechtstarters"
  ],
  [
    "separatist",
    "separatisten",
    "separatist",
    "separatistin",
    "separatisten",
    "separatisten"
  ],
  [
    "sezessionist",
    "sezessionisten",
    "sezessionist",
    "sezessionistin",
    "sezessionisten",
    "sezessionisten"
  ],
  [
    "slaw",
    "slawen",
    "slawe",
    "slawin",
    "slawen",
    "slawen"
  ],
  [
    "sondierer",
    "sondierer",
    "sondierer",
    "sondiererin",
    "sondierer",
    "sondierers"
  ],
  [
    "sophist",
    "sophisten",
    "sophist",
    "sophistin",
    "sophisten",
    "sophisten"
  ],
  [
    "sopranist",
    "sopranisten",
    "sopranist",
    "sopranistin",
    "sopranisten",
    "sopranisten"
  ],
  [
    "sorb",
    "sorben",
    "sorbe",
    "sorbin",
    "sorben",
    "sorben"
  ],
  [
    "soziopath",
    "soziopathen",
    "soziopath",
    "soziopathin",
    "soziopathen",
    "soziopathen"
  ],
  [
    "speläolog",
    "speläologen",
    "speläologe",
    "speläologin",
    "speläologen",
    "speläologen"
  ],
  [
    "spielgefährt",
    "spielgefährten",
    "spielgefährte",
    "spielgefährtin",
    "spielgefährten",
    "spielgefährten"
  ],
  [
    "spießer",
    "spießer",
    "spießer",
    "spießerin",
    "spießer",
    "spießers"
  ],
  [
    "sprinter",
    "sprinter",
    "sprinter",
    "sprinterin",
    "sprinter",
    "sprinters"
  ],
  [
    "staatsrechtler",
    "staatsrechtler",
    "staatsrechtler",
    "staatsrechtlerin",
    "staatsrechtler",
    "staatsrechtlers"
  ],
  [
    "sterndeuter",
    "sterndeuter",
    "sterndeuter",
    "sterndeuterin",
    "sterndeuter",
    "sterndeuters"
  ],
  [
    "stilist",
    "stilisten",
    "stilist",
    "stilistin",
    "stilisten",
    "stilisten"
  ],
  [
    "stotter",
    "stotterer",
    "stotterer",
    "stotterin",
    "stotterer",
    "stotterers"
  ],
  [
    "strafrechtler",
    "strafrechtler",
    "strafrechtler",
    "strafrechtlerin",
    "strafrechtler",
    "strafrechtlers"
  ],
  [
    "streber",
    "streber",
    "streber",
    "streberin",
    "streber",
    "strebers"
  ],
  [
    "studiker",
    "studiker",
    "studiker",
    "studikerin",
    "studiker",
    "studikers"
  ],
  [
    "submittent",
    "submittenten",
    "submittent",
    "submittentin",
    "submittenten",
    "submittenten"
  ],
  [
    "subskribent",
    "subskribenten",
    "subskribent",
    "subskribentin",
    "subskribenten",
    "subskribenten"
  ],
  [
    "sucher",
    "sucher",
    "sucher",
    "sucherin",
    "sucher",
    "suchers"
  ],
  [
    "suderant",
    "suderanten",
    "suderant",
    "suderantin",
    "suderanten",
    "suderanten"
  ],
  [
    "südeuropäer",
    "südeuropäer",
    "südeuropäer",
    "südeuropäerin",
    "südeuropäer",
    "südeuropäers"
  ],
  [
    "südstaatler",
    "südstaatler",
    "südstaatler",
    "südstaatlerin",
    "südstaatler",
    "südstaatlers"
  ],
  [
    "südtiroler",
    "südtiroler",
    "südtiroler",
    "südtirolerin",
    "südtiroler",
    "südtirolers"
  ],
  [
    "surrealist",
    "surrealisten",
    "surrealist",
    "surrealistin",
    "surrealisten",
    "surrealisten"
  ],
  [
    "syndikalist",
    "syndikalisten",
    "syndikalist",
    "syndikalistin",
    "syndikalisten",
    "syndikalisten"
  ],
  [
    "tadler",
    "tadler",
    "tadler",
    "tadlerin",
    "tadler",
    "tadlers"
  ],
  [
    "tagelöhner",
    "tagelöhner",
    "tagelöhner",
    "tagelöhnerin",
    "tagelöhner",
    "tagelöhners"
  ],
  [
    "technokrat",
    "technokraten",
    "technokrat",
    "technokratin",
    "technokraten",
    "technokraten"
  ],
  [
    "texaner",
    "texaner",
    "texaner",
    "texanerin",
    "texaner",
    "texaners"
  ],
  [
    "theist",
    "theisten",
    "theist",
    "theistin",
    "theisten",
    "theisten"
  ],
  [
    "tibetaner",
    "tibetaner",
    "tibetaner",
    "tibetanerin",
    "tibetaner",
    "tibetaners"
  ],
  [
    "tiroler",
    "tiroler",
    "tiroler",
    "tirolerin",
    "tiroler",
    "tirolers"
  ],
  [
    "togoles",
    "togolesen",
    "togolese",
    "togolesin",
    "togolesen",
    "togolesen"
  ],
  [
    "tokioter",
    "tokioter",
    "tokioter",
    "tokioterin",
    "tokioter",
    "tokioters"
  ],
  [
    "topograph",
    "topographen",
    "topograph",
    "topographin",
    "topographen",
    "topographen"
  ],
  [
    "traumatolog",
    "traumatologen",
    "traumatologe",
    "traumatologin",
    "traumatologen",
    "traumatologen"
  ],
  [
    "träumer",
    "träumer",
    "träumer",
    "träumerin",
    "träumer",
    "träumers"
  ],
  [
    "treiber",
    "treiber",
    "treiber",
    "treiberin",
    "treiber",
    "treibers"
  ],
  [
    "trödler",
    "trödler",
    "trödler",
    "trödlerin",
    "trödler",
    "trödlers"
  ],
  [
    "tübinger",
    "tübinger",
    "tübinger",
    "tübingerin",
    "tübinger",
    "tübingers"
  ],
  [
    "tyrann",
    "tyrannen",
    "tyrann",
    "tyrannin",
    "tyrannen",
    "tyrannen"
  ],
  [
    "ulmer",
    "ulmer",
    "ulmer",
    "ulmerin",
    "ulmer",
    "ulmers"
  ],
  [
    "unionist",
    "unionisten",
    "unionist",
    "unionistin",
    "unionisten",
    "unionisten"
  ],
  [
    "utilitarist",
    "utilitaristen",
    "utilitarist",
    "utilitaristin",
    "utilitaristen",
    "utilitaristen"
  ],
  [
    "vagabund",
    "vagabunden",
    "vagabund",
    "vagabundin",
    "vagabunden",
    "vagabunden"
  ],
  [
    "venezianer",
    "venezianer",
    "venezianer",
    "venezianerin",
    "venezianer",
    "venezianers"
  ],
  [
    "vergewaltiger",
    "vergewaltiger",
    "vergewaltiger",
    "vergewaltigerin",
    "vergewaltiger",
    "vergewaltigers"
  ],
  [
    "wander",
    "wanderer",
    "wanderer",
    "wanderin",
    "wanderer",
    "wanderers"
  ],
  [
    "webmaster",
    "webmaster",
    "webmaster",
    "webmasterin",
    "webmaster",
    "webmasters"
  ],
  [
    "westfäl",
    "westfalen",
    "westfale",
    "westfälin",
    "westfalen",
    "westfalen"
  ],
  [
    "zahler",
    "zahler",
    "zahler",
    "zahlerin",
    "zahler",
    "zahlers"
  ],
  [
    "zensor",
    "zensoren",
    "zensor",
    "zensorin",
    "zensor",
    "zensors"
  ],
  [
    "zuwander",
    "zuwanderer",
    "zuwanderer",
    "zuwanderin",
    "zuwanderer",
    "zuwanderers"
  ],
  [
    "zyniker",
    "zyniker",
    "zyniker",
    "zynikerin",
    "zyniker",
    "zynikers"
  ]
] as const;

describe("zweiundachtzigste Lexikon-Ausbauwelle", () => {
  it("enthält exakt 195 vollständig geprüfte Scribbr-Mappings", () => {
    expect(reviewedPersonFormCountWave82).toBe(195);
    expect(cases).toHaveLength(195);
  });

  it.each(cases)(
    "bildet die geprüften Vollformen für %s korrekt ab",
    (base, plural, singular, feminine, oblique, genitive) => {
      expect(getReviewedPersonFormsWave82(base), base).toEqual({
        plural,
        singular,
        feminineSingular: feminine,
        obliqueSingular: oblique,
        genitiveSingular: genitive
      });
    }
  );

  it.each(cases)(
    "ersetzt den geprüften Plural für %s",
    (base, plural) => {
      expect(mappedPluralSeparatorsRule.apply(`${base}:innen`)).toEqual({
        text: plural,
        replacements: 1
      });
    }
  );

  it.each(cases)(
    "erkennt das geprüfte Singularpaar für %s",
    (_base, _plural, singular, feminine) => {
      expect(mapMappedSingularPair(singular, feminine)).toBe(singular);
    }
  );

  it.each(cases)(
    "bildet die geprüften Kasusformen für %s korrekt ab",
    (base, _plural, singular, _feminine, oblique, genitive) => {
      expect(mapMappedSingular(base, "nominative")).toBe(singular);
      expect(mapMappedSingular(base, "accusative")).toBe(oblique);
      expect(mapMappedSingular(base, "dative")).toBe(oblique);
      expect(mapMappedSingular(base, "genitive")).toBe(genitive);
    }
  );
});
